import {beforeEach,describe,expect,it} from "vitest";
import type {PayrollBillingRunDetail,PayrollBillingStatus} from "../domain/types";
import {payrollBillingRepository,resetPayrollBillingMock,setPayrollBillingCurrentRevisionForTest,setPayrollBillingReferenceScenario,setPayrollBillingStatusForTest} from "./mock-adapter";

const actor=(permission:string)=>({userId:"atomic-user",permissionKeys:[permission]});
const data=(overrides:Partial<{runId:string;revisionId:string;revisionVersion:number}>={})=>({runId:"pbr-001",revisionId:"rev-2",revisionVersion:1,...overrides});
const snapshot=async():Promise<PayrollBillingRunDetail>=>structuredClone(await payrollBillingRepository.get("pbr-001"));
async function unchanged(operation:()=>Promise<unknown>,expected:{status?:number;code?:string;name?:string}){const before=await snapshot(),revisionCount=before.revisions.length,activityCount=before.activity.length;await expect(operation()).rejects.toMatchObject(expected);const after=await snapshot();expect(after).toEqual(before);expect(after.revisions).toHaveLength(revisionCount);expect(after.activity).toHaveLength(activityCount);}
const recalculate=(overrides:Partial<Parameters<typeof payrollBillingRepository.recalculate>[0]>={})=>payrollBillingRepository.recalculate({data:data(),actor:actor("payroll-billing.recalculate"),reason:"Recalculate valid",currentVersion:4,...overrides});
const review=(overrides:Partial<Parameters<typeof payrollBillingRepository.review>[0]>={})=>payrollBillingRepository.review({data:{...data(),attestation:true},actor:actor("payroll-billing.review"),reason:"Review valid",currentVersion:4,...overrides});
const reject=(overrides:Partial<Parameters<typeof payrollBillingRepository.reject>[0]>={})=>payrollBillingRepository.reject({data:data(),actor:actor("payroll-billing.reject"),reason:"Reject valid",currentVersion:4,...overrides});
const lock=(overrides:Partial<Parameters<typeof payrollBillingRepository.lock>[0]>={})=>payrollBillingRepository.lock({data:{...data(),attestation:true},actor:actor("payroll-billing.lock"),reason:"Lock valid",currentVersion:5,...overrides});
beforeEach(resetPayrollBillingMock);
describe("Recalculate full failure atomicity",()=>{
it("rejects a persisted current pointer whose revision is missing without fallback or repair",async()=>{setPayrollBillingCurrentRevisionForTest("rev-corrupt");const before=await snapshot();await unchanged(()=>recalculate({data:data({revisionId:"rev-corrupt"})}),{status:404,code:"PAYROLL_BILLING_REVISION_NOT_FOUND"});expect((await snapshot()).run.currentRevisionId).toBe("rev-corrupt");expect(await payrollBillingRepository.revision("pbr-001","rev-2")).toEqual(before.revisions[0]);});
it("returns structured conflict metadata when the command revision is missing",async()=>{const before=await snapshot();await expect(recalculate({data:data({revisionId:"rev-missing"})})).rejects.toMatchObject({status:409,code:"PAYROLL_BILLING_REVISION_CONFLICT",metadata:{attemptedRevisionId:"rev-missing",latestRevisionId:"rev-2",attemptedRevisionVersion:1,latestRevisionVersion:1}});expect(await snapshot()).toEqual(before);});
it("treats a foreign-run revision identifier as non-current without leaking foreign data",async()=>{const before=await snapshot();await expect(recalculate({data:data({revisionId:"other-run-revision"})})).rejects.toMatchObject({status:409,code:"PAYROLL_BILLING_REVISION_CONFLICT",message:"Revision telah berubah."});expect(await snapshot()).toEqual(before);});
it.each(["project-missing","customer-missing","sph-missing","attendance-missing","rate-missing","service-missing","branch-missing"] as const)("returns typed 404 and preserves history when %s",async scenario=>{const historical=await payrollBillingRepository.revision("pbr-001","rev-2"),before=await snapshot();setPayrollBillingReferenceScenario(scenario);await expect(recalculate()).rejects.toMatchObject({status:404,code:"PAYROLL_BILLING_SOURCE_NOT_FOUND",correlation_id:"demo-payroll-reference",metadata:{blockingCount:1}});expect(await snapshot()).toEqual(before);expect(await payrollBillingRepository.revision("pbr-001","rev-2")).toEqual(historical);});
it("keeps the full aggregate unchanged for 403, 404, aggregate 409, and revision 409",async()=>{await unchanged(()=>recalculate({actor:actor("none")}),{status:403});await unchanged(()=>recalculate({data:data({runId:"missing"})}),{status:404});await unchanged(()=>recalculate({currentVersion:3}),{status:409,code:"PAYROLL_BILLING_VERSION_CONFLICT"});await unchanged(()=>recalculate({data:data({revisionVersion:9})}),{status:409,code:"PAYROLL_BILLING_REVISION_CONFLICT"});});
it.each(["","   "])("rejects missing reason %j atomically",async reason=>unchanged(()=>recalculate({reason}),{status:422,code:"PAYROLL_BILLING_REASON_REQUIRED"}));
it.each(["Draft","Reviewed","Locked"] as PayrollBillingStatus[])("rejects lifecycle %s atomically",async status=>{setPayrollBillingStatusForTest(status);await unchanged(()=>recalculate(),{status:422,code:"PAYROLL_BILLING_INVALID_STATE"});});
it.each(["service-inactive","branch-moved","attendance-ineligible","rate-inapplicable","currency-mismatch","unit-mismatch"] as const)("rejects current reference %s atomically",async scenario=>{setPayrollBillingReferenceScenario(scenario);await unchanged(()=>recalculate(),{status:422,code:"PAYROLL_BILLING_REFERENCE_INVALID"});});
it("preserves cancellation and accepts a fresh request",async()=>{const pre=new AbortController();pre.abort();await unchanged(()=>payrollBillingRepository.recalculate({data:data(),actor:actor("payroll-billing.recalculate"),reason:"pre",currentVersion:4},pre.signal),{name:"AbortError"});const mid=new AbortController();await unchanged(()=>{const pending=payrollBillingRepository.recalculate({data:data(),actor:actor("payroll-billing.recalculate"),reason:"mid",currentVersion:4},mid.signal);mid.abort();return pending;},{name:"AbortError"});const before=await snapshot();await recalculate();const after=await snapshot();expect(after.run.version).toBe(before.run.version+1);expect(after.revisions).toHaveLength(before.revisions.length+1);expect(after.activity).toHaveLength(before.activity.length+1);expect(after.revisions[1]).toEqual(before.revisions[0]);});
});
describe("Review full failure atomicity",()=>{
it("covers authorization lookup concurrency reason and attestation",async()=>{await unchanged(()=>review({actor:actor("none")}),{status:403});await unchanged(()=>review({data:{...data({runId:"missing"}),attestation:true}}),{status:404});await unchanged(()=>review({currentVersion:3}),{status:409});await unchanged(()=>review({data:{...data({revisionVersion:9}),attestation:true}}),{status:409});await unchanged(()=>review({reason:" "}),{status:422});await unchanged(()=>review({data:{...data(),attestation:false}}),{status:422,code:"PAYROLL_BILLING_ATTESTATION_REQUIRED"});});
it.each(["Draft","Calculated","Reviewed","Locked","Rejected"] as PayrollBillingStatus[])("rejects lifecycle %s atomically",async status=>{setPayrollBillingStatusForTest(status);await unchanged(()=>review(),{status:422,code:"PAYROLL_BILLING_INVALID_STATE"});});
it("keeps pre/mid cancellation clean and fresh Review succeeds",async()=>{const pre=new AbortController();pre.abort();await unchanged(()=>payrollBillingRepository.review({data:{...data(),attestation:true},actor:actor("payroll-billing.review"),reason:"pre",currentVersion:4},pre.signal),{name:"AbortError"});const mid=new AbortController();await unchanged(()=>{const pending=payrollBillingRepository.review({data:{...data(),attestation:true},actor:actor("payroll-billing.review"),reason:"mid",currentVersion:4},mid.signal);mid.abort();return pending;},{name:"AbortError"});const before=await snapshot();await review();const after=await snapshot();expect(after.run).toMatchObject({status:"Reviewed",version:before.run.version+1});expect(after.revisions.map(x=>x.snapshot)).toEqual(before.revisions.map(x=>x.snapshot));expect(after.activity).toHaveLength(before.activity.length+1);});
});
describe("Reject full failure atomicity",()=>{
it("covers authorization lookup concurrency and blank reason",async()=>{await unchanged(()=>reject({actor:actor("none")}),{status:403});await unchanged(()=>reject({data:data({runId:"missing"})}),{status:404});await unchanged(()=>reject({currentVersion:3}),{status:409});await unchanged(()=>reject({data:data({revisionId:"other"})}),{status:409});await unchanged(()=>reject({reason:"   "}),{status:422});});
it.each(["Draft","Calculated","Locked","Rejected"] as PayrollBillingStatus[])("rejects lifecycle %s atomically",async status=>{setPayrollBillingStatusForTest(status);await unchanged(()=>reject(),{status:422,code:"PAYROLL_BILLING_INVALID_STATE"});});
it("keeps cancellation clean and preserves financial snapshots on success",async()=>{const pre=new AbortController();pre.abort();await unchanged(()=>payrollBillingRepository.reject({data:data(),actor:actor("payroll-billing.reject"),reason:"pre",currentVersion:4},pre.signal),{name:"AbortError"});const mid=new AbortController();await unchanged(()=>{const pending=payrollBillingRepository.reject({data:data(),actor:actor("payroll-billing.reject"),reason:"mid",currentVersion:4},mid.signal);mid.abort();return pending;},{name:"AbortError"});const before=await snapshot();await reject();const after=await snapshot();expect(after.run).toMatchObject({status:"Rejected",version:before.run.version+1});expect(after.revisions).toEqual(before.revisions);expect(after.activity[0]).toMatchObject({reason:"Reject valid",actorUserId:"atomic-user"});});
});
describe("Lock full failure atomicity",()=>{
beforeEach(async()=>{await review();});
it("covers authorization lookup concurrency and attestation",async()=>{await unchanged(()=>lock({actor:actor("none")}),{status:403});await unchanged(()=>lock({data:{...data({runId:"missing"}),attestation:true}}),{status:404});await unchanged(()=>lock({currentVersion:4}),{status:409});await unchanged(()=>lock({data:{...data({revisionVersion:9}),attestation:true}}),{status:409});await unchanged(()=>lock({data:{...data(),attestation:false}}),{status:422});});
it.each(["Draft","Calculated","Needs Review","Rejected","Locked"] as PayrollBillingStatus[])("requires Reviewed instead of %s atomically",async status=>{setPayrollBillingStatusForTest(status);await unchanged(()=>lock(),{status:422,code:"PAYROLL_BILLING_INVALID_STATE"});});
it("keeps cancellation clean and locks a fresh request once",async()=>{const pre=new AbortController();pre.abort();await unchanged(()=>payrollBillingRepository.lock({data:{...data(),attestation:true},actor:actor("payroll-billing.lock"),reason:"pre",currentVersion:5},pre.signal),{name:"AbortError"});const mid=new AbortController();await unchanged(()=>{const pending=payrollBillingRepository.lock({data:{...data(),attestation:true},actor:actor("payroll-billing.lock"),reason:"mid",currentVersion:5},mid.signal);mid.abort();return pending;},{name:"AbortError"});const before=await snapshot();await lock();const after=await snapshot();expect(after.run).toMatchObject({status:"Locked",version:before.run.version+1});expect(after.revisions.map(x=>x.snapshot)).toEqual(before.revisions.map(x=>x.snapshot));expect(after.activity).toHaveLength(before.activity.length+1);await unchanged(()=>reject({currentVersion:after.run.version}),{status:422});});
});
