import Decimal from "decimal.js";
import {AppError} from "@/features/foundation/domain/errors";
import {calculateLine,reconcile} from "../domain/calculation";
import {calculatePayrollBillingReadiness,diffPayrollBillingRevisions,normalizePayrollBillingExceptionQuery} from "../domain/hardening";
import type {PayrollBillingRepository} from "../repositories";
import type {PayrollBillingAdjustment,PayrollBillingException,PayrollBillingLine,PayrollBillingRunDetail,PayrollBillingRunListItem,PayrollBillingSummary,PayrollCommand,PayrollMutationResult,PayrollBillingStatus} from "../domain/types";
const now="2026-08-11T09:00:00+07:00";
const source={projectId:"prj-019",projectLabel:"PRJ-019 · Managed Services",customerId:"cus-001",customerLabel:"PT Customer Demo",sphId:"sph-019",sphLabel:"SPH snapshot demo",attendanceBatchId:"att-001",attendanceRevision:3,attendancePeriod:"2026-07",attendanceRows:2,rateVersionId:"rate-019-v2",rateVersionLabel:"Rate Version 2 · snapshot",branchLabel:"Jakarta",serviceLabel:"Managed Service",currency:"IDR" as const,unit:"HK",capturedAt:now};
const a=calculateLine("20","250000"),b=calculateLine("18","250000","100000");
const seedLines=[{id:"line-1",employeeReference:"••••4821",branchLabel:"Jakarta",serviceLabel:"Managed Service",quantity:"20",unitRate:"250000",componentSubtotal:a.componentSubtotal,adjustment:"0",withholding:"0",finalAmount:a.finalAmount,hasException:false,trace:{attendanceBatchId:"att-001",attendanceRevision:3,sourceRowId:"row-1",quantity:"20",unit:"HK",rateVersionId:"rate-019-v2",rateLineId:"rate-line-1",unitRate:"250000",formulaLabel:"Quantity × applicable rate snapshot (demo)",roundingMethod:"Tidak diterapkan",calculatedAt:now},components:[{code:"BASE",label:"Base billing",amount:a.componentSubtotal,applicability:"Applicable" as const,source:"RateSnapshot" as const}]},{id:"line-2",employeeReference:"••••7734",branchLabel:"Jakarta",serviceLabel:"Managed Service",quantity:"18",unitRate:"250000",componentSubtotal:b.componentSubtotal,adjustment:"100000",withholding:"0",finalAmount:b.finalAmount,hasException:true,trace:{attendanceBatchId:"att-001",attendanceRevision:3,sourceRowId:"row-2",quantity:"18",unit:"HK",rateVersionId:"rate-019-v2",rateLineId:"rate-line-1",unitRate:"250000",formulaLabel:"Quantity × rate snapshot + adjustment demo",roundingMethod:"Tidak diterapkan",calculatedAt:now},components:[{code:"BASE",label:"Base billing",amount:b.componentSubtotal,applicability:"Applicable" as const,source:"RateSnapshot" as const},{code:"ADJ",label:"Adjustment demo",amount:"100000.00",applicability:"Applicable" as const,source:"Adjustment" as const}]}];
const seedSummary={attendanceSourceTotal:"38",baseAmount:"9500000.00",rewardAmount:undefined,bpjsAmount:undefined,managementFee:"0.00",otherCharges:"0.00",taxBase:"9600000.00",vatAmount:undefined,withholdingAmount:undefined,roundingAmount:"0.00",adjustmentAmount:"100000.00",grandTotal:"9600000.00"};
const seedExceptions=[{id:"exc-1",severity:"Warning" as const,code:"MANUAL_ADJUSTMENT_REVIEW",lineId:"line-2",explanation:"Adjustment demo memerlukan review.",affectedValue:"Rp100.000",suggestedAction:"Tinjau reason adjustment.",blocking:false}];
const seedAdjustments=[{id:"adj-1",scope:"Line" as const,lineId:"line-2",type:"Addition" as const,amount:"100000.00",reason:"Koreksi source-driven demo",actorUserId:"usr-demo",createdAt:now}];
const makeSnapshot=(lines:readonly PayrollBillingLine[]=seedLines,summary:PayrollBillingSummary=seedSummary,adjustments:readonly PayrollBillingAdjustment[]=seedAdjustments,exceptions:readonly PayrollBillingException[]=seedExceptions)=>{const rec=reconcile(lines,summary);return{source:structuredClone(source),lines:structuredClone(lines),adjustments:structuredClone(adjustments),exceptions:structuredClone(exceptions),summary:structuredClone(summary),reconciliation:{sourceCalculatedTotal:summary.grandTotal,lineTotal:rec.lineTotal,summaryTotal:rec.summaryTotal,variance:rec.variance,reconciled:rec.reconciled,explanation:"Jumlah line sama dengan grand total."},calculatedAt:now,calculatedByUserId:"usr-demo"};};
function seed():PayrollBillingRunDetail{const snapshot=makeSnapshot();return{run:{id:"pbr-001",status:"Needs Review",revisionNumber:2,currentRevisionId:"rev-2",version:4,currency:"IDR",source:structuredClone(source),summary:structuredClone(seedSummary),exceptionCount:1,createdAt:now,updatedAt:now,calculatedAt:now},lines:structuredClone(seedLines),exceptions:structuredClone(seedExceptions),adjustments:structuredClone(seedAdjustments),revisions:[{id:"rev-2",revisionNumber:2,version:1,status:"Needs Review",reason:"Recalculation demo",total:"9600000.00",exceptionCount:1,createdAt:now,actorUserId:"usr-demo",diffSummary:"Adjustment ditambahkan; revision lama immutable.",source:structuredClone(source),snapshot}],activity:[{id:"act-1",action:"payroll-billing.recalculated",actorUserId:"usr-demo",actorName:"Dewi Sari",occurredAt:now,reason:"Recalculation demo",revisionNumber:2,correlationId:"demo-payroll-activity",summary:"Revision 2 dihitung dari snapshot Attendance dan Rate Version."}],readiness:{readyToReview:true,readyToLock:false,blockers:["Run harus Reviewed sebelum Lock."],nextAction:"Tinjau breakdown dan exception, lalu Review."},reconciliation:structuredClone(snapshot.reconciliation)};}
let aggregate=seed();
type ReferenceScenario="valid"|"project-missing"|"customer-missing"|"sph-missing"|"attendance-missing"|"rate-missing"|"service-missing"|"branch-missing"|"service-inactive"|"branch-moved"|"attendance-ineligible"|"rate-inapplicable"|"currency-mismatch"|"unit-mismatch"|"blocking-exception"|"variance";
let referenceScenario:ReferenceScenario="valid";
const wait=(signal?:AbortSignal)=>{const pending=new Promise<void>((resolve,reject)=>{if(signal?.aborted)return reject(new DOMException("cancelled","AbortError"));const timer=setTimeout(resolve,10);signal?.addEventListener("abort",()=>{clearTimeout(timer);reject(new DOMException("cancelled","AbortError"));},{once:true});});void pending.catch(()=>undefined);return pending;};
const permission=(keys:readonly string[],key:string)=>{if(!keys.includes(key))throw new AppError(403,"PAYROLL_BILLING_FORBIDDEN","Tindakan Payroll Billing tidak diizinkan.",{},false,"demo-payroll-403");};
const current=(command:PayrollCommand<{runId:string;revisionId:string;revisionVersion:number}>)=>{if(command.data.runId!==aggregate.run.id)throw new AppError(404,"PAYROLL_BILLING_NOT_FOUND","Payroll Billing Run tidak ditemukan.",{},false,"demo-payroll-404");if(command.currentVersion!==aggregate.run.version)throw new AppError(409,"PAYROLL_BILLING_VERSION_CONFLICT","Run telah berubah. Muat revision terbaru.",{},false,"demo-payroll-409",{userVersion:command.currentVersion,latestVersion:aggregate.run.version,revision:aggregate.run.revisionNumber,diffs:[{field:"status",label:"Status",before:"attempted",after:aggregate.run.status}]});const revision=aggregate.revisions.find(item=>item.id===aggregate.run.currentRevisionId);if(!revision)throw new AppError(404,"PAYROLL_BILLING_REVISION_NOT_FOUND","Current revision Payroll Billing tidak ditemukan.",{},false,"demo-payroll-revision-404");if(command.data.revisionId!==aggregate.run.currentRevisionId||command.data.revisionVersion!==revision.version)throw new AppError(409,"PAYROLL_BILLING_REVISION_CONFLICT","Revision telah berubah.",{},false,"demo-payroll-revision-409",{attemptedRevisionId:command.data.revisionId,latestRevisionId:aggregate.run.currentRevisionId,attemptedRevisionVersion:command.data.revisionVersion,latestRevisionVersion:revision.version,attemptedStatus:"unknown",latestStatus:aggregate.run.status,runId:aggregate.run.id});return revision;};
const reason=(value:string)=>{if(!value.trim())throw new AppError(422,"PAYROLL_BILLING_REASON_REQUIRED","Reason wajib diisi.",{reason:["Isi reason dari pengguna."]},false,"demo-payroll-reason");};
const event=(action:string,command:PayrollCommand<object>)=>{aggregate.activity=[{id:`act-${aggregate.run.version}`,action,actorUserId:command.actor.userId,occurredAt:now,reason:command.reason,revisionNumber:aggregate.run.revisionNumber,correlationId:`demo-${action}`,summary:`${action} berhasil secara atomic.`},...aggregate.activity];};
const result=(message:string):PayrollMutationResult=>({runId:aggregate.run.id,version:aggregate.run.version,revisionNumber:aggregate.run.revisionNumber,message,correlationId:"demo-payroll-mutation"});
const status=(allowed:readonly PayrollBillingStatus[])=>{if(!allowed.includes(aggregate.run.status))throw new AppError(422,"PAYROLL_BILLING_INVALID_STATE","Status run tidak mendukung tindakan ini.",{},false,"demo-payroll-state");};
const clone=()=>structuredClone(aggregate);
export const resetPayrollBillingMock=()=>{aggregate=seed();referenceScenario="valid";};
export const setPayrollBillingReferenceScenario=(scenario:ReferenceScenario)=>{referenceScenario=scenario;};
export const setPayrollBillingStatusForTest=(status:PayrollBillingStatus)=>{aggregate.run={...aggregate.run,status};};
export const setPayrollBillingCurrentRevisionForTest=(revisionId:string)=>{aggregate.run={...aggregate.run,currentRevisionId:revisionId};};
const assertCurrentReferences=()=>{if(referenceScenario==="valid"||referenceScenario==="blocking-exception"||referenceScenario==="variance")return;const missing=referenceScenario.endsWith("-missing"),referenceType=referenceScenario.replace("-missing","");throw new AppError(missing?404:422,missing?"PAYROLL_BILLING_SOURCE_NOT_FOUND":"PAYROLL_BILLING_REFERENCE_INVALID",missing?"Source Payroll Billing tidak ditemukan.":"Referensi current Payroll Billing tidak valid.",{},false,"demo-payroll-reference",{referenceIssues:[{code:missing?"SOURCE_MISSING":"REFERENCE_INVALID",severity:"Error",blocking:true,referenceType,referenceId:referenceType,field:referenceType,explanation:missing?"Source current tidak tersedia.":"Current reference tidak valid.",suggestedAction:"Perbaiki current reference."}],blockingCount:1,nextAction:"Perbaiki current reference."});};
const authoritativeReadiness=()=>{const revision=aggregate.revisions.find(x=>x.id===aggregate.run.currentRevisionId);if(!revision)throw new AppError(404,"PAYROLL_BILLING_REVISION_NOT_FOUND","Revision tidak ditemukan.",{},false,"demo-payroll-revision-404");const references={project:{id:source.projectId,exists:true,terminal:false},customer:{id:source.customerId,exists:true},sph:{id:source.sphId,exists:true,projectId:source.projectId},attendance:{id:source.attendanceBatchId,exists:true,eligible:referenceScenario!=="attendance-ineligible",projectId:source.projectId,period:source.attendancePeriod,revision:source.attendanceRevision},rateVersion:{id:source.rateVersionId,exists:true,applicable:referenceScenario!=="rate-inapplicable",currency:referenceScenario==="currency-mismatch"?"USD" as const:source.currency,unit:referenceScenario==="unit-mismatch"?"Jam":source.unit},service:{label:source.serviceLabel,exists:true,active:referenceScenario!=="service-inactive",projectId:source.projectId},branch:{label:source.branchLabel,exists:true,active:true,projectId:referenceScenario==="branch-moved"?"other":source.projectId}};const blocking=aggregate.exceptions.filter(x=>x.blocking).length+(referenceScenario==="blocking-exception"?1:0),reconciled=aggregate.reconciliation.reconciled&&referenceScenario!=="variance";const readiness=calculatePayrollBillingReadiness({revision,calculatedAt:revision.snapshot.calculatedAt,currency:revision.snapshot.source.currency,lines:revision.snapshot.lines,summary:revision.snapshot.summary},references,aggregate.run.currentRevisionId,blocking,reconciled);if(!readiness.ready){const referenceIssues=readiness.checks.find(x=>x.code==="CURRENT_REFERENCES")?.issueCount??0,code=!reconciled?"PAYROLL_BILLING_RECONCILIATION_MISMATCH":referenceIssues?"PAYROLL_BILLING_REFERENCE_INVALID":"PAYROLL_BILLING_READINESS_BLOCKED";throw new AppError(422,code,"Payroll Billing belum siap untuk tindakan ini.",{},false,"demo-payroll-readiness",{readinessIssues:readiness.blockers.map(x=>x.explanation),blockingCount:readiness.blockers.length,nextAction:readiness.nextAction});}return readiness;};
export const payrollBillingRepository:PayrollBillingRepository={
 async list(query,signal){await wait(signal);let items:PayrollBillingRunListItem[]=[{...aggregate.run,nextAction:aggregate.readiness.nextAction,reconciled:aggregate.reconciliation.reconciled}];const search=query.search?.trim().toLowerCase();if(search)items=items.filter(item=>`${item.id} ${item.source.projectLabel} ${item.source.customerLabel}`.toLowerCase().includes(search));if(query.statuses?.length)items=items.filter(item=>query.statuses?.includes(item.status));const page=Math.max(1,query.page??1),pageSize=[10,20,50].includes(query.pageSize??20)?query.pageSize??20:20;return{items,total:items.length,page,pageSize,hasNextPage:false,totalPages:Math.max(1,Math.ceil(items.length/pageSize))};},
 async get(id,signal){await wait(signal);if(id!==aggregate.run.id)throw new AppError(404,"PAYROLL_BILLING_NOT_FOUND","Payroll Billing Run tidak ditemukan.",{},false,"demo-payroll-404");return clone();},
 async currentRevision(id,signal){await wait(signal);if(id!==aggregate.run.id)throw new AppError(404,"PAYROLL_BILLING_NOT_FOUND","Payroll Billing Run tidak ditemukan.",{},false,"demo-payroll-404");const item=aggregate.revisions.find(x=>x.id===aggregate.run.currentRevisionId);if(!item)throw new AppError(404,"PAYROLL_BILLING_REVISION_NOT_FOUND","Revision tidak ditemukan.",{},false,"demo-payroll-revision-404");return structuredClone(item);},
 async revision(id,revisionId,signal){await wait(signal);if(id!==aggregate.run.id)throw new AppError(404,"PAYROLL_BILLING_NOT_FOUND","Payroll Billing Run tidak ditemukan.",{},false,"demo-payroll-404");const item=aggregate.revisions.find(x=>x.id===revisionId);if(!item)throw new AppError(404,"PAYROLL_BILLING_REVISION_NOT_FOUND","Revision tidak ditemukan.",{},false,"demo-payroll-revision-404");return structuredClone(item);},
 async revisions(id,signal){await wait(signal);if(id!==aggregate.run.id)throw new AppError(404,"PAYROLL_BILLING_NOT_FOUND","Payroll Billing Run tidak ditemukan.",{},false,"demo-payroll-404");return structuredClone(aggregate.revisions);},
 async revisionLines(id,revisionId,signal){await wait(signal);if(id!==aggregate.run.id)throw new AppError(404,"PAYROLL_BILLING_NOT_FOUND","Payroll Billing Run tidak ditemukan.",{},false,"demo-payroll-404");const item=aggregate.revisions.find(x=>x.id===revisionId);if(!item)throw new AppError(404,"PAYROLL_BILLING_REVISION_NOT_FOUND","Revision tidak ditemukan.",{},false,"demo-payroll-revision-404");return structuredClone(item.snapshot.lines);},
 async revisionSummary(id,revisionId,signal){await wait(signal);if(id!==aggregate.run.id)throw new AppError(404,"PAYROLL_BILLING_NOT_FOUND","Payroll Billing Run tidak ditemukan.",{},false,"demo-payroll-404");const item=aggregate.revisions.find(x=>x.id===revisionId);if(!item)throw new AppError(404,"PAYROLL_BILLING_REVISION_NOT_FOUND","Revision tidak ditemukan.",{},false,"demo-payroll-revision-404");return structuredClone(item.snapshot.summary);},
 async revisionReconciliation(id,revisionId,signal){await wait(signal);if(id!==aggregate.run.id)throw new AppError(404,"PAYROLL_BILLING_NOT_FOUND","Payroll Billing Run tidak ditemukan.",{},false,"demo-payroll-404");const item=aggregate.revisions.find(x=>x.id===revisionId);if(!item)throw new AppError(404,"PAYROLL_BILLING_REVISION_NOT_FOUND","Revision tidak ditemukan.",{},false,"demo-payroll-revision-404");return structuredClone(item.snapshot.reconciliation);},
 async revisionDiff(id,sourceRevisionId,targetRevisionId,signal){await wait(signal);if(id!==aggregate.run.id)throw new AppError(404,"PAYROLL_BILLING_NOT_FOUND","Payroll Billing Run tidak ditemukan.",{},false,"demo-payroll-404");const sourceRevision=aggregate.revisions.find(x=>x.id===sourceRevisionId),targetRevision=aggregate.revisions.find(x=>x.id===targetRevisionId);if(!sourceRevision||!targetRevision)throw new AppError(404,"PAYROLL_BILLING_REVISION_NOT_FOUND","Revision tidak ditemukan.",{},false,"demo-payroll-revision-404");return diffPayrollBillingRevisions({revision:sourceRevision,calculatedAt:sourceRevision.snapshot.calculatedAt,currency:sourceRevision.snapshot.source.currency,lines:structuredClone(sourceRevision.snapshot.lines),summary:structuredClone(sourceRevision.snapshot.summary)},{revision:targetRevision,calculatedAt:targetRevision.snapshot.calculatedAt,currency:targetRevision.snapshot.source.currency,lines:structuredClone(targetRevision.snapshot.lines),summary:structuredClone(targetRevision.snapshot.summary)});},
 async lines(id,signal){await wait(signal);if(id!==aggregate.run.id)throw new AppError(404,"PAYROLL_BILLING_NOT_FOUND","Payroll Billing Run tidak ditemukan.",{},false,"demo-payroll-404");return structuredClone(aggregate.lines);},
 async trace(id,lineId,signal){await wait(signal);if(id!==aggregate.run.id)throw new AppError(404,"PAYROLL_BILLING_NOT_FOUND","Payroll Billing Run tidak ditemukan.",{},false,"demo-payroll-404");const line=aggregate.lines.find(x=>x.id===lineId);if(!line)throw new AppError(404,"PAYROLL_BILLING_LINE_NOT_FOUND","Line tidak ditemukan.",{},false,"demo-payroll-line-404");return structuredClone(line.trace);},
 async summary(id,signal){await wait(signal);if(id!==aggregate.run.id)throw new AppError(404,"PAYROLL_BILLING_NOT_FOUND","Payroll Billing Run tidak ditemukan.",{},false,"demo-payroll-404");return structuredClone(aggregate.run.summary);},
 async exceptions(id,input,signal){await wait(signal);if(id!==aggregate.run.id)throw new AppError(404,"PAYROLL_BILLING_NOT_FOUND","Payroll Billing Run tidak ditemukan.",{},false,"demo-payroll-404");const query=normalizePayrollBillingExceptionQuery(input);let items=aggregate.exceptions.map(item=>({...item,sourceReference:item.lineId?aggregate.lines.find(x=>x.id===item.lineId)?.employeeReference:undefined,affectedField:item.lineId?"adjustment":"run",calculatedAt:aggregate.run.calculatedAt}));if(query.search){const search=query.search.toLowerCase();items=items.filter(item=>`${item.code} ${item.explanation} ${item.suggestedAction}`.toLowerCase().includes(search));}if(query.severities.length)items=items.filter(item=>query.severities.includes(item.severity));if(query.blocking!==undefined)items=items.filter(item=>item.blocking===query.blocking);items.sort((a,b)=>{const left=String(a[query.sort]??""),right=String(b[query.sort]??"");return left.localeCompare(right)*(query.direction==="asc"?1:-1);});const total=items.length,start=(query.page-1)*query.pageSize;return{items:structuredClone(items.slice(start,start+query.pageSize)),total,page:query.page,pageSize:query.pageSize,hasNextPage:start+query.pageSize<total,totalPages:Math.max(1,Math.ceil(total/query.pageSize))};},
 async readiness(id,signal){await wait(signal);if(id!==aggregate.run.id)throw new AppError(404,"PAYROLL_BILLING_NOT_FOUND","Payroll Billing Run tidak ditemukan.",{},false,"demo-payroll-404");return structuredClone(aggregate.readiness);},
 async reconciliation(id,signal){await wait(signal);if(id!==aggregate.run.id)throw new AppError(404,"PAYROLL_BILLING_NOT_FOUND","Payroll Billing Run tidak ditemukan.",{},false,"demo-payroll-404");return structuredClone(aggregate.reconciliation);},
 async activity(id,signal){await wait(signal);if(id!==aggregate.run.id)throw new AppError(404,"PAYROLL_BILLING_NOT_FOUND","Payroll Billing Run tidak ditemukan.",{},false,"demo-payroll-404");return structuredClone(aggregate.activity);},
 async sourceOptions(signal){await wait(signal);return[structuredClone(source)];},
 async create(command,signal){await wait(signal);permission(command.actor.permissionKeys,"payroll-billing.create");reason(command.reason);if(command.data.attendanceBatchId!=="att-001"||command.data.projectId!==source.projectId||command.data.period!==source.attendancePeriod||command.data.sphId!==source.sphId)throw new AppError(422,"PAYROLL_BILLING_SOURCE_INVALID","Attendance Locked, Project, period, SPH, dan Rate Version harus applicable.",{},false,"demo-payroll-source");event("payroll-billing.created",command);return result("Payroll Billing Run demo tersedia.");},
 async adjust(command,signal){await wait(signal);permission(command.actor.permissionKeys,"payroll-billing.adjust");const revision=current(command);reason(command.reason);status(["Draft","Calculated","Needs Review"]);if(command.data.currency!==aggregate.run.currency)throw new AppError(422,"PAYROLL_BILLING_CURRENCY_MISMATCH","Currency adjustment tidak sesuai run.",{currency:["Gunakan currency snapshot run."]},false,"demo-payroll-currency");if(command.data.scope==="Line"&&!aggregate.lines.some(line=>line.id===command.data.lineId))throw new AppError(422,"PAYROLL_BILLING_LINE_INVALID","Target line tidak valid.",{lineId:["Pilih line current revision."]},false,"demo-payroll-line");let amount;try{amount=new Decimal(command.data.amount);}catch{throw new AppError(422,"PAYROLL_BILLING_AMOUNT_INVALID","Amount tidak valid.",{amount:["Masukkan decimal amount."]},false,"demo-payroll-amount");}if(!amount.isPositive())throw new AppError(422,"PAYROLL_BILLING_AMOUNT_INVALID","Amount harus positif.",{amount:["Masukkan amount lebih dari nol."]},false,"demo-payroll-amount");const signed=command.data.type==="Deduction"?amount.negated():amount,nextTotal=new Decimal(aggregate.run.summary.grandTotal).plus(signed),nextRevision=aggregate.run.revisionNumber+1;aggregate={...aggregate,run:{...aggregate.run,status:"Needs Review",revisionNumber:nextRevision,currentRevisionId:`rev-${nextRevision}`,version:aggregate.run.version+1,summary:{...aggregate.run.summary,adjustmentAmount:new Decimal(aggregate.run.summary.adjustmentAmount).plus(signed).toFixed(2),grandTotal:nextTotal.toFixed(2)},updatedAt:now},adjustments:[{id:`adj-${nextRevision}`,scope:command.data.scope,lineId:command.data.lineId,type:command.data.type,amount:amount.toFixed(2),reason:command.reason,note:command.data.note,actorUserId:command.actor.userId,createdAt:now},...aggregate.adjustments],revisions:[{...revision,id:`rev-${nextRevision}`,revisionNumber:nextRevision,version:1,status:"Needs Review",reason:command.reason,total:nextTotal.toFixed(2),actorUserId:command.actor.userId,diffSummary:`Adjustment ${signed.toFixed(2)}; revision sebelumnya immutable.`,source:structuredClone(aggregate.run.source)},...aggregate.revisions],reconciliation:{...aggregate.reconciliation,lineTotal:nextTotal.toFixed(2),summaryTotal:nextTotal.toFixed(2),variance:"0.00",reconciled:true}};aggregate.revisions=[{...aggregate.revisions[0],snapshot:makeSnapshot(aggregate.lines,aggregate.run.summary,aggregate.adjustments,aggregate.exceptions)},...aggregate.revisions.slice(1)];event("payroll-billing.adjusted",command);return result("Adjustment revision dibuat.");},
 async recalculate(command,signal){await wait(signal);permission(command.actor.permissionKeys,"payroll-billing.recalculate");const revision=current(command);reason(command.reason);status(["Calculated","Needs Review","Rejected"]);assertCurrentReferences();const next=aggregate.run.revisionNumber+1;aggregate={...aggregate,run:{...aggregate.run,status:"Calculated",revisionNumber:next,currentRevisionId:`rev-${next}`,version:aggregate.run.version+1,updatedAt:now,calculatedAt:now},revisions:[{...revision,id:`rev-${next}`,revisionNumber:next,version:1,status:"Calculated",reason:command.reason,actorUserId:command.actor.userId,diffSummary:"Recalculation menggunakan current applicable reference; snapshot lama immutable.",source:structuredClone(aggregate.run.source),snapshot:makeSnapshot(aggregate.lines,aggregate.run.summary,aggregate.adjustments,aggregate.exceptions)},...aggregate.revisions]};event("payroll-billing.recalculated",command);return result("Recalculation revision dibuat.");},
 async review(command,signal){await wait(signal);permission(command.actor.permissionKeys,"payroll-billing.review");current(command);reason(command.reason);status(["Needs Review"]);if(!command.data.attestation)throw new AppError(422,"PAYROLL_BILLING_ATTESTATION_REQUIRED","Attestation review wajib.",{attestation:["Konfirmasi review."]},false,"demo-payroll-attestation");authoritativeReadiness();aggregate.run={...aggregate.run,status:"Reviewed",version:aggregate.run.version+1,reviewedAt:now,reviewedByUserId:command.actor.userId,updatedAt:now};aggregate.readiness={readyToReview:false,readyToLock:true,blockers:[],nextAction:"Lock revision setelah attestation."};event("payroll-billing.reviewed",command);return result("Run direview.");},
 async reject(command,signal){await wait(signal);permission(command.actor.permissionKeys,"payroll-billing.reject");current(command);reason(command.reason);status(["Needs Review","Reviewed"]);aggregate.run={...aggregate.run,status:"Rejected",version:aggregate.run.version+1,rejectedAt:now,rejectedByUserId:command.actor.userId,updatedAt:now};event("payroll-billing.rejected",command);return result("Run ditolak.");},
 async lock(command,signal){await wait(signal);permission(command.actor.permissionKeys,"payroll-billing.lock");current(command);reason(command.reason);status(["Reviewed"]);if(!command.data.attestation)throw new AppError(422,"PAYROLL_BILLING_ATTESTATION_REQUIRED","Attestation lock wajib.",{attestation:["Konfirmasi lock."]},false,"demo-payroll-attestation");authoritativeReadiness();aggregate.run={...aggregate.run,status:"Locked",version:aggregate.run.version+1,lockedAt:now,lockedByUserId:command.actor.userId,updatedAt:now};aggregate.readiness={readyToReview:false,readyToLock:false,blockers:[],nextAction:"Revision Locked immutable."};event("payroll-billing.locked",command);return result("Run dikunci immutable.");}
};
