import { QueryClient, QueryClientProvider } from "@tanstack/react-query";
import { act, renderHook, waitFor } from "@testing-library/react";
import { StrictMode, type ReactNode } from "react";
import { describe, expect, it, vi } from "vitest";
import { queryKeys } from "@/lib/query-keys";
import { attendanceRepositories } from "../repositories";
import { useAttendanceActivity, useAttendanceDetail, useAttendanceIssues, useAttendanceList, useAttendanceTemplate, useCorrectAttendance, useCreateAndImportAttendance, useLockAttendance, usePreviewAttendance, useRejectAttendance, useValidateAttendance } from "./hooks";
const command = { data: { batchId: "att-hook", commitDecision: "CommitAll" as const }, actor: { userId: "actor", permissionKeys: ["attendance.validate"] }, reason: "uji hook", currentVersion: 2 };
it("passes a signal and invalidates exact Attendance consumers after success", async () => { let captured: AbortSignal | undefined; const spy = vi.spyOn(attendanceRepositories.attendance, "validate").mockImplementation(async (_command, signal) => { captured = signal; return { batchId: "att-hook", version: 3, message: "ok", correlationId: "corr" }; }), client = new QueryClient(), invalidate = vi.spyOn(client, "invalidateQueries"), wrapper = ({ children }: { children: ReactNode }) => <QueryClientProvider client={client}>{children}</QueryClientProvider>, hook = renderHook(() => useValidateAttendance(), { wrapper }); await act(async () => { await hook.result.current.mutateAsync(command); }); expect(captured).toBeInstanceOf(AbortSignal); expect(captured?.aborted).toBe(false); expect(invalidate.mock.calls.map(([options]) => options?.queryKey)).toEqual([queryKeys.attendance.lists, queryKeys.attendance.detail("att-hook"), queryKeys.attendance.mapping("att-hook"), queryKeys.attendance.summary("att-hook"), ["attendance", "detail", "att-hook", "issues"], queryKeys.attendance.duplicates("att-hook"), queryKeys.attendance.revisions("att-hook"), queryKeys.attendance.readiness("att-hook"), queryKeys.attendance.activity("att-hook")]); spy.mockRestore(); });
it("aborts an owned mutation on unmount without success invalidation", async () => { let started = false; const spy = vi.spyOn(attendanceRepositories.attendance, "validate").mockImplementation((_command, signal) => new Promise((_resolve, reject) => { started = true; signal?.addEventListener("abort", () => reject(new DOMException("stop", "AbortError")), { once: true }); })), client = new QueryClient(), invalidate = vi.spyOn(client, "invalidateQueries"), wrapper = ({ children }: { children: ReactNode }) => <QueryClientProvider client={client}>{children}</QueryClientProvider>, hook = renderHook(() => useValidateAttendance(), { wrapper }); let pending: Promise<unknown>; act(() => { pending = hook.result.current.mutateAsync(command); }); const observed = pending!.catch(error => error); await waitFor(() => expect(started).toBe(true)); hook.unmount(); await expect(observed).resolves.toMatchObject({ name: "AbortError" }); expect(invalidate).not.toHaveBeenCalled(); spy.mockRestore(); });

describe("Attendance hook signal safety", () => {
  it("forwards AbortSignal to every read repository boundary", async () => {
    const captured: Record<string, AbortSignal | undefined> = {};
    const spies = [
      vi.spyOn(attendanceRepositories.attendance, "list").mockImplementation(async (_input, signal) => { captured.list = signal; return { items: [], total: 0, page: 1, pageSize: 20, hasNextPage: false }; }),
      vi.spyOn(attendanceRepositories.attendance, "template").mockImplementation(async signal => { captured.template = signal; return { available: false, version: "pending", label: "Template", reason: "Pending" }; }),
      vi.spyOn(attendanceRepositories.attendance, "get").mockImplementation(async (_id, signal) => { captured.detail = signal; throw new DOMException("stop", "AbortError"); }),
      vi.spyOn(attendanceRepositories.attendance, "issues").mockImplementation(async (_id, _input, signal) => { captured.issues = signal; return { items: [], total: 0, page: 1, pageSize: 20, hasNextPage: false }; }),
      vi.spyOn(attendanceRepositories.attendance, "activity").mockImplementation(async (_id, signal) => { captured.activity = signal; return []; }),
    ];
    const client = new QueryClient({ defaultOptions: { queries: { retry: false } } });
    const wrapper = ({ children }: { children: ReactNode }) => <QueryClientProvider client={client}>{children}</QueryClientProvider>;
    const hooks = [
      renderHook(() => useAttendanceList({ page: 1 }), { wrapper }),
      renderHook(() => useAttendanceTemplate(), { wrapper }),
      renderHook(() => useAttendanceDetail("att-signals"), { wrapper }),
      renderHook(() => useAttendanceIssues("att-signals", { page: 1 }), { wrapper }),
      renderHook(() => useAttendanceActivity("att-signals"), { wrapper }),
    ];
    await waitFor(() => expect(Object.keys(captured)).toHaveLength(5));
    for (const signal of Object.values(captured)) expect(signal).toBeInstanceOf(AbortSignal);
    hooks.forEach(hook => hook.unmount());
    spies.forEach(spy => spy.mockRestore());
  });

  it("keeps preview non-invalidating while forwarding its mutation signal", async () => {
    let captured: AbortSignal | undefined;
    const spy = vi.spyOn(attendanceRepositories.attendance, "preview").mockImplementation(async (_input, signal) => { captured = signal; return { fingerprint: "preview", mapping: [], summary: { totalRows: 0, validRows: 0, invalidRows: 0, duplicateRows: 0, warningRows: 0, commitEligibleRows: 0, blockingIssueCount: 0 }, duplicates: { withinFile: 0, priorBatch: 0, fileDuplicate: false, decision: "Allowed", note: "demo", simulated: true }, readiness: { readyToValidate: true, readyToLock: false, blockers: [], nextAction: "Commit" }, correlationId: "corr", simulated: true }; });
    const client = new QueryClient(), invalidate = vi.spyOn(client, "invalidateQueries"), wrapper = ({ children }: { children: ReactNode }) => <QueryClientProvider client={client}>{children}</QueryClientProvider>, hook = renderHook(() => usePreviewAttendance(), { wrapper });
    await act(async () => { await hook.result.current.mutateAsync({ data: { projectId: "prj-019", period: "2026-08", file: { originalFilename: "ready.xlsx", displayFilename: "ready.xlsx", mimeType: "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet", sizeBytes: 4 }, scenario: "ready" }, actor: { userId: "actor", permissionKeys: ["attendance.import"] } }); });
    expect(captured).toBeInstanceOf(AbortSignal); expect(invalidate).not.toHaveBeenCalled(); spy.mockRestore();
  });

  it("uses a fresh controller after Strict Mode setup-cleanup-setup", async () => {
    const signals: AbortSignal[] = [];
    const spy = vi.spyOn(attendanceRepositories.attendance, "createAndImport").mockImplementation(async (_input, signal) => { if (signal) signals.push(signal); return { batchId: "att-strict", version: 1, message: "ok", correlationId: "corr" }; });
    const client = new QueryClient(), wrapper = ({ children }: { children: ReactNode }) => <StrictMode><QueryClientProvider client={client}>{children}</QueryClientProvider></StrictMode>, hook = renderHook(() => useCreateAndImportAttendance(), { wrapper });
    await act(async () => { await hook.result.current.mutateAsync({ data: { projectId: "prj-019", period: "2026-08", file: { originalFilename: "ready.xlsx", displayFilename: "ready.xlsx", mimeType: "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet", sizeBytes: 4 }, scenario: "ready", previewFingerprint: "preview", commitDecision: "CommitAll" }, actor: { userId: "actor", permissionKeys: ["attendance.import"] }, reason: "strict" }); });
    expect(signals).toHaveLength(1); expect(signals[0]?.aborted).toBe(false); spy.mockRestore();
  });

  it("applies latest-call-wins and invalidates only the successful newest atomic mutation", async () => {
    const signals: AbortSignal[] = [];
    const spy = vi.spyOn(attendanceRepositories.attendance, "createAndImport").mockImplementation((input, signal) => new Promise((resolve, reject) => { if (signal) signals.push(signal); if (input.data.period === "2026-08") signal?.addEventListener("abort", () => reject(new DOMException("superseded", "AbortError")), { once: true }); else resolve({ batchId: "att-latest", version: 1, message: "ok", correlationId: "corr" }); }));
    const client = new QueryClient(), invalidate = vi.spyOn(client, "invalidateQueries"), wrapper = ({ children }: { children: ReactNode }) => <QueryClientProvider client={client}>{children}</QueryClientProvider>, hook = renderHook(() => useCreateAndImportAttendance(), { wrapper });
    const base = { data: { projectId: "prj-019", period: "2026-08", file: { originalFilename: "ready.xlsx", displayFilename: "ready.xlsx", mimeType: "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet", sizeBytes: 4 }, scenario: "ready" as const, previewFingerprint: "preview", commitDecision: "CommitAll" as const }, actor: { userId: "actor", permissionKeys: ["attendance.import"] }, reason: "latest" };
    let first: Promise<unknown>; act(() => { first = hook.result.current.mutateAsync(base).catch(error => error); }); await waitFor(() => expect(signals).toHaveLength(1)); await act(async () => { await hook.result.current.mutateAsync({ ...base, data: { ...base.data, period: "2026-09" } }); });
    await expect(first!).resolves.toMatchObject({ name: "AbortError" }); expect(signals[0]?.aborted).toBe(true); expect(signals[1]?.aborted).toBe(false); expect(invalidate.mock.calls.map(([options]) => options?.queryKey)).toEqual([queryKeys.attendance.lists, queryKeys.attendance.detail("att-latest"), queryKeys.attendance.mapping("att-latest"), queryKeys.attendance.summary("att-latest"), ["attendance", "detail", "att-latest", "issues"], queryKeys.attendance.duplicates("att-latest"), queryKeys.attendance.revisions("att-latest"), queryKeys.attendance.readiness("att-latest"), queryKeys.attendance.activity("att-latest")]); spy.mockRestore();
  });
});

describe("Attendance mutation-specific signals and invalidation", () => {
  const actor = { userId: "actor", permissionKeys: ["attendance.import", "attendance.validate", "attendance.reject", "attendance.lock"] };
  const file = { originalFilename: "ready.xlsx", displayFilename: "ready.xlsx", mimeType: "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet", sizeBytes: 4 };
  const expected = (id: string) => [queryKeys.attendance.lists, queryKeys.attendance.detail(id), queryKeys.attendance.mapping(id), queryKeys.attendance.summary(id), ["attendance", "detail", id, "issues"], queryKeys.attendance.duplicates(id), queryKeys.attendance.revisions(id), queryKeys.attendance.readiness(id), queryKeys.attendance.activity(id)];
  it("covers atomic import signal and exact invalidation", async () => { let signal: AbortSignal | undefined; const spy = vi.spyOn(attendanceRepositories.attendance, "createAndImport").mockImplementation(async (_command, current) => { signal = current; return { batchId: "att-atomic-hook", version: 1, message: "ok", correlationId: "corr" }; }), client = new QueryClient(), invalidate = vi.spyOn(client, "invalidateQueries"), wrapper = ({ children }: { children: ReactNode }) => <QueryClientProvider client={client}>{children}</QueryClientProvider>, hook = renderHook(() => useCreateAndImportAttendance(), { wrapper }); await act(async () => { await hook.result.current.mutateAsync({ data: { projectId: "prj-019", period: "2026-08", file, scenario: "ready", previewFingerprint: "preview", commitDecision: "CommitAll" }, actor, reason: "atomic" }); }); expect(signal).toBeInstanceOf(AbortSignal); expect(invalidate.mock.calls.map(([options]) => options?.queryKey)).toEqual(expected("att-atomic-hook")); spy.mockRestore(); });
  it("covers correction signal and exact invalidation", async () => { let signal: AbortSignal | undefined; const spy = vi.spyOn(attendanceRepositories.attendance, "correct").mockImplementation(async (_command, current) => { signal = current; return { batchId: "att-correct-hook", version: 2, message: "ok", correlationId: "corr" }; }), client = new QueryClient(), invalidate = vi.spyOn(client, "invalidateQueries"), wrapper = ({ children }: { children: ReactNode }) => <QueryClientProvider client={client}>{children}</QueryClientProvider>, hook = renderHook(() => useCorrectAttendance(), { wrapper }); await act(async () => { await hook.result.current.mutateAsync({ data: { batchId: "att-correct-hook", file, scenario: "ready", previewFingerprint: "preview" }, actor, reason: "correction", currentVersion: 1 }); }); expect(signal).toBeInstanceOf(AbortSignal); expect(invalidate.mock.calls.map(([options]) => options?.queryKey)).toEqual(expected("att-correct-hook")); spy.mockRestore(); });
  it("covers reject signal and exact invalidation", async () => { let signal: AbortSignal | undefined; const spy = vi.spyOn(attendanceRepositories.attendance, "reject").mockImplementation(async (_command, current) => { signal = current; return { batchId: "att-reject-hook", version: 2, message: "ok", correlationId: "corr" }; }), client = new QueryClient(), invalidate = vi.spyOn(client, "invalidateQueries"), wrapper = ({ children }: { children: ReactNode }) => <QueryClientProvider client={client}>{children}</QueryClientProvider>, hook = renderHook(() => useRejectAttendance(), { wrapper }); await act(async () => { await hook.result.current.mutateAsync({ data: { batchId: "att-reject-hook" }, actor, reason: "reject", currentVersion: 1 }); }); expect(signal).toBeInstanceOf(AbortSignal); expect(invalidate.mock.calls.map(([options]) => options?.queryKey)).toEqual(expected("att-reject-hook")); spy.mockRestore(); });
  it("covers lock signal and exact invalidation", async () => { let signal: AbortSignal | undefined; const spy = vi.spyOn(attendanceRepositories.attendance, "lock").mockImplementation(async (_command, current) => { signal = current; return { batchId: "att-lock-hook", version: 3, message: "ok", correlationId: "corr" }; }), client = new QueryClient(), invalidate = vi.spyOn(client, "invalidateQueries"), wrapper = ({ children }: { children: ReactNode }) => <QueryClientProvider client={client}>{children}</QueryClientProvider>, hook = renderHook(() => useLockAttendance(), { wrapper }); await act(async () => { await hook.result.current.mutateAsync({ data: { batchId: "att-lock-hook" }, actor, reason: "lock", currentVersion: 2 }); }); expect(signal).toBeInstanceOf(AbortSignal); expect(invalidate.mock.calls.map(([options]) => options?.queryKey)).toEqual(expected("att-lock-hook")); spy.mockRestore(); });
  it("keeps atomic, correction, validate, reject, and lock controllers live after Strict Mode remount", async () => { const signals: AbortSignal[] = [], response = { batchId: "att-strict-all", version: 3, message: "ok", correlationId: "corr" }, spies = [vi.spyOn(attendanceRepositories.attendance, "createAndImport").mockImplementation(async (_command, signal) => { if (signal) signals.push(signal); return response; }), vi.spyOn(attendanceRepositories.attendance, "correct").mockImplementation(async (_command, signal) => { if (signal) signals.push(signal); return response; }), vi.spyOn(attendanceRepositories.attendance, "validate").mockImplementation(async (_command, signal) => { if (signal) signals.push(signal); return response; }), vi.spyOn(attendanceRepositories.attendance, "reject").mockImplementation(async (_command, signal) => { if (signal) signals.push(signal); return response; }), vi.spyOn(attendanceRepositories.attendance, "lock").mockImplementation(async (_command, signal) => { if (signal) signals.push(signal); return response; })], client = new QueryClient(), wrapper = ({ children }: { children: ReactNode }) => <StrictMode><QueryClientProvider client={client}>{children}</QueryClientProvider></StrictMode>, hook = renderHook(() => ({ atomic: useCreateAndImportAttendance(), correct: useCorrectAttendance(), validate: useValidateAttendance(), reject: useRejectAttendance(), lock: useLockAttendance() }), { wrapper }); await act(async () => { await hook.result.current.atomic.mutateAsync({ data: { projectId: "prj-019", period: "2026-08", file, scenario: "ready", previewFingerprint: "preview", commitDecision: "CommitAll" }, actor, reason: "atomic" }); await hook.result.current.correct.mutateAsync({ data: { batchId: "att-strict-all", file, scenario: "ready", previewFingerprint: "preview" }, actor, reason: "correct", currentVersion: 1 }); await hook.result.current.validate.mutateAsync({ data: { batchId: "att-strict-all", commitDecision: "CommitAll" }, actor, reason: "validate", currentVersion: 1 }); await hook.result.current.reject.mutateAsync({ data: { batchId: "att-strict-all" }, actor, reason: "reject", currentVersion: 1 }); await hook.result.current.lock.mutateAsync({ data: { batchId: "att-strict-all" }, actor, reason: "lock", currentVersion: 1 }); }); expect(signals).toHaveLength(5); expect(signals.every(signal => !signal.aborted)).toBe(true); spies.forEach(spy => spy.mockRestore()); });
  it.each(["correct", "reject", "lock"] as const)("aborts %s on unmount without invalidation", async kind => { let captured: AbortSignal | undefined, started = false; type Operation = (typeof attendanceRepositories.attendance)[typeof kind]; const spy = vi.spyOn(attendanceRepositories.attendance, kind).mockImplementation(((_command: never, signal?: AbortSignal) => new Promise((_resolve, reject) => { captured = signal; started = true; signal?.addEventListener("abort", () => reject(new DOMException("stop", "AbortError")), { once: true }); })) as Operation), client = new QueryClient(), invalidate = vi.spyOn(client, "invalidateQueries"), wrapper = ({ children }: { children: ReactNode }) => <QueryClientProvider client={client}>{children}</QueryClientProvider>, hook = renderHook(() => ({ correct: useCorrectAttendance(), reject: useRejectAttendance(), lock: useLockAttendance() }), { wrapper }); let pending: Promise<unknown>; act(() => { pending = kind === "correct" ? hook.result.current.correct.mutateAsync({ data: { batchId: "att-abort", file, scenario: "ready" }, actor, reason: "abort", currentVersion: 1 }) : kind === "reject" ? hook.result.current.reject.mutateAsync({ data: { batchId: "att-abort" }, actor, reason: "abort", currentVersion: 1 }) : hook.result.current.lock.mutateAsync({ data: { batchId: "att-abort" }, actor, reason: "abort", currentVersion: 1 }); }); const observed = pending!.catch(error => error); await waitFor(() => expect(started).toBe(true)); hook.unmount(); await expect(observed).resolves.toMatchObject({ name: "AbortError" }); expect(captured?.aborted).toBe(true); expect(invalidate).not.toHaveBeenCalled(); spy.mockRestore(); });
  it.each(["correct", "reject", "lock"] as const)("gives remounted %s a fresh controller and invalidates only its success", async kind => { const signals: AbortSignal[] = []; let calls = 0; type Operation = (typeof attendanceRepositories.attendance)[typeof kind]; const spy = vi.spyOn(attendanceRepositories.attendance, kind).mockImplementation(((_command: never, signal?: AbortSignal) => { calls += 1; if (signal) signals.push(signal); if (calls === 1) return new Promise((_resolve, reject) => signal?.addEventListener("abort", () => reject(new DOMException("old request", "AbortError")), { once: true })); return Promise.resolve({ batchId: `att-${kind}-remount`, version: 2, message: "ok", correlationId: `corr-${kind}` }); }) as Operation), client = new QueryClient(), invalidate = vi.spyOn(client, "invalidateQueries"), wrapper = ({ children }: { children: ReactNode }) => <QueryClientProvider client={client}>{children}</QueryClientProvider>, first = renderHook(() => ({ correct: useCorrectAttendance(), reject: useRejectAttendance(), lock: useLockAttendance() }), { wrapper }); const mutate = (hook: typeof first) => kind === "correct" ? hook.result.current.correct.mutateAsync({ data: { batchId: `att-${kind}-remount`, file, scenario: "ready" }, actor, reason: "remount", currentVersion: 1 }) : kind === "reject" ? hook.result.current.reject.mutateAsync({ data: { batchId: `att-${kind}-remount` }, actor, reason: "remount", currentVersion: 1 }) : hook.result.current.lock.mutateAsync({ data: { batchId: `att-${kind}-remount` }, actor, reason: "remount", currentVersion: 1 }); let old: Promise<unknown>; act(() => { old = mutate(first).catch(error => error); }); await waitFor(() => expect(signals).toHaveLength(1)); first.unmount(); await expect(old!).resolves.toMatchObject({ name: "AbortError" }); expect(signals[0]?.aborted).toBe(true); expect(invalidate).not.toHaveBeenCalled(); const second = renderHook(() => ({ correct: useCorrectAttendance(), reject: useRejectAttendance(), lock: useLockAttendance() }), { wrapper }); let result: Awaited<ReturnType<typeof mutate>> | undefined; await act(async () => { result = await mutate(second); }); expect(result).toMatchObject({ batchId: `att-${kind}-remount`, correlationId: `corr-${kind}` }); expect(signals[1]).not.toBe(signals[0]); expect(signals[1]?.aborted).toBe(false); expect(invalidate.mock.calls.map(([options]) => options?.queryKey)).toEqual(expected(`att-${kind}-remount`)); expect(invalidate).toHaveBeenCalledTimes(expected(`att-${kind}-remount`).length); second.unmount(); spy.mockRestore(); });
});
