"use client";
import { useMutation,useQuery,useQueryClient } from "@tanstack/react-query";
import { normalizeOrRethrowAppError,type AppError } from "@/features/foundation/domain/errors";
import { repositories } from "@/features/foundation/repositories";
import type { PaginatedResult } from "@/features/foundation/repositories/contracts";
import { queryKeys } from "@/lib/query-keys";
import { normalizeMasterListQuery } from "../domain/list-query";
import type { MasterKind,MasterListQuery,MasterMutationResult,MasterTransition,PartyCreateCommand,PartyDetail,PartyListItem,PartyUpdateCommand,ReferenceCreateCommand,ReferenceDetail,ReferenceListItem,ReferenceUpdateCommand } from "../domain/types";

const repo=()=>{const value=repositories.masterData;if(!value.listParties||!value.getParty||!value.createParty||!value.updateParty||!value.listReferences||!value.getReference||!value.createReference||!value.updateReference||!value.transition)throw new Error("Master data repository belum dikomposisikan.");return{listParties:value.listParties,getParty:value.getParty,createParty:value.createParty,updateParty:value.updateParty,listReferences:value.listReferences,getReference:value.getReference,createReference:value.createReference,updateReference:value.updateReference,transition:value.transition};};
const safe=async<T>(operation:()=>Promise<T>)=>{try{return await operation();}catch(error){throw normalizeOrRethrowAppError(error);}};
export function useMasterList(kind:MasterKind,params:MasterListQuery,enabled=true){const normalized=normalizeMasterListQuery(params);return useQuery<PaginatedResult<PartyListItem>|PaginatedResult<ReferenceListItem>,AppError>({queryKey:queryKeys.masterManagement.list(kind,normalized),enabled,queryFn:({signal})=>safe(async()=>{if(kind==="customers"||kind==="vendors")return repo().listParties(kind,normalized,signal);return repo().listReferences(kind,normalized,signal);})});}
export function useMasterDetail(kind:MasterKind,id:string,enabled=true){return useQuery<PartyDetail|ReferenceDetail,AppError>({queryKey:queryKeys.masterManagement.detail(kind,id),enabled,queryFn:({signal})=>safe(async()=>{if(kind==="customers"||kind==="vendors")return repo().getParty(kind,id,signal);return repo().getReference(kind,id,signal);})});}
function useMasterMutation<T>(kind:MasterKind,fn:(value:T)=>Promise<MasterMutationResult>){const client=useQueryClient();return useMutation<MasterMutationResult,AppError,T>({mutationFn:(value)=>safe(()=>fn(value)),onSuccess:async(result)=>{await Promise.all([client.invalidateQueries({queryKey:["master-management",kind,"list"]}),client.invalidateQueries({queryKey:queryKeys.masterManagement.detail(kind,result.id)}),client.invalidateQueries({queryKey:queryKeys.masterManagement.usage(kind,result.id)}),client.invalidateQueries({queryKey:queryKeys.audit.byObject(kind,result.id)})]);}});}
export function useCreateParty(kind:"customers"|"vendors"){return useMasterMutation<PartyCreateCommand>(kind,(value)=>repo().createParty(kind,value));}export function useUpdateParty(kind:"customers"|"vendors"){return useMasterMutation<PartyUpdateCommand>(kind,(value)=>repo().updateParty(kind,value));}
export function useCreateReference(kind:"services"|"billingCycles"){return useMasterMutation<ReferenceCreateCommand>(kind,(value)=>repo().createReference(kind,value));}export function useUpdateReference(kind:"services"|"billingCycles"){return useMasterMutation<ReferenceUpdateCommand>(kind,(value)=>repo().updateReference(kind,value));}
export function useMasterTransition(kind:MasterKind){return useMasterMutation<MasterTransition>(kind,(value)=>repo().transition(kind,value));}
