import {describe,expect,it} from "vitest";
import {calculatePayrollBillingReadiness,diffPayrollBillingRevisions,normalizePayrollBillingExceptionQuery,normalizePayrollBillingListQuery,validateCurrentPayrollBillingReferences} from "./hardening";
import type {PayrollBillingComponent,PayrollCurrentReferences,PayrollRevisionSnapshot} from "./types";

const source={projectId:"p1",projectLabel:"P1",customerId:"c1",customerLabel:"C1",sphId:"s1",sphLabel:"S1",attendanceBatchId:"a1",attendanceRevision:1,attendancePeriod:"2026-07",attendanceRows:1,rateVersionId:"r1",rateVersionLabel:"R1",branchLabel:"B",serviceLabel:"S",currency:"IDR" as const,unit:"HK",capturedAt:"2026-08-01T00:00:00+07:00"};
const line=(id:string,amount:string,components:readonly PayrollBillingComponent[]=[{code:"BASE",label:"Base",amount,applicability:"Applicable",source:"RateSnapshot"}])=>({id,employeeReference:"••••4821",branchLabel:"B",serviceLabel:"S",quantity:"1.0000000001",unitRate:amount,componentSubtotal:amount,adjustment:"0",withholding:"0",finalAmount:amount,hasException:false,trace:{attendanceBatchId:"a1",attendanceRevision:1,sourceRowId:id,quantity:"1.0000000001",unit:"HK",rateVersionId:"r1",rateLineId:"rl1",unitRate:amount,formulaLabel:"metadata",roundingMethod:"none",calculatedAt:"2026-08-01T00:00:00+07:00"},components});
const snapshot=(id:string,total:string,lines= [line("l1",total)]):PayrollRevisionSnapshot=>{const summary={attendanceSourceTotal:"1",baseAmount:total,managementFee:"0",otherCharges:"0",taxBase:total,roundingAmount:"0",adjustmentAmount:"0",grandTotal:total},reconciliation={sourceCalculatedTotal:total,lineTotal:total,summaryTotal:total,variance:"0",reconciled:true,explanation:"test"},calculatedAt="2026-08-01T00:00:00+07:00";return{revision:{id,revisionNumber:id==="v1"?1:2,version:1,status:"Calculated",reason:"test",total,exceptionCount:0,createdAt:calculatedAt,actorUserId:"u1",diffSummary:"test",source:structuredClone(source),snapshot:{source:structuredClone(source),lines:structuredClone(lines),adjustments:[],exceptions:[],summary:structuredClone(summary),reconciliation,calculatedAt,calculatedByUserId:"u1"}},calculatedAt,currency:"IDR",lines,summary};};
const refs:PayrollCurrentReferences={project:{id:"p1",exists:true,terminal:false},customer:{id:"c1",exists:true},sph:{id:"s1",exists:true,projectId:"p1"},attendance:{id:"a1",exists:true,eligible:true,projectId:"p1",period:"2026-07",revision:1},rateVersion:{id:"r1",exists:true,applicable:true,currency:"IDR",unit:"HK"},service:{label:"S",exists:true,active:true,projectId:"p1"},branch:{label:"B",exists:true,active:true,projectId:"p1"}};
describe("payroll billing hardening",()=>{
it("diffs added removed changed lines and stable component identities",()=>{const before=snapshot("v1","10",[line("removed","2"),line("changed","8")]);const after=snapshot("v2","12",[line("added","2"),line("changed","10",[{code:"EXTRA",label:"Extra",amount:"1",applicability:"Applicable",source:"Adjustment"},{code:"BASE",label:"Base",amount:"9",applicability:"Applicable",source:"RateSnapshot"}])]);const frozen=structuredClone({before,after});const diff=diffPayrollBillingRevisions(before,after);expect(diff.addedLines.map(x=>x.id)).toEqual(["added"]);expect(diff.removedLines.map(x=>x.id)).toEqual(["removed"]);expect(diff.changedLines[0]).toMatchObject({lineId:"changed",finalAmountDelta:"2",components:[{code:"BASE",kind:"Changed"},{code:"EXTRA",kind:"Added"}]});expect({before,after}).toEqual(frozen);});
it("uses Decimal precision and exposes denominator zero",()=>{const diff=diffPayrollBillingRevisions(snapshot("v1","0"),snapshot("v2","0.000000000000000001"));expect(diff.summary).toEqual({before:"0",after:"0.000000000000000001",absoluteDelta:"0.000000000000000001",percentageDelta:undefined,denominatorZero:true});});
it("reports typed current-reference issues without mutating historical snapshot",()=>{const value=snapshot("v1","10"),before=structuredClone(value);const issues=validateCurrentPayrollBillingReferences(value,{...refs,service:{...refs.service,active:false},branch:{...refs.branch,projectId:"other"}},"v2");expect(issues.map(x=>x.code)).toEqual(expect.arrayContaining(["REVISION_NOT_CURRENT","SERVICE_INVALID","BRANCH_INVALID"]));expect(value).toEqual(before);expect(value.revision.source.serviceLabel).toBe("S");});
it("computes authoritative readiness from issues exceptions and reconciliation",()=>{const result=calculatePayrollBillingReadiness(snapshot("v1","10"),refs,"v1",1,false);expect(result.ready).toBe(false);expect(result.blockers.map(x=>x.code)).toEqual(["NO_BLOCKING_EXCEPTIONS","RECONCILED"]);});
it("normalizes equivalent list and exception params to stable values",()=>{expect(normalizePayrollBillingListQuery({search:" x ",statuses:["Locked","Draft","Locked"],page:0})).toEqual(normalizePayrollBillingListQuery({search:"x",statuses:["Draft","Locked"],page:1,pageSize:20,direction:"desc",sort:"updatedAt"}));expect(normalizePayrollBillingExceptionQuery({search:" e ",severities:["Warning","Error","Warning"],pageSize:50})).toMatchObject({search:"e",severities:["Error","Warning"],pageSize:50});});
});
