import type { CurrencyCode, EntityId, IsoDateTime, VersionNumber } from "@/features/foundation/domain/models";
export type PayrollBillingStatus = "Draft" | "Calculated" | "Needs Review" | "Reviewed" | "Locked" | "Rejected";
export type PayrollCapability = "view" | "create" | "adjust" | "review" | "lock";
export interface PayrollBillingSourceSnapshot { projectId:EntityId; projectLabel:string; customerId:EntityId; customerLabel:string; sphId:EntityId; sphLabel:string; attendanceBatchId:EntityId; attendanceRevision:number; attendancePeriod:string; attendanceRows:number; rateVersionId:EntityId; rateVersionLabel:string; branchLabel:string; serviceLabel:string; currency:CurrencyCode; unit:string; capturedAt:IsoDateTime; }
export interface PayrollBillingComponent { code:string; label:string; amount:string; applicability:"Applicable"|"NotApplicable"; source:"RateSnapshot"|"AttendanceSnapshot"|"Adjustment"; }
export interface PayrollCalculationTrace { attendanceBatchId:EntityId; attendanceRevision:number; sourceRowId:string; quantity:string; unit:string; rateVersionId:EntityId; rateLineId:EntityId; unitRate:string; formulaLabel:string; roundingMethod:string; calculatedAt:IsoDateTime; }
export interface PayrollBillingLine { id:EntityId; employeeReference:string; branchLabel:string; serviceLabel:string; quantity:string; unitRate:string; componentSubtotal:string; adjustment:string; withholding:string; finalAmount:string; hasException:boolean; trace:PayrollCalculationTrace; components:readonly PayrollBillingComponent[]; }
export interface PayrollBillingException { id:EntityId; severity:"Warning"|"Error"; code:string; lineId?:EntityId; explanation:string; affectedValue:string; suggestedAction:string; blocking:boolean; }
export interface PayrollBillingAdjustment { id:EntityId; scope:"Run"|"Line"; lineId?:EntityId; type:"Addition"|"Deduction"; amount:string; reason:string; note?:string; actorUserId:EntityId; createdAt:IsoDateTime; }
export interface PayrollBillingSummary { attendanceSourceTotal:string; baseAmount:string; rewardAmount?:string; bpjsAmount?:string; managementFee:string; otherCharges:string; taxBase:string; vatAmount?:string; withholdingAmount?:string; roundingAmount:string; adjustmentAmount:string; grandTotal:string; }
export interface PayrollBillingReadiness { readyToReview:boolean; readyToLock:boolean; blockers:readonly string[]; nextAction:string; }
export interface PayrollBillingRevisionSnapshot { source:PayrollBillingSourceSnapshot; lines:readonly PayrollBillingLine[]; adjustments:readonly PayrollBillingAdjustment[]; exceptions:readonly PayrollBillingException[]; summary:PayrollBillingSummary; reconciliation:PayrollBillingRunDetail["reconciliation"]; calculatedAt:IsoDateTime; calculatedByUserId:EntityId; }
export interface PayrollBillingRevision { id:EntityId; revisionNumber:number; version:VersionNumber; status:PayrollBillingStatus; reason:string; total:string; exceptionCount:number; createdAt:IsoDateTime; actorUserId:EntityId; diffSummary:string; source:PayrollBillingSourceSnapshot; snapshot:PayrollBillingRevisionSnapshot; }
export interface PayrollBillingActivity { id:EntityId; action:string; actorUserId:EntityId; actorName?:string; occurredAt:IsoDateTime; reason:string; revisionNumber:number; correlationId:string; summary:string; }
export interface PayrollBillingRun { id:EntityId; status:PayrollBillingStatus; revisionNumber:number; currentRevisionId:EntityId; version:VersionNumber; currency:CurrencyCode; source:PayrollBillingSourceSnapshot; summary:PayrollBillingSummary; exceptionCount:number; createdAt:IsoDateTime; updatedAt:IsoDateTime; calculatedAt?:IsoDateTime; reviewedAt?:IsoDateTime; reviewedByUserId?:EntityId; rejectedAt?:IsoDateTime; rejectedByUserId?:EntityId; lockedAt?:IsoDateTime; lockedByUserId?:EntityId; }
export interface PayrollBillingRunListItem extends PayrollBillingRun { nextAction:string; reconciled:boolean; }
export interface PayrollBillingRunDetail { run:PayrollBillingRun; lines:readonly PayrollBillingLine[]; exceptions:readonly PayrollBillingException[]; adjustments:readonly PayrollBillingAdjustment[]; revisions:readonly PayrollBillingRevision[]; activity:readonly PayrollBillingActivity[]; readiness:PayrollBillingReadiness; reconciliation:{sourceCalculatedTotal:string; lineTotal:string; summaryTotal:string; variance:string; reconciled:boolean; explanation:string}; }
export interface PayrollBillingListQuery { search?:string; projectIds?:readonly EntityId[]; periods?:readonly string[]; statuses?:readonly PayrollBillingStatus[]; sort?:"updatedAt"|"period"|"total"; direction?:"asc"|"desc"; page?:number; pageSize?:10|20|50; }
export interface PaginatedResult<T>{items:readonly T[];total:number;page:number;pageSize:number;hasNextPage:boolean;totalPages:number;}
export interface PayrollCommand<T>{data:T;actor:{userId:EntityId;permissionKeys:readonly string[]};reason:string;currentVersion?:VersionNumber;}
export type CreatePayrollBillingCommand=PayrollCommand<{attendanceBatchId:EntityId;projectId:EntityId;period:string;sphId:EntityId}>;
export type AdjustPayrollBillingCommand=PayrollCommand<{runId:EntityId;revisionId:EntityId;revisionVersion:VersionNumber;scope:"Run"|"Line";lineId?:EntityId;type:"Addition"|"Deduction";amount:string;currency:CurrencyCode;note?:string}>;
export type RecalculatePayrollBillingCommand=PayrollCommand<{runId:EntityId;revisionId:EntityId;revisionVersion:VersionNumber}>;
export type ReviewPayrollBillingCommand=PayrollCommand<{runId:EntityId;revisionId:EntityId;revisionVersion:VersionNumber;attestation:boolean}>;
export type RejectPayrollBillingCommand=PayrollCommand<{runId:EntityId;revisionId:EntityId;revisionVersion:VersionNumber}>;
export type LockPayrollBillingCommand=PayrollCommand<{runId:EntityId;revisionId:EntityId;revisionVersion:VersionNumber;attestation:boolean}>;
export type PayrollMutationResult={runId:EntityId;version:VersionNumber;revisionNumber:number;message:string;correlationId:string};

export type PayrollExceptionSeverity="Warning"|"Error";
export interface PayrollBillingExceptionListItem extends PayrollBillingException { sourceReference?:string; affectedField?:string; calculatedAt?:IsoDateTime; }
export interface PayrollBillingExceptionQuery { search?:string; severities?:readonly PayrollExceptionSeverity[]; blocking?:boolean; sort?:"severity"|"code"|"calculatedAt"; direction?:"asc"|"desc"; page?:number; pageSize?:10|20|50; }
export interface NormalizedPayrollBillingExceptionQuery { search:string; severities:readonly PayrollExceptionSeverity[]; blocking?:boolean; sort:"severity"|"code"|"calculatedAt"; direction:"asc"|"desc"; page:number; pageSize:10|20|50; }
export interface NormalizedPayrollBillingListQuery { search:string; projectIds:readonly EntityId[]; periods:readonly string[]; statuses:readonly PayrollBillingStatus[]; sort:"updatedAt"|"period"|"total"; direction:"asc"|"desc"; page:number; pageSize:10|20|50; }

export interface PayrollRevisionSnapshot { revision:PayrollBillingRevision; calculatedAt?:IsoDateTime; currency:CurrencyCode; lines:readonly PayrollBillingLine[]; summary:PayrollBillingSummary; }
export interface PayrollComponentChange { code:string; kind:"Added"|"Removed"|"Changed"; before?:PayrollBillingComponent; after?:PayrollBillingComponent; amountDelta?:string; }
export interface PayrollLineChange { lineId:EntityId; before:PayrollBillingLine; after:PayrollBillingLine; quantityDelta:string; rateDelta:string; finalAmountDelta:string; components:readonly PayrollComponentChange[]; changedFields:readonly string[]; }
export interface PayrollRevisionDiff { source:{id:EntityId;number:number;status:PayrollBillingStatus;calculatedAt?:IsoDateTime}; target:{id:EntityId;number:number;status:PayrollBillingStatus;calculatedAt?:IsoDateTime}; addedLines:readonly PayrollBillingLine[]; removedLines:readonly PayrollBillingLine[]; changedLines:readonly PayrollLineChange[]; unchangedCount:number; summary:{before:string;after:string;absoluteDelta:string;percentageDelta?:string;denominatorZero:boolean}; sourceChanges:readonly {field:string;before:string;after:string}[]; issues:readonly {code:"CURRENCY_MISMATCH";message:string}[]; }

export type PayrollReferenceType="Project"|"Customer"|"SPH"|"Attendance"|"RateVersion"|"Service"|"Branch"|"Currency"|"Unit"|"Line"|"Revision";
export interface PayrollReferenceIssue { code:string; severity:"Warning"|"Error"; blocking:boolean; referenceType:PayrollReferenceType; referenceId?:EntityId; lineId?:EntityId; field:string; explanation:string; currentState?:string; expectedState?:string; suggestedAction:string; }
export interface PayrollCurrentReferences { project:{id:EntityId;exists:boolean;terminal:boolean}; customer:{id:EntityId;exists:boolean}; sph:{id:EntityId;exists:boolean;projectId:EntityId}; attendance:{id:EntityId;exists:boolean;eligible:boolean;projectId:EntityId;period:string;revision:number}; rateVersion:{id:EntityId;exists:boolean;applicable:boolean;currency:string;unit:string}; service:{label:string;exists:boolean;active:boolean;projectId:EntityId}; branch:{label:string;exists:boolean;active:boolean;projectId:EntityId}; }
export interface PayrollReadinessCheck { code:string;label:string;passed:boolean;blocking:boolean;explanation:string;issueCount:number;nextAction:string; }
export interface PayrollAuthoritativeReadiness { currentRevisionId:EntityId;ready:boolean;checks:readonly PayrollReadinessCheck[];blockers:readonly PayrollReadinessCheck[];nextAction:string; }
