import type { BillingCycle,Customer,DocumentMetadata,DocumentVersion,ProjectAggregate,RateVersion,Service,User } from "@/features/foundation/domain/models";
export type ReadinessOwner="Admin/PIC"|"PIC"|"Finance/PIC"|"Admin";
export interface ReadinessItem { code:string;label:string;complete:boolean;description:string;nextAction:string;owner:ReadinessOwner;severity:"blocker"|"warning"; }
export interface ProjectReadinessResult { ready:boolean;completedCount:number;totalCount:number;items:readonly ReadinessItem[];blockers:readonly ReadinessItem[];warnings:readonly ReadinessItem[];nextActions:readonly string[]; }
export interface ReadinessContext { aggregate:ProjectAggregate;customers:readonly Customer[];users:readonly User[];billingCycles:readonly BillingCycle[];services:readonly Service[];documentVersions:readonly DocumentVersion[]; }
const codePattern=/^PRJ-[A-Z0-9]+-[0-9]{3,}$/;
export function evaluateProjectReadiness(context:ReadinessContext):ProjectReadinessResult {const {project,sph,branches,rates,documents}=context.aggregate;const customer=context.customers.find((item)=>item.id===project.customerId);const pic=context.users.find((item)=>item.id===project.picUserId);const cycle=context.billingCycles.find((item)=>item.id===sph.billingCycleId);const activeServices=project.serviceIds.filter((id)=>context.services.some((service)=>service.id===id&&service.isActive));const validRate=(rates as readonly RateVersion[]).some((rate)=>rate.status==="Active"||rate.status==="Scheduled");const contractDocs=(documents.sph as readonly DocumentMetadata[]).flatMap((doc)=>context.documentVersions.filter((version)=>version.documentId===doc.id&&version.status==="Available"));const validPeriod=Boolean(sph.startDate&&sph.endDate&&sph.endDate>=sph.startDate);const definitions:[string,string,boolean,string,string,ReadinessOwner][]=[
  ["code","Project Code valid",codePattern.test(project.code),"Format PRJ-UNIT-001 atau setara.","Perbaiki Project Code","Admin/PIC"],["name","Nama project",Boolean(project.name.trim()),"Nama operasional project tersedia.","Isi nama project","Admin/PIC"],["customer","Customer aktif",Boolean(customer?.isActive),"Customer wajib aktif.","Pilih customer aktif","Admin"],["pic","PIC aktif",pic?.status==="Active","PIC menjadi owner operasional.","Pilih PIC aktif","Admin/PIC"],["sph","Nomor SPH",Boolean(sph.number.trim()),"SPH menautkan kontrak project.","Isi nomor SPH","Admin/PIC"],["period","Periode kontrak valid",validPeriod,"Tanggal akhir tidak mendahului tanggal mulai.","Perbaiki periode kontrak","Admin/PIC"],["cycle","Billing cycle aktif",Boolean(cycle?.isActive),"Siklus penagihan wajib aktif.","Pilih billing cycle aktif","Admin"],["cost-center","Cost center",Boolean(sph.costCenter.trim()),"Cost center diperlukan untuk penelusuran biaya.","Isi cost center","Admin/PIC"],["branch","Cabang aktif",branches.some((branch)=>branch.isActive),"Minimal satu cabang aktif.","Tambahkan atau aktifkan cabang","Admin/PIC"],["service","Layanan aktif",activeServices.length>0,"Minimal satu layanan aktif.","Pilih layanan aktif","Admin/PIC"],["rate","Rate aktif/terjadwal",validRate,"Rate lengkap dikelola pada Tahap 1D.","Siapkan rate pada Tahap 1D","Finance/PIC"],["document","Dokumen kontrak tersedia",contractDocs.length>0,"Versi dokumen SPH harus Available.","Unggah dokumen kontrak","Admin/PIC"]];
  const items:ReadinessItem[]=definitions.map(([code,label,complete,description,nextAction,owner])=>({code,label,complete,description,nextAction,owner,severity:"blocker"}));if(project.status==="Closed"||project.status==="Cancelled")items.push({code:"status",label:`Status ${project.status}`,complete:false,description:"Status ini tidak dapat diaktifkan langsung.",nextAction:"Gunakan workflow perubahan status yang disetujui",owner:"PIC",severity:"blocker"});const blockers=items.filter((item)=>!item.complete&&item.severity==="blocker");const warnings=items.filter((item)=>!item.complete&&item.severity==="warning");return{ready:blockers.length===0,completedCount:items.filter((item)=>item.complete).length,totalCount:items.length,items,blockers,warnings,nextActions:[...new Set(blockers.map((item)=>item.nextAction))]};}
