import { describe,expect,it } from "vitest";
import type { AuditEvent,Project,SphContract } from "@/features/foundation/domain/models";
import { createMasterDataManagement } from "./mock-adapter";

const actor={userId:"tester",permissionKeys:["master-data.view","master-data.manage"]};
const project={id:"project-usage",code:"PRJ-TST-001",name:"Demo",description:"",customerId:"cus-aruna",vendorId:"ven-mitra",picUserId:"tester",status:"Active",branchIds:[],serviceIds:["svc-fm"],sphId:"sph",updatedAt:"2026-01-01T00:00:00Z",version:1} satisfies Project;
const contract={id:"sph",projectId:"project-usage",number:"SPH",startDate:"2026-01-01",endDate:"2026-12-31",billingCycleId:"bc-monthly",costCenter:"CC",documentId:"doc"} satisfies SphContract;
const partyData={code:"CUS-NEW",name:"Customer Demo",legalName:"PT Customer Demo",taxIdentifier:"1234567890",billingAddress:"Alamat Demo",city:"Jakarta",province:"DKI Jakarta",postalCode:"12345",contactName:"Kontak",email:"demo@example.test",phone:"081234567890",paymentTermsDays:30,category:"Corporate",notes:"Catatan"};
const serviceData={code:"SVC-NEW",name:"Service Demo",description:"Deskripsi service",category:"Operations",unit:"Person-month"};
function expectNoCommandMetadata(record:object){expect(record).not.toHaveProperty("actor");expect(record).not.toHaveProperty("permissionKeys");expect(record).not.toHaveProperty("reason");expect(record).not.toHaveProperty("currentVersion");}

describe("master repository lifecycle",()=>{
 it("calculates project, service and billing-cycle dependency",async()=>{const repo=createMasterDataManagement([project],[],[contract]);expect((await repo.getParty("customers","cus-aruna")).usage.canDeactivate).toBe(false);expect((await repo.getReference("services","svc-fm")).usage.projectCount).toBe(1);expect((await repo.getReference("billingCycles","bc-monthly")).usage.projectCount).toBe(1);});
 it("blocks referenced deactivation without audit",async()=>{const audits:AuditEvent[]=[];const repo=createMasterDataManagement([project],audits,[contract]);await expect(repo.transition("billingCycles",{id:"bc-monthly",currentVersion:1,active:false,reason:"Demo",actor})).rejects.toMatchObject({status:422,code:"MASTER_DEPENDENCY_BLOCKED"});expect(audits).toHaveLength(0);});
 it("deactivates safe record and retains it historically",async()=>{const audits:AuditEvent[]=[];const repo=createMasterDataManagement([],audits,[]);await repo.transition("customers",{id:"cus-orbit",currentVersion:1,active:false,reason:"Tidak digunakan",actor});expect((await repo.getParty("customers","cus-orbit")).status).toBe("Inactive");expect(audits[0]?.action).toBe("master.deactivated");});
 it("requires reason and permission",async()=>{const repo=createMasterDataManagement([],[],[]);await expect(repo.transition("customers",{id:"cus-orbit",currentVersion:1,active:false,reason:"",actor})).rejects.toMatchObject({status:422});await expect(repo.transition("customers",{id:"cus-orbit",currentVersion:1,active:false,reason:"Demo",actor:{userId:"viewer",permissionKeys:["master-data.view"]}})).rejects.toMatchObject({status:403});});
 it("never persists Party command metadata after create and update",async()=>{const repo=createMasterDataManagement([],[],[]);const created=await repo.createParty("customers",{data:partyData,actor});const createdRecord=await repo.getParty("customers",created.id);expectNoCommandMetadata(createdRecord);await repo.updateParty("customers",{id:created.id,currentVersion:created.version,reason:"Koreksi nama",data:{...partyData,name:"Customer Baru"},actor});const updated=await repo.getParty("customers",created.id);expect(updated.name).toBe("Customer Baru");expectNoCommandMetadata(updated);});
 it("never persists Reference command metadata after create and update",async()=>{const repo=createMasterDataManagement([],[],[]);const created=await repo.createReference("services",{data:serviceData,actor});expectNoCommandMetadata(await repo.getReference("services",created.id));await repo.updateReference("services",{id:created.id,currentVersion:1,reason:"Koreksi unit",data:{...serviceData,unit:"Hour"},actor});const updated=await repo.getReference("services",created.id);expect(updated.unit).toBe("Hour");expectNoCommandMetadata(updated);});
 it("uses attempted version and actual safe Party diff",async()=>{const repo=createMasterDataManagement([],[],[]);try{await repo.updateParty("customers",{id:"cus-aruna",currentVersion:0,reason:"Demo",data:{...partyData,code:"CUS-001",name:"Nama yang dikirim",taxIdentifier:"9876543210"},actor});expect.fail("Expected conflict");}catch(error){expect(error).toMatchObject({status:409,metadata:{userVersion:0,latestVersion:2,diffs:expect.arrayContaining([expect.objectContaining({field:"name",before:"Nama yang dikirim",after:"PT Aruna Nusantara"}),expect.objectContaining({field:"taxIdentifier",before:"••••••3210",after:"••••••••4821"})])}});expect(JSON.stringify(error)).not.toContain("9876543210");}});
 it("uses actual Reference diff",async()=>{const repo=createMasterDataManagement([],[],[]);await expect(repo.updateReference("services",{id:"svc-fm",currentVersion:0,reason:"Demo",data:{...serviceData,code:"SVC-FM",unit:"Hour"},actor})).rejects.toMatchObject({status:409,metadata:{userVersion:0,latestVersion:2,diffs:expect.arrayContaining([expect.objectContaining({field:"unit",before:"Hour",after:"Person-month"})])}});});
 it("returns structured lifecycle conflict without writing audit",async()=>{const audits:AuditEvent[]=[];const repo=createMasterDataManagement([],audits,[]);await expect(repo.transition("customers",{id:"cus-aruna",currentVersion:0,active:false,reason:"Demo",actor})).rejects.toMatchObject({status:409,metadata:{userVersion:0,latestVersion:2,diffs:[expect.objectContaining({field:"status",before:"Tujuan: Inactive",after:"Status terbaru: Active"})]}});expect(audits).toHaveLength(0);});
 it("preserves cancellation",async()=>{const repo=createMasterDataManagement([],[],[]),controller=new AbortController(),request=repo.listParties("customers",{},controller.signal);controller.abort();await expect(request).rejects.toMatchObject({name:"AbortError"});});
});
