import { AppError } from "@/features/foundation/domain/errors";
import { maskSensitive } from "@/features/foundation/domain/permissions";
import type { AuditEvent,Project,SphContract } from "@/features/foundation/domain/models";
import type { BillingCycleFields,MasterDataManagementRepository,MasterKind,MasterListQuery,MasterMutationResult,MasterStatus,PartyFields,PartyRecord,ReferenceFields,ReferenceRecord,ServiceFields,UsageSummary } from "../domain/types";
import { normalizeMasterListQuery } from "../domain/list-query";

const at="2026-08-10T10:00:00+07:00";
const parties={customers:[party("cus-aruna","CUS-001","PT Aruna Nusantara",2),party("cus-orbit","CUS-003","PT Orbit Demo",1)],vendors:[party("ven-mitra","VEN-001","PT Mitra Sarana",1),party("ven-cakra","VEN-002","PT Cakra Demo",1)]} satisfies Record<"customers"|"vendors",PartyRecord[]>;
const references={services:[reference("svc-fm","SVC-FM","Facility Management",2),reference("svc-cleaning","SVC-CLN","Cleaning Demo",1)],billingCycles:[reference("bc-monthly","BC-MONTHLY","Bulanan - tanggal 25",1),reference("bc-weekly","BC-WEEKLY","Mingguan Demo",1)]} satisfies Record<"services"|"billingCycles",ReferenceRecord[]>;
function party(id:string,code:string,name:string,version:number):PartyRecord{return{id,code,name,legalName:name,taxIdentifierMasked:"••••••••4821",billingAddress:"Alamat demo",city:"Jakarta",province:"DKI Jakarta",postalCode:"12190",contactName:"Kontak Demo",email:"kontak@example.test",phone:"••••2211",paymentTermsDays:30,category:"Corporate",notes:"Data demo",status:"Active",createdAt:at,updatedAt:at,version};}
function reference(id:string,code:string,name:string,version:number):ReferenceRecord{return{id,code,name,description:`${name} untuk data demo.`,category:"Operations",unit:"Person-month",frequency:"Monthly",cutoffDay:25,invoiceOffsetDays:2,dueDays:30,status:"Active",createdAt:at,updatedAt:at,version};}
async function latency(signal?:AbortSignal){if(signal?.aborted)throw new DOMException("Dibatalkan","AbortError");await new Promise<void>((resolve,reject)=>{const timer=setTimeout(resolve,120);signal?.addEventListener("abort",()=>{clearTimeout(timer);reject(new DOMException("Dibatalkan","AbortError"));},{once:true});});}
function requireManage(keys:readonly string[]){if(!keys.includes("master-data.manage"))throw new AppError(403,"MASTER_DATA_FORBIDDEN","Anda tidak memiliki izin mengelola master data.",{},false,"demo-master-forbidden");}
function usage(kind:MasterKind,id:string,projects:readonly Project[],contracts:readonly SphContract[]):UsageSummary{const ids=projects.filter((project)=>kind==="customers"?project.customerId===id:kind==="vendors"?project.vendorId===id:kind==="services"?project.serviceIds.includes(id):contracts.some((contract)=>contract.projectId===project.id&&contract.billingCycleId===id)).map((project)=>project.id);const canDeactivate=ids.length===0;return{projectCount:ids.length,projectIds:ids,historicalReferenceCount:ids.length,canDeactivate,blockingReason:canDeactivate?undefined:`Masih direferensikan oleh ${ids.length} project aktif atau historis.`};}
function page<T extends {code:string;name:string;status:MasterStatus;updatedAt:string}>(source:readonly T[],input:MasterListQuery){const query=normalizeMasterListQuery(input);const filtered=source.filter((item)=>(!query.search||`${item.code} ${item.name}`.toLocaleLowerCase("id-ID").includes(query.search))&&(!query.statuses.length||query.statuses.includes(item.status))).sort((a,b)=>{const compared=String(a[query.sort]).localeCompare(String(b[query.sort]),"id-ID",{numeric:true});return(query.direction==="asc"?compared:-compared)||a.code.localeCompare(b.code);});const start=(query.page-1)*query.pageSize;return{items:filtered.slice(start,start+query.pageSize),total:filtered.length,page:query.page,pageSize:query.pageSize,hasNextPage:start+query.pageSize<filtered.length};}
function audit(events:AuditEvent[],kind:MasterKind,id:string,actor:string,action:string,reason:string,correlationId:string){events.unshift({id:`audit-${correlationId}`,actorUserId:actor,action,objectType:kind,objectId:id,occurredAt:new Date().toISOString(),reason,correlationId});}
type Diff={field:string;label:string;before:string;after:string};
function addDiff(diffs:Diff[],field:string,label:string,submitted:string|number,latest:string|number){if(submitted!==latest)diffs.push({field,label,before:String(submitted),after:String(latest)});}
function partyDiff(data:PartyFields,current:PartyRecord){const diffs:Diff[]=[];addDiff(diffs,"name","Nama",data.name,current.name);addDiff(diffs,"legalName","Nama legal",data.legalName,current.legalName);addDiff(diffs,"taxIdentifier","NPWP",data.taxIdentifier?maskSensitive(data.taxIdentifier):"Tidak diubah",current.taxIdentifierMasked);addDiff(diffs,"billingAddress","Alamat penagihan",data.billingAddress,current.billingAddress);addDiff(diffs,"city","Kota",data.city,current.city);addDiff(diffs,"province","Provinsi",data.province,current.province);addDiff(diffs,"postalCode","Kode pos",data.postalCode,current.postalCode);addDiff(diffs,"contactName","Nama kontak",data.contactName,current.contactName);addDiff(diffs,"email","Email",data.email,current.email);addDiff(diffs,"phone","Telepon",maskSensitive(data.phone),current.phone);addDiff(diffs,"paymentTermsDays","Termin pembayaran",data.paymentTermsDays,current.paymentTermsDays);addDiff(diffs,"category","Kategori",data.category,current.category);addDiff(diffs,"notes","Catatan",data.notes,current.notes);return diffs;}
function referenceDiff(kind:"services"|"billingCycles",data:ReferenceFields,current:ReferenceRecord){const diffs:Diff[]=[];addDiff(diffs,"name","Nama",data.name,current.name);addDiff(diffs,"description","Deskripsi",data.description,current.description);if(kind==="services"){const service=data as ServiceFields;addDiff(diffs,"category","Kategori",service.category,current.category);addDiff(diffs,"unit","Unit",service.unit,current.unit);}else{const cycle=data as BillingCycleFields;addDiff(diffs,"frequency","Frekuensi",cycle.frequency,current.frequency);addDiff(diffs,"cutoffDay","Tanggal cutoff",cycle.cutoffDay,current.cutoffDay);addDiff(diffs,"invoiceOffsetDays","Jarak invoice",cycle.invoiceOffsetDays,current.invoiceOffsetDays);addDiff(diffs,"dueDays","Jatuh tempo",cycle.dueDays,current.dueDays);}return diffs;}
function conflict(userVersion:number,current:{version:number},diffs:readonly Diff[]){throw new AppError(409,"MASTER_VERSION_CONFLICT","Record telah diubah pengguna lain.",{},false,"demo-master-conflict",{userVersion,latestVersion:current.version,diffs});}
function transitionConflict(userVersion:number,current:{version:number;status:MasterStatus},active:boolean){const intended=active?"Active":"Inactive";conflict(userVersion,current,[{field:"status",label:"Status",before:`Tujuan: ${intended}`,after:`Status terbaru: ${current.status}`}]);}
function duplicate<T extends {id:string;code:string}>(source:readonly T[],code:string,id?:string){return source.some((item)=>item.id!==id&&item.code.toUpperCase()===code.trim().toUpperCase());}
function mutation(id:string,version:number,status:MasterStatus,message:string,correlationId:string):MasterMutationResult{return{id,version,status,message,correlationId};}
function mapParty(data:PartyFields,id:string,timestamp:string):PartyRecord{return{id,code:data.code,name:data.name,legalName:data.legalName,taxIdentifierMasked:maskSensitive(data.taxIdentifier),billingAddress:data.billingAddress,city:data.city,province:data.province,postalCode:data.postalCode,contactName:data.contactName,email:data.email,phone:maskSensitive(data.phone),paymentTermsDays:data.paymentTermsDays,category:data.category,notes:data.notes,status:"Active",createdAt:timestamp,updatedAt:timestamp,version:1};}
function applyParty(current:PartyRecord,data:PartyFields){current.name=data.name;current.legalName=data.legalName;if(data.taxIdentifier)current.taxIdentifierMasked=maskSensitive(data.taxIdentifier);current.billingAddress=data.billingAddress;current.city=data.city;current.province=data.province;current.postalCode=data.postalCode;current.contactName=data.contactName;current.email=data.email;current.phone=maskSensitive(data.phone);current.paymentTermsDays=data.paymentTermsDays;current.category=data.category;current.notes=data.notes;current.updatedAt=new Date().toISOString();current.version+=1;}
function mapReference(kind:"services"|"billingCycles",data:ReferenceFields,id:string,timestamp:string):ReferenceRecord{const service=kind==="services",serviceData=data as ServiceFields,cycleData=data as BillingCycleFields;return{id,code:data.code,name:data.name,description:data.description,category:service?serviceData.category:"Billing",unit:service?serviceData.unit:"Cycle",frequency:service?"Monthly":cycleData.frequency,cutoffDay:service?25:cycleData.cutoffDay,invoiceOffsetDays:service?2:cycleData.invoiceOffsetDays,dueDays:service?30:cycleData.dueDays,status:"Active",createdAt:timestamp,updatedAt:timestamp,version:1};}
function applyReference(kind:"services"|"billingCycles",current:ReferenceRecord,data:ReferenceFields){current.name=data.name;current.description=data.description;if(kind==="services"){const service=data as ServiceFields;current.category=service.category;current.unit=service.unit;}else{const cycle=data as BillingCycleFields;current.frequency=cycle.frequency;current.cutoffDay=cycle.cutoffDay;current.invoiceOffsetDays=cycle.invoiceOffsetDays;current.dueDays=cycle.dueDays;}current.updatedAt=new Date().toISOString();current.version+=1;}

export function createMasterDataManagement(projects:Project[],audits:AuditEvent[],contracts:SphContract[]=[]):MasterDataManagementRepository{const partyStores=structuredClone(parties),referenceStores=structuredClone(references);let sequence=200;return{
 async listParties(kind,query,signal){await latency(signal);const result=page(partyStores[kind],query);return{...result,items:result.items.map((item)=>{const summary=usage(kind,item.id,projects,contracts);return{id:item.id,code:item.code,name:item.name,legalName:item.legalName,taxIdentifierMasked:item.taxIdentifierMasked,contact:`${item.contactName} · ${item.email}`,location:`${item.city}, ${item.province}`,projectCount:summary.projectCount,status:item.status,updatedAt:item.updatedAt,version:item.version};})};},
 async getParty(kind,id,signal){await latency(signal);const current=partyStores[kind].find((item)=>item.id===id);if(!current)throw new AppError(404,"PARTY_NOT_FOUND","Data party tidak ditemukan.",{},false,"demo-party-not-found");return structuredClone({...current,usage:usage(kind,id,projects,contracts)});},
 async createParty(kind,command,signal){requireManage(command.actor.permissionKeys);if(duplicate(partyStores[kind],command.data.code))throw new AppError(422,"MASTER_CODE_DUPLICATE","Kode sudah digunakan.",{code:["Kode harus unik."]},false,"demo-master-duplicate");await latency(signal);const id=`${kind==="customers"?"cus":"ven"}-${++sequence}`,timestamp=new Date().toISOString(),correlationId=`demo-master-${sequence}`,record=mapParty(command.data,id,timestamp);partyStores[kind].push(record);audit(audits,kind,id,command.actor.userId,"master.created","Record dibuat",correlationId);return mutation(id,1,"Active","Master data berhasil dibuat.",correlationId);},
 async updateParty(kind,command,signal){requireManage(command.actor.permissionKeys);if(!command.reason.trim())throw new AppError(422,"CHANGE_REASON_REQUIRED","Alasan perubahan wajib diisi.",{reason:["Alasan perubahan wajib diisi."]},false,"demo-master-reason");const current=partyStores[kind].find((item)=>item.id===command.id);if(!current)throw new AppError(404,"PARTY_NOT_FOUND","Data party tidak ditemukan.",{},false,"demo-party-not-found");if(current.version!==command.currentVersion)conflict(command.currentVersion,current,partyDiff(command.data,current));if(duplicate(partyStores[kind],command.data.code,current.id))throw new AppError(422,"MASTER_CODE_DUPLICATE","Kode sudah digunakan.",{code:["Kode harus unik."]},false,"demo-master-duplicate");await latency(signal);applyParty(current,command.data);const correlationId=`demo-master-${++sequence}`;audit(audits,kind,current.id,command.actor.userId,"master.updated",command.reason,correlationId);return mutation(current.id,current.version,current.status,"Master data berhasil diperbarui.",correlationId);},
 async listReferences(kind,query,signal){await latency(signal);const result=page(referenceStores[kind],query);return{...result,items:result.items.map((item)=>{const summary=usage(kind,item.id,projects,contracts);return{id:item.id,code:item.code,name:item.name,category:item.category,unitOrRule:kind==="services"?item.unit:`Cutoff ${item.cutoffDay}; +${item.invoiceOffsetDays} hari`,projectCount:summary.projectCount,status:item.status,updatedAt:item.updatedAt,version:item.version};})};},
 async getReference(kind,id,signal){await latency(signal);const current=referenceStores[kind].find((item)=>item.id===id);if(!current)throw new AppError(404,"REFERENCE_NOT_FOUND","Data referensi tidak ditemukan.",{},false,"demo-reference-not-found");return structuredClone({...current,usage:usage(kind,id,projects,contracts),humanRule:`Periode ditutup setiap tanggal ${current.cutoffDay}. Invoice disiapkan ${current.invoiceOffsetDays} hari setelah cutoff dan jatuh tempo ${current.dueDays} hari setelah diterbitkan.`});},
 async createReference(kind,command,signal){requireManage(command.actor.permissionKeys);if(duplicate(referenceStores[kind],command.data.code))throw new AppError(422,"MASTER_CODE_DUPLICATE","Kode sudah digunakan.",{code:["Kode harus unik."]},false,"demo-master-duplicate");await latency(signal);const id=`${kind==="services"?"svc":"bc"}-${++sequence}`,timestamp=new Date().toISOString(),correlationId=`demo-master-${sequence}`,record=mapReference(kind,command.data,id,timestamp);referenceStores[kind].push(record);audit(audits,kind,id,command.actor.userId,"master.created","Record dibuat",correlationId);return mutation(id,1,"Active","Data referensi berhasil dibuat.",correlationId);},
 async updateReference(kind,command,signal){requireManage(command.actor.permissionKeys);if(!command.reason.trim())throw new AppError(422,"CHANGE_REASON_REQUIRED","Alasan perubahan wajib diisi.",{reason:["Alasan perubahan wajib diisi."]},false,"demo-master-reason");const current=referenceStores[kind].find((item)=>item.id===command.id);if(!current)throw new AppError(404,"REFERENCE_NOT_FOUND","Data referensi tidak ditemukan.",{},false,"demo-reference-not-found");if(current.version!==command.currentVersion)conflict(command.currentVersion,current,referenceDiff(kind,command.data,current));await latency(signal);applyReference(kind,current,command.data);const correlationId=`demo-master-${++sequence}`;audit(audits,kind,current.id,command.actor.userId,"master.updated",command.reason,correlationId);return mutation(current.id,current.version,current.status,"Data referensi berhasil diperbarui.",correlationId);},
 async transition(kind,command,signal){requireManage(command.actor.permissionKeys);if(!command.reason.trim())throw new AppError(422,"TRANSITION_REASON_REQUIRED","Alasan perubahan status wajib diisi.",{reason:["Alasan wajib diisi."]},false,"demo-master-transition-reason");const store=kind==="customers"||kind==="vendors"?partyStores[kind]:referenceStores[kind],current=store.find((item)=>item.id===command.id);if(!current)throw new AppError(404,"MASTER_NOT_FOUND","Master data tidak ditemukan.",{},false,"demo-master-not-found");if(current.version!==command.currentVersion)transitionConflict(command.currentVersion,current,command.active);const summary=usage(kind,current.id,projects,contracts);if(!command.active&&!summary.canDeactivate)throw new AppError(422,"MASTER_DEPENDENCY_BLOCKED","Record masih digunakan dan tidak dapat dinonaktifkan.",{reason:[summary.blockingReason??"Dependency masih aktif."]},false,"demo-master-dependency",{usage:summary});await latency(signal);current.status=command.active?"Active":"Inactive";current.version+=1;current.updatedAt=new Date().toISOString();const correlationId=`demo-master-${++sequence}`;audit(audits,kind,current.id,command.actor.userId,command.active?"master.activated":"master.deactivated",command.reason,correlationId);return mutation(current.id,current.version,current.status,command.active?"Master data diaktifkan.":"Master data dinonaktifkan. Referensi historis tidak berubah.",correlationId);}
};}
