import { AppError } from "@/features/foundation/domain/errors";
import type { AccessAudit, AccessRepository, AccessRole, AccessUser, NormalizedAccessListQuery, PermissionKey, RoleCommand, UserCommand } from "../domain/types";
import { evaluateSod, permissionCatalog, resolveEffectivePermissions } from "../domain/logic";

const now = "2026-08-10T10:00:00+07:00";
const users: AccessUser[] = [
  { id: "usr-dewi", employeeId: "EMP-001", name: "Dewi Sari", email: "dewi.sari@example.test", status: "Active", roleIds: ["role-admin"], projectScopeIds: [], createdAt: now, updatedAt: now, version: 2 },
  { id: "usr-raka", employeeId: "EMP-002", name: "Raka Pratama", email: "raka.pratama@example.test", status: "Active", roleIds: ["role-pic"], projectScopeIds: ["prj-026", "prj-019"], createdAt: now, updatedAt: now, version: 1 },
  { id: "usr-sod-inactive", employeeId: "EMP-003", name: "Demo Konflik SoD", email: "sod.inactive@example.test", status: "Inactive", roleIds: ["role-admin", "role-pic"], projectScopeIds: [], createdAt: now, updatedAt: now, version: 1 },
];
const roles: AccessRole[] = [
  { id: "role-admin", code: "ADMIN_ACCESS", name: "Access Administrator", description: "Mengelola user dan role tanpa approval transaksi.", status: "Active", permissionKeys: ["access.view", "access.manage", "project.view"], isSystem: true, createdAt: now, updatedAt: now, version: 2 },
  { id: "role-pic", code: "PIC", name: "PIC", description: "Owner project dan final approver.", status: "Active", permissionKeys: ["project.view", "project.manage", "pic.approve"], isSystem: true, createdAt: now, updatedAt: now, version: 1 },
  { id: "role-finance", code: "FINANCE", name: "Finance", description: "Operasional finance tanpa final approval.", status: "Active", permissionKeys: ["project.view"], isSystem: false, createdAt: now, updatedAt: now, version: 1 },
];
const audits: AccessAudit[] = [];
let sequence = 20;

const wait = (signal?: AbortSignal) => new Promise<void>((resolve, reject) => { if (signal?.aborted) return reject(new DOMException("Dibatalkan", "AbortError")); const timer = setTimeout(resolve, 20); signal?.addEventListener("abort", () => { clearTimeout(timer); reject(new DOMException("Dibatalkan", "AbortError")); }, { once: true }); });
const unique = <T extends string>(values: readonly T[]) => [...new Set(values)].sort();
const permission = (keys: readonly string[], key: "access.view" | "access.manage") => { if (!keys.includes(key)) throw new AppError(403, "ACCESS_FORBIDDEN", "Anda tidak memiliki izin administrasi akses.", {}, false, "demo-access-forbidden"); };
const requiredReason = (value: string) => { if (value.trim().length < 3) throw new AppError(422, "REASON_REQUIRED", "Alasan perubahan wajib diisi.", { reason: ["Alasan wajib diisi."] }, false, "demo-access-reason"); };
const assertSod = (keys: readonly PermissionKey[]) => { const findings = evaluateSod(keys); if (findings.length) throw new AppError(422, "SOD_CONFLICT", "Kombinasi permission melanggar Segregation of Duties.", { permissionKeys: [findings[0]!.explanation] }, false, "demo-sod-conflict", { findings }); };
const addAudit = (objectType: "User" | "Role", objectId: string, action: string, actorUserId: string, reason: string, before?: Readonly<Record<string, unknown>>, after?: Readonly<Record<string, unknown>>) => { const correlationId = `demo-access-${++sequence}`; audits.unshift({ id: `audit-access-${sequence}`, actorUserId, action, objectType, objectId, occurredAt: now, reason: reason.trim(), correlationId, before, after }); return correlationId; };
const validateKeys = (keys: readonly string[]) => { const catalog = new Set(permissionCatalog.map(item => item.key)); if (keys.some(key => !catalog.has(key as PermissionKey))) throw new AppError(422, "PERMISSION_UNKNOWN", "Permission tidak dikenal.", { permissionKeys: ["Terdapat permission yang tidak dikenal."] }, false, "demo-permission-unknown"); return unique(keys) as PermissionKey[]; };
const paginate = <T,>(items: T[], query: NormalizedAccessListQuery) => { const start = (query.page - 1) * query.pageSize; return { items: items.slice(start, start + query.pageSize), total: items.length, page: query.page, pageSize: query.pageSize, hasNextPage: start + query.pageSize < items.length }; };
function filterSort<T extends { name: string; status: string; updatedAt: string }>(items: T[], query: NormalizedAccessListQuery, searchable: (item: T) => string) { return items.filter(item => (!query.search || searchable(item).toLocaleLowerCase("id-ID").includes(query.search)) && (!query.statuses.length || query.statuses.includes(item.status as "Active" | "Inactive"))).sort((left, right) => { const result = String(left[query.sort]).localeCompare(String(right[query.sort]), "id-ID"); return query.direction === "asc" ? result : -result; }); }
const auditFor = (type: "User" | "Role", id: string) => structuredClone(audits.filter(event => event.objectType === type && event.objectId === id).map(event => ({ ...event, actorName: users.find(user => user.id === event.actorUserId)?.name })));
const labels = (ids: readonly string[]) => unique(ids).join(", ");

function userConflict(command: UserCommand, current: AccessUser) { return new AppError(409, "USER_VERSION_CONFLICT", "Pengguna telah berubah.", {}, false, "demo-user-conflict", { userVersion: command.currentVersion, latestVersion: current.version, diffs: [{ field: "name", label: "Nama", before: command.data.name, after: current.name }, { field: "email", label: "Email", before: command.data.email, after: current.email }, { field: "roleIds", label: "Role", before: labels(command.data.roleIds), after: labels(current.roleIds) }, { field: "projectScopeIds", label: "Scope project", before: labels(command.data.projectScopeIds), after: labels(current.projectScopeIds) }] }); }
function roleConflict(command: RoleCommand, current: AccessRole) { return new AppError(409, "ROLE_VERSION_CONFLICT", "Role telah berubah.", {}, false, "demo-role-conflict", { userVersion: command.currentVersion, latestVersion: current.version, diffs: [{ field: "name", label: "Nama", before: command.data.name, after: current.name }, { field: "description", label: "Deskripsi", before: command.data.description, after: current.description }, { field: "permissionKeys", label: "Permission", before: labels(command.data.permissionKeys), after: labels(current.permissionKeys) }] }); }

export const accessRepository: AccessRepository = {
  async listUsers(query, signal) { await wait(signal); const rows = filterSort(users.map(user => ({ ...structuredClone(user), roleNames: roles.filter(role => user.roleIds.includes(role.id)).map(role => role.name), effectivePermissions: resolveEffectivePermissions(user.roleIds, roles) })), query, item => `${item.employeeId} ${item.name} ${item.email} ${item.roleNames.join(" ")}`).filter(item => !query.roleIds.length || query.roleIds.some(id => item.roleIds.includes(id))); return paginate(rows, query); },
  async getUser(id, signal) { await wait(signal); const user = users.find(item => item.id === id); if (!user) throw new AppError(404, "USER_NOT_FOUND", "Pengguna tidak ditemukan.", {}, false, "demo-user-not-found"); const assigned = roles.filter(role => user.roleIds.includes(role.id)), effectivePermissions = resolveEffectivePermissions(user.roleIds, roles); return { user: structuredClone(user), roles: structuredClone(assigned), effectivePermissions, sodFindings: evaluateSod(effectivePermissions), audit: auditFor("User", id) }; },
  async listUserAudit(id, signal) { await wait(signal); if (!users.some(user => user.id === id)) throw new AppError(404, "USER_NOT_FOUND", "Pengguna tidak ditemukan.", {}, false, "demo-user-not-found"); return auditFor("User", id); },
  async saveUser(command, signal) {
    permission(command.actor.permissionKeys, "access.manage"); requiredReason(command.reason);
    const current = command.userId ? users.find(user => user.id === command.userId) : undefined;
    if (command.userId && !current) throw new AppError(404, "USER_NOT_FOUND", "Pengguna tidak ditemukan.", {}, false, "demo-user-not-found");
    if (current && current.version !== command.currentVersion) throw userConflict(command, current);
    const errors: Record<string, string[]> = {};
    if (users.some(user => user.employeeId === command.data.employeeId && user.id !== current?.id)) errors.employeeId = ["Identifier sudah digunakan."];
    if (users.some(user => user.email.toLowerCase() === command.data.email.toLowerCase() && user.id !== current?.id)) errors.email = ["Email sudah digunakan."];
    const roleIds = unique(command.data.roleIds), assigned = roleIds.map(id => roles.find(role => role.id === id && role.status === "Active"));
    if (assigned.some(role => !role)) errors.roleIds = ["Role tidak valid atau inactive."];
    if (Object.keys(errors).length) throw new AppError(422, "USER_VALIDATION_FAILED", "Periksa kembali data pengguna.", errors, false, "demo-user-validation");
    assertSod(resolveEffectivePermissions(roleIds, roles)); await wait(signal);
    if (current) { const before = { name: current.name, email: current.email, roleIds: [...current.roleIds], projectScopeIds: [...current.projectScopeIds] }; current.name = command.data.name.trim(); current.email = command.data.email.trim().toLowerCase(); current.roleIds = roleIds; current.projectScopeIds = unique(command.data.projectScopeIds); current.updatedAt = now; current.version += 1; const after = { name: current.name, email: current.email, roleIds: current.roleIds, projectScopeIds: current.projectScopeIds }; return { objectType: "User", objectId: current.id, version: current.version, message: "Pengguna berhasil diperbarui.", correlationId: addAudit("User", current.id, "user.updated", command.actor.userId, command.reason, before, after) }; }
    const user: AccessUser = { id: `usr-${++sequence}`, employeeId: command.data.employeeId.trim(), name: command.data.name.trim(), email: command.data.email.trim().toLowerCase(), status: "Active", roleIds, projectScopeIds: unique(command.data.projectScopeIds), createdAt: now, updatedAt: now, version: 1 }; users.push(user); return { objectType: "User", objectId: user.id, version: 1, message: "Pengguna berhasil dibuat.", correlationId: addAudit("User", user.id, "user.created", command.actor.userId, command.reason, undefined, { roleIds, projectScopeIds: user.projectScopeIds }) };
  },
  async setUserStatus(command, signal) { permission(command.actor.permissionKeys, "access.manage"); requiredReason(command.reason); const user = users.find(item => item.id === command.objectId); if (!user) throw new AppError(404, "USER_NOT_FOUND", "Pengguna tidak ditemukan.", {}, false, "demo-user-not-found"); if (user.version !== command.currentVersion) throw new AppError(409, "USER_VERSION_CONFLICT", "Pengguna telah berubah.", {}, false, "demo-user-conflict", { userVersion: command.currentVersion, latestVersion: user.version, currentStatus: user.status, targetStatus: command.target, diffs: [{ field: "status", label: "Status", before: `Tujuan: ${command.target}`, after: `Status terbaru: ${user.status}` }] }); if (user.status === command.target) throw new AppError(422, "USER_STATE_INVALID", "Status pengguna sudah sama.", {}, false, "demo-user-state"); if (command.target === "Active") { const effective = resolveEffectivePermissions(user.roleIds, roles); if (!effective.length) throw new AppError(422, "USER_ASSIGNMENT_INVALID", "Pengguna tidak memiliki role aktif.", {}, false, "demo-user-assignment"); assertSod(effective); } await wait(signal); const before = user.status; user.status = command.target; user.version += 1; user.updatedAt = now; return { objectType: "User", objectId: user.id, version: user.version, message: `Pengguna berhasil ${command.target === "Active" ? "diaktifkan" : "dinonaktifkan"}.`, correlationId: addAudit("User", user.id, command.target === "Active" ? "user.activated" : "user.deactivated", command.actor.userId, command.reason, { status: before }, { status: user.status }) }; },
  async listRoles(query, signal) { await wait(signal); return paginate(filterSort(roles.map(role => ({ ...structuredClone(role), userCount: users.filter(user => user.roleIds.includes(role.id)).length, sodFindings: evaluateSod(role.permissionKeys) })), query, item => `${item.code} ${item.name} ${item.description}`), query); },
  async getRole(id, signal) { await wait(signal); const role = roles.find(item => item.id === id); if (!role) throw new AppError(404, "ROLE_NOT_FOUND", "Role tidak ditemukan.", {}, false, "demo-role-not-found"); return { role: structuredClone(role), userCount: users.filter(user => user.roleIds.includes(id)).length, sodFindings: evaluateSod(role.permissionKeys), audit: auditFor("Role", id) }; },
  async listRoleAudit(id, signal) { await wait(signal); if (!roles.some(role => role.id === id)) throw new AppError(404, "ROLE_NOT_FOUND", "Role tidak ditemukan.", {}, false, "demo-role-not-found"); return auditFor("Role", id); },
  async saveRole(command, signal) { permission(command.actor.permissionKeys, "access.manage"); requiredReason(command.reason); const current = command.roleId ? roles.find(role => role.id === command.roleId) : undefined; if (command.roleId && !current) throw new AppError(404, "ROLE_NOT_FOUND", "Role tidak ditemukan.", {}, false, "demo-role-not-found"); if (current && current.version !== command.currentVersion) throw roleConflict(command, current); const keys = validateKeys(command.data.permissionKeys); assertSod(keys); if (roles.some(role => role.code === command.data.code && role.id !== current?.id)) throw new AppError(422, "ROLE_CODE_DUPLICATE", "Kode role sudah digunakan.", { code: ["Kode role sudah digunakan."] }, false, "demo-role-code"); await wait(signal); if (current) { const before = { name: current.name, description: current.description, permissionKeys: [...current.permissionKeys] }; current.name = command.data.name.trim(); current.description = command.data.description.trim(); current.permissionKeys = keys; current.version += 1; current.updatedAt = now; return { objectType: "Role", objectId: current.id, version: current.version, message: "Role berhasil diperbarui.", correlationId: addAudit("Role", current.id, "role.updated", command.actor.userId, command.reason, before, { name: current.name, description: current.description, permissionKeys: keys }) }; } const role: AccessRole = { id: `role-${++sequence}`, code: command.data.code.trim(), name: command.data.name.trim(), description: command.data.description.trim(), status: "Active", permissionKeys: keys, isSystem: false, createdAt: now, updatedAt: now, version: 1 }; roles.push(role); return { objectType: "Role", objectId: role.id, version: 1, message: "Role berhasil dibuat.", correlationId: addAudit("Role", role.id, "role.created", command.actor.userId, command.reason, undefined, { permissionKeys: keys }) }; },
  async setRoleStatus(command, signal) { permission(command.actor.permissionKeys, "access.manage"); requiredReason(command.reason); const role = roles.find(item => item.id === command.objectId); if (!role) throw new AppError(404, "ROLE_NOT_FOUND", "Role tidak ditemukan.", {}, false, "demo-role-not-found"); if (role.version !== command.currentVersion) throw new AppError(409, "ROLE_VERSION_CONFLICT", "Role telah berubah.", {}, false, "demo-role-conflict", { userVersion: command.currentVersion, latestVersion: role.version, currentStatus: role.status, targetStatus: command.target, diffs: [{ field: "status", label: "Status", before: `Tujuan: ${command.target}`, after: `Status terbaru: ${role.status}` }] }); if (role.status === command.target) throw new AppError(422, "ROLE_STATE_INVALID", "Status role sudah sama.", {}, false, "demo-role-state"); if (command.target === "Inactive" && users.some(user => user.status === "Active" && user.roleIds.includes(role.id))) throw new AppError(422, "ROLE_IN_USE", "Role masih digunakan pengguna aktif.", {}, false, "demo-role-in-use"); if (command.target === "Active") assertSod(role.permissionKeys); await wait(signal); const before = role.status; role.status = command.target; role.version += 1; role.updatedAt = now; return { objectType: "Role", objectId: role.id, version: role.version, message: `Role berhasil ${command.target === "Active" ? "diaktifkan" : "dinonaktifkan"}.`, correlationId: addAudit("Role", role.id, command.target === "Active" ? "role.activated" : "role.deactivated", command.actor.userId, command.reason, { status: before }, { status: role.status }) }; },
  async listPermissions(signal) { await wait(signal); return permissionCatalog; },
  evaluatePermissions: evaluateSod,
};
