"use client";
import { zodResolver } from "@hookform/resolvers/zod";
import { useRouter } from "next/navigation";
import { useEffect, useState } from "react";
import { useForm, useWatch } from "react-hook-form";
import { Alert, Badge, Button, Card, CardHeader, DataState, Input, LoadingState, PageHeader, Select } from "@/components/ui";
import { isRequestCancellation, normalizeAppError } from "@/features/foundation/domain/errors";
import { useUnsavedGuard } from "@/features/payroll-billing/components/use-unsaved-guard";
import { formatRupiah } from "@/lib/formatters";
import { invoiceDraftSchema, type InvoiceDraftFormValues } from "../domain/schema";
import { useCreateInvoiceDraft, useInvoiceSourceOptions } from "../queries/hooks";
export function InvoiceCreatePage({ access = "manage" }: { access?: string }) { if (access !== "manage") return <DataState kind="denied" title="Create Draft Invoice tidak diizinkan" />; return <Create access={access} />; }
function Create({ access }: { access: string }) {
  const router = useRouter(), sources = useInvoiceSourceOptions(access), mutation = useCreateInvoiceDraft();
  const [review, setReview] = useState(false), [serverError, setServerError] = useState<string>();
  const form = useForm<InvoiceDraftFormValues>({ resolver: zodResolver(invoiceDraftSchema), defaultValues: { sourceOptionId: "", invoiceDate: "2026-08-01", note: "" } });
  const watchedSourceId = useWatch({ control: form.control, name: "sourceOptionId" });
  const sourceId = watchedSourceId || sources.data?.[0]?.id || "", selected = sources.data?.find(item => item.id === sourceId), guard = useUnsavedGuard(form.formState.isDirty);
  useEffect(() => { if (!watchedSourceId && sources.data?.[0]) form.setValue("sourceOptionId", sources.data[0].id); }, [watchedSourceId, sources.data, form]);
  const submit = form.handleSubmit(async values => { if (!selected) return; try { const result = await mutation.mutateAsync({ data: { sourceOptionId: selected.id, invoiceDate: values.invoiceDate, note: values.note }, actor: { userId: "usr-demo", permissionKeys: ["invoice.create"] }, reason: values.note || "Create Draft Invoice" }); router.push(`/invoices/${result.invoiceId}/edit?access=${access}`); } catch (error) { if (!isRequestCancellation(error)) setServerError(normalizeAppError(error).message); } });
  return <><PageHeader eyebrow="Create Draft Invoice" title="Pilih Locked Payroll Billing source" description="Draft baru dibuat hanya setelah review eksplisit." meta={<Badge tone="warning">Data demo</Badge>} />{serverError && <Alert tone="danger" title="Draft belum dapat dibuat">{serverError}</Alert>}{sources.isPending ? <LoadingState /> : sources.isError ? <DataState kind="server" action={<Button onClick={() => void sources.refetch()}>Coba lagi</Button>} /> : <form onSubmit={submit} noValidate><Card><CardHeader title="Source selection" /><div className="form-section"><Select label="Eligible Payroll Billing source" {...form.register("sourceOptionId")} value={sourceId}><option value="">Pilih source</option>{sources.data?.map(item => <option key={item.id} value={item.id}>{item.source.payrollBillingRunId} / R{item.source.payrollBillingRevisionNumber} / {item.source.projectName}</option>)}</Select><Input label="Draft date" type="date" error={form.formState.errors.invoiceDate?.message} {...form.register("invoiceDate")} /><Input label="Draft note" error={form.formState.errors.note?.message} {...form.register("note")} />{selected && <dl className="detail-list"><dt>Project/customer</dt><dd>{selected.source.projectName} / {selected.source.customerName}</dd><dt>SPH</dt><dd>{selected.source.sphNumber}</dd><dt>Period/source</dt><dd>{selected.source.attendancePeriod} / {selected.source.attendanceSourceReference}</dd><dt>Rate snapshot</dt><dd>{selected.source.rateVersionLabel}</dd><dt>Branches/services</dt><dd>{selected.source.branchLabels.length} branch / {selected.source.serviceLabels.length} service</dd><dt>Source total</dt><dd>{formatRupiah(selected.source.sourceFinancialTotal)}</dd><dt>Tax</dt><dd>Menunggu konfigurasi backend</dd></dl>}<div className="responsive-actions"><Button variant="secondary" onClick={() => guard(() => router.push(`/invoices?access=${access}`))}>Batal</Button><Button disabled={!selected} onClick={() => setReview(true)}>Tinjau create</Button></div></div></Card>{review && selected && <Card><CardHeader title="Review sebelum create" /><p>Satu Draft untuk SPH <strong>{selected.source.sphNumber}</strong>. {selected.lines.length} source line dari {selected.source.branchLabels.length} branch disimpan sebagai snapshot immutable.</p><p>Invoice final number, customer confirmation, approval, release, dan AR belum tersedia.</p><div className="responsive-actions"><Button variant="secondary" onClick={() => setReview(false)}>Kembali</Button><Button type="submit" disabled={mutation.isPending}>{mutation.isPending ? "Membuat..." : "Buat Draft Invoice"}</Button></div></Card>}</form>}</>;
}
