"use client";
import { zodResolver } from "@hookform/resolvers/zod";
import Link from "next/link";
import { useRouter } from "next/navigation";
import { useCallback, useEffect, useRef, useState } from "react";
import { useForm, useWatch } from "react-hook-form";
import { toast } from "sonner";
import { Alert, Badge, Button, Card, CardHeader, DataState, Input, LoadingState, PageHeader, StatusBadge, TableShell } from "@/components/ui";
import { isRequestCancellation, normalizeAppError } from "@/features/foundation/domain/errors";
import { useUnsavedGuard } from "@/features/payroll-billing/components/use-unsaved-guard";
import { formatDate, formatRupiah } from "@/lib/formatters";
import { revisionEditorSchema, type RevisionEditorFormValues } from "../domain/schema";
import type { InvoiceDetail } from "../domain/types";
import { useAutosaveInvoiceDraft, useAutosaveInvoiceRevision, useInvoiceConfirmationState, useInvoiceDetail, useInvoicePreview, useSaveInvoiceDraft, useSaveInvoiceRevision } from "../queries/hooks";
import { InvoiceConfirmationPanel } from "./invoice-confirmation-panel";
const actor = { userId: "usr-demo", permissionKeys: ["invoice.edit"] };
export function InvoiceDetailPage({ id, access = "manage", edit = false }: { id: string; access?: string; edit?: boolean }) { if (access === "none") return <DataState kind="denied" title="Invoice tidak diizinkan" />; return <Detail id={id} access={access} edit={edit && (access === "manage" || access === "pic")} />; }
function Detail({ id, access, edit }: { id: string; access: string; edit: boolean }) { const query = useInvoiceDetail(id, access); if (query.isPending) return <LoadingState />; if (query.isError) { const error = normalizeAppError(query.error); return <DataState kind={error.status === 404 ? "empty" : "server"} title={error.status === 404 ? "Draft Invoice tidak ditemukan" : "Draft belum dapat dimuat"} correlationId={error.correlation_id} action={<Link className="button button-secondary" href={`/invoices?access=${access}`}>Kembali ke daftar</Link>} />; } return query.data ? <Builder key={`${query.data.invoice.id}-${query.data.invoice.version}`} initial={query.data} access={access} edit={edit} /> : null; }
function Builder({ initial, access, edit: requestedEdit }: { initial: InvoiceDetail; access: string; edit: boolean }) {
  const edit = requestedEdit && (initial.invoice.status === "Draft" || initial.invoice.status === "Revision");
  const router = useRouter(), [authoritative, setAuthoritative] = useState(initial), [previewOpen, setPreviewOpen] = useState(false), [lastSaveData, setLastSaveData] = useState<RevisionEditorFormValues>(), [autosaveState, setAutosaveState] = useState<"idle" | "saving" | "saved" | "failed" | "conflict">("idle"), [error, setError] = useState<ReturnType<typeof normalizeAppError>>();
  const revisionMode = initial.invoice.status === "Revision", confirmation = useInvoiceConfirmationState(initial.invoice.id, access), lastAutosavePayload = useRef(""), draftSave = useSaveInvoiceDraft(), revisionSave = useSaveInvoiceRevision(), draftAutosave = useAutosaveInvoiceDraft(), revisionAutosave = useAutosaveInvoiceRevision();
  const savePending = draftSave.isPending || revisionSave.isPending, autosavePending = draftAutosave.isPending || revisionAutosave.isPending, draftAutosaveMutate = draftAutosave.mutateAsync, revisionAutosaveMutate = revisionAutosave.mutateAsync, cancelDraftAutosave = draftAutosave.cancel, cancelRevisionAutosave = revisionAutosave.cancel, cancelAutosave = useCallback(() => { cancelDraftAutosave(); cancelRevisionAutosave(); }, [cancelDraftAutosave, cancelRevisionAutosave]);
  const form = useForm<RevisionEditorFormValues>({ resolver: zodResolver(revisionEditorSchema), defaultValues: { invoiceDate: initial.revision.snapshot.invoiceDate, note: initial.revision.snapshot.note, lines: initial.lines.map(line => ({ id: line.id, description: line.description })), resolutions: (confirmation.data?.requestedChanges ?? []).map(item => ({ requestedChangeId: item.id, resolved: item.resolutionStatus === "Resolved", resolutionNote: item.resolutionNote ?? "" })) } });
  const values = useWatch({ control: form.control }), preview = useInvoicePreview(initial.invoice.id, access, previewOpen), guard = useUnsavedGuard(form.formState.isDirty || autosaveState === "conflict");
  useEffect(() => { if (!revisionMode || !confirmation.data || form.formState.isDirty) return; form.setValue("resolutions", confirmation.data.requestedChanges.map(item => ({ requestedChangeId: item.id, resolved: item.resolutionStatus === "Resolved", resolutionNote: item.resolutionNote ?? "" })), { shouldDirty: false }); }, [confirmation.data, form, form.formState.isDirty, revisionMode]);
  const createDraftCommand = useCallback((data: RevisionEditorFormValues) => ({ invoiceId: authoritative.invoice.id, data: { invoiceDate: data.invoiceDate, note: data.note, lines: data.lines }, actor, reason: "Update Draft presentation", currentVersion: authoritative.invoice.version, currentRevisionId: authoritative.revision.id, currentRevisionVersion: authoritative.revision.version }), [authoritative.invoice.id, authoritative.invoice.version, authoritative.revision.id, authoritative.revision.version]);
  const createRevisionCommand = useCallback((data: RevisionEditorFormValues) => ({ invoiceId: authoritative.invoice.id, data: { invoiceDate: data.invoiceDate, note: data.note, lines: data.lines ?? [], resolutions: data.resolutions }, actor: { userId: access === "pic" ? "usr-pic" : "usr-demo", permissionKeys: ["invoice.revision.edit"] }, reason: "Update working Invoice revision", currentVersion: authoritative.invoice.version, currentRevisionId: authoritative.revision.id, currentRevisionVersion: authoritative.revision.version }), [access, authoritative.invoice.id, authoritative.invoice.version, authoritative.revision.id, authoritative.revision.version]);
  const applyResult = useCallback((result: { version: number; revisionVersion: number; savedAt: string }) => { setAuthoritative(current => ({ ...current, invoice: { ...current.invoice, version: result.version, updatedAt: result.savedAt, autosavedAt: result.savedAt }, revision: { ...current.revision, version: result.revisionVersion, updatedAt: result.savedAt } })); form.reset(form.getValues()); setAutosaveState("saved"); }, [form]);
  const applyAutosaveResult = useCallback((result: { version: number; revisionVersion: number; savedAt: string }, submitted: RevisionEditorFormValues) => { const current=form.getValues();lastAutosavePayload.current=JSON.stringify(submitted);setAuthoritative(value=>({...value,invoice:{...value.invoice,version:result.version,updatedAt:result.savedAt,autosavedAt:result.savedAt},revision:{...value.revision,version:result.revisionVersion,updatedAt:result.savedAt}}));form.reset(submitted);if(current.invoiceDate!==submitted.invoiceDate)form.setValue("invoiceDate",current.invoiceDate,{shouldDirty:true});if(current.note!==submitted.note)form.setValue("note",current.note,{shouldDirty:true});current.lines?.forEach((line,index)=>{if(line.description!==submitted.lines?.[index]?.description)form.setValue(`lines.${index}.description`,line.description,{shouldDirty:true});});current.resolutions.forEach((resolution,index)=>{const saved=submitted.resolutions[index];if(resolution.resolved!==saved?.resolved)form.setValue(`resolutions.${index}.resolved`,resolution.resolved,{shouldDirty:true});if(resolution.resolutionNote!==saved?.resolutionNote)form.setValue(`resolutions.${index}.resolutionNote`,resolution.resolutionNote,{shouldDirty:true});});setAutosaveState(JSON.stringify(current)===JSON.stringify(submitted)?"saved":"idle"); }, [form]);
  const handleError = useCallback((value: unknown) => { if (isRequestCancellation(value)) return; const app = normalizeAppError(value); setError(app); setAutosaveState(app.status === 409 ? "conflict" : "failed"); }, []);
  useEffect(() => { if (!edit || !form.formState.isDirty || savePending || autosaveState === "conflict") return; const current = revisionEditorSchema.safeParse(values); if (!current.success) return; const payload = JSON.stringify(current.data); if (payload === lastAutosavePayload.current) return; lastAutosavePayload.current = payload; if (autosavePending) cancelAutosave(); const timer = setTimeout(() => { setAutosaveState("saving"); const operation = revisionMode ? revisionAutosaveMutate(createRevisionCommand(current.data)) : draftAutosaveMutate(createDraftCommand(current.data)); void operation.then(result=>applyAutosaveResult(result,current.data)).catch(handleError); }, 800); return () => clearTimeout(timer); }, [values, edit, form.formState.isDirty, savePending, autosaveState, autosavePending, cancelAutosave, revisionMode, revisionAutosaveMutate, draftAutosaveMutate, createRevisionCommand, createDraftCommand, applyAutosaveResult, handleError]);
  useEffect(() => () => cancelAutosave(), [cancelAutosave]);
  useEffect(() => { if (error) document.getElementById("invoice-save-error")?.focus(); }, [error]);
  async function explicitSave(data: RevisionEditorFormValues) { cancelAutosave(); setError(undefined); setLastSaveData(data); try { const result = revisionMode ? await revisionSave.mutateAsync(createRevisionCommand(data)) : await draftSave.mutateAsync(createDraftCommand(data)); applyResult(result); setLastSaveData(undefined); toast.success(revisionMode ? "Working revision berhasil disimpan." : "Draft berhasil disimpan."); } catch (value) { if (!isRequestCancellation(value)) { const appError=normalizeAppError(value); for(const [field,messages] of Object.entries(appError.field_errors)){if(field==="note"||field==="invoiceDate")form.setError(field,{type:"server",message:messages[0]});else if(field.startsWith("lines."))form.setError(field as `lines.${number}.description`,{type:"server",message:messages[0]});} } handleError(value); } }
  const source = authoritative.revision.snapshot.source, shownAutosaveState = form.formState.isDirty && autosaveState === "idle" ? "dirty" : autosaveState;
  return <><PageHeader eyebrow="Invoice Builder" title={authoritative.invoice.draftReference} description="Nomor Invoice final belum tersedia pada tahap customer confirmation." meta={<><StatusBadge tone={authoritative.invoice.status === "Revision" ? "warning" : "info"}>{authoritative.invoice.status}</StatusBadge> <Badge tone="warning">Data demo</Badge></>} actions={<div className="responsive-actions"><Link className="button button-secondary" href={`/invoices?access=${access}`}>Kembali ke daftar</Link>{access === "manage" && !edit && authoritative.invoice.status === "Draft" && <Link className="button button-primary" href={`/invoices/${authoritative.invoice.id}/edit?access=${access}`}>Edit Draft</Link>}<Button variant="secondary" onClick={() => setPreviewOpen(value => !value)}>Preview Draft</Button></div>} />
    {error && <div id="invoice-save-error" tabIndex={-1}><Alert tone={error.status === 409 ? "warning" : "danger"} title={error.status === 409 ? `Konflik versi ${revisionMode ? "Working Revision" : "Draft"}` : `${revisionMode ? "Working Revision" : "Draft"} belum tersimpan`}><p>{error.message}</p><code>{error.code}; ID korelasi: {error.correlation_id}</code>{error.status === 409 && <><dl className="detail-list"><dt>Invoice</dt><dd>{String(error.metadata.invoiceId ?? authoritative.invoice.id)}</dd><dt>Aggregate version</dt><dd>Attempted {String(error.metadata.attemptedVersion)}; latest {String(error.metadata.latestVersion)}</dd><dt>Revision</dt><dd>Attempted {String(error.metadata.attemptedRevisionId ?? authoritative.revision.id)} / {String(error.metadata.attemptedRevisionVersion)}; latest {String(error.metadata.latestRevisionId)} / {String(error.metadata.latestRevisionVersion)}</dd><dt>Status/cycle</dt><dd>{String(error.metadata.attemptedStatus ?? authoritative.invoice.status)} → {String(error.metadata.latestStatus)}; cycle {String(error.metadata.confirmationCycle ?? "—")}</dd></dl><p>Input lokal tetap dipertahankan; penimpaan paksa tidak tersedia.</p><Button variant="secondary" onClick={() => router.refresh()}>Buka versi authoritative</Button></>}{error.retryable&&lastSaveData&&<Button variant="secondary" disabled={savePending} onClick={()=>void explicitSave(lastSaveData)}>{savePending?"Mencoba lagi...":"Coba lagi"}</Button>}</Alert></div>}
    <form onSubmit={form.handleSubmit(explicitSave)} noValidate><div className="invoice-builder-grid"><div><Card><CardHeader title={revisionMode ? "Working revision header" : "Draft header"} description={`Aggregate version ${authoritative.invoice.version}; Revision ${authoritative.revision.revisionNumber} / version ${authoritative.revision.version}`} /><dl className="detail-list"><dt>Project/customer</dt><dd>{source.projectName} / {source.customerName}</dd><dt>Billing identity</dt><dd>{source.billingAddress} / {source.customerTaxIdentityMasked}</dd><dt>SPH/contract</dt><dd>{source.sphNumber} / {source.contractStart} - {source.contractEnd}</dd><dt>Payroll Billing</dt><dd>{source.payrollBillingRunId} / revision {source.payrollBillingRevisionNumber} / version {source.payrollBillingRevisionVersion}</dd><dt>Attendance/rate</dt><dd>{source.attendanceSourceReference} / {source.rateVersionLabel}</dd><dt>Period/currency</dt><dd>{source.attendancePeriod} / {source.currency}</dd></dl>{edit && <div className="form-section"><Input label={revisionMode ? "Invoice date" : "Draft date"} type="date" error={form.formState.errors.invoiceDate?.message} {...form.register("invoiceDate")} /><Input label={revisionMode ? "Revision note" : "Draft note"} error={form.formState.errors.note?.message} {...form.register("note")} /></div>}</Card>{revisionMode && <RequestedChanges form={form} detail={authoritative} changes={confirmation.data?.requestedChanges ?? []} edit={edit} />}<Lines detail={authoritative} edit={edit} form={form} /></div>
      <aside><Card><CardHeader title="Reconciliation" /><dl className="detail-list"><dt>Payroll Billing source</dt><dd>{formatRupiah(authoritative.reconciliation.sourceTotal)}</dd><dt>Mapped source lines</dt><dd>{formatRupiah(authoritative.reconciliation.mappedSourceTotal)}</dd><dt>Fee/charge</dt><dd>{formatRupiah(authoritative.reconciliation.feeAndChargeTotal)}</dd><dt>Invoice grand total</dt><dd>{formatRupiah(authoritative.reconciliation.invoiceGrandTotal)}</dd><dt>Variance</dt><dd>{formatRupiah(authoritative.reconciliation.variance)}</dd></dl><StatusBadge tone={authoritative.reconciliation.reconciled ? "success" : "danger"}>{authoritative.reconciliation.reconciled ? "Reconciled" : "Belum reconciled"}</StatusBadge></Card><Card><CardHeader title="Tax dan rounding preview" /><p><strong>Tax:</strong> {authoritative.taxPreview.explanation}</p><p><strong>Rounding:</strong> {authoritative.rounding.configured ? authoritative.rounding.method : "Metadata rounding belum tersedia; tidak ada rounding buatan."}</p></Card><Card><CardHeader title="Autosave" /><p role="status">{shownAutosaveState === "idle" ? "Belum ada perubahan." : shownAutosaveState === "dirty" ? "Perubahan belum disimpan." : shownAutosaveState === "saving" ? "Menyimpan..." : shownAutosaveState === "saved" ? `Tersimpan pada ${formatDate(authoritative.invoice.autosavedAt ?? authoritative.invoice.updatedAt, true)}.` : shownAutosaveState === "conflict" ? "Konflik; autosave dihentikan." : "Gagal menyimpan."}</p>{edit && <div className="responsive-actions"><Button type="submit" disabled={savePending || autosavePending || autosaveState === "conflict"}>{savePending ? "Menyimpan..." : revisionMode ? "Simpan Working Revision" : "Simpan Draft"}</Button><Button variant="secondary" onClick={() => guard(() => router.push(`/invoices/${authoritative.invoice.id}?access=${access}`))}>Batal</Button></div>}</Card><Card><CardHeader title="Activity Invoice" />{authoritative.activity.map(item => <article className="activity-item" key={item.id}><strong>{item.action}</strong><span>{item.actorName ?? item.actorUserId}; version {item.version}</span><small>{formatDate(item.occurredAt, true)}; {item.reason}</small><code>{item.correlationId}</code></article>)}</Card></aside></div></form>
    <InvoiceConfirmationPanel detail={authoritative} access={access} revisionBusy={revisionMode && (form.formState.isDirty || savePending || autosavePending || autosaveState === "conflict")}/>{previewOpen && <Card className="invoice-preview"><CardHeader title="DRAFT - Preview Invoice" description="HTML print-style preview; bukan PDF backend." action={<Button variant="secondary" disabled title="Backend PDF belum tersedia">Download PDF belum tersedia</Button>} />{preview.isPending ? <LoadingState /> : preview.data && <><h2>{preview.data.source.customerName}</h2><p>{preview.data.source.billingAddress}</p><p>SPH {preview.data.source.sphNumber}; periode {preview.data.source.attendancePeriod}; Draft date {preview.data.invoiceDate}</p>{preview.data.lines.map(line => <p key={line.id}>{line.description} - {line.branchLabel}: {formatRupiah(line.finalAmount)}</p>)}<strong>Grand total {formatRupiah(preview.data.summary.grandTotal)} {preview.data.source.currency}</strong><p>{preview.data.note}</p><small>Source {preview.data.source.payrollBillingRunId} / revision {preview.data.source.payrollBillingRevisionNumber}. Nomor Invoice final belum tersedia.</small></>}</Card>}</>;
}
function RequestedChanges({ form, detail, changes, edit }: { form: ReturnType<typeof useForm<RevisionEditorFormValues>>; detail: InvoiceDetail; changes: readonly import("../domain/types").InvoiceRequestedChange[]; edit: boolean }) { const resolved = changes.filter(item => item.resolutionStatus === "Resolved").length; return <Card><CardHeader title="Requested changes" description={`${resolved}/${changes.length} resolved; ${changes.length - resolved} blocking`} />{changes.length === 0 ? <DataState kind="empty" title="Tidak ada requested change" /> : <div className="invoice-line-cards">{changes.map((item, index) => <article key={item.id}><StatusBadge tone={item.resolutionStatus === "Resolved" ? "success" : "warning"}>{item.resolutionStatus}</StatusBadge><strong>{item.id}: {item.section}</strong><span>Customer request: {item.customerRequestSummary}</span><span>Previous/current: {item.currentValueSummary}</span><span>Financial: {item.requiresFinancialRecalculation ? "Perlu recalculation" : "Tidak"}; source correction: {item.requiresSourceCorrection ? "Perlu—selesaikan di source" : "Tidak"}; document: {item.requiresDocumentUpdate ? "Perlu" : "Tidak"}</span>{edit && <><label><input type="checkbox" {...form.register(`resolutions.${index}.resolved`)} /> Resolved</label><Input label={`Resolution note ${item.id}`} error={form.formState.errors.resolutions?.[index]?.resolutionNote?.message} {...form.register(`resolutions.${index}.resolutionNote`)} /></>}</article>)}</div>}<p>Reconciliation impact: {detail.reconciliation.reconciled ? "tetap nol" : `variance ${formatRupiah(detail.reconciliation.variance)}`}.</p></Card>; }
function Lines({ detail, edit, form }: { detail: InvoiceDetail; edit: boolean; form: ReturnType<typeof useForm<RevisionEditorFormValues>> }) { return <Card><CardHeader title="Invoice lines" description="Quantity, rate, source revision, SPH, dan currency terkunci." /><TableShell caption="Invoice source lines"><thead><tr><th>Description</th><th>Service/branch</th><th>Quantity/rate</th><th>Base/final</th><th>Source</th></tr></thead><tbody>{detail.lines.map((line, index) => <tr key={line.id}><td>{edit ? <Input label={`Description line ${index + 1}`} {...form.register(`lines.${index}.description`)} /> : line.description}</td><td>{line.serviceLabel}<small className="table-subtext">{line.branchLabel}</small></td><td>{line.quantity} {line.unit}<small className="table-subtext">{formatRupiah(line.unitRate)}</small></td><td>{formatRupiah(line.baseAmount)}</td><td>{line.source.payrollBillingLineId}</td></tr>)}</tbody></TableShell><div className="invoice-line-cards">{detail.lines.map(line => <article key={line.id}><strong>{line.description}</strong><span>{line.serviceLabel}; {line.branchLabel}</span><span>{line.quantity} {line.unit} x {formatRupiah(line.unitRate)}</span><strong>{formatRupiah(line.finalAmount)}</strong><small>Source: {line.source.payrollBillingLineId}</small></article>)}</div></Card>; }
