"use client";

import { zodResolver } from "@hookform/resolvers/zod";
import Link from "next/link";
import { useEffect, useState } from "react";
import { useForm, type FieldErrors, type FieldValues, type Path, type UseFormRegister, type UseFormReturn } from "react-hook-form";
import { Alert, Badge, Button, Card, CardHeader, DataState, Input, LoadingState, Select, StatusBadge, TableShell } from "@/components/ui";
import { isRequestCancellation, normalizeAppError } from "@/features/foundation/domain/errors";
import { formatDate, formatRupiah } from "@/lib/formatters";
import { useUnsavedGuard } from "@/features/payroll-billing/components/use-unsaved-guard";
import { customerConfirmedSchema, requestConfirmationSchema, resubmitRevisionSchema, revisionRequestSchema, type CustomerConfirmedFormValues, type RequestConfirmationFormValues, type ResubmitRevisionFormValues, type RevisionRequestFormValues } from "../domain/schema";
import type { ConfirmationChannel, InvoiceConfirmationEvidence, InvoiceDetail } from "../domain/types";
import { resolveInvoiceCapabilities } from "../permissions/capabilities";
import { useInvoiceConfirmationState, useInvoiceRevisionDiff, useRecordCustomerConfirmed, useRecordInvoiceRevisionRequest, useRequestInvoiceConfirmation, useResubmitInvoiceRevision } from "../queries/hooks";

const today = "2026-08-11";
const defaults = { channel: "Meeting" as const, customerContactName: "Budi Customer", reference: "REF-DEMO-001", note: "Konfirmasi manual; sistem tidak mengirim email otomatis." };
type EvidenceValues = { channel: ConfirmationChannel; customerContactName: string; reference: string; note: string };
const evidence = (values: EvidenceValues): Omit<InvoiceConfirmationEvidence, "id" | "recordedAt" | "recordedByUserId" | "version" | "correlationId"> => ({ channel: values.channel, displayLabel: "Catatan komunikasi customer", reference: values.reference, referenceDate: today, customerContactName: values.customerContactName, note: values.note });

function Fields<T extends FieldValues & EvidenceValues>({ register, errors, prefix }: { register: UseFormRegister<T>; errors: FieldErrors<T>; prefix: string }) {
  const field = (name: keyof EvidenceValues) => register(name as Path<T>), message = (name: keyof EvidenceValues) => errors[name]?.message as string | undefined;
  return <><Select label="Confirmation channel" id={`${prefix}-channel`} aria-required="true" error={message("channel")} {...field("channel")}><option value="Meeting">Meeting</option><option value="Phone">Phone</option><option value="EmailMetadata">Email metadata</option><option value="DocumentReference">Document reference</option></Select><Input label="Customer contact" id={`${prefix}-contact`} aria-required="true" error={message("customerContactName")} {...field("customerContactName")} /><Input label="Evidence reference" id={`${prefix}-reference`} aria-required="true" error={message("reference")} {...field("reference")} /><Input label="Catatan" id={`${prefix}-note`} aria-required="true" error={message("note")} {...field("note")} /></>;
}

type NormalizedError = ReturnType<typeof normalizeAppError>;
type RetryAttempt = { action: string; execute: () => Promise<void> };
function FormError({ error, action, access, retry, pending, onBack }: { error?: NormalizedError; action: string; access: string; retry?: () => void; pending: boolean; onBack: () => void }) { if (!error) return null; const metadata = error.metadata, correlation = error.correlation_id && error.correlation_id !== "demo-correlation-unavailable"; return <div id="confirmation-error-summary" className="confirmation-conflict break-anywhere" role="alert" aria-label={`${action} belum berhasil`} tabIndex={-1}><Alert tone={error.status === 409 ? "warning" : "danger"} title={`${action} belum berhasil`}><p>{error.message}</p><code>{error.code}{correlation ? `; ID korelasi: ${error.correlation_id}` : ""}</code>{error.status === 409 && <><dl className="detail-list"><dt>Invoice</dt><dd>{String(metadata.invoiceId ?? "Tidak tersedia")}</dd><dt>Aggregate version</dt><dd>Attempted {String(metadata.attemptedVersion ?? "—")}; latest {String(metadata.latestVersion ?? "—")}</dd><dt>Revision</dt><dd>Attempted {String(metadata.attemptedRevisionId ?? "—")} / {String(metadata.attemptedRevisionVersion ?? "—")}; latest {String(metadata.latestRevisionId ?? "—")} / {String(metadata.latestRevisionVersion ?? "—")}</dd><dt>Status</dt><dd>Attempted {String(metadata.attemptedStatus ?? "—")}; latest {String(metadata.latestStatus ?? "—")}</dd><dt>Confirmation cycle</dt><dd>Attempted {String(metadata.attemptedConfirmationCycle ?? metadata.confirmationCycle ?? "—")}; latest {String(metadata.latestConfirmationCycle ?? metadata.confirmationCycle ?? "—")}</dd>{Array.isArray(metadata.fieldDiff) && <><dt>Perubahan aman</dt><dd>{metadata.fieldDiff.map(item => typeof item === "object" && item && "field" in item ? String(item.field) : "Perubahan tersedia").join(", ")}</dd></>}</dl><div className="responsive-actions"><Button variant="secondary" onClick={onBack}>Kembali ke form</Button><Link className="button button-secondary" href={`/invoices/${String(metadata.invoiceId ?? "")}?access=${encodeURIComponent(access)}`}>Buka Invoice terbaru</Link></div></>}{error.retryable && retry && <Button variant="secondary" disabled={pending} onClick={retry}>{pending ? "Mencoba lagi..." : "Coba lagi"}</Button>}<p>Input tetap dipertahankan. Penimpaan paksa dan retry otomatis tidak tersedia.</p></Alert></div>; }

function mapFieldErrors<T extends FieldValues>(form: UseFormReturn<T>, error: NormalizedError) { const known = new Set(Object.keys(form.getValues())); let unknown = false; for (const [name, messages] of Object.entries(error.field_errors)) { if (known.has(name)) form.setError(name as Path<T>, { type: "server", message: messages.join(" ") }); else unknown = true; } return unknown; }

export function ConfirmationTimeline({ invoiceId, access }: { invoiceId: string; access: string }) {
  const query = useInvoiceConfirmationState(invoiceId, access);
  if (query.isPending) return <section aria-label="Timeline evidence customer confirmation"><LoadingState /></section>;
  if (query.isError) { const error = normalizeAppError(query.error); return <section aria-label="Timeline evidence customer confirmation"><DataState kind={error.status === 403 ? "denied" : error.status === 404 ? "empty" : "server"} correlationId={error.correlation_id} action={error.retryable ? <Button variant="secondary" onClick={() => void query.refetch()}>Coba lagi</Button> : undefined} /></section>; }
  if (!query.data?.cycles.length) return <section aria-label="Timeline evidence customer confirmation"><DataState kind="empty" title="Belum ada confirmation cycle" /></section>;
  return <section className="confirmation-timeline" aria-label="Timeline evidence customer confirmation">{query.data.cycles.map(cycle => <article key={cycle.cycle}><StatusBadge tone={cycle.status === "Confirmed" ? "success" : cycle.status === "RevisionRequested" ? "warning" : "info"}>{cycle.status}</StatusBadge><strong>Cycle {cycle.cycle}; revision {cycle.request.revisionId}</strong><span aria-label={`Actor ${cycle.request.actorName ?? cycle.request.actorUserId}`}>{cycle.request.actorName ?? cycle.request.actorUserId}{cycle.request.actorName ? ` (${cycle.request.actorUserId})` : ""}; {cycle.request.channel}; {cycle.request.customerContactName}; {formatDate(cycle.request.requestedAt, true)}</span><span className="break-anywhere">Evidence: {cycle.request.evidence.displayLabel}; {cycle.request.evidence.reference || "Tidak tersedia"}</span><code className="break-anywhere">{cycle.request.evidence.correlationId}</code>{cycle.revisionRequest && <p>{cycle.revisionRequest.reason}; {cycle.revisionRequest.requestedChanges.length} requested change.</p>}{cycle.confirmation && <p>PIC {cycle.confirmation.picName ?? cycle.confirmation.picUserId}{cycle.confirmation.picName ? ` (${cycle.confirmation.picUserId})` : ""}; {cycle.confirmation.statement}; {formatDate(cycle.confirmation.confirmedAt,true)}; revision {cycle.confirmation.revisionId}</p>}</article>)}</section>;
}

export function RevisionDiff({ detail, access, sourceId }: { detail: InvoiceDetail; access: string; sourceId?: string }) {
  const query = useInvoiceRevisionDiff(detail.invoice.id, sourceId ?? "", detail.revision.id, access);
  if (!sourceId || sourceId === detail.revision.id) return <DataState kind="empty" title="Belum ada pasangan revision untuk dibandingkan" />;
  if (query.isPending) return <LoadingState />;
  if (query.isError) { const error = normalizeAppError(query.error); return <DataState kind={error.status === 403 ? "denied" : error.status === 404 ? "empty" : "server"} correlationId={error.correlation_id} action={error.retryable ? <Button variant="secondary" onClick={() => void query.refetch()}>Coba lagi</Button> : undefined} />; }
  const diff = query.data;
  if (!diff) return null;
  return <Card><CardHeader title="Persisted revision diff" description={`${diff.sourceRevisionId} → ${diff.targetRevisionId}`} /><dl className="detail-list"><dt>Grand total before</dt><dd>{formatRupiah(diff.grandTotalBefore)}</dd><dt>Grand total after</dt><dd>{formatRupiah(diff.grandTotalAfter)}</dd><dt>Absolute delta</dt><dd className="break-anywhere">{formatRupiah(diff.absoluteDelta)}</dd><dt>Percentage delta</dt><dd>{diff.denominatorZero ? "Tidak dapat dihitung: denominator nol" : `${diff.percentageDelta}%`}</dd><dt>Reconciliation</dt><dd>{diff.reconciledBefore ? "Before reconciled" : "Before belum reconciled"}; {diff.reconciledAfter ? "after reconciled" : "after belum reconciled"}</dd></dl>{diff.changes.length === 0 ? <DataState kind="empty" title="Tidak ada perubahan persisted" /> : <><TableShell caption="Perbandingan persisted Invoice revision"><thead><tr><th>Perubahan</th><th>Field</th><th>Before</th><th>After</th><th>Requested change</th></tr></thead><tbody>{diff.changes.map((change, index) => <tr key={`${change.field}-${index}`}><td>{change.kind}</td><td>{change.field}</td><td>{change.before ?? "—"}</td><td>{change.after ?? "—"}</td><td>{change.requestedChangeId ?? "Tidak dipetakan otomatis"}</td></tr>)}</tbody></TableShell><div className="invoice-line-cards">{diff.changes.map((change, index) => <article key={`${change.field}-mobile-${index}`}><Badge tone="info">{change.kind}</Badge><strong>{change.field}</strong><span>Before: {change.before ?? "—"}</span><span>After: {change.after ?? "—"}</span><small className="break-anywhere">Requested change: {change.requestedChangeId ?? "Tidak dipetakan otomatis"}</small></article>)}</div></>}</Card>;
}

export function RevisionDiffExplorer({detail,access,state}:{detail:InvoiceDetail;access:string;state:import("../domain/types").InvoiceConfirmationState}){const valid=state.revisions.filter(item=>item.id!==detail.revision.id),initialSource=state.cycles.at(-1)?.revisionRequest?.submittedRevisionId??state.submittedRevisionId??valid[0]?.id??"",[selectedSource,setSelectedSource]=useState(initialSource),[selectedTarget,setSelectedTarget]=useState(detail.revision.id),ids=new Set(state.revisions.map(item=>item.id)),targetId=ids.has(selectedTarget)?selectedTarget:detail.revision.id,sourceId=ids.has(selectedSource)&&selectedSource!==targetId?selectedSource:state.revisions.find(item=>item.id!==targetId)?.id??"",selectedDetail=targetId===detail.revision.id?detail:{...detail,revision:state.revisions.find(item=>item.id===targetId)??detail.revision};return <section aria-label="Revision diff pair selector"><Card><CardHeader title="Pilih persisted revision pair" description="Pair baru menyembunyikan hasil lama sampai query authoritative selesai."/><div className="form-section"><Select label="Source revision" value={sourceId} onChange={event=>setSelectedSource(event.target.value)}>{state.revisions.map(item=><option key={item.id} value={item.id} disabled={item.id===targetId}>{item.id} / R{item.revisionNumber} / V{item.version}</option>)}</Select><Select label="Target revision" value={targetId} onChange={event=>setSelectedTarget(event.target.value)}>{state.revisions.map(item=><option key={item.id} value={item.id} disabled={item.id===sourceId}>{item.id} / R{item.revisionNumber} / V{item.version}</option>)}</Select><code className="break-anywhere">Pair: {sourceId||"tidak tersedia"} {"\u2192"} {targetId}</code></div></Card><RevisionDiff key={`${sourceId}-${targetId}`} detail={selectedDetail} access={access} sourceId={sourceId}/></section>}

export function InvoiceConfirmationPanel({ detail, access, revisionBusy = false, onDirtyChange }: { detail: InvoiceDetail; access: string; revisionBusy?: boolean; onDirtyChange?: (dirty: boolean) => void }) {
  const capabilities = resolveInvoiceCapabilities(access), stateQuery = useInvoiceConfirmationState(detail.invoice.id, access), request = useRequestInvoiceConfirmation(), revision = useRecordInvoiceRevisionRequest(), resubmit = useResubmitInvoiceRevision(), confirmed = useRecordCustomerConfirmed(), [serverError, setServerError] = useState<NormalizedError>(), [failedAction, setFailedAction] = useState("Tindakan"), [retryAttempt, setRetryAttempt] = useState<RetryAttempt>(), [actionPending, setActionPending] = useState(false);
  const requestForm = useForm<RequestConfirmationFormValues>({ resolver: zodResolver(requestConfirmationSchema), defaultValues: { ...defaults, requestDate: today, attestation: false } });
  const revisionForm = useForm<RevisionRequestFormValues>({ resolver: zodResolver(revisionRequestSchema), defaultValues: { ...defaults, responseDate: today, reason: "", customerRequestSummary: "", } });
  const resubmitForm = useForm<ResubmitRevisionFormValues>({ resolver: zodResolver(resubmitRevisionSchema), defaultValues: { resolutionSummary: "", attestation: false } });
  const confirmedForm = useForm<CustomerConfirmedFormValues>({ resolver: zodResolver(customerConfirmedSchema), defaultValues: { ...defaults, confirmedAt: "2026-08-11T10:00:00+07:00", statement: "", attestation: false } });
  const confirmationDirty = requestForm.formState.isDirty || revisionForm.formState.isDirty || resubmitForm.formState.isDirty || confirmedForm.formState.isDirty;
  useUnsavedGuard(confirmationDirty);
  useEffect(() => { onDirtyChange?.(confirmationDirty); return () => onDirtyChange?.(false); }, [confirmationDirty, onDirtyChange]);
  useEffect(() => { if (serverError) document.getElementById("confirmation-error-summary")?.focus(); }, [serverError]);
  if (stateQuery.isPending) return <LoadingState />;
  const state = stateQuery.data;
  if (stateQuery.isError) { const error = normalizeAppError(stateQuery.error); return <DataState kind={error.status === 403 ? "denied" : error.status === 404 ? "empty" : "server"} title="Customer confirmation belum dapat dimuat" correlationId={error.correlation_id} action={error.retryable ? <Button variant="secondary" onClick={() => void stateQuery.refetch()}>Coba lagi</Button> : undefined} />; }
  if (!state) return <DataState kind="server" title="Customer confirmation belum dapat dimuat" />;
  const actor = { userId: access === "pic" ? "usr-pic" : "usr-demo", permissionKeys: access === "pic" ? ["invoice.confirmation.request", "invoice.confirmation.revision-request", "invoice.confirmation.resubmit", "invoice.confirmation.confirm", "invoice.revision.edit"] : ["invoice.confirmation.request", "invoice.confirmation.resubmit", "invoice.revision.edit"] };
  const base = { invoiceId: detail.invoice.id, actor, reason: "Customer confirmation workflow", currentVersion: detail.invoice.version, currentRevisionId: detail.revision.id, currentRevisionVersion: detail.revision.version };
  const run = async <T extends FieldValues>(action: string, operation: () => Promise<unknown>, form: UseFormReturn<T>) => { if (actionPending) return; setActionPending(true); setServerError(undefined); setFailedAction(action); try { await operation(); setRetryAttempt(undefined); form.reset(form.getValues()); } catch (value) { if (!isRequestCancellation(value)) { const error = normalizeAppError(value); mapFieldErrors(form, error); setServerError(error); setRetryAttempt(error.retryable ? { action, execute: () => run(action, operation, form) } : undefined); } } finally { setActionPending(false); } };
  const requestSubmit = requestForm.handleSubmit(values => { const command = { ...base, reason: values.note, data: { ...values, evidence: evidence(values) } }; return run("Request Confirmation", () => request.mutateAsync(command), requestForm); });
  const revisionSubmit = revisionForm.handleSubmit(values => { const command = { ...base, reason: values.reason, data: { ...values, requestedChanges: [{ section: "LinePresentation" as const, currentValueSummary: detail.lines[0]?.description ?? "Tidak tersedia", customerRequestSummary: values.customerRequestSummary, requiresFinancialRecalculation: false, requiresSourceCorrection: false, requiresDocumentUpdate: false, resolutionStatus: "Open" as const }], evidence: evidence(values) } }; return run("Revision Request", () => revision.mutateAsync(command), revisionForm); });
  const resubmitSubmit = resubmitForm.handleSubmit(values => { const command = { ...base, reason: values.resolutionSummary, data: { note: values.resolutionSummary, attestation: values.attestation } }; return run("Resubmit Revision", () => resubmit.mutateAsync(command), resubmitForm); });
  const confirmedSubmit = confirmedForm.handleSubmit(values => { const command = { ...base, reason: values.note, data: { ...values, evidence: evidence(values) } }; return run("Record Customer Confirmed", () => confirmed.mutateAsync(command), confirmedForm); });
  const retry = retryAttempt ? () => void retryAttempt.execute() : undefined;
  const backToForm = () => { setServerError(undefined); setRetryAttempt(undefined); requestAnimationFrame(() => document.querySelector<HTMLElement>(`[data-confirmation-action="${failedAction}"]`)?.focus()); };
  return <><Card><CardHeader title="Customer Confirmation" description="Proses dicatat manual; sistem tidak mengirim email, portal, atau e-signature otomatis." /><FormError error={serverError} action={failedAction} access={access} retry={retry} pending={actionPending} onBack={backToForm} />
    {detail.invoice.status === "Draft" && capabilities.requestConfirmation && <form aria-label="Request Customer Confirmation" aria-describedby="request-help" data-confirmation-action="Request Confirmation" tabIndex={-1} onSubmit={requestSubmit} noValidate className="form-section confirmation-form"><h3>Request Customer Confirmation</h3><p id="request-help">Catat permintaan konfirmasi manual setelah preview dan reconciliation ditinjau.</p><Fields register={requestForm.register} errors={requestForm.formState.errors} prefix="request" /><Input label="Request date" id="request-date" type="date" required error={requestForm.formState.errors.requestDate?.message} {...requestForm.register("requestDate")} /><label className="attestation"><input type="checkbox" aria-invalid={requestForm.formState.errors.attestation ? true : undefined} aria-describedby={requestForm.formState.errors.attestation ? "request-attestation-error" : undefined} {...requestForm.register("attestation")} /> Saya memastikan preview, source, dan reconciliation telah ditinjau.</label>{requestForm.formState.errors.attestation && <span id="request-attestation-error" className="field-error">{requestForm.formState.errors.attestation.message}</span>}<Button type="submit" disabled={request.isPending}>{request.isPending ? "Mencatat..." : "Request confirmation"}</Button></form>}
    {detail.invoice.status === "Pending Customer" && capabilities.recordRevisionRequest && <form aria-label="Record Customer Revision Request" aria-describedby="revision-request-help" data-confirmation-action="Revision Request" tabIndex={-1} onSubmit={revisionSubmit} noValidate className="form-section confirmation-form"><h3>Record Customer Revision Request</h3><p id="revision-request-help">Catat alasan, requested change, dan evidence customer tanpa mengubah submitted snapshot.</p><Fields register={revisionForm.register} errors={revisionForm.formState.errors} prefix="revision-request" /><Input label="Customer response date" id="revision-response-date" type="date" required error={revisionForm.formState.errors.responseDate?.message} {...revisionForm.register("responseDate")} /><Input label="Alasan revisi" id="revision-reason" required error={revisionForm.formState.errors.reason?.message} {...revisionForm.register("reason")} /><Input label="Requested change" id="revision-requested-change" required error={revisionForm.formState.errors.customerRequestSummary?.message} {...revisionForm.register("customerRequestSummary")} /><Button type="submit" disabled={revision.isPending}>{revision.isPending ? "Mencatat..." : "Catat revision request"}</Button></form>}
    {detail.invoice.status === "Revision" && capabilities.resubmit && <form aria-label="Resubmit Invoice Revision" aria-describedby="resubmit-help" data-confirmation-action="Resubmit Revision" tabIndex={-1} onSubmit={resubmitSubmit} noValidate className="form-section confirmation-form"><h3>Resubmit Invoice Revision</h3><p id="resubmit-help">Kirim working revision yang seluruh requested change-nya sudah resolved.</p><Input label="Resolution summary" id="resubmit-summary" required error={resubmitForm.formState.errors.resolutionSummary?.message} {...resubmitForm.register("resolutionSummary")} /><label className="attestation"><input type="checkbox" aria-invalid={resubmitForm.formState.errors.attestation ? true : undefined} aria-describedby={resubmitForm.formState.errors.attestation ? "resubmit-attestation-error" : undefined} {...resubmitForm.register("attestation")} /> Saya memastikan semua perubahan resolved dan reconciliation nol.</label>{resubmitForm.formState.errors.attestation && <span id="resubmit-attestation-error" className="field-error">{resubmitForm.formState.errors.attestation.message}</span>}{revisionBusy && <p role="status">Selesaikan penyimpanan working revision sebelum resubmit.</p>}<Button type="submit" disabled={revisionBusy || resubmit.isPending || state.requestedChanges.some(item => item.resolutionStatus !== "Resolved")}>{resubmit.isPending ? "Mengirim..." : "Resubmit revision"}</Button></form>}
    {detail.invoice.status === "Pending Customer" && capabilities.recordConfirmed && <form aria-label="Record Customer Confirmed" aria-describedby="confirmed-help" data-confirmation-action="Record Customer Confirmed" tabIndex={-1} onSubmit={confirmedSubmit} noValidate className="form-section confirmation-form"><h3>Record Customer Confirmed</h3><p id="confirmed-help">PIC mencatat confirmation dan evidence manual yang authoritative.</p><Fields register={confirmedForm.register} errors={confirmedForm.formState.errors} prefix="confirmed" /><Input label="Confirmation date/time" id="confirmed-at" required error={confirmedForm.formState.errors.confirmedAt?.message} {...confirmedForm.register("confirmedAt")} /><Input label="Confirmation summary" id="confirmed-statement" required error={confirmedForm.formState.errors.statement?.message} {...confirmedForm.register("statement")} /><label className="attestation"><input type="checkbox" aria-invalid={confirmedForm.formState.errors.attestation ? true : undefined} aria-describedby={confirmedForm.formState.errors.attestation ? "confirmed-attestation-error" : undefined} {...confirmedForm.register("attestation")} /> Saya memastikan evidence customer confirmation benar.</label>{confirmedForm.formState.errors.attestation && <span id="confirmed-attestation-error" className="field-error">{confirmedForm.formState.errors.attestation.message}</span>}<Button type="submit" disabled={confirmed.isPending}>{confirmed.isPending ? "Mencatat..." : "Catat customer confirmed"}</Button></form>}
    {detail.invoice.status === "Pending Approval" && <div className="break-anywhere" aria-label="Status customer confirmation"><Alert tone="info" title={"CUSTOMER CONFIRMED \u2014 BELUM DISETUJUI"}>Handoff informatif menunggu tahap berikutnya. Tidak ada approval atau release action pada tahap ini. Confirmed revision {detail.revision.id}; grand total {formatRupiah(detail.summary.grandTotal)}; reconciliation {detail.reconciliation.reconciled?"nol":"belum nol"}.</Alert></div>}
  </Card><ConfirmationTimeline invoiceId={detail.invoice.id} access={access} />{detail.invoice.status === "Revision" && <RevisionDiffExplorer detail={detail} access={access} state={state} />}</>;
}
