import { describe,expect,it } from "vitest";
import type { AuditEvent,DocumentMetadata,DocumentVersion,Project } from "@/features/foundation/domain/models";
import { assertDocumentInvariant } from "../domain/validation";
import { createDocumentRepository } from "./mock-adapter";

const actor={userId:"usr-1",permissionKeys:["document.view","document.manage","document.upload","audit.view"]};
const file={originalFileName:"contract.pdf",displayFileName:"contract.pdf",mimeType:"application/pdf",sizeBytes:1200};
const project:Project={id:"prj-1",code:"P1",name:"Project",description:"",customerId:"c1",picUserId:"usr-1",status:"Active",branchIds:[],serviceIds:[],sphId:"sph-1",updatedAt:"2026-01-01T00:00:00+07:00",version:1};
function setup(){
 const audits:AuditEvent[]=[];
 const documents:DocumentMetadata[]=[{id:"doc-1",objectType:"Project",objectId:"prj-1",category:"Project Brief",currentVersionId:"dv-1",versionIds:["dv-1"]}];
 const versions:DocumentVersion[]=[{id:"dv-1",documentId:"doc-1",version:1,fileName:"old.pdf",mimeType:"application/pdf",sizeBytes:100,checksumSha256:"",status:"Available",uploadedByUserId:"usr-1",uploadedAt:"2026-01-01T00:00:00+07:00"}];
 const repo=createDocumentRepository({documents,versions,audits,getProjects:()=>[project],getContracts:()=>[],getUsers:()=>[{id:"usr-1",name:"Manager"}],getRateVersion:async()=>({rate:{id:"rate-1",status:"Draft"}})});
 return{repo,audits};
}
const upload=(repo:ReturnType<typeof createDocumentRepository>,currentVersion:number,scenario:"pending"|"scanning"|"clean"|"malware"|"scanner-failure"="pending")=>repo.createVersion({documentId:"doc-1",currentVersion,file,reason:"Versi pengganti",notes:"",scenario,actor});

describe("document lifecycle remediation",()=>{
 it.each(["pending","scanning","malware","scanner-failure"] as const)("increments aggregate for %s",async scenario=>{const {repo}=setup(),before=await repo.getDocument("doc-1"),result=await upload(repo,before.document.version,scenario);expect(result.documentAggregateVersion).toBe(before.document.version+1);expect(result.documentVersionRecordVersion).toBe(1);});
 it("rejects stale upload without partial state",async()=>{const {repo,audits}=setup(),before=await repo.getDocument("doc-1");await upload(repo,before.document.version);const snapshot=await repo.getDocument("doc-1"),count=audits.length;await expect(upload(repo,before.document.version)).rejects.toMatchObject({status:409});expect(await repo.getDocument("doc-1")).toEqual(snapshot);expect(audits).toHaveLength(count);});
 it("enforces transition concurrency and matrix",async()=>{const {repo,audits}=setup(),created=await upload(repo,1),before=await repo.getDocument("doc-1"),version=before.versions.find(v=>v.id===created.documentVersionId)!;await expect(repo.transitionVersionStatus({documentId:"doc-1",documentVersionId:version.id,currentDocumentVersion:1,currentVersionVersion:version.version,target:"Scanning",reason:"stale",actor})).rejects.toMatchObject({status:409});const count=audits.length;await expect(repo.transitionVersionStatus({documentId:"doc-1",documentVersionId:version.id,currentDocumentVersion:before.document.version,currentVersionVersion:version.version,target:"Pending",reason:"illegal",actor})).rejects.toMatchObject({code:"DOCUMENT_VERSION_TRANSITION_INVALID"});expect(audits).toHaveLength(count);const result=await repo.transitionVersionStatus({documentId:"doc-1",documentVersionId:version.id,currentDocumentVersion:before.document.version,currentVersionVersion:version.version,target:"Scanning",reason:"Mulai scan",actor});expect(result).toMatchObject({processingStatus:"Scanning",documentVersionRecordVersion:2,documentAggregateVersion:3});});
 it("keeps newer current on out-of-order completion",async()=>{const {repo,audits}=setup(),v2=await upload(repo,1,"scanning"),d2=await repo.getDocument("doc-1"),v3=await upload(repo,d2.document.version,"scanning"),d3=await repo.getDocument("doc-1"),r3=d3.versions.find(v=>v.id===v3.documentVersionId)!;await repo.transitionVersionStatus({documentId:"doc-1",documentVersionId:r3.id,currentDocumentVersion:d3.document.version,currentVersionVersion:r3.version,target:"Clean",reason:"v3 clean",actor});const mid=await repo.getDocument("doc-1"),r2=mid.versions.find(v=>v.id===v2.documentVersionId)!;await repo.transitionVersionStatus({documentId:"doc-1",documentVersionId:r2.id,currentDocumentVersion:mid.document.version,currentVersionVersion:r2.version,target:"Clean",reason:"v2 terlambat",actor});const final=await repo.getDocument("doc-1");expect(final.currentVersion?.id).toBe(r3.id);expect(final.versions.find(v=>v.id===r2.id)).toMatchObject({processingStatus:"Clean",isCurrent:false});expect(audits.filter(a=>a.action==="document.version.promoted"&&a.reason==="v2 terlambat")).toHaveLength(0);assertDocumentInvariant(final.document,final.versions);});
 it("audits clean creation with one correlation",async()=>{const {repo,audits}=setup(),created=await repo.createDocument({owner:{objectType:"Project",objectId:"prj-1",projectId:"prj-1"},category:"Project Brief",title:"New",description:"",required:false,file,reason:"Create",notes:"",scenario:"clean",actor}),events=audits.filter(a=>a.objectId===created.documentId);expect(events.map(e=>e.action)).toEqual(expect.arrayContaining(["document.created","document.version.uploaded","document.scan.clean","document.version.promoted"]));expect(new Set(events.map(e=>e.correlationId)).size).toBe(1);});
 it("rejects cross-owner category authoritatively",async()=>{const {repo}=setup();await expect(repo.createDocument({owner:{objectType:"Project",objectId:"prj-1",projectId:"prj-1"},category:"Contract",title:"Wrong",description:"",required:false,file,reason:"Test",notes:"",scenario:"clean",actor})).rejects.toMatchObject({status:422,code:"DOCUMENT_CATEGORY_INVALID",field_errors:{category:expect.any(Array)}});});
 it("preserves AbortError cancellation",async()=>{const {repo}=setup(),controller=new AbortController(),request=repo.listByOwner("Project","prj-1",{},controller.signal);controller.abort();await expect(request).rejects.toMatchObject({name:"AbortError"});});
});
