"use client";
import { zodResolver } from "@hookform/resolvers/zod";
import { faFileArrowUp,faTrash } from "@fortawesome/free-solid-svg-icons";
import { useRouter,useSearchParams } from "next/navigation";
import { useEffect,useMemo,useState } from "react";
import { useDropzone } from "react-dropzone";
import { useForm } from "react-hook-form";
import { toast } from "sonner";
import { Alert,AppIcon,Badge,Button,Card,CardHeader,DataState,Input,LoadingState,Modal,PageHeader,Select } from "@/components/ui";
import type { DocumentObjectType } from "@/features/foundation/domain/models";
import { isRequestCancellation } from "@/features/foundation/domain/errors";
import { useProjectQuery } from "@/features/foundation/queries/hooks";
import { ConflictState,ErrorSummary,LeaveGuard,focusErrorSummary } from "@/features/master-data/components/form-shared";
import { useUnsavedGuard } from "@/features/master-data/components/use-unsaved-guard";
import type { ConflictMetadata } from "@/features/master-data/domain/mutation-error";
import { formatBytes,formatDate } from "@/lib/formatters";
import { createDocumentFormSchema,type DocumentCreateFormValues } from "../domain/form-schema";
import { mapDocumentMutationError } from "../domain/mutation-error";
import type { DocumentScenario } from "../domain/types";
import { allowedDocumentCategories,defaultDocumentCategory,DOCUMENT_MAX_SIZE_BYTES,safeFileName,validateUploadMetadata } from "../domain/validation";
import { useDocumentAccess } from "../permissions/demo-access";
import { useCreateDocument,useCreateDocumentVersion,useDocumentDetail } from "../queries/hooks";

const objectTypes:readonly DocumentObjectType[]=["Project","SPH","RateVersion"];
const scenarios:readonly DocumentScenario[]=["clean","pending","scanning","malware","scanner-failure","server-failure"];
export function DocumentUploadForm({mode,projectId,documentId}:{mode:"create"|"version";projectId?:string;documentId?:string}){
 const access=useDocumentAccess(),params=useSearchParams(),router=useRouter(),rawType=params.get("objectType"),objectType=objectTypes.find(v=>v===rawType)??(rawType?undefined:"Project"),detail=useDocumentDetail(documentId??"",access.canUpload&&mode==="version"),project=useProjectQuery(projectId??"",access.canUpload&&mode==="create"&&Boolean(objectType)),create=useCreateDocument(),createVersion=useCreateDocumentVersion();
 const schema=useMemo(()=>createDocumentFormSchema(objectType??"Project"),[objectType]),initialCategory=defaultDocumentCategory(objectType??"Project"),form=useForm<DocumentCreateFormValues>({resolver:zodResolver(schema),shouldFocusError:false,defaultValues:{category:initialCategory,title:"",description:"",required:false,reason:"",notes:""}}),[file,setFile]=useState<File|null>(null),[fileError,setFileError]=useState(""),[globalError,setGlobalError]=useState<{code:string;message:string;details:readonly string[];correlationId:string;retryable:boolean}|null>(null),[review,setReview]=useState<DocumentCreateFormValues|null>(null),[reviewOpen,setReviewOpen]=useState(false),[conflict,setConflict]=useState<{metadata:ConflictMetadata;correlationId:string}|null>(null);
 const document=detail.data?.document,current=detail.data?.currentVersion,objectId=objectType==="Project"?projectId??"":params.get("objectId")??"",ownerProjectId=projectId??document?.owner.projectId??"",categoryOptions=useMemo(()=>objectType?allowedDocumentCategories(objectType):[],[objectType]);
 useEffect(()=>{if(objectType&&!categoryOptions.includes(form.getValues("category")))form.setValue("category",defaultDocumentCategory(objectType));},[categoryOptions,form,objectType]);
 const guard=useUnsavedGuard(form.formState.isDirty||Boolean(file),()=>router.push(access.url(mode==="version"?`/documents/${documentId}`:`/projects/${projectId}/documents`)));
 const dropzone=useDropzone({maxFiles:1,maxSize:DOCUMENT_MAX_SIZE_BYTES,accept:{"application/pdf":[".pdf"],"image/jpeg":[".jpg",".jpeg"],"image/png":[".png"]},onDropAccepted:files=>{setFile(files[0]??null);setFileError("");},onDropRejected:()=>setFileError("File harus PDF, JPEG, atau PNG dengan ukuran maksimal 5 MB.")});
 if(!access.canUpload)return <DataState kind="denied" title="Tidak dapat mengunggah dokumen"/>;
 if(mode==="create"&&!objectType)return <DataState kind="server" title="Tipe owner tidak valid" description="Gunakan Project, SPH, atau RateVersion."/>;
 if(mode==="create"&&!objectId)return <DataState kind="empty" title="Owner dokumen belum dipilih" description="Object ID wajib tersedia sebelum upload."/>;
 if((mode==="version"&&detail.isPending)||(mode==="create"&&project.isPending))return <LoadingState/>;
 if(mode==="version"&&detail.isError)return <DataState kind={detail.error.status===404?"empty":"server"} correlationId={detail.error.correlation_id} action={<Button onClick={()=>detail.refetch()}>Coba lagi</Button>}/>;
 if(mode==="create"&&project.isError)return <DataState kind={project.error.status===404?"empty":"server"} title="Owner tidak dapat dimuat" correlationId={project.error.correlation_id} action={<Button onClick={()=>project.refetch()}>Coba lagi</Button>}/>;
 const scenario=scenarios.find(v=>v===params.get("scenario"))??"clean",errorCount=Object.keys(form.formState.errors).length+(fileError?1:0)+(globalError?1:0),ownerLabel=objectType==="Project"?`${project.data?.project.code??objectId} · ${project.data?.project.name??objectId}`:objectType==="SPH"?`SPH ${project.data?.sph.id===objectId?project.data.sph.number:objectId} · Project ${project.data?.project.name??ownerProjectId}`:`Rate Version ${project.data?.rates.find(rate=>rate.id===objectId)?.id??objectId} · Project ${project.data?.project.name??ownerProjectId}`;
 const submit=form.handleSubmit(values=>{setGlobalError(null);if(!file){setFileError("Pilih satu file sebelum melanjutkan.");focusErrorSummary();return;}const validation=validateUploadMetadata({originalFileName:file.name,displayFileName:safeFileName(file.name)??"",mimeType:file.type,sizeBytes:file.size});if(!validation.valid){setFileError(Object.values(validation.errors).flat().join(" "));focusErrorSummary();return;}setReview(values);setReviewOpen(true);},()=>{if(!file)setFileError("Pilih satu file sebelum melanjutkan.");focusErrorSummary();});
 const save=async()=>{if(!review||!file||!objectType)return;const name=safeFileName(file.name)??file.name,metadata={originalFileName:name,displayFileName:name,mimeType:file.type,sizeBytes:file.size};try{const result=mode==="create"?await create.mutateAsync({owner:{objectType,objectId,projectId:ownerProjectId},category:review.category,title:review.title,description:review.description,required:review.required,file:metadata,reason:review.reason,notes:review.notes,scenario,actor:access.actor}):await createVersion.mutateAsync({documentId:document!.id,currentVersion:params.get("scenario")==="conflict"?document!.version-1:document!.version,file:metadata,reason:review.reason,notes:review.notes,scenario,actor:access.actor});toast.success(result.message);form.reset(review);setFile(null);setReview(null);setReviewOpen(false);router.push(access.url(`/documents/${result.documentId}`));}catch(error){if(isRequestCancellation(error))return;const mapped=mapDocumentMutationError(error);setReviewOpen(false);if(mapped.conflict)setConflict({metadata:mapped.conflict,correlationId:mapped.correlationId});else{for(const field of ["title","category","description","reason","notes"] as const){const message=mapped.fieldErrors[field];if(message)form.setError(field,{type:"server",message});}if(mapped.fieldErrors.file)setFileError(mapped.fieldErrors.file);setGlobalError({code:mapped.code,message:mapped.message,details:mapped.globalErrors,correlationId:mapped.correlationId,retryable:mapped.retryable});focusErrorSummary();}}};
 return <><PageHeader eyebrow="Document Versioning" title={mode==="create"?"Tambah dokumen":"Unggah versi baru"} description={mode==="create"?`${objectType} · ${ownerLabel}`:`${document?.title} · ${document?.owner.label}`} meta={<Badge tone="warning">Data demo · scanning simulasi</Badge>}/>{conflict&&<ConflictState metadata={conflict.metadata} correlationId={conflict.correlationId} reload={access.url(`/documents/${documentId}/versions/new`)} back={access.url(`/documents/${documentId}`)}/>} {globalError&&<Alert tone="danger" title="Dokumen belum dapat disimpan"><p>{globalError.code} · {globalError.message} · {globalError.correlationId}</p>{globalError.details.length>0&&<ul>{globalError.details.map(detail=><li key={detail}>{detail}</li>)}</ul>}{globalError.retryable&&<Button onClick={save} disabled={create.isPending||createVersion.isPending}>Coba lagi</Button>}</Alert>}{mode==="version"&&current&&<Card><CardHeader title="Current clean version"/><p>v{current.versionNumber} · {current.displayFileName} · {formatDate(current.uploadedAt,true)}</p></Card>}
 <form onSubmit={submit} noValidate><ErrorSummary count={errorCount}/><Card><CardHeader title="Metadata dokumen" description={mode==="create"?`Owner ${objectType}; kategori mengikuti jenis owner ini.`:undefined}/><div className="form-section">{mode==="create"&&<><Select label="Kategori" error={form.formState.errors.category?.message} {...form.register("category")}>{categoryOptions.map(category=><option key={category}>{category}</option>)}</Select><Input label="Judul dokumen" error={form.formState.errors.title?.message} {...form.register("title")}/><Input label="Deskripsi" error={form.formState.errors.description?.message} {...form.register("description")}/><label className="check-row"><input type="checkbox" {...form.register("required")}/>Dokumen wajib</label></>}<Input label={mode==="create"?"Alasan pencatatan":"Alasan penggantian"} error={form.formState.errors.reason?.message} {...form.register("reason")}/><Input label="Catatan" error={form.formState.errors.notes?.message} {...form.register("notes")}/></div></Card>
 <Card><CardHeader title="File upload" description="Satu file PDF/JPEG/PNG, maksimal 5 MB."/><div {...dropzone.getRootProps({className:"dropzone",role:"button","aria-label":"Pilih file dokumen","aria-invalid":fileError?true:undefined,"aria-describedby":fileError?"document-file-help document-file-error":"document-file-help"})}><input {...dropzone.getInputProps({id:"document-file-input","aria-invalid":fileError?true:undefined,"aria-describedby":fileError?"document-file-help document-file-error":"document-file-help"})}/><AppIcon icon={faFileArrowUp}/><strong>{file?safeFileName(file.name):"Pilih atau jatuhkan file"}</strong><span id="document-file-help">Validasi browser adalah feedback awal; repository tetap authoritative.</span></div>{fileError&&<div id="document-file-error" className="field-error" role="alert" tabIndex={-1}>{fileError} <Button variant="quiet" onClick={()=>globalThis.document.getElementById("document-file-input")?.focus()}>Fokus ke file</Button></div>}{file&&<div className="file-summary"><span>{safeFileName(file.name)} · {file.type} · {formatBytes(file.size)}</span><Button variant="danger" leadingIcon={<AppIcon icon={faTrash}/>} onClick={()=>{setFile(null);setFileError("");}}>Hapus file</Button></div>}</Card><div className="form-actions"><Button variant="secondary" onClick={guard.requestLeave}>Kembali</Button><Button type="submit" disabled={create.isPending||createVersion.isPending}>Tinjau upload</Button></div></form>
 <Modal open={reviewOpen} onClose={()=>setReviewOpen(false)} title="Tinjau metadata upload" description="Binary hanya berada pada sesi browser dan tidak disimpan ke mock repository." footer={<><Button variant="secondary" onClick={()=>setReviewOpen(false)}>Kembali</Button><Button onClick={save} disabled={create.isPending||createVersion.isPending}>Konfirmasi upload</Button></>}><p>{file&&safeFileName(file.name)} · {file&&formatBytes(file.size)}</p></Modal><LeaveGuard guard={guard}/></>;
}
