"use client";
import Link from "next/link";
import { useSearchParams } from "next/navigation";
import { useState } from "react";
import { Alert,Badge,Button,Card,CardHeader,DataState,Input,LoadingState,Modal,PageHeader,StatusBadge } from "@/components/ui";
import { useAuditQuery,useUsersQuery } from "@/features/foundation/queries/hooks";
import { formatBytes,formatDate } from "@/lib/formatters";
import type { DocumentProcessingStatus,ManagedDocumentVersion } from "../domain/types";
import { allowedDocumentVersionTransitions } from "../domain/validation";
import { useDocumentAccess } from "../permissions/demo-access";
import { useDocumentDetail,useTransitionDocumentVersion } from "../queries/hooks";

export function DocumentDetailPage({documentId}:{documentId:string}){
 const access=useDocumentAccess(),params=useSearchParams(),query=useDocumentDetail(documentId,access.canView),audits=useAuditQuery("Document",documentId,access.canView&&access.canAudit),users=useUsersQuery(access.canView&&access.canAudit),transition=useTransitionDocumentVersion();
 const [intent,setIntent]=useState<{version:ManagedDocumentVersion;target:DocumentProcessingStatus}|null>(null),[reason,setReason]=useState(""),[feedback,setFeedback]=useState<{tone:"success"|"danger";text:string}|null>(null),[conflict,setConflict]=useState<Readonly<Record<string,unknown>>|null>(null);
 if(!access.canView)return <DataState kind="denied" title="Akses dokumen dibatasi" description="Filename, owner, dan version history tidak dimuat."/>;
 if(query.isPending)return <LoadingState/>;
 if(query.isError)return <DataState kind={query.error.status===404?"empty":"server"} title={query.error.status===404?"Dokumen tidak ditemukan":undefined} correlationId={query.error.correlation_id} action={<Button onClick={()=>query.refetch()}>Coba lagi</Button>}/>;
 const {document,currentVersion,versions}=query.data;
 const submit=async()=>{if(!intent||!reason.trim())return;try{const stale=params.get("scenario")==="transition-conflict",result=await transition.mutateAsync({documentId,documentVersionId:intent.version.id,currentDocumentVersion:stale?document.version-1:document.version,currentVersionVersion:intent.version.version,target:intent.target,reason:reason.trim(),actor:access.actor});setFeedback({tone:"success",text:`${result.message} · ${result.correlationId}`});setIntent(null);setReason("");}catch(error){const app=error as import("@/features/foundation/domain/errors").AppError;if(app.status===409)setConflict(app.metadata);else setFeedback({tone:"danger",text:`${app.code} · ${app.message} · ${app.correlation_id}`});}};
 const actionLabel=(target:DocumentProcessingStatus)=>target==="Scanning"?"Mulai scanning":`Tandai ${target}`;
 return <><PageHeader eyebrow={`${document.owner.objectType} · ${document.owner.label}`} title={document.title} description={`${document.category} · ${document.description||"Tanpa deskripsi"}`} meta={<><StatusBadge tone={document.status==="Active"?"success":"neutral"}>{document.status}</StatusBadge><StatusBadge tone={currentVersion?.scanStatus==="Clean"?"success":"warning"}>{currentVersion?.scanStatus??"Belum ada current"}</StatusBadge><Badge tone="warning">Data demo</Badge></>} actions={<><Link className="button button-secondary" href={access.url(`/projects/${document.owner.projectId}/documents`)}>Daftar dokumen</Link>{access.canUpload&&document.status==="Active"&&<Link className="button button-primary" href={access.url(`/documents/${document.id}/versions/new`)}>Unggah versi baru</Link>}</>}/>
 {conflict?<DataState kind="conflict" title="Status versi telah berubah" description={`Versi agregat pengguna/terbaru: ${String(conflict.userVersion)}/${String(conflict.latestVersion)}. Version record pengguna/terbaru: ${String(conflict.userVersionRecordVersion??"-")}/${String(conflict.latestVersionRecordVersion??"-")}. Current version: ${String(conflict.currentVersionNumber)}.`} correlationId="demo-transition-conflict" action={<div className="page-actions"><Button onClick={()=>{setConflict(null);query.refetch();}}>Muat versi terbaru</Button><Button variant="secondary" onClick={()=>setConflict(null)}>Kembali tanpa mengubah</Button></div>}/>:feedback&&<Alert tone={feedback.tone} title={feedback.text}/>}<Alert tone="info" title="Metadata-only">File binary dan signed download URL belum tersedia karena backend belum terhubung. Preview dan Download dinonaktifkan.</Alert>
 <div className="detail-grid"><Card><CardHeader title="Current version"/>{currentVersion?<dl className="detail-list"><dt>Versi</dt><dd>v{currentVersion.versionNumber}</dd><dt>File</dt><dd className="break-long">{currentVersion.displayFileName}</dd><dt>MIME/ukuran</dt><dd>{currentVersion.mimeType} · {formatBytes(currentVersion.sizeBytes)}</dd><dt>Validation</dt><dd>{currentVersion.validationStatus}</dd><dt>Scanning</dt><dd>{currentVersion.scanStatus}</dd><dt>Uploader</dt><dd>{users.data?.find((u)=>u.id===currentVersion.uploadedByUserId)?.name??currentVersion.uploadedByUserId}</dd><dt>Waktu</dt><dd>{formatDate(currentVersion.uploadedAt,true)}</dd><dt>Alasan</dt><dd>{currentVersion.reason}</dd></dl>:<DataState kind="empty" title="Belum ada current Clean version"/>}<div className="form-actions"><Button disabled>Preview</Button><Button disabled>Download</Button></div></Card><Card><CardHeader title="Aturan versioning"/><p>Initial upload scenario menentukan hasil pipeline mock. Transition manual hanya mengikuti Pending → Scanning → terminal.</p><p><strong>Simulasi scanning — backend belum terhubung.</strong></p></Card></div>
 <Card><CardHeader title="Version timeline"/><ol className="document-version-timeline">{versions.map((version)=><li key={version.id}><div><StatusBadge tone={version.processingStatus==="Clean"?"success":version.processingStatus==="Rejected"||version.processingStatus==="Failed"?"danger":"warning"}>{version.processingStatus}</StatusBadge><strong>v{version.versionNumber} · {version.isCurrent?"Current":"Historical / belum dipromosikan"}</strong></div><span className="break-long">{version.displayFileName}</span><small>{version.mimeType} · {formatBytes(version.sizeBytes)} · {formatDate(version.uploadedAt,true)}</small><small>{version.reason} · {version.correlationId}</small>{version.failureMessage&&<Alert tone="danger" title="Versi tidak dipromosikan">{version.failureMessage}</Alert>}{access.canManage&&!version.isCurrent&&allowedDocumentVersionTransitions(version.processingStatus).length>0&&<div className="table-actions">{allowedDocumentVersionTransitions(version.processingStatus).map((target)=><Button key={target} size="sm" variant={target==="Rejected"||target==="Failed"?"danger":"primary"} onClick={()=>{setIntent({version,target});setReason("");}}>{actionLabel(target)}</Button>)}</div>}</li>)}</ol></Card>
 <Card><CardHeader title="Audit trail dokumen"/>{!access.canAudit?<DataState kind="denied" title="Izin audit tidak tersedia"/>:audits.isPending?<LoadingState/>:audits.isError?<DataState kind="server" title="Audit tidak dapat dimuat" correlationId={audits.error.correlation_id} action={<Button onClick={()=>audits.refetch()}>Coba lagi</Button>}/>:!audits.data?.length?<DataState kind="empty" title="Belum ada audit dokumen"/>:<>{users.isError&&<Alert tone="warning" title="Nama actor tidak dapat dimuat">Event tetap ditampilkan menggunakan actor ID. <Button onClick={()=>users.refetch()}>Coba lagi</Button></Alert>}<ol className="audit-list">{audits.data.map((event)=><li key={event.id}><strong>{event.action}</strong><span>{users.data?.find((u)=>u.id===event.actorUserId)?.name??event.actorUserId} · {formatDate(event.occurredAt,true)}</span><small>{event.reason??"Tanpa alasan"} · {event.correlationId}</small></li>)}</ol></>}</Card>
 <Modal open={Boolean(intent)} onClose={()=>setIntent(null)} title="Konfirmasi simulasi processing" description="Alasan pengguna dicatat ke audit; antivirus backend belum terhubung." footer={<><Button variant="secondary" onClick={()=>setIntent(null)}>Batal</Button><Button onClick={submit} disabled={!reason.trim()||transition.isPending}>{transition.isPending?"Memproses…":"Konfirmasi"}</Button></>}><dl className="detail-list"><dt>Versi</dt><dd>v{intent?.version.versionNumber}</dd><dt>Status</dt><dd>{intent?.version.processingStatus} → {intent?.target}</dd><dt>File</dt><dd className="break-long">{intent?.version.displayFileName}</dd><dt>Konsekuensi</dt><dd>{intent?.target==="Clean"?"Menjadi current hanya jika lebih baru daripada current Clean.":"Versi tidak menjadi current."}</dd></dl><Input label="Alasan transition" value={reason} onChange={(event)=>setReason(event.target.value)} error={!reason.trim()?"Alasan wajib diisi.":undefined}/></Modal></>;
}
