import { fireEvent,render,screen,waitFor } from "@testing-library/react";
import userEvent from "@testing-library/user-event";
import { beforeEach,describe,expect,it,vi } from "vitest";
import { toast } from "sonner";
import { AppError } from "@/features/foundation/domain/errors";
import { DocumentDetailPage } from "./document-detail-page";
import { DocumentListPage } from "./document-list-page";
import { DocumentUploadForm } from "./document-upload-form";

let search="access=manage";
const replace=vi.fn(),push=vi.fn(),listHook=vi.fn(),detailHook=vi.fn(),auditHook=vi.fn(),usersHook=vi.fn(),projectHook=vi.fn(),mutation={mutateAsync:vi.fn(),isPending:false};
vi.mock("next/navigation",()=>({useRouter:()=>({replace,push}),usePathname:()=>"/projects/prj-026/documents",useSearchParams:()=>new URLSearchParams(search)}));
vi.mock("../queries/hooks",()=>({useDocumentList:(...args:unknown[])=>listHook(...args),useDocumentDetail:(...args:unknown[])=>detailHook(...args),useCreateDocument:()=>mutation,useCreateDocumentVersion:()=>mutation,useTransitionDocumentVersion:()=>mutation}));
vi.mock("@/features/foundation/queries/hooks",()=>({useProjectQuery:(...args:unknown[])=>projectHook(...args),useAuditQuery:()=>auditHook(),useUsersQuery:()=>usersHook()}));

const owner={objectType:"Project" as const,objectId:"prj-026",projectId:"prj-026",label:"Project Demo"};
const version={id:"docv-1",documentId:"doc-1",versionNumber:1,originalFileName:"contract.pdf",displayFileName:"contract.pdf",mimeType:"application/pdf",sizeBytes:1200,uploadStatus:"Received" as const,validationStatus:"Valid" as const,scanStatus:"Clean" as const,processingStatus:"Clean" as const,uploadedByUserId:"usr-dewi",uploadedAt:"2026-08-10T10:00:00+07:00",reason:"Awal",notes:"",isCurrent:true,correlationId:"corr-doc",version:1};
const document={id:"doc-1",owner,category:"Project Brief" as const,title:"Project brief",description:"Demo",status:"Active" as const,required:false,currentVersionId:version.id,currentVersionNumber:1,createdByUserId:"usr-dewi",createdAt:version.uploadedAt,updatedAt:version.uploadedAt,version:2};
const projectData={project:{id:"prj-026",code:"PRJ-026",name:"Project Demo"},sph:{id:"sph-026",number:"SPH-026"},rates:[{id:"rate-prj-026-v2",status:"Draft",effectiveFrom:"2026-01-01"}]};

beforeEach(()=>{search="access=manage";replace.mockReset();push.mockReset();mutation.mutateAsync.mockReset();mutation.isPending=false;projectHook.mockReturnValue({data:projectData,isPending:false,isError:false});listHook.mockReturnValue({data:{owner,summary:{total:1,requiredComplete:0,pendingOrScanning:0,rejectedOrFailed:0,withoutCurrentClean:0},items:[{id:document.id,owner,category:document.category,title:document.title,status:document.status,required:false,currentVersionNumber:1,currentFileName:version.displayFileName,currentMimeType:version.mimeType,currentSizeBytes:version.sizeBytes,currentScanStatus:"Clean",latestProcessingStatus:"Clean",uploadedByName:"Dewi",updatedAt:document.updatedAt,version:2}],total:1,page:1,pageSize:20,hasNextPage:false},isPending:false,isError:false});detailHook.mockReturnValue({data:{document,currentVersion:version,versions:[version]},isPending:false,isError:false});auditHook.mockReturnValue({data:[{id:"audit",actorUserId:"usr-dewi",action:"document.created",objectType:"Document",objectId:"doc-1",occurredAt:version.uploadedAt,reason:"Awal",correlationId:"corr-doc"}],isPending:false,isError:false});usersHook.mockReturnValue({data:[{id:"usr-dewi",name:"Dewi"}],isPending:false,isError:false});});

async function fillValidForm(){const user=userEvent.setup();await user.type(screen.getByLabelText("Judul dokumen"),"Dokumen baru");await user.type(screen.getByLabelText("Alasan pencatatan"),"Kebutuhan project");const input=screen.getByLabelText("Pilih file dokumen").querySelector<HTMLInputElement>('input[type="file"]')??documentQueryFile();fireEvent.change(input,{target:{files:[new File(["demo"],"document.pdf",{type:"application/pdf"})]}});return user;}
function documentQueryFile(){const input=globalThis.document.querySelector<HTMLInputElement>('input[type="file"]');if(!input)throw new Error("file input missing");return input;}
async function openReview(){const user=await fillValidForm();await user.click(screen.getByRole("button",{name:"Tinjau upload"}));return user;}

describe("document production components",()=>{
 it("renders document list and immutable detail",()=>{const list=render(<DocumentListPage projectId="prj-026"/>);expect(screen.getByRole("table",{name:"Daftar dokumen project"})).toBeVisible();list.unmount();render(<DocumentDetailPage documentId="doc-1"/>);expect(screen.getByText("v1 · Current")).toBeVisible();expect(screen.getByRole("button",{name:"Preview"})).toBeDisabled();});
 it.each(["view","none"])("enforces direct upload denial for %s persona",access=>{search=`access=${access}`;render(<DocumentUploadForm mode="create" projectId="prj-026"/>);expect(screen.getByText("Tidak dapat mengunggah dokumen")).toBeVisible();expect(screen.queryByRole("button",{name:"Tinjau upload"})).not.toBeInTheDocument();expect(projectHook).toHaveBeenCalledWith("prj-026",false);expect(mutation.mutateAsync).not.toHaveBeenCalled();});
 it.each([["",["Project Brief","Other"],"Project Brief","PRJ-026 · Project Demo"],["objectType=SPH&objectId=sph-026",["Contract","Other"],"Contract","SPH SPH-026 · Project Project Demo"],["objectType=RateVersion&objectId=rate-prj-026-v2",["Rate Support","Other"],"Rate Support","Rate Version rate-prj-026-v2 · Project Project Demo"]] as const)("renders owner policy for %s",(query,categories,selected,label)=>{search=`access=manage&${query}`;render(<DocumentUploadForm mode="create" projectId="prj-026"/>);const select=screen.getByLabelText("Kategori") as HTMLSelectElement;expect([...select.options].map(option=>option.text)).toEqual(categories);expect(select.value).toBe(selected);expect(screen.getByText(new RegExp(label))).toBeVisible();});
 it("rejects invalid objectType without owner query or mutation",()=>{search="access=manage&objectType=Invoice&objectId=inv-1";render(<DocumentUploadForm mode="create" projectId="prj-026"/>);expect(screen.getByText("Tipe owner tidak valid")).toBeVisible();expect(projectHook).toHaveBeenCalledWith("prj-026",false);expect(mutation.mutateAsync).not.toHaveBeenCalled();});
 it("connects file error to input and focuses summary",async()=>{const user=userEvent.setup();render(<DocumentUploadForm mode="create" projectId="prj-026"/>);await user.click(screen.getByRole("button",{name:"Tinjau upload"}));await waitFor(()=>expect(globalThis.document.getElementById("master-form-errors")).toHaveFocus());const input=documentQueryFile();expect(input).toHaveAttribute("aria-invalid","true");expect(input).toHaveAttribute("aria-describedby","document-file-help document-file-error");expect(screen.getByText("Pilih satu file sebelum melanjutkan.").closest("div")).toHaveAttribute("role","alert");});
 it("maps backend fields, unknown errors and retains file",async()=>{mutation.mutateAsync.mockRejectedValue(new AppError(422,"DOCUMENT_INVALID","Periksa data.",{title:["Judul backend invalid"],category:["Kategori backend invalid"],description:["Deskripsi backend invalid"],reason:["Alasan backend invalid"],notes:["Catatan backend invalid"],mimeType:["MIME backend invalid"],unknown:["Field tambahan invalid"]},false,"corr-fields"));render(<DocumentUploadForm mode="create" projectId="prj-026"/>);const user=await openReview();await user.click(screen.getByRole("button",{name:"Konfirmasi upload"}));await waitFor(()=>expect(screen.getByText("Judul backend invalid")).toBeVisible());expect(globalThis.document.getElementById("title")).toHaveAttribute("aria-invalid","true");expect(screen.getByText("MIME backend invalid").closest("div")).toHaveAttribute("role","alert");expect(screen.getByText("Field tambahan invalid")).toBeVisible();expect(screen.getByText(/corr-fields/)).toBeVisible();expect(screen.getAllByText(/document\.pdf/).length).toBeGreaterThan(0);});
 it("offers safe retry only for retryable failures and retains metadata file",async()=>{mutation.mutateAsync.mockRejectedValueOnce(new AppError(503,"DOCUMENT_SERVER_FAILURE","Layanan sementara tidak tersedia.",{},true,"corr-retry")).mockResolvedValueOnce({documentId:"doc-new",message:"Berhasil"});render(<DocumentUploadForm mode="create" projectId="prj-026"/>);const user=await openReview();await user.click(screen.getByRole("button",{name:"Konfirmasi upload"}));const retry=await screen.findByRole("button",{name:"Coba lagi"});expect(screen.getAllByText(/document\.pdf/).length).toBeGreaterThan(0);await user.click(retry);expect(mutation.mutateAsync).toHaveBeenCalledTimes(2);expect(mutation.mutateAsync.mock.calls[0]?.[0].file).not.toBeInstanceOf(File);});
 it("retains file when review closes and removes it only on explicit remove",async()=>{render(<DocumentUploadForm mode="create" projectId="prj-026"/>);const user=await openReview(),backButtons=screen.getAllByRole("button",{name:"Kembali"});await user.click(backButtons.at(-1)!);expect(screen.getAllByText(/document\.pdf/).length).toBeGreaterThan(0);await user.click(screen.getByRole("button",{name:"Hapus file"}));expect(screen.queryByText(/document\.pdf/)).not.toBeInTheDocument();});
 it("consumes cancellation without UI error, retry, toast, or navigation",async()=>{const toastSpy=vi.spyOn(toast,"success");mutation.mutateAsync.mockRejectedValue(new DOMException("cancelled","AbortError"));render(<DocumentUploadForm mode="create" projectId="prj-026"/>);const user=await openReview();await user.click(screen.getByRole("button",{name:"Konfirmasi upload"}));await waitFor(()=>expect(mutation.mutateAsync).toHaveBeenCalledTimes(1));expect(screen.queryByText("Dokumen belum dapat disimpan")).not.toBeInTheDocument();expect(screen.queryByRole("button",{name:"Coba lagi"})).not.toBeInTheDocument();expect(screen.queryByText(/correlation/i)).not.toBeInTheDocument();expect(push).not.toHaveBeenCalled();expect(toastSpy).not.toHaveBeenCalled();expect(screen.getAllByText(/document\.pdf/).length).toBeGreaterThan(0);expect(screen.getByLabelText("Judul dokumen")).toHaveValue("Dokumen baru");toastSpy.mockRestore();});
 it("asserts every backend field error and ARIA relationship",async()=>{mutation.mutateAsync.mockRejectedValue(new AppError(422,"INVALID","Periksa data.",{title:["E-title"],category:["E-category"],description:["E-description"],reason:["E-reason"],notes:["E-notes"],originalFileName:["E-file"]},false,"corr-all"));render(<DocumentUploadForm mode="create" projectId="prj-026"/>);const user=await openReview();await user.click(screen.getByRole("button",{name:"Konfirmasi upload"}));for(const [id,message] of [["title","E-title"],["category","E-category"],["description","E-description"],["reason","E-reason"],["notes","E-notes"]] as const){const field=globalThis.document.getElementById(id);expect(await screen.findByText(message)).toBeVisible();expect(field).toHaveAttribute("aria-invalid","true");expect(field).toHaveAttribute("aria-describedby",`${id}-message`);}const fileInput=documentQueryFile();expect(screen.getByText("E-file")).toBeVisible();expect(fileInput).toHaveAttribute("aria-invalid","true");expect(fileInput.getAttribute("aria-describedby")).toContain("document-file-error");expect(screen.queryByRole("button",{name:"Coba lagi"})).not.toBeInTheDocument();});
 it.each([["","Contract"],["objectType=SPH&objectId=sph-026","Rate Support"],["objectType=RateVersion&objectId=rate-prj-026-v2","Project Brief"]] as const)("rejects crafted cross-owner category for %s",async(query,invalidCategory)=>{search=`access=manage&${query}`;render(<DocumentUploadForm mode="create" projectId="prj-026"/>);const user=await fillValidForm(),select=screen.getByLabelText("Kategori");fireEvent.change(select,{target:{value:invalidCategory}});await user.click(screen.getByRole("button",{name:"Tinjau upload"}));expect(await screen.findByText("Kategori tidak sesuai jenis owner.")).toBeVisible();expect(select).toHaveAttribute("aria-invalid","true");expect(mutation.mutateAsync).not.toHaveBeenCalled();});
 it("renders non-retryable permission and structured conflict without force overwrite",async()=>{mutation.mutateAsync.mockRejectedValueOnce(new AppError(403,"DOCUMENT_FORBIDDEN","Tidak diizinkan.",{},false,"corr-403"));const first=render(<DocumentUploadForm mode="create" projectId="prj-026"/>),user=await openReview();await user.click(screen.getByRole("button",{name:"Konfirmasi upload"}));expect(await screen.findByText(/corr-403/)).toBeVisible();expect(screen.queryByRole("button",{name:"Coba lagi"})).not.toBeInTheDocument();first.unmount();mutation.mutateAsync.mockRejectedValueOnce(new AppError(409,"DOCUMENT_VERSION_CONFLICT","Berubah.",{},false,"corr-409",{userVersion:1,latestVersion:2,diffs:[{field:"version",label:"Versi",before:"1",after:"2"}]}));render(<DocumentUploadForm mode="create" projectId="prj-026"/>);const secondUser=await openReview();await secondUser.click(screen.getByRole("button",{name:"Konfirmasi upload"}));expect(await screen.findByText("Record telah berubah")).toBeVisible();expect(screen.getAllByText(/document\.pdf/).length).toBeGreaterThan(0);expect(screen.getByLabelText("Judul dokumen")).toHaveValue("Dokumen baru");expect(screen.queryByText(/force overwrite/i)).not.toBeInTheDocument();expect(mutation.mutateAsync).toHaveBeenCalledTimes(2);});
 it("cleans up after success and sends metadata only",async()=>{const toastSpy=vi.spyOn(toast,"success");mutation.mutateAsync.mockResolvedValue({documentId:"doc-new",message:"Upload berhasil"});render(<DocumentUploadForm mode="create" projectId="prj-026"/>);const user=await openReview();await user.click(screen.getByRole("button",{name:"Konfirmasi upload"}));await waitFor(()=>expect(push).toHaveBeenCalledWith("/documents/doc-new?access=manage"));expect(mutation.mutateAsync).toHaveBeenCalledTimes(1);const command=mutation.mutateAsync.mock.calls[0]?.[0];expect(command.file).toEqual({originalFileName:"document.pdf",displayFileName:"document.pdf",mimeType:"application/pdf",sizeBytes:4});expect(command.file).not.toBeInstanceOf(File);expect(toastSpy).toHaveBeenCalledWith("Upload berhasil");expect(screen.queryByText(/document\.pdf/)).not.toBeInTheDocument();toastSpy.mockRestore();});
 it("focuses file from summary and supports keyboard review cancellation",async()=>{render(<DocumentUploadForm mode="create" projectId="prj-026"/>);const user=userEvent.setup();await user.type(screen.getByLabelText("Judul dokumen"),"Dokumen keyboard");await user.type(screen.getByLabelText("Alasan pencatatan"),"Alasan keyboard");const reviewButton=screen.getByRole("button",{name:"Tinjau upload"});reviewButton.focus();await user.keyboard("{Enter}");await waitFor(()=>expect(globalThis.document.getElementById("master-form-errors")).toHaveFocus());await user.click(screen.getByRole("button",{name:"Ke field pertama yang bermasalah"}));expect(screen.getByRole("button",{name:"Pilih file dokumen"})).toHaveFocus();fireEvent.change(documentQueryFile(),{target:{files:[new File(["demo"],"document.pdf",{type:"application/pdf"})]}});reviewButton.focus();await user.keyboard("{Enter}");const backButtons=await screen.findAllByRole("button",{name:"Kembali"});backButtons.at(-1)!.focus();await user.keyboard("{Enter}");expect(screen.getAllByText(/document\.pdf/).length).toBeGreaterThan(0);});
});
