import { QueryClient, QueryClientProvider } from "@tanstack/react-query";
import { render, screen, waitFor } from "@testing-library/react";
import userEvent from "@testing-library/user-event";
import type { ReactNode } from "react";
import { beforeEach, describe, expect, it, vi } from "vitest";
import { AppError } from "@/features/foundation/domain/errors";
import { queryKeys } from "@/lib/query-keys";
import { InvoiceCreatePage } from "./components/invoice-create-page";
import { InvoiceDetailPage } from "./components/invoice-detail-page";
import { InvoiceListPage } from "./components/invoice-list-page";
import { resetInvoiceMock } from "./infrastructure/mock-adapter";
import { invoiceRepository } from "./repositories";
const push=vi.fn(),replace=vi.fn(),refresh=vi.fn();
vi.mock("next/navigation",()=>({useRouter:()=>({push,replace,refresh}),usePathname:()=>"/invoices",useSearchParams:()=>new URLSearchParams()}));
vi.mock("sonner",()=>({toast:{success:vi.fn()}}));
function Wrapper({children}:{children:ReactNode}){return <QueryClientProvider client={new QueryClient({defaultOptions:{queries:{retry:false},mutations:{retry:false}}})}>{children}</QueryClientProvider>}
const seed=()=>invoiceRepository.createDraft({data:{sourceOptionId:"src-pbr-001-r4",invoiceDate:"2026-08-01",note:"Demo"},actor:{userId:"usr",permissionKeys:["invoice.create"]},reason:"Seed"});
async function toPendingCustomer(){await seed();const detail=await invoiceRepository.detail("inv-draft-001");await invoiceRepository.requestConfirmation({invoiceId:detail.invoice.id,actor:{userId:"usr-pic",permissionKeys:["invoice.confirmation.request"]},reason:"Request",currentVersion:detail.invoice.version,currentRevisionId:detail.revision.id,currentRevisionVersion:detail.revision.version,data:{requestDate:"2026-08-11",channel:"Meeting",customerContactName:"Customer",reference:"REF-PENDING",note:"Manual confirmation request",attestation:true,evidence:{channel:"Meeting",displayLabel:"Meeting note",reference:"REF-PENDING",referenceDate:"2026-08-11",customerContactName:"Customer",note:"Manual confirmation request"}}});}
async function toPendingApproval(){await toPendingCustomer();const detail=await invoiceRepository.detail("inv-draft-001");await invoiceRepository.recordCustomerConfirmed({invoiceId:detail.invoice.id,actor:{userId:"usr-pic",permissionKeys:["invoice.confirmation.confirm"]},reason:"Confirmed",currentVersion:detail.invoice.version,currentRevisionId:detail.revision.id,currentRevisionVersion:detail.revision.version,data:{confirmedAt:"2026-08-11T10:00:00+07:00",channel:"Meeting",customerContactName:"Customer",reference:"REF-CONFIRMED",statement:"Customer confirmed",note:"PIC record",attestation:true,evidence:{channel:"Meeting",displayLabel:"Meeting note",reference:"REF-CONFIRMED",referenceDate:"2026-08-11",customerContactName:"Customer",note:"PIC record"}}});}
async function toRevision(){await seed();let detail=await invoiceRepository.detail("inv-draft-001");await invoiceRepository.requestConfirmation({invoiceId:detail.invoice.id,actor:{userId:"usr-pic",permissionKeys:["invoice.confirmation.request"]},reason:"Request",currentVersion:detail.invoice.version,currentRevisionId:detail.revision.id,currentRevisionVersion:detail.revision.version,data:{requestDate:"2026-08-11",channel:"Meeting",customerContactName:"Customer",reference:"REF-1",note:"Manual",attestation:true,evidence:{channel:"Meeting",displayLabel:"Meeting note",reference:"REF-1",referenceDate:"2026-08-11",customerContactName:"Customer",note:"Manual"}}});detail=await invoiceRepository.detail("inv-draft-001");await invoiceRepository.recordRevisionRequest({invoiceId:detail.invoice.id,actor:{userId:"usr-pic",permissionKeys:["invoice.confirmation.revision-request"]},reason:"Change label",currentVersion:detail.invoice.version,currentRevisionId:detail.revision.id,currentRevisionVersion:detail.revision.version,data:{responseDate:"2026-08-11",channel:"Meeting",customerContactName:"Customer",reference:"REF-2",reason:"Change label",note:"Manual",requestedChanges:[{section:"LinePresentation",currentValueSummary:detail.lines[0].description,customerRequestSummary:"Perbarui deskripsi",requiresFinancialRecalculation:false,requiresSourceCorrection:false,requiresDocumentUpdate:false,resolutionStatus:"Open"}],evidence:{channel:"Meeting",displayLabel:"Meeting note",reference:"REF-2",referenceDate:"2026-08-11",customerContactName:"Customer",note:"Manual"}}});}
async function resolveWorkingRevision(){await toRevision();const detail=await invoiceRepository.detail("inv-draft-001"),state=await invoiceRepository.confirmationState("inv-draft-001");await invoiceRepository.saveRevision({invoiceId:detail.invoice.id,actor:{userId:"usr-demo",permissionKeys:["invoice.revision.edit"]},reason:"Resolve",currentVersion:detail.invoice.version,currentRevisionId:detail.revision.id,currentRevisionVersion:detail.revision.version,data:{invoiceDate:detail.revision.snapshot.invoiceDate,note:detail.revision.snapshot.note,lines:detail.lines.map(line=>({id:line.id,description:line.description})),resolutions:state.requestedChanges.map(item=>({requestedChangeId:item.id,resolved:true,resolutionNote:"Resolved"}))}});}
beforeEach(()=>{vi.restoreAllMocks();resetInvoiceMock();push.mockReset();replace.mockReset();refresh.mockReset();});
describe("Invoice 2C-A production components",()=>{
  it("denies none persona before sensitive list query",()=>{const spy=vi.spyOn(invoiceRepository,"list");render(<InvoiceListPage access="none"/>,{wrapper:Wrapper});expect(screen.getByText("Invoice tidak diizinkan")).toBeVisible();expect(spy).not.toHaveBeenCalled();});
  it("denies direct create for review and view personas",()=>{const {rerender}=render(<InvoiceCreatePage access="review"/>,{wrapper:Wrapper});expect(screen.getByText("Create Draft Invoice tidak diizinkan")).toBeVisible();rerender(<InvoiceCreatePage access="view"/>);expect(screen.getByText("Create Draft Invoice tidak diizinkan")).toBeVisible();});
  it("loads source from repository and creates only after explicit review",async()=>{const spy=vi.spyOn(invoiceRepository,"createDraft"),user=userEvent.setup();render(<InvoiceCreatePage access="manage"/>,{wrapper:Wrapper});expect(await screen.findByLabelText("Eligible Payroll Billing source")).toHaveValue("src-pbr-001-r4");expect(spy).not.toHaveBeenCalled();await user.click(screen.getByRole("button",{name:"Tinjau create"}));await user.click(screen.getByRole("button",{name:"Buat Draft Invoice"}));await waitFor(()=>expect(spy).toHaveBeenCalledTimes(1));expect(spy.mock.calls[0][0].data).toEqual({sourceOptionId:"src-pbr-001-r4",invoiceDate:"2026-08-01",note:""});});
  it("renders read-only detail and persona-preserving navigation",async()=>{await seed();render(<InvoiceDetailPage id="inv-draft-001" access="view"/>,{wrapper:Wrapper});expect(await screen.findByText("DRAFT-DEMO-001")).toBeVisible();expect(screen.queryByRole("link",{name:"Edit Draft"})).not.toBeInTheDocument();expect(screen.getByRole("link",{name:"Kembali ke daftar"})).toHaveAttribute("href","/invoices?access=view");});
  it("provides desktop table and mobile card alternatives without row queries",async()=>{await seed();const spy=vi.spyOn(invoiceRepository,"detail");render(<InvoiceListPage access="manage"/>,{wrapper:Wrapper});expect(await screen.findByRole("table",{name:"Daftar Draft Invoice"})).toBeVisible();expect(document.querySelector(".invoice-mobile-list")).toBeInTheDocument();expect(spy).not.toHaveBeenCalled();});
  it("renders accessible editable labels and locked source values",async()=>{await seed();render(<InvoiceDetailPage id="inv-draft-001" access="manage" edit/>,{wrapper:Wrapper});expect(await screen.findByLabelText("Draft date")).toBeVisible();expect(screen.getByLabelText("Description line 1")).toBeVisible();expect(screen.getByText(/Quantity, rate, source revision/)).toBeVisible();});
  it("shows truthful initial autosave state",async()=>{await seed();render(<InvoiceDetailPage id="inv-draft-001" access="manage" edit/>,{wrapper:Wrapper});expect(await screen.findByText("Belum ada perubahan.")).toBeVisible();expect(screen.queryByText(/Tersimpan pada/)).not.toBeInTheDocument();});
  it("debounces autosave and shows the authoritative timestamp only after success",async()=>{await seed();const spy=vi.spyOn(invoiceRepository,"autosaveDraft"),user=userEvent.setup();render(<InvoiceDetailPage id="inv-draft-001" access="manage" edit/>,{wrapper:Wrapper});const note=await screen.findByLabelText("Draft note");await user.type(note," changed");expect(spy).not.toHaveBeenCalled();expect(screen.getByText("Perubahan belum disimpan.")).toBeVisible();await waitFor(()=>expect(spy).toHaveBeenCalledTimes(1),{timeout:1500});expect(await screen.findByText(/Tersimpan pada/)).toBeVisible();});
  it("prevents explicit Save and pending autosave from racing",async()=>{await seed();const autoSpy=vi.spyOn(invoiceRepository,"autosaveDraft"),saveSpy=vi.spyOn(invoiceRepository,"saveDraft"),user=userEvent.setup();render(<InvoiceDetailPage id="inv-draft-001" access="manage" edit/>,{wrapper:Wrapper});await user.type(await screen.findByLabelText("Draft note")," explicit");await user.click(screen.getByRole("button",{name:"Simpan Draft"}));await waitFor(()=>expect(saveSpy).toHaveBeenCalledTimes(1));await new Promise(resolve=>setTimeout(resolve,850));expect(autoSpy.mock.calls.length).toBeLessThanOrEqual(1);if(autoSpy.mock.calls[0])expect(autoSpy.mock.calls[0][1]?.aborted).toBe(true);expect((await invoiceRepository.detail("inv-draft-001")).invoice.version).toBe(2);});
  it("shows Draft HTML preview and disables PDF fallback",async()=>{await seed();const user=userEvent.setup();render(<InvoiceDetailPage id="inv-draft-001" access="view"/>,{wrapper:Wrapper});await user.click(await screen.findByRole("button",{name:"Preview Draft"}));expect(await screen.findByText("DRAFT - Preview Invoice")).toBeVisible();expect(screen.getByRole("button",{name:"Download PDF belum tersedia"})).toBeDisabled();expect(screen.getAllByText(/Nomor Invoice final belum tersedia/).length).toBeGreaterThan(0);});
  it("keeps review persona read-only with preview access",async()=>{await seed();render(<InvoiceDetailPage id="inv-draft-001" access="review" edit/>,{wrapper:Wrapper});expect(await screen.findByRole("button",{name:"Preview Draft"})).toBeVisible();expect(screen.queryByRole("button",{name:"Simpan Draft"})).not.toBeInTheDocument();});
  it("preserves list persona and URL-controlled pagination",async()=>{await seed();render(<InvoiceListPage access="view" initialSearch="demo" initialPage={1} initialPageSize={10}/>,{wrapper:Wrapper});expect(await screen.findByLabelText("Baris per halaman")).toHaveValue("10");const links=await screen.findAllByRole("link",{name:"DRAFT-DEMO-001"});expect(links).toHaveLength(2);for(const link of links)expect(link).toHaveAttribute("href","/invoices/inv-draft-001?access=view");});
});

describe("Invoice 2C-B remediation production components",()=>{
  it("keeps Pending Customer read-only and exposes only PIC customer-response actions",async()=>{await toPendingCustomer();const draftSave=vi.spyOn(invoiceRepository,"saveDraft"),draftAuto=vi.spyOn(invoiceRepository,"autosaveDraft"),revisionSave=vi.spyOn(invoiceRepository,"saveRevision");render(<InvoiceDetailPage id="inv-draft-001" access="pic" edit/>,{wrapper:Wrapper});expect(await screen.findByText("Pending Customer")).toBeVisible();expect(screen.queryByLabelText("Description line 1")).not.toBeInTheDocument();expect(screen.queryByRole("button",{name:/Simpan/})).not.toBeInTheDocument();expect(await screen.findByRole("form",{name:"Record Customer Revision Request"})).toBeVisible();expect(screen.getByRole("form",{name:"Record Customer Confirmed"})).toBeVisible();expect(screen.queryByRole("button",{name:"Request confirmation"})).not.toBeInTheDocument();expect(screen.queryByRole("button",{name:"Resubmit revision"})).not.toBeInTheDocument();expect(screen.getByText(/Cycle 1; revision/)).toBeVisible();expect(draftSave).not.toHaveBeenCalled();expect(draftAuto).not.toHaveBeenCalled();expect(revisionSave).not.toHaveBeenCalled();});
  it("keeps manage, review, and view personas read-only in Pending Customer",async()=>{await toPendingCustomer();const {rerender}=render(<InvoiceDetailPage id="inv-draft-001" access="manage" edit/>,{wrapper:Wrapper});expect(await screen.findByText("Pending Customer")).toBeVisible();expect(screen.queryByRole("button",{name:"Catat customer confirmed"})).not.toBeInTheDocument();rerender(<InvoiceDetailPage id="inv-draft-001" access="review" edit/>);expect(screen.queryByRole("button",{name:"Catat revision request"})).not.toBeInTheDocument();rerender(<InvoiceDetailPage id="inv-draft-001" access="view" edit/>);expect(screen.queryByLabelText("Description line 1")).not.toBeInTheDocument();});
  it("renders Pending Approval as evidence-rich handoff with no mutation or downstream action",async()=>{await toPendingApproval();const draftSave=vi.spyOn(invoiceRepository,"saveDraft"),revisionSave=vi.spyOn(invoiceRepository,"saveRevision");render(<InvoiceDetailPage id="inv-draft-001" access="pic" edit/>,{wrapper:Wrapper});expect(await screen.findByText("Pending Approval")).toBeVisible();expect(await screen.findByText(/CUSTOMER CONFIRMED.*BELUM DISETUJUI/)).toBeVisible();expect(screen.getByLabelText("Status customer confirmation")).toBeVisible();expect(screen.getAllByText(/PIC Demo \(usr-pic\)/).length).toBeGreaterThan(0);expect(screen.getAllByText(/Customer confirmed/i).length).toBeGreaterThan(0);expect(screen.queryByLabelText("Description line 1")).not.toBeInTheDocument();expect(screen.queryByRole("button",{name:/Request confirmation|Catat revision request|Resubmit revision|Catat customer confirmed|Approve|Release/})).not.toBeInTheDocument();expect(screen.queryByText(/Invoice number final/i)).not.toBeInTheDocument();expect(draftSave).not.toHaveBeenCalled();expect(revisionSave).not.toHaveBeenCalled();});
  it("uses the authoritative working revision and Revision save command",async()=>{await toRevision();const draftSpy=vi.spyOn(invoiceRepository,"saveDraft"),revisionSpy=vi.spyOn(invoiceRepository,"saveRevision"),user=userEvent.setup();render(<InvoiceDetailPage id="inv-draft-001" access="manage" edit/>,{wrapper:Wrapper});expect(await screen.findByText("Working revision header")).toBeVisible();expect(screen.getByText(/Revision 2 \/ version 1/)).toBeVisible();await user.type(screen.getByLabelText("Revision note")," selesai");await user.click(screen.getByLabelText("Resolved"));await user.type(screen.getByLabelText(/Resolution note change/),"Label diperbarui");await user.click(screen.getByRole("button",{name:"Simpan Working Revision"}));await waitFor(()=>expect(revisionSpy).toHaveBeenCalledTimes(1));expect(draftSpy).not.toHaveBeenCalled();expect(revisionSpy.mock.calls[0][0].data).not.toHaveProperty("status");expect(revisionSpy.mock.calls[0][0].data).not.toHaveProperty("source");});
  it("uses Revision autosave only after debounce",async()=>{await toRevision();const revisionSpy=vi.spyOn(invoiceRepository,"saveRevision"),draftSpy=vi.spyOn(invoiceRepository,"autosaveDraft"),user=userEvent.setup();render(<InvoiceDetailPage id="inv-draft-001" access="manage" edit/>,{wrapper:Wrapper});await user.type(await screen.findByLabelText("Revision note")," autosave");expect(revisionSpy).not.toHaveBeenCalled();await waitFor(()=>expect(revisionSpy).toHaveBeenCalledTimes(1),{timeout:1600});expect(draftSpy).not.toHaveBeenCalled();});
  it("retains dirty working fields across same-revision detail and confirmation refetch",async()=>{await toRevision();const client=new QueryClient({defaultOptions:{queries:{retry:false},mutations:{retry:false}}}),StableWrapper=({children}:{children:ReactNode})=><QueryClientProvider client={client}>{children}</QueryClientProvider>,user=userEvent.setup();render(<InvoiceDetailPage id="inv-draft-001" access="manage" edit/>,{wrapper:StableWrapper});const note=await screen.findByLabelText("Revision note"),description=screen.getByLabelText("Description line 1");await user.type(note," dirty-refetch");await user.clear(description);await user.type(description,"Local description retained");await client.invalidateQueries({queryKey:queryKeys.invoices.confirmationCycles("inv-draft-001"),exact:true});await client.invalidateQueries({queryKey:queryKeys.invoices.detail("inv-draft-001"),exact:true});expect(note).toHaveValue("Demo dirty-refetch");expect(description).toHaveValue("Local description retained");expect(screen.getByText("Perubahan belum disimpan.")).toBeVisible();});
  it("applies only the autosave payload baseline while preserving newer edits as dirty",async()=>{await toRevision();let resolveFirst:(value:{invoiceId:string;version:number;revisionId:string;revisionVersion:number;savedAt:string;message:string;correlationId:string})=>void=()=>undefined;const commands:import("./domain/types").SaveRevisionCommand[]=[],spy=vi.spyOn(invoiceRepository,"saveRevision").mockImplementation(command=>{commands.push(structuredClone(command));if(commands.length===1)return new Promise(resolve=>{resolveFirst=resolve;});return Promise.resolve({invoiceId:command.invoiceId,version:5,revisionId:command.currentRevisionId,revisionVersion:3,savedAt:"2026-08-11T12:02:00+07:00",message:"Saved",correlationId:"auto-2"});});const user=userEvent.setup();render(<InvoiceDetailPage id="inv-draft-001" access="manage" edit/>,{wrapper:Wrapper});const note=await screen.findByLabelText("Revision note");await user.type(note," B");await waitFor(()=>expect(spy).toHaveBeenCalledTimes(1),{timeout:1600});await user.type(note," C");resolveFirst({invoiceId:"inv-draft-001",version:4,revisionId:commands[0].currentRevisionId,revisionVersion:2,savedAt:"2026-08-11T12:01:00+07:00",message:"Saved B",correlationId:"auto-1"});await waitFor(()=>expect(note).toHaveValue("Demo B C"));expect(screen.getByText("Perubahan belum disimpan.")).toBeVisible();await waitFor(()=>expect(spy).toHaveBeenCalledTimes(2),{timeout:1800});expect(commands[0].data.note).toBe("Demo B");expect(commands[1].data.note).toBe("Demo B C");expect(commands[1].currentVersion).toBe(4);});
  it("disables Resubmit while Revision is dirty or autosave pending and enables it after authoritative save",async()=>{await resolveWorkingRevision();let resolveSave:(value:{invoiceId:string;version:number;revisionId:string;revisionVersion:number;savedAt:string;message:string;correlationId:string})=>void=()=>undefined;const spy=vi.spyOn(invoiceRepository,"saveRevision").mockImplementation(()=>new Promise(resolve=>{resolveSave=resolve;})),resubmit=vi.spyOn(invoiceRepository,"resubmitRevision"),user=userEvent.setup();render(<InvoiceDetailPage id="inv-draft-001" access="manage" edit/>,{wrapper:Wrapper});const button=await screen.findByRole("button",{name:"Resubmit revision"});await user.type(screen.getByLabelText("Revision note")," pending");expect(button).toBeDisabled();expect(screen.getByText("Selesaikan penyimpanan working revision sebelum resubmit.")).toBeVisible();await waitFor(()=>expect(spy).toHaveBeenCalledTimes(1),{timeout:1600});expect(button).toBeDisabled();await user.click(button);expect(resubmit).not.toHaveBeenCalled();const command=spy.mock.calls[0][0];resolveSave({invoiceId:command.invoiceId,version:5,revisionId:command.currentRevisionId,revisionVersion:3,savedAt:"2026-08-11T12:03:00+07:00",message:"Saved",correlationId:"auto-settle"});await waitFor(()=>expect(button).toBeEnabled());});
  it("hydrates authoritative Pending Customer mode after Resubmit success with no later autosave",async()=>{await resolveWorkingRevision();const autosave=vi.spyOn(invoiceRepository,"saveRevision"),resubmit=vi.spyOn(invoiceRepository,"resubmitRevision"),user=userEvent.setup();render(<InvoiceDetailPage id="inv-draft-001" access="manage" edit/>,{wrapper:Wrapper});await user.type(await screen.findByLabelText("Resolution summary"),"Ready for customer");await user.click(screen.getByRole("checkbox",{name:/semua perubahan resolved/}));await user.click(screen.getByRole("button",{name:"Resubmit revision"}));await waitFor(()=>expect(resubmit).toHaveBeenCalledTimes(1));expect(await screen.findByText("Pending Customer")).toBeVisible();expect(screen.queryByLabelText("Revision note")).not.toBeInTheDocument();expect(screen.queryByRole("button",{name:"Simpan Working Revision"})).not.toBeInTheDocument();expect((await invoiceRepository.confirmationState("inv-draft-001")).cycles).toHaveLength(2);await new Promise(resolve=>setTimeout(resolve,850));expect(autosave).not.toHaveBeenCalled();});
  it.each([403,409,422,503,"cancel"] as const)("keeps Revision, cycle, activity, and input unchanged after Resubmit %s",async scenario=>{await resolveWorkingRevision();const beforeDetail=await invoiceRepository.detail("inv-draft-001"),beforeState=await invoiceRepository.confirmationState("inv-draft-001");vi.spyOn(invoiceRepository,"resubmitRevision").mockRejectedValueOnce(scenario==="cancel"?new DOMException("Aborted","AbortError"):new AppError(scenario,scenario===409?"RESUBMIT_CONFLICT":"RESUBMIT_FAILED","Resubmit gagal.",{},scenario===503,`corr-resubmit-${scenario}`,scenario===409?{invoiceId:"inv-draft-001",attemptedVersion:beforeDetail.invoice.version,latestVersion:beforeDetail.invoice.version+1}:{}));const user=userEvent.setup();render(<InvoiceDetailPage id="inv-draft-001" access="manage" edit/>,{wrapper:Wrapper});const summary=await screen.findByLabelText("Resolution summary");await user.type(summary,`Retain ${scenario}`);await user.click(screen.getByRole("checkbox",{name:/semua perubahan resolved/}));await user.click(screen.getByRole("button",{name:"Resubmit revision"}));await waitFor(async()=>expect((await invoiceRepository.detail("inv-draft-001")).invoice.status).toBe("Revision"));expect(await invoiceRepository.confirmationState("inv-draft-001")).toEqual(beforeState);expect((await invoiceRepository.detail("inv-draft-001")).activity).toEqual(beforeDetail.activity);expect(summary).toHaveValue(`Retain ${scenario}`);});
  it("renders requested changes and persisted diff in desktop and mobile alternatives",async()=>{await toRevision();const detail=await invoiceRepository.detail("inv-draft-001"),state=await invoiceRepository.confirmationState("inv-draft-001");await invoiceRepository.saveRevision({invoiceId:detail.invoice.id,actor:{userId:"usr",permissionKeys:["invoice.revision.edit"]},reason:"Persisted change",currentVersion:detail.invoice.version,currentRevisionId:detail.revision.id,currentRevisionVersion:detail.revision.version,data:{invoiceDate:detail.revision.snapshot.invoiceDate,note:detail.revision.snapshot.note,lines:detail.lines.map((line,index)=>({id:line.id,description:index===0?"Deskripsi persisted baru":line.description})),resolutions:state.requestedChanges.map(item=>({requestedChangeId:item.id,resolved:true,resolutionNote:"Selesai"}))}});render(<InvoiceDetailPage id="inv-draft-001" access="view"/>,{wrapper:Wrapper});expect(await screen.findByText(/Perbarui deskripsi/)).toBeVisible();expect(await screen.findByRole("table",{name:"Perbandingan persisted Invoice revision"})).toBeVisible();expect(screen.getAllByText("Changed").length).toBeGreaterThan(1);expect(document.querySelector(".invoice-line-cards")).toBeInTheDocument();});
  it("exposes an action-specific RHF form and accessible validation",async()=>{await seed();const user=userEvent.setup();render(<InvoiceDetailPage id="inv-draft-001" access="pic"/>,{wrapper:Wrapper});const contact=await screen.findByLabelText("Customer contact");expect(screen.getByRole("form",{name:"Request Customer Confirmation"})).toBeVisible();await user.clear(contact);await user.click(screen.getByRole("button",{name:"Request confirmation"}));expect(await screen.findByText("Customer contact wajib diisi")).toBeVisible();expect(contact).toHaveAttribute("aria-invalid","true");});
  it("guards dirty confirmation form input and cleans the listener on unmount",async()=>{await seed();const add=vi.spyOn(window,"addEventListener"),remove=vi.spyOn(window,"removeEventListener"),user=userEvent.setup(),view=render(<InvoiceDetailPage id="inv-draft-001" access="pic"/>,{wrapper:Wrapper});await user.type(await screen.findByLabelText("Catatan")," berubah");await waitFor(()=>expect(add.mock.calls.some(call=>call[0]==="beforeunload")).toBe(true));const registered=add.mock.calls.find(call=>call[0]==="beforeunload")?.[1];view.unmount();expect(remove.mock.calls.some(call=>call[0]==="beforeunload"&&call[1]===registered)).toBe(true);});
  it("renders structured Request Confirmation conflict and retains form input",async()=>{await seed();vi.spyOn(invoiceRepository,"requestConfirmation").mockRejectedValueOnce(new AppError(409,"INVOICE_VERSION_CONFLICT","Invoice berubah.",{},false,"corr-request",{invoiceId:"inv-draft-001",attemptedVersion:1,latestVersion:2,attemptedRevisionId:"rev-1",latestRevisionId:"rev-2",attemptedRevisionVersion:1,latestRevisionVersion:2,attemptedStatus:"Draft",latestStatus:"Pending Customer",confirmationCycle:1}));const user=userEvent.setup();render(<InvoiceDetailPage id="inv-draft-001" access="pic"/>,{wrapper:Wrapper});const reference=await screen.findByLabelText("Evidence reference");await user.clear(reference);await user.type(reference,"REF-RETAIN");await user.click(screen.getByRole("checkbox"));await user.click(screen.getByRole("button",{name:"Request confirmation"}));const summary=await screen.findByText("Request Confirmation belum berhasil");expect(summary.closest("#confirmation-error-summary")).toHaveFocus();expect(screen.getByText(/Attempted 1; latest 2/)).toBeVisible();expect(screen.getByText(/corr-request/)).toBeVisible();expect(reference).toHaveValue("REF-RETAIN");expect(screen.queryByRole("button",{name:"Coba lagi"})).not.toBeInTheDocument();});
  it("keeps Invoice detail visible when the local evidence query fails",async()=>{await seed();vi.spyOn(invoiceRepository,"confirmationState").mockRejectedValueOnce({status:503,code:"EVIDENCE_UNAVAILABLE",message:"Evidence unavailable",field_errors:{},retryable:true,correlation_id:"corr-evidence"});render(<InvoiceDetailPage id="inv-draft-001" access="view"/>,{wrapper:Wrapper});expect(await screen.findByText("DRAFT-DEMO-001")).toBeVisible();expect(screen.getByText("Reconciliation")).toBeVisible();expect(await screen.findByText("Customer confirmation belum dapat dimuat")).toBeVisible();});
  it("suppresses all Invoice queries for none persona",()=>{const detail=vi.spyOn(invoiceRepository,"detail"),confirmation=vi.spyOn(invoiceRepository,"confirmationState"),diff=vi.spyOn(invoiceRepository,"revisionDiff");render(<InvoiceDetailPage id="inv-draft-001" access="none"/>,{wrapper:Wrapper});expect(screen.getByText("Invoice tidak diizinkan")).toBeVisible();expect(detail).not.toHaveBeenCalled();expect(confirmation).not.toHaveBeenCalled();expect(diff).not.toHaveBeenCalled();});
});

describe("Invoice 2C-BR1 Save Revision DOM errors",()=>{
  it.each([[403,"REVISION_FORBIDDEN"],[404,"WORKING_REVISION_NOT_FOUND"]] as const)("retains input for %s without generic retry",async(status,code)=>{await toRevision();vi.spyOn(invoiceRepository,"saveRevision").mockRejectedValueOnce(new AppError(status,code,"Working revision tidak dapat disimpan.",{},false,`corr-${status}`));const user=userEvent.setup();render(<InvoiceDetailPage id="inv-draft-001" access="manage" edit/>,{wrapper:Wrapper});const note=await screen.findByLabelText("Revision note");await user.type(note," retained");await user.click(screen.getByRole("button",{name:"Simpan Working Revision"}));expect(await screen.findByText(`${code}; ID korelasi: corr-${status}`)).toBeVisible();expect(note).toHaveValue("Demo retained");expect(screen.queryByRole("button",{name:"Coba lagi"})).not.toBeInTheDocument();});
  it("maps editable 422 field errors to RHF and focuses the summary",async()=>{await toRevision();vi.spyOn(invoiceRepository,"saveRevision").mockRejectedValueOnce(new AppError(422,"REVISION_VALIDATION_FAILED","Periksa field.",{note:["Note ditolak server"]},false,"corr-422"));const user=userEvent.setup();render(<InvoiceDetailPage id="inv-draft-001" access="manage" edit/>,{wrapper:Wrapper});const note=await screen.findByLabelText("Revision note");await user.type(note," invalid");await user.click(screen.getByRole("button",{name:"Simpan Working Revision"}));expect(await screen.findByText("Note ditolak server")).toBeVisible();expect(note).toHaveAttribute("aria-invalid","true");expect(document.getElementById("invoice-save-error")).toHaveFocus();expect(note).toHaveValue("Demo invalid");});
  it("renders full structured Save Revision conflict without rehydrating input",async()=>{await toRevision();vi.spyOn(invoiceRepository,"saveRevision").mockRejectedValueOnce(new AppError(409,"REVISION_VERSION_CONFLICT","Revision berubah.",{},false,"corr-save",{invoiceId:"inv-draft-001",attemptedVersion:3,latestVersion:4,attemptedRevisionId:"rev-2",latestRevisionId:"rev-2",attemptedRevisionVersion:1,latestRevisionVersion:2,attemptedStatus:"Revision",latestStatus:"Revision",confirmationCycle:1}));const user=userEvent.setup();render(<InvoiceDetailPage id="inv-draft-001" access="manage" edit/>,{wrapper:Wrapper});const note=await screen.findByLabelText("Revision note");await user.type(note," conflict");await user.click(screen.getByRole("button",{name:"Simpan Working Revision"}));expect(await screen.findByText("Konflik versi Working Revision")).toBeVisible();expect(screen.getByText(/Attempted 3; latest 4/)).toBeVisible();expect(screen.getByText(/corr-save/)).toBeVisible();expect(note).toHaveValue("Demo conflict");expect(screen.queryByRole("button",{name:"Coba lagi"})).not.toBeInTheDocument();});
  it.each([500,502,503] as const)("retries Save Revision %s with an identical command and fresh signal",async status=>{await toRevision();const original=invoiceRepository.saveRevision,commands:unknown[]=[],signals:AbortSignal[]=[],spy=vi.spyOn(invoiceRepository,"saveRevision").mockImplementation((command,signal)=>{commands.push(structuredClone(command));if(signal)signals.push(signal);return commands.length===1?Promise.reject(new AppError(status,`REVISION_${status}`,"Server belum tersedia.",{},true,`corr-${status}`)):original(command,signal);});const user=userEvent.setup();render(<InvoiceDetailPage id="inv-draft-001" access="manage" edit/>,{wrapper:Wrapper});await user.type(await screen.findByLabelText("Revision note"),` retry-${status}`);await user.click(screen.getByRole("button",{name:"Simpan Working Revision"}));await user.click(await screen.findByRole("button",{name:"Coba lagi"}));await waitFor(()=>expect(spy).toHaveBeenCalledTimes(2));expect(commands[1]).toEqual(commands[0]);expect(signals[1]).not.toBe(signals[0]);await waitFor(async()=>expect((await invoiceRepository.detail("inv-draft-001")).revision.version).toBe(2));expect(screen.queryByText(`REVISION_${status}; ID korelasi: corr-${status}`)).not.toBeInTheDocument();});
  it("consumes cancellation and allows an explicit fresh Save",async()=>{await toRevision();const original=invoiceRepository.saveRevision,signals:AbortSignal[]=[],spy=vi.spyOn(invoiceRepository,"saveRevision").mockImplementation((command,signal)=>{if(signal)signals.push(signal);return signals.length===1?Promise.reject(new DOMException("Aborted","AbortError")):original(command,signal);});const user=userEvent.setup();render(<InvoiceDetailPage id="inv-draft-001" access="manage" edit/>,{wrapper:Wrapper});await user.type(await screen.findByLabelText("Revision note")," cancel");await user.click(screen.getByRole("button",{name:"Simpan Working Revision"}));expect(screen.queryByText(/belum tersimpan/)).not.toBeInTheDocument();await user.click(screen.getByRole("button",{name:"Simpan Working Revision"}));await waitFor(()=>expect(spy).toHaveBeenCalledTimes(2));expect(signals[1]).not.toBe(signals[0]);});
});
