import{beforeEach,describe,expect,it}from"vitest";import{legalInvoiceTransition,invoiceRevisionDiff}from"./domain/confirmation";import type{InvoiceDraftCommand,InvoiceWorkflowCommand,RecordCustomerConfirmedCommand,RecordRevisionRequestCommand,RequestConfirmationCommand,ResubmitRevisionCommand,SaveRevisionCommand}from"./domain/types";import{resetInvoiceMock}from"./infrastructure/mock-adapter";import{invoiceRepository}from"./repositories";
const seed:InvoiceDraftCommand={data:{sourceOptionId:"src-pbr-001-r4",invoiceDate:"2026-08-01",note:"Draft"},actor:{userId:"usr",permissionKeys:["invoice.create"]},reason:"Seed"};
const evidence={channel:"Meeting" as const,displayLabel:"Meeting notes",reference:"REF-001",referenceDate:"2026-08-11",customerContactName:"Budi",note:"Manual evidence"};
async function base<T>(data:T,userId="usr-pic",permissions:string[]=[]):Promise<InvoiceWorkflowCommand<T>>{const detail=await invoiceRepository.detail("inv-draft-001");return{invoiceId:detail.invoice.id,data,actor:{userId,permissionKeys:permissions},reason:"Workflow test",currentVersion:detail.invoice.version,currentRevisionId:detail.revision.id,currentRevisionVersion:detail.revision.version};}
const request=()=>base<RequestConfirmationCommand["data"]>({requestDate:"2026-08-11",channel:"Meeting",customerContactName:"Budi",reference:"REF-001",note:"Manual request",attestation:true,evidence},"usr-pic",["invoice.confirmation.request"]);
async function toPending(){await invoiceRepository.requestConfirmation(await request());}
const revisionRequest=()=>base<RecordRevisionRequestCommand["data"]>({responseDate:"2026-08-11",channel:"Meeting",customerContactName:"Budi",reference:"REF-002",reason:"Change label",note:"Customer revision",requestedChanges:[{section:"LinePresentation",currentValueSummary:"Old",customerRequestSummary:"New label",requiresFinancialRecalculation:false,requiresSourceCorrection:false,requiresDocumentUpdate:false,resolutionStatus:"Open"}],evidence},"usr-pic",["invoice.confirmation.revision-request"]);
beforeEach(async()=>{resetInvoiceMock();await invoiceRepository.createDraft(seed);});
describe("Invoice customer confirmation and revision loop",()=>{
 it("enforces the final 2C-B transition matrix",()=>{expect(legalInvoiceTransition("Draft","Pending Customer")).toBe(true);expect(legalInvoiceTransition("Pending Customer","Revision")).toBe(true);expect(legalInvoiceTransition("Revision","Pending Customer")).toBe(true);expect(legalInvoiceTransition("Pending Customer","Pending Approval")).toBe(true);for(const pair of [["Draft","Pending Approval"],["Revision","Pending Approval"],["Pending Approval","Approved"]]as const)expect(legalInvoiceTransition(pair[0],pair[1])).toBe(false);});
 it("requests confirmation only after readiness and records one immutable cycle",async()=>{const before=await invoiceRepository.detail("inv-draft-001");const result=await invoiceRepository.requestConfirmation(await request());const after=await invoiceRepository.detail(result.invoiceId),state=await invoiceRepository.confirmationState(result.invoiceId);expect(after.invoice.status).toBe("Pending Customer");expect(after.invoice.version).toBe(before.invoice.version+1);expect(state.submittedRevisionId).toBe(before.revision.id);expect(state.cycles).toHaveLength(1);expect(after.activity[0].action).toBe("invoice.confirmation-requested");});
 it("keeps request failure atomic",async()=>{const before=await invoiceRepository.detail("inv-draft-001"),bad=await request();bad.data={...bad.data,attestation:false};await expect(invoiceRepository.requestConfirmation(bad)).rejects.toMatchObject({status:422});expect(await invoiceRepository.detail("inv-draft-001")).toEqual(before);expect((await invoiceRepository.confirmationState("inv-draft-001")).cycles).toHaveLength(0);});
 it("preserves cancellation without workflow effects",async()=>{const controller=new AbortController();controller.abort();await expect(invoiceRepository.requestConfirmation(await request(),controller.signal)).rejects.toMatchObject({name:"AbortError"});expect((await invoiceRepository.detail("inv-draft-001")).invoice.status).toBe("Draft");});
 it("creates a new working revision without overwriting submitted snapshot",async()=>{await toPending();const submitted=(await invoiceRepository.detail("inv-draft-001")).revision;await invoiceRepository.recordRevisionRequest(await revisionRequest());const detail=await invoiceRepository.detail("inv-draft-001"),state=await invoiceRepository.confirmationState("inv-draft-001");expect(detail.invoice.status).toBe("Revision");expect(detail.revision.id).not.toBe(submitted.id);expect(state.revisions.find(item=>item.id===submitted.id)).toEqual(submitted);expect(state.requestedChanges[0].resolutionStatus).toBe("Open");});
 it("requires reason, evidence, and requested changes atomically",async()=>{await toPending();const before=await invoiceRepository.detail("inv-draft-001"),bad=await revisionRequest();bad.data={...bad.data,reason:"",requestedChanges:[]};await expect(invoiceRepository.recordRevisionRequest(bad)).rejects.toMatchObject({status:422});expect(await invoiceRepository.detail("inv-draft-001")).toEqual(before);});
 it("saves only working Revision and resolves requested changes",async()=>{await toPending();await invoiceRepository.recordRevisionRequest(await revisionRequest());const detail=await invoiceRepository.detail("inv-draft-001"),state=await invoiceRepository.confirmationState("inv-draft-001");const command=await base<SaveRevisionCommand["data"]>({invoiceDate:"2026-08-01",note:"Resolved",lines:detail.lines.map((line,index)=>({id:line.id,description:index===0?"Updated customer label":line.description})),resolutions:[{requestedChangeId:state.requestedChanges[0].id,resolutionNote:"Label updated",resolved:true}]},"usr-pic",["invoice.revision.edit"]);await invoiceRepository.saveRevision(command);const after=await invoiceRepository.confirmationState("inv-draft-001");expect(after.requestedChanges[0]).toMatchObject({resolutionStatus:"Resolved",resolutionNote:"Label updated"});expect(after.revisions).toHaveLength(2);});
 it("rejects a crafted resolved item without its required resolution note",async()=>{await toPending();await invoiceRepository.recordRevisionRequest(await revisionRequest());const detail=await invoiceRepository.detail("inv-draft-001"),state=await invoiceRepository.confirmationState("inv-draft-001"),before=await invoiceRepository.confirmationState("inv-draft-001");const command=await base<SaveRevisionCommand["data"]>({invoiceDate:detail.revision.snapshot.invoiceDate,note:detail.revision.snapshot.note,lines:detail.lines.map(line=>({id:line.id,description:line.description})),resolutions:[{requestedChangeId:state.requestedChanges[0].id,resolutionNote:" ",resolved:true}]},"usr-pic",["invoice.revision.edit"]);await expect(invoiceRepository.saveRevision(command)).rejects.toMatchObject({status:422,code:"RESOLUTION_NOTE_REQUIRED"});expect(await invoiceRepository.confirmationState("inv-draft-001")).toEqual(before);});
 it("blocks resubmit while a requested change remains open",async()=>{await toPending();await invoiceRepository.recordRevisionRequest(await revisionRequest());const command=await base<ResubmitRevisionCommand["data"]>({attestation:true,note:"Resubmit"},"usr-pic",["invoice.confirmation.resubmit"]);await expect(invoiceRepository.resubmitRevision(command)).rejects.toMatchObject({status:422,code:"REVISION_NOT_READY"});});
 it("resubmits a resolved working revision as immutable Pending Customer",async()=>{await toPending();await invoiceRepository.recordRevisionRequest(await revisionRequest());const detail=await invoiceRepository.detail("inv-draft-001"),state=await invoiceRepository.confirmationState("inv-draft-001");await invoiceRepository.saveRevision(await base<SaveRevisionCommand["data"]>({invoiceDate:"2026-08-01",note:"Resolved",lines:detail.lines.map(line=>({id:line.id,description:line.description})),resolutions:[{requestedChangeId:state.requestedChanges[0].id,resolutionNote:"Done",resolved:true}]},"usr-pic",["invoice.revision.edit"]));const result=await invoiceRepository.resubmitRevision(await base<ResubmitRevisionCommand["data"]>({attestation:true,note:"Ready"},"usr-pic",["invoice.confirmation.resubmit"]));expect((await invoiceRepository.detail(result.invoiceId)).invoice.status).toBe("Pending Customer");expect((await invoiceRepository.confirmationState(result.invoiceId)).submittedRevisionId).toBe(result.revisionId);});
 it("produces persisted revision diff and Decimal delta",async()=>{await toPending();await invoiceRepository.recordRevisionRequest(await revisionRequest());const state=await invoiceRepository.confirmationState("inv-draft-001"),source=state.revisions[0],target={...state.revisions[1],snapshot:{...state.revisions[1].snapshot,note:"Changed"}};const diff=invoiceRevisionDiff(source,target);expect(diff.changes).toContainEqual(expect.objectContaining({field:"note",kind:"Changed"}));expect(diff.absoluteDelta).toBe("0.00");expect(diff.denominatorZero).toBe(false);});
 it("requires PIC identity, evidence, and attestation for customer confirmed",async()=>{await toPending();const data:RecordCustomerConfirmedCommand["data"]={confirmedAt:"2026-08-11T10:00:00+07:00",channel:"Meeting",customerContactName:"Budi",reference:"REF-C",statement:"Confirmed",note:"PIC record",attestation:true,evidence};const nonPic=await base(data,"usr-demo",["invoice.confirmation.confirm"]);await expect(invoiceRepository.recordCustomerConfirmed(nonPic)).rejects.toMatchObject({status:403,code:"PIC_REQUIRED"});const missing=await base({...data,evidence:{...evidence,reference:""}},"usr-pic",["invoice.confirmation.confirm"]);await expect(invoiceRepository.recordCustomerConfirmed(missing)).rejects.toMatchObject({status:422});});
 it("hands off to Pending Approval without automatic approval",async()=>{await toPending();const data:RecordCustomerConfirmedCommand["data"]={confirmedAt:"2026-08-11T10:00:00+07:00",channel:"Meeting",customerContactName:"Budi",reference:"REF-C",statement:"Confirmed",note:"PIC record",attestation:true,evidence};const result=await invoiceRepository.recordCustomerConfirmed(await base(data,"usr-pic",["invoice.confirmation.confirm"]));const detail=await invoiceRepository.detail(result.invoiceId),state=await invoiceRepository.confirmationState(result.invoiceId);expect(detail.invoice.status).toBe("Pending Approval");expect(detail.activity.slice(0,2).map(item=>item.action)).toEqual(["invoice.pending-approval-handoff","invoice.customer-confirmed"]);expect(state.cycles[0].confirmation?.picUserId).toBe("usr-pic");expect(detail.activity.some(item=>item.action.includes("approved"))).toBe(false);});
 it("returns structured workflow conflict without partial changes",async()=>{const stale=await request();await invoiceRepository.requestConfirmation(stale);await expect(invoiceRepository.requestConfirmation(stale)).rejects.toMatchObject({status:422});const current=await invoiceRepository.detail("inv-draft-001");expect(current.invoice.status).toBe("Pending Customer");expect((await invoiceRepository.confirmationState("inv-draft-001")).cycles).toHaveLength(1);});
 it("uses honest preview watermarks for workflow status",async()=>{expect((await invoiceRepository.preview("inv-draft-001")).draftLabel).toBe("DRAFT");await toPending();expect((await invoiceRepository.preview("inv-draft-001")).draftLabel).toBe("MENUNGGU KONFIRMASI CUSTOMER");});
});
