import { QueryClient, QueryClientProvider } from "@tanstack/react-query";
import { render, screen, waitFor } from "@testing-library/react";
import userEvent from "@testing-library/user-event";
import type { ReactNode } from "react";
import { beforeEach, describe, expect, it, vi } from "vitest";
import { AppError } from "@/features/foundation/domain/errors";
import { ConfirmationTimeline, RevisionDiff, RevisionDiffExplorer } from "./components/invoice-confirmation-panel";
import type { InvoiceConfirmationState, InvoiceRevisionDiff } from "./domain/types";
import { resetInvoiceMock } from "./infrastructure/mock-adapter";
import { invoiceRepository } from "./repositories";

function createWrapper(){const client=new QueryClient({defaultOptions:{queries:{retry:false},mutations:{retry:false}}});return{client,Wrapper:({children}:{children:ReactNode})=><QueryClientProvider client={client}>{children}</QueryClientProvider>};}
const seed=()=>invoiceRepository.createDraft({data:{sourceOptionId:"src-pbr-001-r4",invoiceDate:"2026-08-01",note:"Demo"},actor:{userId:"usr",permissionKeys:["invoice.create"]},reason:"Seed"});
const diff:InvoiceRevisionDiff={sourceRevisionId:"rev-a",targetRevisionId:"inv-draft-001-rev-1",changes:[{field:"note",kind:"Changed",before:"Before",after:"After",requestedChangeId:"change-1"}],grandTotalBefore:"9600000.00",grandTotalAfter:"9600000.00",absoluteDelta:"0.00",percentageDelta:"0",denominatorZero:false,reconciledBefore:true,reconciledAfter:true};
const emptyState:InvoiceConfirmationState={cycles:[],revisions:[],requestedChanges:[],readiness:{ready:true,blockers:[],confirmationCycle:0,nextAction:"Request confirmation"},picUserId:"usr-pic"};
beforeEach(async()=>{vi.restoreAllMocks();resetInvoiceMock();await seed();});

describe("Invoice BR1 persisted diff local states",()=>{
 it("keeps loading local and preserves surrounding content",async()=>{vi.spyOn(invoiceRepository,"revisionDiff").mockImplementation((_id,_source,_target,signal)=>new Promise((_resolve,reject)=>signal?.addEventListener("abort",()=>reject(new DOMException("Aborted","AbortError")),{once:true})));const detail=await invoiceRepository.detail("inv-draft-001"),{Wrapper}=createWrapper();render(<><h1>Invoice sibling</h1><RevisionDiff detail={detail} access="view" sourceId="rev-a"/></>,{wrapper:Wrapper});expect(screen.getByText("Invoice sibling")).toBeVisible();expect(screen.getByLabelText("Memuat data")).toBeVisible();});
 it("renders no-change as successful persisted comparison with summaries",async()=>{vi.spyOn(invoiceRepository,"revisionDiff").mockResolvedValue({...diff,changes:[]});const detail=await invoiceRepository.detail("inv-draft-001"),{Wrapper}=createWrapper();render(<RevisionDiff detail={detail} access="view" sourceId="rev-a"/>,{wrapper:Wrapper});expect(await screen.findByText("Tidak ada perubahan persisted")).toBeVisible();expect(screen.getByText("Grand total before")).toBeVisible();expect(screen.getByText("Grand total after")).toBeVisible();});
 it("disables invalid or identical pairs without querying",async()=>{const spy=vi.spyOn(invoiceRepository,"revisionDiff"),detail=await invoiceRepository.detail("inv-draft-001"),{Wrapper}=createWrapper();const view=render(<RevisionDiff detail={detail} access="view"/>,{wrapper:Wrapper});expect(screen.getByText("Belum ada pasangan revision untuk dibandingkan")).toBeVisible();view.rerender(<RevisionDiff detail={detail} access="view" sourceId={detail.revision.id}/>);expect(spy).not.toHaveBeenCalled();});
 it.each([[403,"Akses terbatas"],[404,"Belum ada data"]] as const)("renders %s locally without retry",async(status,title)=>{vi.spyOn(invoiceRepository,"revisionDiff").mockRejectedValue(new AppError(status,status===403?"DIFF_FORBIDDEN":"REVISION_NOT_FOUND","Diff unavailable",{},false,`corr-${status}`));const detail=await invoiceRepository.detail("inv-draft-001"),{Wrapper}=createWrapper();render(<><h1>Invoice sibling</h1><RevisionDiff detail={detail} access="view" sourceId="rev-a"/></>,{wrapper:Wrapper});expect(await screen.findByText(title)).toBeVisible();expect(screen.getByText(`ID korelasi: corr-${status}`)).toBeVisible();expect(screen.getByText("Invoice sibling")).toBeVisible();expect(screen.queryByRole("button",{name:"Coba lagi"})).not.toBeInTheDocument();});
 it("retries 503 once with a fresh signal and renders desktop/mobile parity",async()=>{const signals:AbortSignal[]=[],spy=vi.spyOn(invoiceRepository,"revisionDiff").mockImplementation(async(_id,_source,_target,signal)=>{if(signal)signals.push(signal);if(signals.length===1)throw new AppError(503,"DIFF_UNAVAILABLE","Diff unavailable",{},true,"corr-diff");return diff;});const detail=await invoiceRepository.detail("inv-draft-001"),{Wrapper}=createWrapper(),user=userEvent.setup();render(<RevisionDiff detail={detail} access="view" sourceId="rev-a"/>,{wrapper:Wrapper});await user.click(await screen.findByRole("button",{name:"Coba lagi"}));expect(await screen.findByRole("table",{name:"Perbandingan persisted Invoice revision"})).toBeVisible();expect(screen.getAllByText("Changed")).toHaveLength(2);expect(spy).toHaveBeenCalledTimes(2);expect(signals[0]).not.toBe(signals[1]);});
 it("aborts on unmount and uses a fresh signal after remount",async()=>{const signals:AbortSignal[]=[],spy=vi.spyOn(invoiceRepository,"revisionDiff").mockImplementation((_id,_source,_target,signal)=>{if(signal)signals.push(signal);return signals.length===1?new Promise((_resolve,reject)=>signal?.addEventListener("abort",()=>reject(new DOMException("Aborted","AbortError")),{once:true})):Promise.resolve(diff);});const detail=await invoiceRepository.detail("inv-draft-001"),first=createWrapper(),view=render(<RevisionDiff detail={detail} access="view" sourceId="rev-a"/>,{wrapper:first.Wrapper});await waitFor(()=>expect(spy).toHaveBeenCalledTimes(1));view.unmount();expect(signals[0].aborted).toBe(true);const second=createWrapper();render(<RevisionDiff detail={detail} access="view" sourceId="rev-a"/>,{wrapper:second.Wrapper});expect(await screen.findByText("Persisted revision diff")).toBeVisible();expect(signals[1]).not.toBe(signals[0]);});
 it("aborts pair A and renders only latest selected pair B",async()=>{const detail=await invoiceRepository.detail("inv-draft-001"),revA={...detail.revision,id:"rev-a",revisionNumber:1},revB={...detail.revision,id:"rev-b",revisionNumber:2},state:InvoiceConfirmationState={...emptyState,revisions:[revA,revB,detail.revision],submittedRevisionId:"rev-a"},signals:AbortSignal[]=[],spy=vi.spyOn(invoiceRepository,"revisionDiff").mockImplementation((_id,source,target,signal)=>{if(signal)signals.push(signal);if(source==="rev-a")return new Promise((_resolve,reject)=>signal?.addEventListener("abort",()=>reject(new DOMException("Aborted","AbortError")),{once:true}));return Promise.resolve({...diff,sourceRevisionId:source,targetRevisionId:target,changes:[{field:"note-B",kind:"Changed",before:"B1",after:"B2"}]});}),{Wrapper}=createWrapper(),user=userEvent.setup();render(<RevisionDiffExplorer detail={detail} access="view" state={state}/>,{wrapper:Wrapper});await waitFor(()=>expect(spy).toHaveBeenCalledTimes(1));await user.selectOptions(screen.getByLabelText("Source revision"),"rev-b");expect((await screen.findAllByText("note-B")).length).toBe(2);expect(screen.getByText(`Pair: rev-b → ${detail.revision.id}`)).toBeVisible();expect(signals[0].aborted).toBe(true);expect(signals[1]).not.toBe(signals[0]);expect(screen.queryByText("rev-a →")).not.toBeInTheDocument();});
 it("keeps only pair C after rapid A to B to C switching",async()=>{const detail=await invoiceRepository.detail("inv-draft-001"),revisions=["rev-a","rev-b","rev-c"].map((id,index)=>({...detail.revision,id,revisionNumber:index+1})),state:InvoiceConfirmationState={...emptyState,revisions:[...revisions,detail.revision],submittedRevisionId:"rev-a"},signals:AbortSignal[]=[],spy=vi.spyOn(invoiceRepository,"revisionDiff").mockImplementation((_id,source,target,signal)=>{if(signal)signals.push(signal);if(source!=="rev-c")return new Promise((_resolve,reject)=>signal?.addEventListener("abort",()=>reject(new DOMException("Aborted","AbortError")),{once:true}));return Promise.resolve({...diff,sourceRevisionId:source,targetRevisionId:target,changes:[{field:"only-C",kind:"Changed",before:"C1",after:"C2"}]});}),{Wrapper}=createWrapper(),user=userEvent.setup();render(<RevisionDiffExplorer detail={detail} access="view" state={state}/>,{wrapper:Wrapper});await waitFor(()=>expect(spy).toHaveBeenCalledTimes(1));await user.selectOptions(screen.getByLabelText("Source revision"),"rev-b");await user.selectOptions(screen.getByLabelText("Source revision"),"rev-c");expect((await screen.findAllByText("only-C")).length).toBe(2);expect(screen.queryByText("note-B")).not.toBeInTheDocument();expect(signals.filter(signal=>signal.aborted).length).toBeGreaterThanOrEqual(2);});
 it("recovers a removed selected revision to a valid pair without mutating current pointer",async()=>{const detail=await invoiceRepository.detail("inv-draft-001"),revA={...detail.revision,id:"rev-a"},revB={...detail.revision,id:"rev-b"},state:InvoiceConfirmationState={...emptyState,revisions:[revA,revB,detail.revision],submittedRevisionId:"rev-a"},spy=vi.spyOn(invoiceRepository,"revisionDiff").mockResolvedValue(diff),{Wrapper}=createWrapper(),user=userEvent.setup(),view=render(<RevisionDiffExplorer detail={detail} access="view" state={state}/>,{wrapper:Wrapper});await user.selectOptions(screen.getByLabelText("Source revision"),"rev-b");view.rerender(<RevisionDiffExplorer detail={detail} access="view" state={{...state,revisions:[revA,detail.revision]}}/>);expect(screen.getByLabelText("Source revision")).toHaveValue("rev-a");expect(detail.invoice.currentRevisionId).toBe(detail.revision.id);expect(spy.mock.calls.at(-1)?.[1]).toBe("rev-a");});
});

describe("Invoice BR1 evidence timeline local states",()=>{
 it("renders loading and empty locally",async()=>{let resolveState:(value:InvoiceConfirmationState)=>void=()=>undefined;vi.spyOn(invoiceRepository,"confirmationState").mockImplementation(()=>new Promise(resolve=>{resolveState=resolve;}));const {Wrapper}=createWrapper();render(<><h1>Invoice sibling</h1><ConfirmationTimeline invoiceId="inv-draft-001" access="view"/></>,{wrapper:Wrapper});expect(screen.getByLabelText("Memuat data")).toBeVisible();resolveState(emptyState);expect(await screen.findByText("Belum ada confirmation cycle")).toBeVisible();expect(screen.getByText("Invoice sibling")).toBeVisible();});
 it.each([[403,"Akses terbatas"],[404,"Belum ada data"]] as const)("renders evidence %s without leaking or retry",async(status,title)=>{vi.spyOn(invoiceRepository,"confirmationState").mockRejectedValue(new AppError(status,status===403?"EVIDENCE_FORBIDDEN":"EVIDENCE_NOT_FOUND","Evidence unavailable",{},false,`corr-${status}`));const {Wrapper}=createWrapper();render(<ConfirmationTimeline invoiceId="inv-draft-001" access="view"/>,{wrapper:Wrapper});expect(await screen.findByText(title)).toBeVisible();expect(screen.queryByRole("button",{name:"Coba lagi"})).not.toBeInTheDocument();});
 it("retries evidence 503 once with a fresh signal",async()=>{const signals:AbortSignal[]=[],spy=vi.spyOn(invoiceRepository,"confirmationState").mockImplementation(async(_id,signal)=>{if(signal)signals.push(signal);if(signals.length===1)throw new AppError(503,"EVIDENCE_UNAVAILABLE","Evidence unavailable",{},true,"corr-evidence");return emptyState;});const {Wrapper}=createWrapper(),user=userEvent.setup();render(<ConfirmationTimeline invoiceId="inv-draft-001" access="view"/>,{wrapper:Wrapper});await user.click(await screen.findByRole("button",{name:"Coba lagi"}));expect(await screen.findByText("Belum ada confirmation cycle")).toBeVisible();expect(spy).toHaveBeenCalledTimes(2);expect(signals[0]).not.toBe(signals[1]);});
 it("renders authoritative actor name and fallback ID without per-row lookups",async()=>{const detail=await invoiceRepository.detail("inv-draft-001");await invoiceRepository.requestConfirmation({invoiceId:detail.invoice.id,actor:{userId:"usr-pic",permissionKeys:["invoice.confirmation.request"]},reason:"Request",currentVersion:detail.invoice.version,currentRevisionId:detail.revision.id,currentRevisionVersion:detail.revision.version,data:{requestDate:"2026-08-11",channel:"Meeting",customerContactName:"Customer",reference:"REF-ACTOR",note:"Actor test",attestation:true,evidence:{channel:"Meeting",displayLabel:"Meeting note",reference:"REF-ACTOR",referenceDate:"2026-08-11",customerContactName:"Customer",note:"Actor test"}}});const state=await invoiceRepository.confirmationState("inv-draft-001"),fallback={...state.cycles[0],cycle:2,request:{...state.cycles[0].request,id:"req-fallback",cycle:2,actorUserId:"usr-fallback",actorName:undefined}},mixed={...state,cycles:[state.cycles[0],fallback]},spy=vi.spyOn(invoiceRepository,"confirmationState").mockResolvedValue(mixed),{Wrapper}=createWrapper();render(<ConfirmationTimeline invoiceId="inv-draft-001" access="view"/>,{wrapper:Wrapper});expect(await screen.findByLabelText("Actor PIC Demo")).toHaveTextContent("PIC Demo (usr-pic)");expect(screen.getByLabelText("Actor usr-fallback")).toHaveTextContent("usr-fallback");expect(screen.queryByText("undefined")).not.toBeInTheDocument();expect(spy).toHaveBeenCalledTimes(1);});
 it("aborts evidence on unmount, succeeds on fresh remount, and suppresses none persona",async()=>{const signals:AbortSignal[]=[],spy=vi.spyOn(invoiceRepository,"confirmationState").mockImplementation((_id,signal)=>{if(signal)signals.push(signal);return signals.length===1?new Promise((_resolve,reject)=>signal?.addEventListener("abort",()=>reject(new DOMException("Aborted","AbortError")),{once:true})):Promise.resolve(emptyState);});const first=createWrapper(),view=render(<ConfirmationTimeline invoiceId="inv-draft-001" access="view"/>,{wrapper:first.Wrapper});await waitFor(()=>expect(spy).toHaveBeenCalledTimes(1));view.unmount();expect(signals[0].aborted).toBe(true);const second=createWrapper();const fresh=render(<ConfirmationTimeline invoiceId="inv-draft-001" access="view"/>,{wrapper:second.Wrapper});expect(await screen.findByText("Belum ada confirmation cycle")).toBeVisible();expect(signals[1]).not.toBe(signals[0]);fresh.unmount();const third=createWrapper();render(<ConfirmationTimeline invoiceId="inv-draft-001" access="none"/>,{wrapper:third.Wrapper});await new Promise(resolve=>setTimeout(resolve,10));expect(spy).toHaveBeenCalledTimes(2);});
});
