import { QueryClient, QueryClientProvider } from "@tanstack/react-query";
import { act, renderHook, waitFor } from "@testing-library/react";
import type { ReactNode } from "react";
import { beforeEach, describe, expect, it, vi } from "vitest";
import { queryKeys } from "@/lib/query-keys";
import type { InvoiceDraftCommand } from "./domain/types";
import { resetInvoiceMock } from "./infrastructure/mock-adapter";
import { invoiceMutationInvalidationKeys, useAutosaveInvoiceDraft, useInvoiceDetail } from "./queries/hooks";
import { invoiceRepository } from "./repositories";
const seedCommand:InvoiceDraftCommand={data:{sourceOptionId:"src-pbr-001-r4",invoiceDate:"2026-08-01",note:"Seed"},actor:{userId:"usr",permissionKeys:["invoice.create"]},reason:"Seed"};
const edit=async():Promise<InvoiceDraftCommand>=>{const detail=await invoiceRepository.detail("inv-draft-001");return{invoiceId:detail.invoice.id,data:{invoiceDate:"2026-08-01",note:"Autosave",lines:detail.lines.map(line=>({id:line.id,description:line.description}))},actor:{userId:"usr",permissionKeys:["invoice.edit"]},reason:"Autosave",currentVersion:detail.invoice.version,currentRevisionId:detail.revision.id,currentRevisionVersion:detail.revision.version};};
function setup(){const client=new QueryClient({defaultOptions:{queries:{retry:false},mutations:{retry:false}}});const wrapper=({children}:{children:ReactNode})=><QueryClientProvider client={client}>{children}</QueryClientProvider>;return{client,wrapper};}
beforeEach(()=>{vi.restoreAllMocks();resetInvoiceMock();});
describe("Invoice query and autosave contracts",()=>{
 it("suppresses detail query for none persona",()=>{const spy=vi.spyOn(invoiceRepository,"detail"),{wrapper}=setup();renderHook(()=>useInvoiceDetail("inv-draft-001","none"),{wrapper});expect(spy).not.toHaveBeenCalled();});
 it("uses mutation-specific invalidation families without unrelated consumers",()=>{const request=invoiceMutationInvalidationKeys.request("inv-1"),autosave=invoiceMutationInvalidationKeys.revisionAutosave("inv-1"),confirmed=invoiceMutationInvalidationKeys.confirmed("inv-1");expect(request).toContainEqual(queryKeys.invoices.confirmationCycles("inv-1"));expect(request).not.toContainEqual(queryKeys.invoices.workingRevision("inv-1"));expect(autosave).toContainEqual(queryKeys.invoices.revisionDiffs("inv-1"));expect(autosave).not.toContainEqual(queryKeys.invoices.lists);expect(autosave).not.toContainEqual(queryKeys.invoices.activity("inv-1"));expect(confirmed).toContainEqual(queryKeys.invoices.customerResponses("inv-1"));expect(confirmed).not.toContainEqual(queryKeys.invoices.history("inv-1"));});
 it("defines exact unique scoped keys for every 2C-B mutation",()=>{const id="inv-1",sets={request:invoiceMutationInvalidationKeys.request(id),revisionRequest:invoiceMutationInvalidationKeys.revisionRequest(id),revisionSave:invoiceMutationInvalidationKeys.revisionSave(id),revisionAutosave:invoiceMutationInvalidationKeys.revisionAutosave(id),resubmit:invoiceMutationInvalidationKeys.resubmit(id),confirmed:invoiceMutationInvalidationKeys.confirmed(id)};for(const keys of Object.values(sets))expect(new Set(keys.map(key=>JSON.stringify(key))).size).toBe(keys.length);expect(sets.request).not.toContainEqual(queryKeys.invoices.revisionDiffs(id));expect(sets.revisionRequest).toContainEqual(queryKeys.invoices.history(id));expect(sets.revisionSave).toContainEqual(queryKeys.invoices.activity(id));expect(sets.revisionAutosave).not.toContainEqual(queryKeys.invoices.activity(id));expect(sets.resubmit).toContainEqual(queryKeys.invoices.confirmationCycles(id));expect(sets.confirmed).not.toContainEqual(queryKeys.invoices.workingRevision(id));});
 it("autosave mutation increases the authoritative version",async()=>{await invoiceRepository.createDraft(seedCommand);const {wrapper}=setup(),hook=renderHook(()=>useAutosaveInvoiceDraft(),{wrapper});await act(async()=>{await hook.result.current.mutateAsync(await edit());});await waitFor(()=>expect(hook.result.current.isSuccess).toBe(true));expect((await invoiceRepository.detail("inv-draft-001")).invoice.version).toBe(2);});
 it("latest autosave cancels an older request without false success",async()=>{await invoiceRepository.createDraft(seedCommand);let calls=0;const original=invoiceRepository.autosaveDraft;const spy=vi.spyOn(invoiceRepository,"autosaveDraft").mockImplementation((command,signal)=>{calls+=1;if(calls===1)return new Promise((resolve,reject)=>signal?.addEventListener("abort",()=>reject(new DOMException("Aborted","AbortError")),{once:true}));return original(command,signal);});const {wrapper}=setup(),hook=renderHook(()=>useAutosaveInvoiceDraft(),{wrapper}),first=await edit();let firstResult:Promise<unknown>;act(()=>{firstResult=hook.result.current.mutateAsync(first).catch(error=>error);});await waitFor(()=>expect(spy).toHaveBeenCalledTimes(1));await act(async()=>{await hook.result.current.mutateAsync(first);});expect(await firstResult!).toMatchObject({name:"AbortError"});expect((await invoiceRepository.detail("inv-draft-001")).invoice.version).toBe(2);});
 it("unmount cancellation aborts autosave and creates a fresh controller next mount",async()=>{await invoiceRepository.createDraft(seedCommand);const original=invoiceRepository.autosaveDraft;const signals:AbortSignal[]=[];vi.spyOn(invoiceRepository,"autosaveDraft").mockImplementation((command,signal)=>{if(signal)signals.push(signal);return original(command,signal);});const first=setup(),hook=renderHook(()=>useAutosaveInvoiceDraft(),{wrapper:first.wrapper});await act(async()=>{await hook.result.current.mutateAsync(await edit());});hook.unmount();const second=setup(),next=renderHook(()=>useAutosaveInvoiceDraft(),{wrapper:second.wrapper});await act(async()=>{await next.result.current.mutateAsync(await edit());});expect(signals).toHaveLength(2);expect(signals[0]).not.toBe(signals[1]);});
 it("structured conflict is not retried or invalidated as success",async()=>{await invoiceRepository.createDraft(seedCommand);const stale=await edit();await invoiceRepository.saveDraft(stale);const {client,wrapper}=setup(),invalidate=vi.spyOn(client,"invalidateQueries"),hook=renderHook(()=>useAutosaveInvoiceDraft(),{wrapper});let failure:unknown;await act(async()=>{try{await hook.result.current.mutateAsync(stale);}catch(error){failure=error;}});expect(failure).toMatchObject({status:409});expect(invalidate).not.toHaveBeenCalled();});
});
