import { QueryClient, QueryClientProvider } from "@tanstack/react-query";
import { fireEvent, render, screen, waitFor, within } from "@testing-library/react";
import userEvent from "@testing-library/user-event";
import type { ReactNode } from "react";
import { beforeEach, describe, expect, it, vi } from "vitest";
import { AppError } from "@/features/foundation/domain/errors";
import { InvoiceConfirmationPanel } from "./components/invoice-confirmation-panel";
import type { InvoiceDetail, SaveRevisionCommand } from "./domain/types";
import { resetInvoiceMock } from "./infrastructure/mock-adapter";
import { invoiceRepository } from "./repositories";

function Wrapper({ children }: { children: ReactNode }) { return <QueryClientProvider client={new QueryClient({ defaultOptions: { queries: { retry: false }, mutations: { retry: false } } })}>{children}</QueryClientProvider>; }
const seed = () => invoiceRepository.createDraft({ data: { sourceOptionId: "src-pbr-001-r4", invoiceDate: "2026-08-01", note: "BR2" }, actor: { userId: "usr-pic", permissionKeys: ["invoice.create"] }, reason: "BR2 seed" });
async function pending() { await seed(); const detail = await invoiceRepository.detail("inv-draft-001"); await invoiceRepository.requestConfirmation({ invoiceId: detail.invoice.id, actor: { userId: "usr-pic", permissionKeys: ["invoice.confirmation.request"] }, reason: "Request", currentVersion: detail.invoice.version, currentRevisionId: detail.revision.id, currentRevisionVersion: detail.revision.version, data: { requestDate: "2026-08-11", channel: "Meeting", customerContactName: "Customer", reference: "REF-1", note: "Manual", attestation: true, evidence: { channel: "Meeting", displayLabel: "Meeting note", reference: "REF-1", referenceDate: "2026-08-11", customerContactName: "Customer", note: "Manual" } } }); }
async function working(resolved = false) { await pending(); let detail = await invoiceRepository.detail("inv-draft-001"); await invoiceRepository.recordRevisionRequest({ invoiceId: detail.invoice.id, actor: { userId: "usr-pic", permissionKeys: ["invoice.confirmation.revision-request"] }, reason: "Change", currentVersion: detail.invoice.version, currentRevisionId: detail.revision.id, currentRevisionVersion: detail.revision.version, data: { responseDate: "2026-08-11", channel: "Meeting", customerContactName: "Customer", reference: "REF-2", reason: "Change", note: "Manual", requestedChanges: [{ section: "LinePresentation", currentValueSummary: detail.lines[0].description, customerRequestSummary: "Update", requiresFinancialRecalculation: false, requiresSourceCorrection: false, requiresDocumentUpdate: false, resolutionStatus: "Open" }], evidence: { channel: "Meeting", displayLabel: "Meeting note", reference: "REF-2", referenceDate: "2026-08-11", customerContactName: "Customer", note: "Manual" } } }); if (resolved) { detail = await invoiceRepository.detail("inv-draft-001"); const state = await invoiceRepository.confirmationState(detail.invoice.id); const command: SaveRevisionCommand = { invoiceId: detail.invoice.id, actor: { userId: "usr-pic", permissionKeys: ["invoice.revision.edit"] }, reason: "Resolve", currentVersion: detail.invoice.version, currentRevisionId: detail.revision.id, currentRevisionVersion: detail.revision.version, data: { invoiceDate: detail.revision.snapshot.invoiceDate, note: detail.revision.snapshot.note, lines: detail.lines.map(line => ({ id: line.id, description: line.description })), resolutions: state.requestedChanges.map(item => ({ requestedChangeId: item.id, resolved: true, resolutionNote: "Done" })) } }; await invoiceRepository.saveRevision(command); } }
const conflict = (action: string) => new AppError(409, `${action}_CONFLICT`, "Invoice berubah; input aman dipertahankan.", {}, false, `corr-${action}`, { invoiceId: "inv-draft-001", attemptedVersion: 2, latestVersion: 3, attemptedRevisionId: "rev-old", latestRevisionId: "rev-new", attemptedRevisionVersion: 1, latestRevisionVersion: 2, attemptedStatus: "Pending Customer", latestStatus: "Revision", attemptedConfirmationCycle: 1, latestConfirmationCycle: 2, fieldDiff: [{ field: "status", attempted: "Pending Customer", latest: "Revision" }] });
async function detail() { return invoiceRepository.detail("inv-draft-001"); }
function show(value: InvoiceDetail, access = "pic") { return render(<InvoiceConfirmationPanel detail={value} access={access} />, { wrapper: Wrapper }); }

beforeEach(() => { vi.restoreAllMocks(); resetInvoiceMock(); });

describe("Invoice BR2 production confirmation actions", () => {
  it("isolates Request Confirmation command and prevents a pending double-submit", async () => { await seed(); const calls: unknown[] = []; let finish: (() => void) | undefined; vi.spyOn(invoiceRepository, "requestConfirmation").mockImplementation((command) => { calls.push(structuredClone(command)); return new Promise(resolve => { finish = () => resolve({ invoiceId: command.invoiceId, version: 2, revisionId: command.currentRevisionId, revisionVersion: 1, savedAt: "2026-08-11T10:00:00+07:00", message: "ok", correlationId: "corr-ok" }); }); }); show(await detail()); const user = userEvent.setup(), form = await screen.findByRole("form", { name: "Request Customer Confirmation" }), submit = within(form).getByRole("button", { name: "Request confirmation" }); await user.click(within(form).getByRole("checkbox")); await user.click(submit); await user.click(submit); fireEvent.keyDown(form, { key: "Enter" }); expect(calls).toHaveLength(1); expect(submit).toBeDisabled(); expect(calls[0]).toEqual(expect.objectContaining({ invoiceId: "inv-draft-001", currentVersion: 1, currentRevisionId: expect.any(String), currentRevisionVersion: 1, data: expect.not.objectContaining({ status: expect.anything(), totals: expect.anything(), reconciliation: expect.anything(), readiness: expect.anything() }) })); finish?.(); });

  it("renders full Request conflict, retains values, focuses recovery, and preserves persona URL", async () => { await seed(); const spy = vi.spyOn(invoiceRepository, "requestConfirmation").mockRejectedValue(conflict("REQUEST")), user = userEvent.setup(); show(await detail()); const reference = await screen.findByLabelText("Evidence reference"); await user.clear(reference); await user.type(reference, "LONG-REFERENCE-RETAINED"); await user.click(screen.getByRole("checkbox")); await user.click(screen.getByRole("button", { name: "Request confirmation" })); const region = await screen.findByRole("alert", { name: "Request Confirmation belum berhasil" }); expect(region).toHaveFocus(); expect(region).toHaveTextContent("Attempted 2; latest 3"); expect(region).toHaveTextContent("Attempted 1; latest 2"); expect(within(region).getByRole("link", { name: "Buka Invoice terbaru" })).toHaveAttribute("href", "/invoices/inv-draft-001?access=pic"); await user.click(within(region).getByRole("button", { name: "Kembali ke form" })); expect(reference).toHaveValue("LONG-REFERENCE-RETAINED"); expect(spy).toHaveBeenCalledTimes(1); expect(screen.getByRole("form", { name: "Request Customer Confirmation" })).toHaveFocus(); });

  it.each([403, 404, 422] as const)("keeps Request form dirty after non-retryable %s", async status => { await seed(); vi.spyOn(invoiceRepository, "requestConfirmation").mockRejectedValue(new AppError(status, `REQUEST_${status}`, "Request ditolak.", status === 422 ? { reference: ["Reference ditolak backend"] } : {}, false, `corr-${status}`)); const user = userEvent.setup(); show(await detail()); const reference = await screen.findByLabelText("Evidence reference"); await user.clear(reference); await user.type(reference, "RETAIN"); await user.click(screen.getByRole("checkbox")); await user.click(screen.getByRole("button", { name: "Request confirmation" })); expect(await screen.findByText(new RegExp(`REQUEST_${status}`))).toBeVisible(); expect(reference).toHaveValue("RETAIN"); expect(screen.queryByRole("button", { name: "Coba lagi" })).not.toBeInTheDocument(); if (status === 422) expect(reference).toHaveAccessibleDescription("Reference ditolak backend"); });

  it.each([500, 502, 503] as const)("retries Request %s with captured command and fresh signal", async status => { await seed(); const original = invoiceRepository.requestConfirmation, commands: unknown[] = [], signals: AbortSignal[] = []; vi.spyOn(invoiceRepository, "requestConfirmation").mockImplementation((command, signal) => { commands.push(structuredClone(command)); if (signal) signals.push(signal); return commands.length === 1 ? Promise.reject(new AppError(status, `REQUEST_${status}`, "Server belum tersedia.", {}, true, `corr-${status}`)) : original(command, signal); }); const user = userEvent.setup(); show(await detail()); await user.click(await screen.findByRole("checkbox")); await user.click(screen.getByRole("button", { name: "Request confirmation" })); await user.click(await screen.findByRole("button", { name: "Coba lagi" })); await waitFor(() => expect(commands).toHaveLength(2)); expect(commands[1]).toEqual(commands[0]); expect(signals[1]).not.toBe(signals[0]); expect((await invoiceRepository.detail("inv-draft-001")).invoice.status).toBe("Pending Customer"); });

  it("consumes Request cancellation and allows a fresh explicit success", async () => { await seed(); const original = invoiceRepository.requestConfirmation, signals: AbortSignal[] = []; const spy = vi.spyOn(invoiceRepository, "requestConfirmation").mockImplementation((command, signal) => { if (signal) signals.push(signal); return signals.length === 1 ? Promise.reject(new DOMException("Aborted", "AbortError")) : original(command, signal); }); const user = userEvent.setup(); show(await detail()); await user.click(await screen.findByRole("checkbox")); const submit = screen.getByRole("button", { name: "Request confirmation" }); await user.click(submit); expect(screen.queryByRole("alert")).not.toBeInTheDocument(); await user.click(submit); await waitFor(() => expect(spy).toHaveBeenCalledTimes(2)); expect(signals[1]).not.toBe(signals[0]); expect((await invoiceRepository.detail("inv-draft-001")).invoice.status).toBe("Pending Customer"); });

  it("isolates and retains Revision Request on structured conflict", async () => { await pending(); const commands: unknown[] = []; vi.spyOn(invoiceRepository, "recordRevisionRequest").mockImplementation(command => { commands.push(structuredClone(command)); return Promise.reject(conflict("REVISION_REQUEST")); }); const user = userEvent.setup(); show(await detail()); const form = await screen.findByRole("form", { name: "Record Customer Revision Request" }); await user.type(within(form).getByLabelText("Alasan revisi"), "Customer asks a clear label"); await user.type(within(form).getByLabelText("Requested change"), "Use contract wording"); await user.click(within(form).getByRole("button", { name: "Catat revision request" })); expect(await screen.findByRole("alert", { name: "Revision Request belum berhasil" })).toHaveFocus(); expect(within(form).getByLabelText("Requested change")).toHaveValue("Use contract wording"); expect(commands).toHaveLength(1); expect(commands[0]).toEqual(expect.objectContaining({ data: expect.objectContaining({ requestedChanges: [expect.objectContaining({ section: "LinePresentation", customerRequestSummary: "Use contract wording" })] }) })); });

  it("isolates and retains Resubmit on structured conflict", async () => { await working(true); const commands: unknown[] = []; vi.spyOn(invoiceRepository, "resubmitRevision").mockImplementation(command => { commands.push(structuredClone(command)); return Promise.reject(conflict("RESUBMIT")); }); const user = userEvent.setup(); show(await detail()); const form = await screen.findByRole("form", { name: "Resubmit Invoice Revision" }); await user.type(within(form).getByLabelText("Resolution summary"), "All requested changes resolved"); await user.click(within(form).getByRole("checkbox")); await user.click(within(form).getByRole("button", { name: "Resubmit revision" })); expect(await screen.findByRole("alert", { name: "Resubmit Revision belum berhasil" })).toHaveFocus(); expect(within(form).getByLabelText("Resolution summary")).toHaveValue("All requested changes resolved"); expect(commands).toHaveLength(1); expect(commands[0]).toEqual(expect.objectContaining({ data: { note: "All requested changes resolved", attestation: true } })); });

  it("isolates PIC Confirmed and retains all evidence on structured conflict", async () => { await pending(); const commands: unknown[] = []; vi.spyOn(invoiceRepository, "recordCustomerConfirmed").mockImplementation(command => { commands.push(structuredClone(command)); return Promise.reject(conflict("CONFIRMED")); }); const user = userEvent.setup(); show(await detail()); const form = await screen.findByRole("form", { name: "Record Customer Confirmed" }); await user.type(within(form).getByLabelText("Confirmation summary"), "Customer explicitly confirmed"); await user.click(within(form).getByRole("checkbox")); await user.click(within(form).getByRole("button", { name: "Catat customer confirmed" })); expect(await screen.findByRole("alert", { name: "Record Customer Confirmed belum berhasil" })).toHaveFocus(); expect(within(form).getByLabelText("Confirmation summary")).toHaveValue("Customer explicitly confirmed"); expect(commands).toHaveLength(1); expect(commands[0]).toEqual(expect.objectContaining({ actor: expect.objectContaining({ userId: "usr-pic" }), data: expect.not.objectContaining({ approvalStatus: expect.anything(), finalNumber: expect.anything(), ar: expect.anything(), tax: expect.anything() }) })); });

  it("enforces persona actions and responsive/wrapping structure", async () => { await pending(); const value = await detail(), pic = show(value); const revision = await screen.findByRole("form", { name: "Record Customer Revision Request" }), confirmed = screen.getByRole("form", { name: "Record Customer Confirmed" }); expect(revision).toHaveClass("confirmation-form"); expect(confirmed).toHaveClass("confirmation-form"); expect(within(revision).getByLabelText("Evidence reference")).toHaveAttribute("aria-required", "true"); pic.unmount(); show(value, "manage"); await screen.findByText("Customer Confirmation"); expect(screen.queryByRole("form", { name: "Record Customer Revision Request" })).not.toBeInTheDocument(); expect(screen.queryByRole("form", { name: "Record Customer Confirmed" })).not.toBeInTheDocument(); expect(document.querySelectorAll(".break-anywhere").length).toBeGreaterThan(0); });
});
