import Link from "next/link";
import {Alert,Badge,Card,CardHeader,DataState,PageHeader,StatusBadge,TableShell} from "@/components/ui";
import {formatDate,formatRupiah} from "@/lib/formatters";
import {payrollBillingRepository} from "../repositories";
import {PayrollBillingExceptions} from "./payroll-billing-exceptions";
import {PayrollBillingActions} from "./payroll-billing-actions";
import {PayrollCalculationTrace} from "./payroll-calculation-trace";
import {PayrollRevisionWorkspace} from "./payroll-revision-workspace";

export async function PayrollBillingDetailPage({id,access="manage"}:{id:string;access?:string}){
  if(access==="none")return <DataState kind="denied" title="Payroll Billing tidak diizinkan"/>;
  let detail;
  try{detail=await payrollBillingRepository.get(id);}catch{return <DataState kind="empty" title="Payroll Billing Run tidak ditemukan" action={<Link className="button button-secondary" href={`/payroll-billing?access=${access}`}>Kembali ke daftar</Link>}/>;}
  const {run}=detail,s=run.source;
  return <>
    <PageHeader eyebrow="Payroll Billing Run" title={`${run.id} · Revision ${run.revisionNumber}`} description={`${s.projectLabel} · ${s.customerLabel} · ${s.attendancePeriod}`} meta={<><StatusBadge tone="warning">{run.status}</StatusBadge><Badge tone="warning">Snapshot demo</Badge></>} actions={<Link className="button button-secondary" href={`/payroll-billing?access=${access}`}>Kembali ke daftar</Link>}/>
    <Alert tone={detail.readiness.readyToLock?"success":"warning"} title="Next action">{detail.readiness.nextAction}<ul>{detail.readiness.blockers.map(item=><li key={item}>{item}</li>)}</ul></Alert>
    <PayrollBillingActions detail={detail} access={access}/>
    <div className="detail-grid"><Card><CardHeader title="Source snapshot immutable"/><dl className="detail-list"><dt>Attendance</dt><dd>{s.attendanceBatchId} · R{s.attendanceRevision} · {s.attendanceRows} row</dd><dt>SPH</dt><dd>{s.sphLabel}</dd><dt>Rate Version</dt><dd>{s.rateVersionLabel}</dd><dt>Scope</dt><dd>{s.branchLabel} · {s.serviceLabel} · {s.unit}</dd><dt>Captured</dt><dd>{formatDate(s.capturedAt,true)}</dd></dl></Card><Card><CardHeader title="Financial summary"/><dl className="detail-list"><dt>Base amount</dt><dd>{formatRupiah(run.summary.baseAmount)}</dd><dt>Adjustment</dt><dd>{formatRupiah(run.summary.adjustmentAmount)}</dd><dt>Management fee</dt><dd>{formatRupiah(run.summary.managementFee)}</dd><dt>PPN</dt><dd>{run.summary.vatAmount?formatRupiah(run.summary.vatAmount):"Tidak berlaku"}</dd><dt>PPh/withholding</dt><dd>{run.summary.withholdingAmount?formatRupiah(run.summary.withholdingAmount):"Tidak berlaku"}</dd><dt>Grand total</dt><dd><strong>{formatRupiah(run.summary.grandTotal)}</strong></dd></dl></Card></div>
    <Card><CardHeader title="Calculated lines"/><TableShell caption="Calculated payroll billing lines"><thead><tr><th>Source</th><th>Branch/service</th><th>HK</th><th>Rate</th><th>Subtotal</th><th>Adjustment</th><th>Final billing</th></tr></thead><tbody>{detail.lines.map(line=><tr key={line.id}><td>{line.employeeReference}</td><td>{line.branchLabel}<small className="table-subtext">{line.serviceLabel}</small></td><td>{line.quantity}</td><td>{formatRupiah(line.unitRate)}</td><td>{formatRupiah(line.componentSubtotal)}</td><td>{formatRupiah(line.adjustment)}</td><td>{formatRupiah(line.finalAmount)}</td></tr>)}</tbody></TableShell><div className="mobile-card-list calculated-lines-mobile" aria-label="Calculated lines mobile">{detail.lines.map(line=><article key={line.id}><strong className="break-all">{line.employeeReference}</strong><dl className="detail-list"><dt>Branch / service</dt><dd>{line.branchLabel} / {line.serviceLabel}</dd><dt>HK</dt><dd>{line.quantity}</dd><dt>Rate</dt><dd className="amount-wrap">{formatRupiah(line.unitRate)}</dd><dt>Subtotal</dt><dd className="amount-wrap">{formatRupiah(line.componentSubtotal)}</dd><dt>Adjustment</dt><dd className="amount-wrap">{formatRupiah(line.adjustment)}</dd><dt>Final billing</dt><dd className="amount-wrap">{formatRupiah(line.finalAmount)}</dd></dl></article>)}</div></Card>
    <PayrollCalculationTrace lines={detail.lines} currency={detail.run.currency}/>
    <PayrollRevisionWorkspace detail={detail} access={access}/>
    <div className="detail-grid"><PayrollBillingExceptions runId={id} access={access}/><Card><CardHeader title="Reconciliation"/><dl className="detail-list"><dt>Line total</dt><dd>{formatRupiah(detail.reconciliation.lineTotal)}</dd><dt>Summary</dt><dd>{formatRupiah(detail.reconciliation.summaryTotal)}</dd><dt>Variance</dt><dd>{formatRupiah(detail.reconciliation.variance)}</dd><dt>Status</dt><dd>{detail.reconciliation.reconciled?"Reconciled":"Not reconciled"}</dd></dl></Card><Card><CardHeader title="Revision history"/><ol className="audit-list">{detail.revisions.map(revision=><li key={revision.id}><strong>Revision {revision.revisionNumber} · {revision.status}</strong><span>{revision.reason} · {formatRupiah(revision.total)}</span><small>{revision.diffSummary}</small></li>)}</ol></Card><Card><CardHeader title="Activity"/><ol className="audit-list">{detail.activity.map(item=><li key={item.id}><strong>{item.action}</strong><span>{item.actorName??item.actorUserId} · {formatDate(item.occurredAt,true)}</span><small>{item.reason} · {item.correlationId}</small></li>)}</ol></Card></div>
  </>;
}
