"use client";
import { useEffect } from "react";
import { usePathname, useRouter, useSearchParams } from "next/navigation";
import { Button, Card, CardHeader, DataState, Input, LoadingState, Select, TableShell } from "@/components/ui";
import { mapPayrollBillingMutationError } from "../domain/mutation-error";
import { readPayrollExceptionUrl, updatePayrollExceptionUrl, writePayrollExceptionUrl } from "../domain/exception-url";
import type { PayrollBillingExceptionQuery } from "../domain/types";
import { usePayrollBillingExceptions } from "../queries/hooks";

export function PayrollBillingExceptions({ runId, access }: { runId: string; access: string }) {
  const router = useRouter(), pathname = usePathname(), searchParams = useSearchParams(), raw = searchParams.toString(), query = readPayrollExceptionUrl(new URLSearchParams(raw)), result = usePayrollBillingExceptions(runId, query, access);
  const navigate = (patch: Partial<PayrollBillingExceptionQuery> | "reset") => { const current = new URLSearchParams(raw), next = patch === "reset" ? writePayrollExceptionUrl(current, "reset") : updatePayrollExceptionUrl(current, patch, result.data?.totalPages); router.replace(next.size ? `${pathname}?${next}` : pathname, { scroll: false }); };
  useEffect(() => { if (access === "none") return; const current = new URLSearchParams(raw), canonical = writePayrollExceptionUrl(current, query, result.data?.totalPages); if (canonical.toString() !== current.toString()) router.replace(canonical.size ? `${pathname}?${canonical}` : pathname, { scroll: false }); }, [access, pathname, query, result.data?.totalPages, raw, router]);
  if (access === "none") return <Card><CardHeader title="Exception" /><DataState kind="denied" title="Exception tidak diizinkan" /></Card>;
  const filtered = Boolean(query.search || query.severities?.length || query.blocking !== undefined);
  return <Card><CardHeader title="Exception" />
    <div className="filter-grid" aria-label="Filter exception"><Input label="Cari exception" value={query.search ?? ""} onChange={(event) => navigate({ search: event.currentTarget.value })} /><Select label="Severity" value={query.severities?.[0] ?? ""} onChange={(event) => navigate({ severities: event.currentTarget.value ? [event.currentTarget.value as "Warning" | "Error"] : [] })}><option value="">Semua</option><option value="Error">Error</option><option value="Warning">Warning</option></Select><Select label="Blocking" value={query.blocking === undefined ? "" : String(query.blocking)} onChange={(event) => navigate({ blocking: event.currentTarget.value === "" ? undefined : event.currentTarget.value === "true" })}><option value="">Semua</option><option value="true">Blocking</option><option value="false">Non-blocking</option></Select><Select label="Urutkan" value={query.sort} onChange={(event) => navigate({ sort: event.currentTarget.value as "severity" | "code" | "calculatedAt" })}><option value="severity">Severity</option><option value="code">Code</option><option value="calculatedAt">Waktu kalkulasi</option></Select><Select label="Arah" value={query.direction} onChange={(event) => navigate({ direction: event.currentTarget.value as "asc" | "desc" })}><option value="desc">Menurun</option><option value="asc">Menaik</option></Select><Select label="Baris per halaman" value={query.pageSize} onChange={(event) => navigate({ pageSize: Number(event.currentTarget.value) as 10 | 20 | 50 })}><option value="10">10</option><option value="20">20</option><option value="50">50</option></Select><Button variant="quiet" onClick={() => navigate("reset")}>Reset</Button></div>
    {result.isPending ? <LoadingState /> : result.isError ? <ExceptionError error={result.error} retry={() => void result.refetch()} /> : result.data?.total === 0 ? <DataState kind={filtered ? "zero" : "empty"} title={filtered ? "Tidak ada exception sesuai filter" : "Tidak ada exception"} action={filtered ? <Button variant="secondary" onClick={() => navigate("reset")}>Reset filter</Button> : undefined} /> : <><TableShell caption="Daftar exception Payroll Billing"><thead><tr><th>Code</th><th>Severity</th><th>Blocking</th><th>Source</th><th>Penjelasan</th><th>Tindakan</th></tr></thead><tbody>{result.data?.items.map((item) => <tr key={item.id}><td>{item.code}</td><td>{item.severity}</td><td>{item.blocking ? "Blocking" : "Non-blocking"}</td><td>{item.sourceReference ?? item.lineId ?? "Run"}</td><td>{item.explanation}</td><td>{item.suggestedAction}</td></tr>)}</tbody></TableShell>
      <div className="mobile-card-list exception-mobile-list" aria-label="Exception mobile">{result.data?.items.map((item) => <article key={item.id}><strong className="break-all">{item.code} / {item.severity}</strong><dl className="detail-list"><dt>Blocking</dt><dd>{item.blocking ? "Blocking" : "Non-blocking"}</dd><dt>Source</dt><dd className="break-all">{item.sourceReference ?? item.lineId ?? "Run"}</dd><dt>Penjelasan</dt><dd>{item.explanation}</dd><dt>Tindakan</dt><dd>{item.suggestedAction}</dd></dl></article>)}</div>
      <nav aria-label="Pagination exception" className="pagination"><Button variant="secondary" disabled={query.page === 1} onClick={() => navigate({ page: Math.max(1, (query.page ?? 1) - 1) })}>Sebelumnya</Button><span>Halaman {result.data?.page} dari {result.data?.totalPages}</span><Button variant="secondary" disabled={!result.data?.hasNextPage} onClick={() => navigate({ page: (query.page ?? 1) + 1 })}>Berikutnya</Button></nav></>}
  </Card>;
}

function ExceptionError({ error, retry }: { error: Error; retry: () => void }) { const mapped = mapPayrollBillingMutationError(error); if (mapped.cancelled) return <LoadingState />; return <DataState kind={mapped.safeCode.includes("FORBIDDEN") ? "denied" : "server"} title="Exception belum dapat dimuat" description={mapped.safeMessage} correlationId={mapped.correlationId} action={mapped.retryable ? <Button variant="secondary" onClick={retry}>Coba lagi</Button> : undefined} />; }
