import { fireEvent, render, screen } from "@testing-library/react";
import userEvent from "@testing-library/user-event";
import { beforeEach, describe, expect, it, vi } from "vitest";
import { AttendanceIssueToolbar } from "./attendance-issue-toolbar";

const navigation = vi.hoisted(() => ({ params: "", replace: vi.fn() }));
vi.mock("next/navigation", () => ({ usePathname: () => "/attendance/att-001", useRouter: () => ({ replace: navigation.replace }), useSearchParams: () => new URLSearchParams(navigation.params) }));

const base = "access=manage&tab=audit&issueSearch=lama&severity=Warning&issueSort=severity&issueDirection=desc&issuePage=3&issuePageSize=20";
const url = () => new URL(String(navigation.replace.mock.calls.at(-1)?.[0]), "https://esa.test");
const expectContext = (result: URL) => { expect(result.pathname).toBe("/attendance/att-001"); expect(result.searchParams.get("access")).toBe("manage"); expect(result.searchParams.get("tab")).toBe("audit"); for (const key of new Set(result.searchParams.keys())) expect(result.searchParams.getAll(key)).toHaveLength(1); };

beforeEach(() => { navigation.params = base; navigation.replace.mockReset(); });

describe("Attendance issue toolbar exact URLs", () => {
  it("normalizes search, removes empty search, resets page, and preserves context", () => { render(<AttendanceIssueToolbar page={3} hasNext />); const search = screen.getByLabelText("Cari issue"); fireEvent.change(search, { target: { value: " nik " } }); let result = url(); expectContext(result); expect(result.searchParams.get("issueSearch")).toBe("nik"); expect(result.searchParams.has("issuePage")).toBe(false); expect(result.searchParams.get("severity")).toBe("Warning"); expect(result.searchParams.get("issueSort")).toBe("severity"); expect(result.searchParams.get("issueDirection")).toBe("desc"); expect(result.searchParams.get("issuePageSize")).toBe("20"); fireEvent.change(search, { target: { value: "" } }); result = url(); expect(result.searchParams.has("issueSearch")).toBe(false); });
  it.each(["Error", "Warning", "Duplicate", ""])("writes supported severity %s canonically", async severity => { const actor = userEvent.setup(); render(<AttendanceIssueToolbar page={3} hasNext />); await actor.selectOptions(screen.getByLabelText("Severity issue"), severity); const result = url(); expectContext(result); expect(result.searchParams.get("severity")).toBe(severity || null); expect(result.searchParams.has("issuePage")).toBe(false); expect(result.searchParams.get("issueSearch")).toBe("lama"); });
  it.each(["rowNumber", "severity"])("writes sort %s and preserves all other context", async sort => { render(<AttendanceIssueToolbar page={3} hasNext />); await userEvent.selectOptions(screen.getByLabelText("Urutan issue"), sort); const result = url(); expectContext(result); expect(result.searchParams.get("issueSort")).toBe(sort); expect(result.searchParams.has("issuePage")).toBe(false); expect(result.searchParams.get("issueDirection")).toBe("desc"); expect(result.searchParams.get("issuePageSize")).toBe("20"); });
  it.each(["asc", "desc"])("writes direction %s and resets page", async direction => { render(<AttendanceIssueToolbar page={3} hasNext />); await userEvent.selectOptions(screen.getByLabelText("Arah urutan issue"), direction); const result = url(); expectContext(result); expect(result.searchParams.get("issueDirection")).toBe(direction); expect(result.searchParams.has("issuePage")).toBe(false); });
  it.each(["10", "20", "50"])("writes page size %s and resets page", async pageSize => { render(<AttendanceIssueToolbar page={3} hasNext />); await userEvent.selectOptions(screen.getByLabelText("Ukuran halaman issue"), pageSize); const result = url(); expectContext(result); expect(result.searchParams.get("issuePageSize")).toBe(pageSize); expect(result.searchParams.has("issuePage")).toBe(false); });
  it("canonicalizes invalid page size, direction, sort, and page to production defaults", async () => { navigation.params = "access=view&tab=audit&issuePageSize=-7&issueDirection=sideways&issueSort=unknown&issuePage=0"; render(<AttendanceIssueToolbar page={1} hasNext={false} />); expect(screen.getByLabelText("Ukuran halaman issue")).toHaveValue("20"); expect(screen.getByLabelText("Arah urutan issue")).toHaveValue("asc"); expect(screen.getByLabelText("Urutan issue")).toHaveValue("rowNumber"); await vi.waitFor(() => expect(navigation.replace).toHaveBeenCalledOnce()); const result = url(); expect(result.href).toBe("https://esa.test/attendance/att-001?access=view&tab=audit"); expect(screen.getByRole("button", { name: "Sebelumnya" })).toBeDisabled(); expect(screen.getByRole("button", { name: "Berikutnya" })).toBeDisabled(); });
  it("enforces middle-page pagination and retains every filter", async () => { const actor = userEvent.setup(); render(<AttendanceIssueToolbar page={3} hasNext />); await actor.click(screen.getByRole("button", { name: "Sebelumnya" })); let result = url(); expectContext(result); expect(result.searchParams.get("issuePage")).toBe("2"); expect(result.searchParams.get("issueSearch")).toBe("lama"); await actor.click(screen.getByRole("button", { name: "Berikutnya" })); result = url(); expect(result.searchParams.get("issuePage")).toBe("4"); });
  it("removes every issue parameter on reset without touching persona or domain context", async () => { render(<AttendanceIssueToolbar page={3} hasNext />); await userEvent.click(screen.getByRole("button", { name: "Reset filter" })); const result = url(); expectContext(result); for (const key of ["issueSearch", "severity", "issueSort", "issueDirection", "issuePage", "issuePageSize"]) expect(result.searchParams.has(key)).toBe(false); });
});
