import { render, screen } from "@testing-library/react";
import { expect, it, vi } from "vitest";
import { AppError } from "@/features/foundation/domain/errors";
import { AttendanceDetailPage } from "./attendance-detail-page";
const batch = { id: "att-001", projectId: "prj-019", projectLabel: "PRJ-019 · Managed Services", period: "2026-07", status: "Imported" as const, revisionNumber: 1, file: { originalFilename: "attendance.xlsx", displayFilename: "attendance.xlsx", mimeType: "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet", sizeBytes: 100 }, templateVersion: "pending-backend", mapping: [{ sourceColumn: "Identitas", targetField: "Identitas placeholder", required: true, status: "Ready" as const, exampleValue: "••••4821" }], summary: { totalRows: 1, validRows: 1, invalidRows: 0, duplicateRows: 0, warningRows: 0, commitEligibleRows: 1, blockingIssueCount: 0 }, duplicates: { withinFile: 0, priorBatch: 0, fileDuplicate: false, decision: "Allowed" as const, note: "Simulasi", simulated: true as const }, createdAt: "2026-08-11T09:00:00+07:00", importedAt: "2026-08-11T09:00:00+07:00", createdByUserId: "actor", correlationId: "corr", version: 2 };
vi.mock("next/navigation", () => ({ usePathname: () => "/attendance/att-001", useRouter: () => ({ replace: vi.fn() }), useSearchParams: () => new URLSearchParams("access=manage") }));
vi.mock("../permissions/demo-access", () => ({ useAttendanceAccess: () => ({ access: "manage", canView: true, canManage: true, actor: { userId: "actor", permissionKeys: ["attendance.import", "attendance.validate"] }, url: (path: string) => `${path}?access=manage` }) }));
vi.mock("../queries/hooks", () => ({ useAttendanceDetail: () => ({ data: { batch, revisions: [{ id: "rev-1", revisionNumber: 1, reason: "Import", actorUserId: "actor", createdAt: batch.createdAt, diffSummary: "Revision awal", status: "Imported" }], activity: [], readiness: { readyToValidate: true, readyToLock: false, blockers: [], nextAction: "Validasi seluruh batch." } }, isPending: false, isError: false, error: null, refetch: vi.fn() }), useAttendanceActivity: () => ({ data: undefined, isPending: false, isError: true, error: new AppError(503, "ACTIVITY_UNAVAILABLE", "Activity gagal.", {}, true, "corr-activity"), refetch: vi.fn() }), useAttendanceIssues: () => ({ data: { items: [{ id: "issue", rowNumber: 2, sourceColumn: "Identitas", safeValue: "••••4821", reason: "Aman untuk test", severity: "Warning", code: "DEMO" }], total: 1, page: 1, pageSize: 20, hasNextPage: false }, isPending: false, isError: false, error: null, refetch: vi.fn() }), useValidateAttendance: () => ({ mutateAsync: vi.fn(), isPending: false }), useRejectAttendance: () => ({ mutateAsync: vi.fn(), isPending: false }), useLockAttendance: () => ({ mutateAsync: vi.fn(), isPending: false }) }));
it("keeps authoritative Attendance detail visible when the isolated activity query fails", () => { render(<AttendanceDetailPage id="att-001" />); expect(screen.getByRole("heading", { name: /PRJ-019.*2026-07/ })).toBeVisible(); expect(screen.getByText("Imported")).toBeVisible(); expect(screen.getByText("attendance.xlsx")).toBeVisible(); expect(screen.getByRole("table", { name: "Mapping attendance" })).toBeVisible(); expect(screen.getByRole("table", { name: "Issue attendance" })).toBeVisible(); expect(screen.getAllByText("••••4821").length).toBeGreaterThan(0); expect(screen.getByText(/corr-activity/)).toBeVisible(); expect(screen.getByRole("button", { name: "Coba lagi activity" })).toBeVisible(); expect(screen.getByText("Revision awal")).toBeVisible(); });
