import { render, screen, waitFor } from "@testing-library/react";
import userEvent from "@testing-library/user-event";
import { beforeEach, describe, expect, it, vi } from "vitest";
import { AppError } from "@/features/foundation/domain/errors";
import { AttendanceCorrectionPage } from "./attendance-correction-page";

const state = vi.hoisted(() => ({ access: "manage" as "manage" | "view" | "none", detailMode: "ready" as "ready" | "loading" | "error", detailError: undefined as unknown, enabled: vi.fn(), preview: vi.fn(), correct: vi.fn(), push: vi.fn() }));
const batch = { id: "att-001", projectId: "prj-019", projectLabel: "PRJ-019 · Managed Services", period: "2026-07", status: "Imported" as const, revisionNumber: 2, file: { originalFilename: "source.xlsx", displayFilename: "source.xlsx", mimeType: "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet", sizeBytes: 100 }, templateVersion: "v1", mapping: [], summary: { totalRows: 1, validRows: 1, invalidRows: 0, duplicateRows: 0, warningRows: 0, commitEligibleRows: 1, blockingIssueCount: 0 }, duplicates: { withinFile: 0, priorBatch: 0, fileDuplicate: false, decision: "Allowed" as const, note: "demo", simulated: true as const }, createdAt: "2026-08-11T09:00:00+07:00", createdByUserId: "actor", correlationId: "corr", version: 7 };
const preview = { fingerprint: "preview-correction", mapping: [{ sourceColumn: "NIK", targetField: "employeeReference", required: true, status: "Ready" as const, exampleValue: "••••4821" }], summary: batch.summary, duplicates: batch.duplicates, readiness: { readyToValidate: true, readyToLock: false, blockers: [], nextAction: "Buat revision." }, correlationId: "corr-preview", simulated: true as const };
const file = new File(["demo"], "ready-correction.xlsx", { type: "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet", lastModified: 1 });

vi.mock("next/navigation", () => ({ useRouter: () => ({ push: state.push }), useSearchParams: () => new URLSearchParams(`access=${state.access}`) }));
vi.mock("../permissions/demo-access", () => ({ useAttendanceAccess: () => ({ access: state.access, canManage: state.access === "manage", actor: { userId: "actor", permissionKeys: ["attendance.import"] }, url: (path: string) => `${path}?access=${state.access}` }) }));
vi.mock("../queries/hooks", () => ({ useAttendanceDetail: (_id: string, enabled: boolean) => { state.enabled(enabled); if (state.detailMode === "loading") return { isPending: true, isError: false }; if (state.detailMode === "error") return { isPending: false, isError: true, error: state.detailError }; return { isPending: false, isError: false, data: { batch } }; }, usePreviewAttendance: () => ({ mutateAsync: state.preview, isPending: false }), useCorrectAttendance: () => ({ mutateAsync: state.correct, isPending: false }) }));

beforeEach(() => { state.access = "manage"; state.detailMode = "ready"; state.detailError = undefined; for (const mock of [state.enabled, state.preview, state.correct, state.push]) mock.mockReset(); state.preview.mockResolvedValue(preview); state.correct.mockResolvedValue({ batchId: "att-001", version: 8, message: "ok", correlationId: "corr-ok" }); });

describe("Attendance correction production acceptance", () => {
  it("requires a file with an accessible error and never starts either mutation", async () => { const actor = userEvent.setup(); render(<AttendanceCorrectionPage batchId="att-001" />); const region = screen.getByRole("button", { name: "Pilih file correction attendance" }); await actor.click(screen.getByRole("button", { name: "Buat preview correction" })); expect((await screen.findAllByRole("alert"))[0]).toHaveTextContent("File correction wajib dipilih"); expect(region).toHaveAttribute("aria-invalid", "true"); expect(region).toHaveAttribute("aria-describedby", "correction-help correction-error"); expect(screen.getByLabelText("file upload")).toBeInTheDocument(); expect(state.preview).not.toHaveBeenCalled(); expect(state.correct).not.toHaveBeenCalled(); });
  it.each([
    [new File([], "ready-empty.xlsx", { type: "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet" }), /kosong/i],
    [new File(["x"], "ready-source.csv", { type: "text/csv" }), /xlsx|extension/i],
    [new File(["x"], "ready-source.xlsx", { type: "text/csv" }), /MIME/i],
    [new File(["x"], "unsafe<name>.xlsx", { type: "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet" }), /nama file/i],
    [new File(["x"], `ready-${"a".repeat(250)}.xlsx`, { type: "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet" }), /nama file/i],
  ])("rejects invalid correction metadata without preview or correction", async (invalidFile, expected) => { const actor = userEvent.setup({ applyAccept: false }); render(<AttendanceCorrectionPage batchId="att-001" />); await actor.upload(screen.getByLabelText("file upload"), invalidFile); expect((await screen.findAllByText(expected))[0]).toBeVisible(); expect(screen.getByRole("button", { name: "Pilih file correction attendance" })).toHaveAttribute("aria-invalid", "true"); expect(state.preview).not.toHaveBeenCalled(); expect(state.correct).not.toHaveBeenCalled(); });
  it("removes the selected file and invalidates its preview", async () => { const actor = userEvent.setup(); render(<AttendanceCorrectionPage batchId="att-001" />); await actor.upload(screen.getByLabelText("file upload"), file); await actor.click(screen.getByRole("button", { name: "Buat preview correction" })); expect(await screen.findByRole("table", { name: "Mapping correction" })).toBeVisible(); await actor.click(screen.getByRole("button", { name: "Hapus file" })); expect(screen.queryByText("ready-correction.xlsx")).not.toBeInTheDocument(); expect(screen.queryByRole("table", { name: "Mapping correction" })).not.toBeInTheDocument(); expect(state.correct).not.toHaveBeenCalled(); });
  it("renders a structured correction conflict and explicit persona-preserving recovery URLs", async () => { state.correct.mockRejectedValueOnce(new AppError(409, "ATTENDANCE_VERSION_CONFLICT", "Versi berubah.", {}, false, "corr-correction-conflict", { userVersion: 7, latestVersion: 8, revision: 4, diffs: [{ field: "revision", label: "Revision", before: "3", after: "4" }, { field: "status", label: "Status", before: "Imported", after: "Validated" }, { field: "file", label: "File", before: "source.xlsx", after: "latest.xlsx" }] })); const actor = userEvent.setup(); render(<AttendanceCorrectionPage batchId="att-001" />); await actor.upload(screen.getByLabelText("file upload"), file); await actor.type(screen.getByLabelText("Alasan correction"), "alasan conflict"); await actor.click(screen.getByRole("button", { name: "Buat preview correction" })); await actor.click(await screen.findByRole("button", { name: "Buat revision correction" })); expect(await screen.findByLabelText("Perbandingan versi conflict")).toHaveTextContent("7"); expect(screen.getByLabelText("Perbandingan versi conflict")).toHaveTextContent("8"); expect(screen.getByRole("table", { name: "Perubahan aman sejak versi dikirim" })).toHaveTextContent("latest.xlsx"); expect(screen.getByText(/corr-correction-conflict/)).toBeVisible(); expect(screen.getByRole("link", { name: "Muat versi terbaru" })).toHaveAttribute("href", "/attendance/att-001?access=manage"); expect(screen.getByRole("link", { name: "Kembali tanpa menyimpan" })).toHaveAttribute("href", "/attendance?access=manage"); expect(state.correct).toHaveBeenCalledOnce(); expect(state.push).not.toHaveBeenCalled(); });
  it("suppresses source query for view/none direct routes", () => { state.access = "view"; const view = render(<AttendanceCorrectionPage batchId="att-001" />); expect(screen.getByText("Correction attendance tidak diizinkan")).toBeVisible(); expect(state.enabled).toHaveBeenLastCalledWith(false); view.unmount(); state.access = "none"; render(<AttendanceCorrectionPage batchId="att-001" />); expect(state.enabled).toHaveBeenLastCalledWith(false); });
  it("renders source loading and maps 404 without leaking the batch", () => { state.detailMode = "loading"; const loading = render(<AttendanceCorrectionPage batchId="att-001" />); expect(screen.getByLabelText("Memuat data")).toBeVisible(); loading.unmount(); state.detailMode = "error"; state.detailError = new AppError(404, "ATTENDANCE_NOT_FOUND", "Tidak ditemukan", {}, false, "corr-404"); render(<AttendanceCorrectionPage batchId="att-001" />); expect(screen.getByText("Belum ada data")).toBeVisible(); expect(screen.queryByText("source.xlsx")).not.toBeInTheDocument(); });
  it("previews metadata and commits a new Imported revision with actual source version", async () => { const actor = userEvent.setup(); render(<AttendanceCorrectionPage batchId="att-001" />); expect(screen.getByRole("heading", { name: "Buat revision dari R2" })).toBeVisible(); await actor.upload(screen.getByLabelText("file upload"), file); await actor.type(screen.getByLabelText("Alasan correction"), "perbaiki sumber"); await actor.click(screen.getByRole("button", { name: "Buat preview correction" })); expect(await screen.findByRole("table", { name: "Mapping correction" })).toBeVisible(); expect(screen.getByText(/Preview R2.*R3/)).toBeVisible(); expect(screen.getByText("••••4821")).toBeVisible(); await actor.click(screen.getByRole("button", { name: "Buat revision correction" })); await waitFor(() => expect(state.correct).toHaveBeenCalledOnce()); expect(state.correct.mock.calls[0]?.[0]).toMatchObject({ data: { batchId: "att-001", previewFingerprint: "preview-correction", scenario: "ready", file: { displayFilename: "ready-correction.xlsx" } }, reason: "perbaiki sumber", currentVersion: 7 }); expect(state.correct.mock.calls[0]?.[0].data.file).not.toBeInstanceOf(File); expect(state.push).toHaveBeenCalledWith("/attendance/att-001?access=manage"); });
  it("retains file, reason, and preview then retries correction 503 with an identical payload", async () => { state.correct.mockRejectedValueOnce(new AppError(503, "ATTENDANCE_UNAVAILABLE", "Gagal sementara.", {}, true, "corr-retry")); const actor = userEvent.setup(); render(<AttendanceCorrectionPage batchId="att-001" />); await actor.upload(screen.getByLabelText("file upload"), file); await actor.type(screen.getByLabelText("Alasan correction"), "alasan tetap"); await actor.click(screen.getByRole("button", { name: "Buat preview correction" })); await actor.click(await screen.findByRole("button", { name: "Buat revision correction" })); expect(await screen.findByText(/corr-retry/)).toBeVisible(); expect(screen.getByText("ready-correction.xlsx")).toBeVisible(); expect(screen.getByLabelText("Alasan correction")).toHaveValue("alasan tetap"); expect(screen.getByRole("table", { name: "Mapping correction" })).toBeVisible(); const first = state.correct.mock.calls[0]?.[0]; expect(state.push).not.toHaveBeenCalled(); await actor.click(screen.getByRole("button", { name: "Coba lagi" })); await waitFor(() => expect(state.correct).toHaveBeenCalledTimes(2)); expect(state.correct.mock.calls[1]?.[0]).toEqual(first); expect(state.push).toHaveBeenCalledWith("/attendance/att-001?access=manage"); });
  it("consumes correction cancellation without false error and retains the session", async () => { state.correct.mockRejectedValueOnce(new DOMException("cancelled", "AbortError")); const actor = userEvent.setup(); render(<AttendanceCorrectionPage batchId="att-001" />); await actor.upload(screen.getByLabelText("file upload"), file); await actor.type(screen.getByLabelText("Alasan correction"), "alasan cancel"); await actor.click(screen.getByRole("button", { name: "Buat preview correction" })); await actor.click(await screen.findByRole("button", { name: "Buat revision correction" })); await waitFor(() => expect(state.correct).toHaveBeenCalledOnce()); expect(screen.getByText("ready-correction.xlsx")).toBeVisible(); expect(screen.getByLabelText("Alasan correction")).toHaveValue("alasan cancel"); expect(screen.getByRole("table", { name: "Mapping correction" })).toBeVisible(); expect(screen.queryByText(/ID korelasi/)).not.toBeInTheDocument(); expect(screen.queryByRole("button", { name: "Coba lagi" })).not.toBeInTheDocument(); expect(state.push).not.toHaveBeenCalled(); });
  it("guards dirty navigation and preserves data when staying", async () => { const actor = userEvent.setup(); render(<AttendanceCorrectionPage batchId="att-001" />); await actor.type(screen.getByLabelText("Alasan correction"), "belum disimpan"); await actor.click(screen.getByRole("button", { name: "Kembali" })); expect(screen.getByRole("dialog", { name: "Perubahan belum disimpan" })).toBeVisible(); await actor.click(screen.getByRole("button", { name: "Tetap di halaman" })); expect(screen.getByLabelText("Alasan correction")).toHaveValue("belum disimpan"); expect(state.push).not.toHaveBeenCalled(); });
  it("installs one beforeunload guard while dirty and removes the same listener on unmount", async () => { const add = vi.spyOn(window, "addEventListener"), remove = vi.spyOn(window, "removeEventListener"), actor = userEvent.setup(), view = render(<AttendanceCorrectionPage batchId="att-001" />); await actor.type(screen.getByLabelText("Alasan correction"), "dirty guard"); const added = add.mock.calls.find(([type]) => type === "beforeunload"); expect(added).toBeDefined(); expect(add.mock.calls.filter(([type]) => type === "beforeunload")).toHaveLength(1); view.unmount(); const removed = remove.mock.calls.find(([type]) => type === "beforeunload"); expect(removed?.[1]).toBe(added?.[1]); add.mockRestore(); remove.mockRestore(); });
  it("cleans the correction guard when removing the only dirty file", async () => { const add = vi.spyOn(window, "addEventListener"), remove = vi.spyOn(window, "removeEventListener"), actor = userEvent.setup(); render(<AttendanceCorrectionPage batchId="att-001" />); await actor.upload(screen.getByLabelText("file upload"), file); const added = add.mock.calls.find(([type]) => type === "beforeunload"); await actor.click(screen.getByRole("button", { name: "Hapus file" })); await waitFor(() => expect(remove.mock.calls.find(([type]) => type === "beforeunload")?.[1]).toBe(added?.[1])); add.mockRestore(); remove.mockRestore(); });
});
