import { render, screen } from "@testing-library/react";
import userEvent from "@testing-library/user-event";
import { beforeEach, describe, expect, it, vi } from "vitest";
import { AppError } from "@/features/foundation/domain/errors";
import { AttendanceListPage } from "./attendance-list-page";

type Mode = "ready" | "loading" | "empty" | "error";
const state = vi.hoisted(() => ({
  access: "manage" as "manage" | "view" | "none",
  enabled: vi.fn(),
  mode: "ready" as Mode,
  error: undefined as unknown,
  params: "access=manage",
  page: 1,
  hasNextPage: false,
  replace: vi.fn(),
  refetch: vi.fn(),
}));
const batch = { id: "att-001", projectId: "prj-019", projectLabel: "PRJ-019 · Managed Services", period: "2026-07", status: "Imported" as const, revisionNumber: 2, mapping: [], summary: { totalRows: 12, validRows: 10, invalidRows: 2, duplicateRows: 0, warningRows: 0, commitEligibleRows: 10, blockingIssueCount: 2 }, duplicates: { withinFile: 0, priorBatch: 0, fileDuplicate: false, decision: "Allowed" as const, note: "demo", simulated: true as const }, createdAt: "2026-08-11T09:00:00+07:00", createdByUserId: "actor", correlationId: "corr", version: 2 };

vi.mock("next/navigation", () => ({ usePathname: () => "/attendance", useRouter: () => ({ replace: state.replace }), useSearchParams: () => new URLSearchParams(state.params) }));
vi.mock("../permissions/demo-access", () => ({ useAttendanceAccess: () => ({ access: state.access, canView: state.access !== "none", canManage: state.access === "manage", url: (path: string) => `${path}?access=${state.access}` }) }));
vi.mock("../queries/hooks", () => ({ useAttendanceList: (_query: unknown, enabled: boolean) => { state.enabled(enabled); if (state.mode === "loading") return { isPending: true, isError: false }; if (state.mode === "error") return { isPending: false, isError: true, error: state.error, refetch: state.refetch }; return { isPending: false, isError: false, data: { items: state.mode === "empty" ? [] : [batch], total: state.mode === "empty" ? 0 : 45, page: state.page, pageSize: 20, hasNextPage: state.hasNextPage }, refetch: state.refetch }; } }));

beforeEach(() => { state.access = "manage"; state.mode = "ready"; state.error = undefined; state.params = "access=manage"; state.page = 1; state.hasNextPage = false; state.enabled.mockReset(); state.replace.mockReset(); state.refetch.mockReset(); });

describe("Attendance list production acceptance", () => {
  it("isolates loading and authoritative empty states from sensitive rows", () => { state.mode = "loading"; const loading = render(<AttendanceListPage />); expect(screen.getByLabelText("Memuat data")).toBeVisible(); expect(screen.queryByText(batch.projectLabel)).not.toBeInTheDocument(); loading.unmount(); state.mode = "empty"; render(<AttendanceListPage />); expect(screen.getByText("Belum ada batch attendance")).toBeVisible(); expect(screen.getByText(/Halaman 0/)).toBeVisible(); });
  it("shows retry only for retryable errors and never exposes raw internals", async () => { state.mode = "error"; state.error = new AppError(503, "ATTENDANCE_UNAVAILABLE", "Tidak dapat memuat attendance.", {}, true, "corr-list"); const retryable = render(<AttendanceListPage />); expect(screen.getByText(/corr-list/)).toBeVisible(); await userEvent.click(screen.getByRole("button", { name: "Coba lagi" })); expect(state.refetch).toHaveBeenCalledOnce(); retryable.unmount(); state.error = new AppError(500, "ATTENDANCE_FAILED", "Tidak dapat memuat attendance.", {}, false, "corr-final"); const final = render(<AttendanceListPage />); expect(screen.queryByRole("button", { name: "Coba lagi" })).not.toBeInTheDocument(); final.unmount(); state.error = new Error("database password secret"); render(<AttendanceListPage />); expect(screen.queryByText(/database password secret/)).not.toBeInTheDocument(); });
  it("enforces manage, view, and none persona presentation and query suppression", () => { const manage = render(<AttendanceListPage />); expect(screen.getByRole("link", { name: "Import attendance" })).toHaveAttribute("href", "/attendance/import?access=manage"); manage.unmount(); state.access = "view"; state.params = "access=view"; const view = render(<AttendanceListPage />); expect(screen.queryByRole("link", { name: "Import attendance" })).not.toBeInTheDocument(); expect(screen.getByRole("link", { name: "Buka" })).toHaveAttribute("href", "/attendance/att-001?access=view"); view.unmount(); state.access = "none"; state.params = "access=none"; render(<AttendanceListPage />); expect(screen.getByText("Akses attendance ditolak")).toBeVisible(); expect(state.enabled).toHaveBeenLastCalledWith(false); expect(screen.queryByText(batch.projectLabel)).not.toBeInTheDocument(); });
  it("renders equivalent desktop and mobile essentials without per-row detail queries", () => { render(<AttendanceListPage />); expect(screen.getByRole("table", { name: "Daftar batch attendance" })).toBeVisible(); expect(screen.getAllByText(batch.projectLabel)).toHaveLength(2); expect(screen.getAllByText("Imported").length).toBeGreaterThanOrEqual(2); expect(screen.getByText("R2")).toBeVisible(); expect(screen.getByText(/10 valid/)).toBeVisible(); expect(state.enabled).toHaveBeenCalledTimes(1); });
  it("preserves persona while changing normalized filters, sort, page size, and pagination boundaries", async () => { const actor = userEvent.setup(); render(<AttendanceListPage />); await actor.type(screen.getByLabelText("Cari batch"), " managed "); expect(state.replace).toHaveBeenLastCalledWith(expect.stringContaining("search=managed"), { scroll: false }); expect(state.replace.mock.calls.at(-1)?.[0]).not.toContain("page="); await actor.selectOptions(screen.getByLabelText("Status batch"), "Imported"); expect(state.replace).toHaveBeenLastCalledWith(expect.stringContaining("status=Imported"), { scroll: false }); await actor.selectOptions(screen.getByLabelText("Urutkan batch"), "period"); expect(state.replace).toHaveBeenLastCalledWith(expect.stringContaining("sort=period"), { scroll: false }); await actor.selectOptions(screen.getByLabelText("Arah urutan batch"), "asc"); expect(state.replace).toHaveBeenLastCalledWith(expect.stringContaining("direction=asc"), { scroll: false }); await actor.selectOptions(screen.getByLabelText("Ukuran halaman"), "50"); expect(state.replace).toHaveBeenLastCalledWith(expect.stringContaining("pageSize=50"), { scroll: false }); expect(state.replace.mock.calls.at(-1)?.[0]).toContain("access=manage"); expect(screen.getByRole("button", { name: "Sebelumnya" })).toBeDisabled(); expect(screen.getByRole("button", { name: "Berikutnya" })).toBeDisabled(); });
  it("offers an observable reset for zero filtered results", async () => { state.mode = "empty"; state.params = "access=manage&search=missing&page=4&sort=period&direction=asc"; render(<AttendanceListPage />); expect(screen.getByText("Tidak ada hasil")).toBeVisible(); await userEvent.click(screen.getAllByRole("button", { name: "Reset filter" }).at(-1)!); expect(state.replace).toHaveBeenCalledWith("/attendance?access=manage", { scroll: false }); });
  it("clicks Next and preserves the complete normalized list state", async () => { state.params = "access=manage&search=managed&status=Imported&sort=period&direction=asc&page=2&pageSize=50"; state.page = 2; state.hasNextPage = true; render(<AttendanceListPage />); await userEvent.click(screen.getByRole("button", { name: "Berikutnya" })); expect(state.replace).toHaveBeenCalledWith("/attendance?access=manage&search=managed&status=Imported&sort=period&direction=asc&page=3&pageSize=50", { scroll: false }); });
  it("clicks Previous and preserves filters while normalizing invalid page inputs", async () => { state.params = "access=view&search=managed&status=Validated&sort=status&direction=desc&page=3&pageSize=10"; state.access = "view"; state.page = 3; render(<AttendanceListPage />); await userEvent.click(screen.getByRole("button", { name: "Sebelumnya" })); expect(state.replace).toHaveBeenCalledWith("/attendance?access=view&search=managed&status=Validated&sort=status&direction=desc&page=2&pageSize=10", { scroll: false }); });
});
