import { render, screen, waitFor } from "@testing-library/react";
import userEvent from "@testing-library/user-event";
import { beforeEach, describe, expect, it, vi } from "vitest";
import { AppError } from "@/features/foundation/domain/errors";
import type { AttendanceStatus } from "../domain/types";
import { AttendanceDetailPage } from "./attendance-detail-page";

const state = vi.hoisted(() => ({ access: "manage" as "manage" | "view" | "none", status: "Imported" as AttendanceStatus, params: "access=manage", issueMode: "events" as "events" | "loading" | "empty" | "forbidden" | "retryable" | "fatal" | "cancelled", activityMode: "events" as "events" | "loading" | "empty" | "forbidden" | "retryable" | "fatal" | "cancelled", replace: vi.fn(), detailEnabled: vi.fn(), issuesEnabled: vi.fn(), activityEnabled: vi.fn(), validate: vi.fn(), reject: vi.fn(), lock: vi.fn(), retryIssue: vi.fn(), retryActivity: vi.fn() }));
const summary = { totalRows: 4, validRows: 4, invalidRows: 0, duplicateRows: 0, warningRows: 0, commitEligibleRows: 4, blockingIssueCount: 0 };
const issue = { id: "issue-1", rowNumber: 7, sourceColumn: "NIK", safeValue: "••••4821", reason: "Format perlu diperiksa", severity: "Warning" as const, code: "ATTENDANCE_VALUE", suggestedAction: "Periksa sumber" };
const activity = { id: "activity-1", action: "attendance.imported", actorUserId: "user-fallback", actorName: "Rani Finance", occurredAt: "2026-08-11T09:00:00+07:00", reason: "Import awal", correlationId: "corr-activity", summary: "Empat row diimpor" };
const response = { batchId: "att-001", version: 6, message: "Attendance diperbarui", correlationId: "corr-success" };

vi.mock("next/navigation", () => ({ usePathname: () => "/attendance/att-001", useRouter: () => ({ replace: state.replace }), useSearchParams: () => new URLSearchParams(state.params) }));
vi.mock("../permissions/demo-access", () => ({ useAttendanceAccess: () => ({ access: state.access, canView: state.access !== "none", canManage: state.access === "manage", actor: { userId: "actor", permissionKeys: state.access === "manage" ? ["attendance.validate", "attendance.lock", "attendance.reject"] : ["attendance.view"] }, url: (path: string, extra?: URLSearchParams) => { const params = new URLSearchParams(extra); params.set("access", state.access); return `${path}?${params.toString()}`; } }) }));
vi.mock("../queries/hooks", () => ({
  useAttendanceDetail: (_id: string, enabled: boolean) => { state.detailEnabled(enabled); const batch = { id: "att-001", projectId: "prj-019", projectLabel: "PRJ-019 · Managed Services", period: "2026-07", status: state.status, revisionNumber: 3, file: { originalFilename: "source.xlsx", displayFilename: "source.xlsx", mimeType: "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet", sizeBytes: 100 }, templateVersion: "v1", mapping: [{ sourceColumn: "NIK", targetField: "employeeReference", required: true, status: "Ready", exampleValue: "••••4821" }], summary, duplicates: { withinFile: 0, priorBatch: 0, fileDuplicate: false, decision: "Allowed", note: "Tidak ada duplicate", simulated: true }, createdAt: "2026-08-11T09:00:00+07:00", createdByUserId: "actor", correlationId: "corr", version: 5 }; return { data: { batch, revisions: [{ id: "rev-3", revisionNumber: 3, reason: "Correction", actorUserId: "actor", createdAt: batch.createdAt, diffSummary: "File metadata berubah", status: state.status }], activity: [], readiness: { readyToValidate: state.status === "Imported", readyToLock: state.status === "Validated", blockers: [], nextAction: state.status === "Locked" ? "Batch immutable." : "Lanjutkan review." } }, isPending: false, isError: false, error: null, refetch: vi.fn() }; },
  useAttendanceIssues: (_id: string, _query: unknown, enabled: boolean) => { state.issuesEnabled(enabled); if (state.issueMode === "loading") return { data: undefined, isPending: true, isError: false, refetch: state.retryIssue }; if (state.issueMode === "forbidden") return { data: undefined, isPending: false, isError: true, error: new AppError(403, "ATTENDANCE_ISSUES_FORBIDDEN", "Akses ditolak.", {}, false, "corr-issue-403"), refetch: state.retryIssue }; if (state.issueMode === "retryable") return { data: undefined, isPending: false, isError: true, error: new AppError(503, "ATTENDANCE_ISSUES_UNAVAILABLE", "Issue sementara gagal.", {}, true, "corr-issue-503"), refetch: state.retryIssue }; if (state.issueMode === "fatal") return { data: undefined, isPending: false, isError: true, error: new AppError(422, "ATTENDANCE_ISSUES_FAILED", "Pesan aman.", {}, false, "corr-issue-422"), refetch: state.retryIssue }; return { data: { items: state.issueMode === "empty" ? [] : [issue], total: state.issueMode === "empty" ? 0 : 1, page: Math.max(1, Number(new URLSearchParams(state.params).get("issuePage") || 1)), pageSize: 20, hasNextPage: state.params.includes("hasNext=true") }, isPending: false, isError: false, error: null, refetch: state.retryIssue }; },
  useAttendanceActivity: (_id: string, enabled: boolean) => { state.activityEnabled(enabled); if (state.activityMode === "loading") return { data: undefined, isPending: true, isError: false, refetch: state.retryActivity }; if (state.activityMode === "forbidden") return { data: undefined, isPending: false, isError: true, error: new AppError(403, "ATTENDANCE_ACTIVITY_FORBIDDEN", "Akses ditolak.", {}, false, "corr-activity-403"), refetch: state.retryActivity }; if (state.activityMode === "retryable") return { data: undefined, isPending: false, isError: true, error: new AppError(503, "ATTENDANCE_ACTIVITY_UNAVAILABLE", "Activity sementara gagal.", {}, true, "corr-activity-503"), refetch: state.retryActivity }; if (state.activityMode === "fatal") return { data: undefined, isPending: false, isError: true, error: new AppError(422, "ATTENDANCE_ACTIVITY_FAILED", "Pesan aman.", {}, false, "corr-activity-422"), refetch: state.retryActivity }; const fallback = { ...activity, id: "activity-2", actorName: undefined, actorUserId: "user-id-fallback", action: "attendance.reviewed", correlationId: "corr-fallback" }; return { data: state.activityMode === "empty" ? [] : [activity, fallback], isPending: false, isError: false, error: null, refetch: state.retryActivity }; },
  useValidateAttendance: () => ({ mutateAsync: state.validate, isPending: false }), useRejectAttendance: () => ({ mutateAsync: state.reject, isPending: false }), useLockAttendance: () => ({ mutateAsync: state.lock, isPending: false }),
}));

beforeEach(() => { state.access = "manage"; state.status = "Imported"; state.params = "access=manage"; state.issueMode = "events"; state.activityMode = "events"; for (const mock of [state.replace, state.detailEnabled, state.issuesEnabled, state.activityEnabled, state.validate, state.reject, state.lock, state.retryIssue, state.retryActivity]) mock.mockReset(); state.validate.mockResolvedValue(response); state.reject.mockResolvedValue(response); state.lock.mockResolvedValue(response); });
async function confirm(actionName: string, reason: string) { const actor = userEvent.setup(); await actor.click(screen.getByRole("button", { name: actionName })); await actor.type(screen.getByLabelText("Alasan / attestation"), reason); await actor.click(screen.getByRole("button", { name: "Konfirmasi" })); }

describe("Attendance lifecycle production acceptance", () => {
  it("submits Validate with CommitAll, actual version, reason, and actor", async () => { render(<AttendanceDetailPage id="att-001" />); await confirm("Validasi batch", "validasi final"); await waitFor(() => expect(state.validate).toHaveBeenCalledOnce()); expect(state.validate.mock.calls[0]?.[0]).toMatchObject({ data: { batchId: "att-001", commitDecision: "CommitAll" }, reason: "validasi final", currentVersion: 5, actor: { userId: "actor" } }); expect(screen.getByText(/corr-success/)).toBeVisible(); expect(screen.queryByRole("dialog")).not.toBeInTheDocument(); });
  it.each(["Imported", "Validated"] as const)("submits Reject from %s with actual version", async status => { state.status = status; render(<AttendanceDetailPage id="att-001" />); await confirm("Tolak", "alasan penolakan"); expect(state.reject).toHaveBeenCalledWith(expect.objectContaining({ data: { batchId: "att-001" }, reason: "alasan penolakan", currentVersion: 5 })); });
  it("offers Lock only for Validated and submits attestation", async () => { state.status = "Validated"; render(<AttendanceDetailPage id="att-001" />); expect(screen.queryByRole("button", { name: "Validasi batch" })).not.toBeInTheDocument(); await confirm("Kunci batch", "attestation lengkap"); expect(state.lock).toHaveBeenCalledWith(expect.objectContaining({ data: { batchId: "att-001" }, reason: "attestation lengkap", currentVersion: 5 })); });
  it("renders structured conflict recovery without force overwrite or automatic retry", async () => { state.validate.mockRejectedValueOnce(new AppError(409, "ATTENDANCE_VERSION_CONFLICT", "Versi berubah.", {}, false, "corr-conflict")); render(<AttendanceDetailPage id="att-001" />); await confirm("Validasi batch", "validasi konflik"); expect(await screen.findByText(/corr-conflict/)).toBeVisible(); expect(screen.getByRole("link", { name: "Muat versi terbaru" })).toHaveAttribute("href", "/attendance/att-001?access=manage"); expect(screen.getByRole("link", { name: "Kembali tanpa menyimpan" })).toHaveAttribute("href", "/attendance?access=manage"); expect(screen.queryByText(/force overwrite/i)).not.toBeInTheDocument(); expect(state.validate).toHaveBeenCalledOnce(); });
  it.each(["reject", "lock"] as const)("renders structured %s conflict with retained input and explicit recovery", async kind => { state.status = kind === "lock" ? "Validated" : "Imported"; const mutation = kind === "lock" ? state.lock : state.reject, target = kind === "lock" ? "Locked" : "Rejected", current = state.status; mutation.mockRejectedValueOnce(new AppError(409, "ATTENDANCE_VERSION_CONFLICT", "Batch telah berubah.", {}, false, `corr-${kind}-conflict`, { userVersion: 5, latestVersion: 6, revision: 4, diffs: [{ field: "status", label: "Status", before: current, after: target }] })); render(<AttendanceDetailPage id="att-001" />); await confirm(kind === "lock" ? "Kunci batch" : "Tolak", `alasan ${kind} tetap`); expect(await screen.findByRole("heading", { name: kind === "lock" ? "Conflict saat mengunci batch" : "Conflict saat menolak batch" })).toBeVisible(); expect(screen.getByText(/Batch att-001 telah berubah/)).toBeVisible(); expect(screen.getByLabelText("Perbandingan versi conflict")).toHaveTextContent("Versi dikirim5Versi terbaru6Revision terbaru4"); expect(screen.getByRole("table", { name: "Perubahan aman sejak versi dikirim" })).toHaveTextContent(`Status${current}${target}`); expect(screen.getByText(new RegExp(`corr-${kind}-conflict`))).toBeVisible(); expect(screen.getByRole("link", { name: "Muat versi terbaru" })).toHaveAttribute("href", "/attendance/att-001?access=manage"); expect(screen.getByRole("link", { name: "Kembali tanpa menyimpan" })).toHaveAttribute("href", "/attendance?access=manage"); expect(screen.getByRole("dialog")).toBeVisible(); expect(screen.getByLabelText("Alasan / attestation")).toHaveValue(`alasan ${kind} tetap`); expect(screen.queryByText(/force overwrite/i)).not.toBeInTheDocument(); expect(screen.queryByText(/corr-success/)).not.toBeInTheDocument(); expect(mutation).toHaveBeenCalledOnce(); });
  it("keeps issue and activity semantics local and preserves persona in issue URL changes", async () => { const actor = userEvent.setup(); render(<AttendanceDetailPage id="att-001" />); expect(screen.getByRole("table", { name: "Issue attendance" })).toBeVisible(); expect(screen.getAllByText("••••4821").length).toBeGreaterThan(0); expect(screen.getByText("Periksa sumber")).toBeVisible(); expect(screen.getByText(/Rani Finance/)).toBeVisible(); expect(screen.getByText(/corr-activity/)).toBeVisible(); await actor.selectOptions(screen.getByLabelText("Severity issue"), "Warning"); expect(state.replace).toHaveBeenCalledWith(expect.stringContaining("severity=Warning"), { scroll: false }); expect(state.replace.mock.calls[0]?.[0]).toContain("access=manage"); });
  it("makes Locked and view personas read-only and suppresses all queries for none", () => { state.status = "Locked"; const locked = render(<AttendanceDetailPage id="att-001" />); expect(screen.getByText("Batch immutable.")).toBeVisible(); expect(screen.queryByRole("button", { name: /Validasi|Kunci|Tolak/ })).not.toBeInTheDocument(); locked.unmount(); state.access = "view"; state.params = "access=view"; const view = render(<AttendanceDetailPage id="att-001" />); expect(screen.queryByRole("button", { name: /Validasi|Kunci|Tolak/ })).not.toBeInTheDocument(); view.unmount(); state.access = "none"; state.params = "access=none"; render(<AttendanceDetailPage id="att-001" />); expect(screen.getByText("Akses attendance ditolak")).toBeVisible(); expect(state.detailEnabled).toHaveBeenLastCalledWith(false); expect(state.issuesEnabled).toHaveBeenLastCalledWith(false); expect(state.activityEnabled).toHaveBeenLastCalledWith(false); expect(screen.queryByText("source.xlsx")).not.toBeInTheDocument(); });
  it.each([
    ["validate", "Imported", "Validasi batch"], ["reject", "Imported", "Tolak"], ["lock", "Validated", "Kunci batch"],
  ] as const)("retries %s 503 manually with identical payload", async (kind, status, label) => { state.status = status; const mutation = kind === "validate" ? state.validate : kind === "reject" ? state.reject : state.lock; mutation.mockRejectedValueOnce(new AppError(503, "ATTENDANCE_UNAVAILABLE", "Sementara gagal.", {}, true, `corr-${kind}-503`)); render(<AttendanceDetailPage id="att-001" />); await confirm(label, `alasan ${kind}`); expect(await screen.findByText(new RegExp(`corr-${kind}-503`))).toBeVisible(); const first = mutation.mock.calls[0]?.[0]; expect(screen.queryByText(/corr-success/)).not.toBeInTheDocument(); await userEvent.click(screen.getByRole("button", { name: "Coba lagi" })); await waitFor(() => expect(mutation).toHaveBeenCalledTimes(2)); expect(mutation.mock.calls[1]?.[0]).toEqual(first); expect(screen.getByText(/corr-success/)).toBeVisible(); });
  it.each([
    ["validate", "Imported", "Validasi batch"], ["reject", "Imported", "Tolak"], ["lock", "Validated", "Kunci batch"],
  ] as const)("consumes %s cancellation with modal reason retained", async (kind, status, label) => { state.status = status; const mutation = kind === "validate" ? state.validate : kind === "reject" ? state.reject : state.lock; mutation.mockRejectedValueOnce(new DOMException("cancelled", "AbortError")); render(<AttendanceDetailPage id="att-001" />); await confirm(label, `alasan ${kind}`); await waitFor(() => expect(mutation).toHaveBeenCalledOnce()); expect(screen.getByRole("dialog")).toBeVisible(); expect(screen.getByLabelText("Alasan / attestation")).toHaveValue(`alasan ${kind}`); expect(screen.queryByText(/ID korelasi|corr-success/)).not.toBeInTheDocument(); expect(screen.queryByRole("button", { name: "Coba lagi" })).not.toBeInTheDocument(); });
  it.each([
    ["validate", "Imported", "Validasi batch", 422], ["reject", "Imported", "Tolak", 403], ["lock", "Validated", "Kunci batch", 422],
  ] as const)("renders non-retryable %s status %s safely", async (kind, status, label, errorStatus) => { state.status = status; const mutation = kind === "validate" ? state.validate : kind === "reject" ? state.reject : state.lock; mutation.mockRejectedValueOnce(new AppError(errorStatus, `ATTENDANCE_${kind.toUpperCase()}_FAILED`, "Tindakan tidak diizinkan.", {}, false, `corr-${kind}-${errorStatus}`)); render(<AttendanceDetailPage id="att-001" />); await confirm(label, `alasan ${kind}`); expect(await screen.findByText(new RegExp(`corr-${kind}-${errorStatus}`))).toBeVisible(); expect(screen.queryByRole("button", { name: "Coba lagi" })).not.toBeInTheDocument(); expect(screen.queryByText(/corr-success/)).not.toBeInTheDocument(); expect(mutation).toHaveBeenCalledOnce(); });
  it.each(["loading", "empty", "forbidden", "retryable", "fatal", "cancelled"] as const)("isolates issue %s state while retaining main detail", async mode => { state.issueMode = mode; render(<AttendanceDetailPage id="att-001" />); expect(screen.getByRole("heading", { name: /PRJ-019.*2026-07/ })).toBeVisible(); expect(screen.getByRole("table", { name: "Mapping attendance" })).toBeVisible(); if (mode === "empty") expect(screen.getByText("Tidak ada issue")).toBeVisible(); if (mode === "forbidden") { expect(screen.getByText(/corr-issue-403/)).toBeVisible(); expect(screen.queryByRole("button", { name: "Coba lagi issue" })).not.toBeInTheDocument(); } if (mode === "retryable") { await userEvent.click(screen.getByRole("button", { name: "Coba lagi issue" })); expect(state.retryIssue).toHaveBeenCalledOnce(); } if (mode === "fatal") expect(screen.queryByRole("button", { name: "Coba lagi issue" })).not.toBeInTheDocument(); if (mode === "cancelled") { expect(screen.getByRole("table", { name: "Issue attendance" })).toBeVisible(); expect(screen.queryByText(/server error/i)).not.toBeInTheDocument(); } });
  it("resets only issue URL parameters and preserves persona plus non-issue context", async () => { state.issueMode = "empty"; state.params = "access=manage&tab=audit&issueSearch=nik&severity=Warning&issueSort=severity&issueDirection=desc&issuePage=3&issuePageSize=50"; render(<AttendanceDetailPage id="att-001" />); expect(screen.getByText("Tidak ada issue")).toBeVisible(); expect(screen.getByRole("button", { name: "Reset filter" })).toBeVisible(); await userEvent.click(screen.getByRole("button", { name: "Reset filter" })); expect(state.replace).toHaveBeenCalledWith("/attendance/att-001?access=manage&tab=audit", { scroll: false }); });
  it("writes issue direction, page size, next and previous while preserving URL context", async () => { state.params = "access=manage&tab=audit&issueSearch=nik&severity=Warning&issueSort=rowNumber&issueDirection=asc&issuePage=2&issuePageSize=20&hasNext=true"; const actor = userEvent.setup(); render(<AttendanceDetailPage id="att-001" />); await actor.selectOptions(screen.getByLabelText("Arah urutan issue"), "desc"); expect(state.replace).toHaveBeenLastCalledWith(expect.stringContaining("issueDirection=desc"), { scroll: false }); await actor.selectOptions(screen.getByLabelText("Ukuran halaman issue"), "50"); expect(state.replace).toHaveBeenLastCalledWith(expect.stringContaining("issuePageSize=50"), { scroll: false }); await actor.click(screen.getByRole("button", { name: "Berikutnya" })); expect(state.replace).toHaveBeenLastCalledWith(expect.stringContaining("issuePage=3"), { scroll: false }); await actor.click(screen.getByRole("button", { name: "Sebelumnya" })); expect(state.replace).toHaveBeenLastCalledWith(expect.stringContaining("issuePage=1"), { scroll: false }); expect(String(state.replace.mock.calls.at(-1)?.[0])).toContain("access=manage"); });
  it.each(["loading", "empty", "forbidden", "retryable", "fatal", "cancelled"] as const)("isolates activity %s state and exposes actor ID fallback", async mode => { state.activityMode = mode; render(<AttendanceDetailPage id="att-001" />); expect(screen.getByRole("heading", { name: /PRJ-019.*2026-07/ })).toBeVisible(); expect(screen.getByRole("table", { name: "Issue attendance" })).toBeVisible(); if (mode === "empty") expect(screen.getByText("Belum ada activity")).toBeVisible(); if (mode === "forbidden") { expect(screen.getByText(/corr-activity-403/)).toBeVisible(); expect(screen.queryByRole("button", { name: "Coba lagi activity" })).not.toBeInTheDocument(); } if (mode === "retryable") { await userEvent.click(screen.getByRole("button", { name: "Coba lagi activity" })); expect(state.retryActivity).toHaveBeenCalledOnce(); } if (mode === "fatal") expect(screen.queryByRole("button", { name: "Coba lagi activity" })).not.toBeInTheDocument(); if (mode === "cancelled") { expect(screen.getByText(/user-id-fallback/)).toBeVisible(); expect(screen.getByText(/corr-fallback/)).toBeVisible(); expect(screen.queryByText(/server error/i)).not.toBeInTheDocument(); } });
});
