import { render, screen, waitFor } from "@testing-library/react";
import userEvent from "@testing-library/user-event";
import { beforeEach, describe, expect, it, vi } from "vitest";
import { NewAttendanceImportPage } from "./attendance-import-page";

const state = vi.hoisted(() => ({ preview: vi.fn(), atomic: vi.fn(), push: vi.fn() }));
vi.mock("next/navigation", () => ({ useRouter: () => ({ push: state.push }), useSearchParams: () => new URLSearchParams("access=manage") }));
vi.mock("../permissions/demo-access", () => ({ useAttendanceAccess: () => ({ access: "manage", canView: true, canManage: true, actor: { userId: "actor", permissionKeys: ["attendance.import"] }, url: (path: string) => `${path}?access=manage` }) }));
vi.mock("@/features/foundation/queries/hooks", () => ({ useProjectsQuery: () => ({ data: { items: [{ id: "prj-019", code: "PRJ-019", name: "Managed Services", status: "Active" }], total: 1, page: 1, pageSize: 50, hasNextPage: false }, isPending: false, isError: false, error: null, refetch: vi.fn() }) }));
vi.mock("../queries/hooks", () => ({ useAttendanceTemplate: () => ({ data: { available: false, version: "pending", label: "Template", reason: "Binary belum tersedia." }, isPending: false, isError: false, error: null, refetch: vi.fn() }), usePreviewAttendance: () => ({ mutateAsync: state.preview, isPending: false }), useCreateAndImportAttendance: () => ({ mutateAsync: state.atomic, isPending: false }) }));

beforeEach(() => { state.preview.mockReset(); state.atomic.mockReset(); state.push.mockReset(); });
async function initialize(actor: ReturnType<typeof userEvent.setup>) { await actor.selectOptions(screen.getByLabelText("Project"), "prj-019"); await actor.type(screen.getByLabelText("Periode"), "2026-08"); }
function oversizedFile() { const file = new File(["x"], "oversize.xlsx", { type: "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet" }); Object.defineProperty(file, "size", { value: 5_000_001 }); return file; }

describe("Attendance import file validation matrix", () => {
  it("maps missing file to the accessible file region and focuses the error summary", async () => { const actor = userEvent.setup(); const { container } = render(<NewAttendanceImportPage />); await initialize(actor); await actor.click(screen.getByRole("button", { name: "Buat mapping preview" })); expect((await screen.findAllByText("File wajib dipilih.")).length).toBeGreaterThan(0); const dropzone = screen.getByRole("button", { name: "Pilih atau letakkan file attendance" }); expect(dropzone).toHaveAttribute("aria-invalid", "true"); expect(dropzone).toHaveAttribute("aria-describedby", "attendance-file-help attendance-file-error"); expect(dropzone).toHaveAttribute("tabindex", "0"); await waitFor(() => expect(container.querySelector(".form-error-summary")).toHaveFocus()); expect(state.preview).not.toHaveBeenCalled(); expect(state.atomic).not.toHaveBeenCalled(); });
  it.each([
    ["empty", new File([], "empty.xlsx", { type: "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet" }), /File kosong/],
    ["extension", new File(["x"], "attendance.csv", { type: "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet" }), /Ekstensi file harus/],
    ["MIME", new File(["x"], "attendance.xlsx", { type: "text/csv" }), /MIME file tidak didukung/],
    ["oversize", oversizedFile(), /Ukuran file melebihi/],
    ["unsafe name", new File(["x"], "attendance?.xlsx", { type: "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet" }), /karakter yang tidak aman/],
    ["control character", new File(["x"], "attendance\u0001.xlsx", { type: "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet" }), /karakter yang tidak aman/],
    ["long name", new File(["x"], `${"a".repeat(121)}.xlsx`, { type: "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet" }), /Nama file terlalu panjang/],
  ])("rejects %s in production DOM/ARIA without preview", async (_label, file, message) => { const actor = userEvent.setup(); render(<NewAttendanceImportPage />); await initialize(actor); await actor.upload(screen.getByLabelText("file upload"), file); expect((await screen.findAllByText(message)).length).toBeGreaterThan(0); expect(screen.getByRole("button", { name: "Pilih atau letakkan file attendance" })).toHaveAttribute("aria-invalid", "true"); await actor.click(screen.getByRole("button", { name: "Buat mapping preview" })); expect(state.preview).not.toHaveBeenCalled(); expect(state.atomic).not.toHaveBeenCalled(); });
  it("keeps a valid native File in session but sends metadata only", async () => { const actor = userEvent.setup(), file = new File(["safe"], "ready-attendance.xlsx", { type: "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet", lastModified: 4 }); state.preview.mockResolvedValue({ fingerprint: "preview", mapping: [], summary: { totalRows: 1, validRows: 1, invalidRows: 0, duplicateRows: 0, warningRows: 0, commitEligibleRows: 1, blockingIssueCount: 0 }, duplicates: { withinFile: 0, priorBatch: 0, fileDuplicate: false, decision: "Allowed", note: "demo", simulated: true }, readiness: { readyToValidate: true, readyToLock: false, blockers: [], nextAction: "Commit" }, correlationId: "corr", simulated: true }); render(<NewAttendanceImportPage />); await initialize(actor); await actor.upload(screen.getByLabelText("file upload"), file); expect(screen.getByText("ready-attendance.xlsx")).toBeVisible(); await actor.click(screen.getByRole("button", { name: "Buat mapping preview" })); await waitFor(() => expect(state.preview).toHaveBeenCalledOnce()); const metadata = state.preview.mock.calls[0]?.[0].data.file; expect(metadata).toMatchObject({ originalFilename: "ready-attendance.xlsx", sizeBytes: 4, lastModified: 4 }); expect(metadata).not.toBeInstanceOf(File); expect(JSON.stringify(metadata)).not.toMatch(/base64|ArrayBuffer|Blob/); });
});
