"use client";
import Link from "next/link";
import { zodResolver } from "@hookform/resolvers/zod";
import { useRouter } from "next/navigation";
import { useEffect, useRef, useState } from "react";
import { useDropzone } from "react-dropzone";
import { useForm } from "react-hook-form";
import { z } from "zod";
import { Alert, Badge, Button, Card, CardHeader, DataState, Input, LoadingState, Modal, PageHeader, TableShell } from "@/components/ui";
import { isRequestCancellation } from "@/features/foundation/domain/errors";
import { useProjectsQuery } from "@/features/foundation/queries/hooks";
import { DEMO_FILE_POLICY, validateFileMetadata } from "../domain/logic";
import { mapAttendanceMutationError, type AttendanceMutationErrorView } from "../domain/mutation-error";
import type { AttendanceFileMetadata, AttendanceImportPreview, AttendanceSessionFile } from "../domain/types";
import { useAttendanceAccess } from "../permissions/demo-access";
import { useAttendanceTemplate, useCreateAndImportAttendance, usePreviewAttendance } from "../queries/hooks";
import { AttendanceConflictDetails } from "./attendance-conflict-details";

const schema = z.object({ projectId: z.string().min(1, "Project wajib dipilih."), period: z.string().regex(/^\d{4}-(0[1-9]|1[0-2])$/, "Periode harus YYYY-MM."), reason: z.string().min(3, "Alasan minimal 3 karakter."), decision: z.boolean().refine(Boolean, "Konfirmasi commit seluruh batch wajib.") });
type Values = z.infer<typeof schema>;
export function NewAttendanceImportPage() {
  const access = useAttendanceAccess(), router = useRouter(), projects = useProjectsQuery({ statuses: ["Active"], pageSize: 50 }, access.canManage), template = useAttendanceTemplate(access.canManage), previewMutation = usePreviewAttendance(), importMutation = useCreateAndImportAttendance();
  const [session, setSession] = useState<AttendanceSessionFile>(), [preview, setPreview] = useState<AttendanceImportPreview>(), [review, setReview] = useState(false), [guard, setGuard] = useState(false), [failure, setFailure] = useState<AttendanceMutationErrorView>();
  const summaryRef = useRef<HTMLDivElement>(null), dropRef = useRef<HTMLDivElement>(null);
  const form = useForm<Values>({ resolver: zodResolver(schema), defaultValues: { projectId: "", period: "", reason: "", decision: false } }), dirty = form.formState.isDirty || Boolean(session) || Boolean(preview);
  useEffect(() => { if (!dirty) return; const handler = (event: BeforeUnloadEvent) => event.preventDefault(); window.addEventListener("beforeunload", handler); return () => window.removeEventListener("beforeunload", handler); }, [dirty]);
  const invalidatePreview = () => { setPreview(undefined); setFailure(undefined); };
  const onDrop = (files: File[]) => { const file = files[0]; if (!file) return; const metadata: AttendanceFileMetadata = { originalFilename: file.name, displayFilename: file.name, mimeType: file.type, sizeBytes: file.size, lastModified: file.lastModified }, errors = validateFileMetadata(metadata); setSession({ metadata, scenario: file.name.toLocaleLowerCase("id-ID").includes("ready") ? "ready" : file.name.toLocaleLowerCase("id-ID").includes("duplicate") ? "duplicate" : "issues" }); setPreview(undefined); setFailure(errors.length ? { status: 422, code: "ATTENDANCE_FILE_INVALID", message: "File tidak valid.", fieldErrors: { file: errors }, globalErrors: [], retryable: false, correlationId: "local-file-policy" } : undefined); };
  const dropzone = useDropzone({ onDrop, onDropRejected: rejected => onDrop(rejected.map(item => item.file)), multiple: false, accept: { [DEMO_FILE_POLICY.mimeTypes[0]]: [".xlsx"] }, maxSize: DEMO_FILE_POLICY.maxBytes });
  const applyFailure = (error: unknown) => { if (isRequestCancellation(error)) return; const mapped = mapAttendanceMutationError(error); setFailure(mapped); for (const field of ["projectId", "period", "reason"] as const) if (mapped.fieldErrors[field]?.[0]) form.setError(field, { message: mapped.fieldErrors[field]![0] }); if (mapped.fieldErrors.commitDecision?.[0]) form.setError("decision", { message: mapped.fieldErrors.commitDecision[0] }); requestAnimationFrame(() => summaryRef.current?.focus()); };
  const createPreview = async () => { const valid = await form.trigger(["projectId", "period"]), value = form.getValues(); if (!valid) return; const fileErrors = validateFileMetadata(session?.metadata); if (fileErrors.length) { setFailure({ status: 422, code: session ? "ATTENDANCE_FILE_INVALID" : "ATTENDANCE_FILE_REQUIRED", message: session ? "File tidak valid." : "File wajib.", fieldErrors: { file: fileErrors }, globalErrors: [], retryable: false, correlationId: session ? "local-file-policy" : "local-file-required" }); requestAnimationFrame(() => { summaryRef.current?.focus(); dropRef.current?.focus(); }); return; } if (!session) return; try { setFailure(undefined); const result = await previewMutation.mutateAsync({ data: { projectId: value.projectId, period: value.period, file: session.metadata, scenario: session.scenario, templateVersion: template.data?.version }, actor: access.actor }); setPreview(result); } catch (error) { applyFailure(error); } };
  const openReview = async () => { if (await form.trigger(["reason", "decision"])) setReview(true); };
  const commit = async () => form.handleSubmit(async value => { if (!session || !preview) return; try { setFailure(undefined); const result = await importMutation.mutateAsync({ data: { projectId: value.projectId, period: value.period, file: session.metadata, scenario: session.scenario, previewFingerprint: preview.fingerprint, commitDecision: "CommitAll" }, actor: access.actor, reason: value.reason }); setSession(undefined); setPreview(undefined); form.reset(); router.push(access.url(`/attendance/${result.batchId}`)); } catch (error) { if (!isRequestCancellation(error)) { applyFailure(error); setReview(false); } } })();
  if (!access.canManage) return <DataState kind="denied" title="Import attendance tidak diizinkan" description="Persona view bersifat read-only." />;
  if (projects.isPending) return <LoadingState />;
  if (projects.isError) { const error = mapAttendanceMutationError(projects.error); return <DataState kind={error.status === 403 ? "denied" : "server"} correlationId={error.correlationId} action={error.retryable ? <Button onClick={() => projects.refetch()}>Coba lagi project</Button> : undefined} />; }
  if (!projects.data.items.length) return <DataState kind="empty" title="Tidak ada Project eligible" description="Hanya Project Active dalam scope yang dapat menerima Attendance." action={<Link className="button button-secondary" href={access.url("/projects")}>Lihat Project</Link>} />;
  return <><PageHeader eyebrow="Attendance Import" title="Import batch attendance" description="Preview deterministic mock sebelum commit atomic; bukan payroll pembayaran gaji." meta={<Badge tone="warning">Flow dan policy demo</Badge>} actions={<Button variant="secondary" onClick={() => dirty ? setGuard(true) : router.push(access.url("/attendance"))}>Kembali</Button>} />
    {failure && <div ref={summaryRef} tabIndex={-1} className="form-error-summary"><Alert tone="danger" title={`${failure.code}: ${failure.message}`}><ul>{[...failure.globalErrors, ...Object.values(failure.fieldErrors).flat()].map(message => <li key={message}>{message}</li>)}</ul><small>ID korelasi: {failure.correlationId}</small>{failure.retryable && <Button onClick={() => preview ? void commit() : void createPreview()} disabled={previewMutation.isPending || importMutation.isPending}>Coba lagi</Button>}{failure.conflict && <><AttendanceConflictDetails conflict={failure.conflict} /><div className="page-actions"><Link className="button button-secondary" href={access.url("/attendance/import")}>Muat versi terbaru</Link><Link className="button button-quiet" href={access.url("/attendance")}>Kembali tanpa menyimpan</Link></div></>}</Alert></div>}
    <form onSubmit={event => event.preventDefault()} noValidate><Card><CardHeader title="Project dan periode" /><div className="form-section"><label className="field" htmlFor="attendance-project"><span className="field-label">Project</span><select id="attendance-project" aria-invalid={Boolean(form.formState.errors.projectId)} aria-describedby="attendance-project-error" {...form.register("projectId", { onChange: invalidatePreview })}><option value="">Pilih project aktif</option>{projects.data.items.map(project => <option key={project.id} value={project.id}>{project.code} · {project.name}</option>)}</select><span id="attendance-project-error" className="field-error">{form.formState.errors.projectId?.message}</span></label><Input label="Periode" type="month" error={form.formState.errors.period?.message} {...form.register("period", { onChange: invalidatePreview })} /><Input label="Alasan import" error={form.formState.errors.reason?.message} {...form.register("reason")} /></div></Card>
      <Card><CardHeader title="Template dan file" />{template.isPending ? <LoadingState /> : template.isError ? <DataState kind={mapAttendanceMutationError(template.error).status === 403 ? "denied" : "server"} correlationId={mapAttendanceMutationError(template.error).correlationId} action={mapAttendanceMutationError(template.error).retryable ? <Button onClick={() => template.refetch()}>Coba lagi template</Button> : undefined} /> : <Alert tone="info" title={`${template.data.label} · ${template.data.version}`}>{template.data.reason}<div><Button disabled aria-describedby="template-disabled-reason">Unduh template</Button><small id="template-disabled-reason">Download disabled karena binary contract belum tersedia.</small></div></Alert>}<div ref={dropRef} {...dropzone.getRootProps({ className: "attendance-dropzone", role: "button", "aria-describedby": "attendance-file-help attendance-file-error", "aria-invalid": Boolean(failure?.fieldErrors.file), "aria-label": "Pilih atau letakkan file attendance" })}><input {...dropzone.getInputProps()} /><strong>Letakkan file di sini atau aktifkan dengan keyboard</strong><span id="attendance-file-help">Satu .xlsx, maksimal 5 MB menurut policy demo.</span></div><div id="attendance-file-error" role="alert">{failure?.fieldErrors.file?.join(" ")}</div>{session && <div className="file-summary"><strong>{session.metadata.displayFilename}</strong><span>{session.metadata.mimeType} · {session.metadata.sizeBytes} byte</span><Button type="button" variant="secondary" onClick={() => { setSession(undefined); setPreview(undefined); }}>Hapus file</Button></div>}</Card>
      <Card><CardHeader title="Keputusan commit" /><label className="check-row"><input id="attendance-decision" type="checkbox" aria-invalid={Boolean(form.formState.errors.decision || failure?.fieldErrors.commitDecision)} aria-describedby="attendance-decision-error" {...form.register("decision")} />Saya memahami seluruh batch diproses atomic tanpa silent partial row.</label><span id="attendance-decision-error" className="field-error">{form.formState.errors.decision?.message ?? failure?.fieldErrors.commitDecision?.join(" ")}</span><Button type="button" onClick={() => void createPreview()} disabled={previewMutation.isPending}>Buat mapping preview</Button></Card></form>
    {preview && <Card tabIndex={-1}><CardHeader title="Mapping preview deterministic mock" /><TableShell caption="Preview mapping attendance"><thead><tr><th>Source</th><th>Target</th><th>Required</th><th>Status</th><th>Example</th><th>Message</th></tr></thead><tbody>{preview.mapping.map(item => <tr key={item.sourceColumn}><td>{item.sourceColumn}</td><td>{item.targetField}</td><td>{item.required ? "Ya" : "Tidak"}</td><td>{item.status}</td><td>{item.exampleValue}</td><td>{item.message ?? "-"}</td></tr>)}</tbody></TableShell><p>Total {preview.summary.totalRows}; valid {preview.summary.validRows}; invalid {preview.summary.invalidRows}; duplicate {preview.summary.duplicateRows}; warning {preview.summary.warningRows}; blocking {preview.summary.blockingIssueCount}.</p><StatusPreview preview={preview} /><Button onClick={() => void openReview()} disabled={!preview.readiness.readyToValidate}>Tinjau commit final</Button></Card>}
    <Modal open={review} onClose={() => setReview(false)} title="Tinjau commit attendance" description="Repository memvalidasi ulang preview dan command sebelum satu atomic write." footer={<><Button variant="secondary" onClick={() => setReview(false)}>Kembali</Button><Button onClick={() => void commit()} disabled={importMutation.isPending}>Commit seluruh batch</Button></>}><p>Project: {projects.data.items.find(item => item.id === form.getValues("projectId"))?.name}</p><p>Periode: {form.getValues("period")}</p><p>File: {session?.metadata.displayFilename}</p><p>Duplicate decision: {preview?.duplicates.decision}</p><p>Partial commit: tidak diizinkan.</p></Modal>
    <Modal open={guard} onClose={() => setGuard(false)} title="Perubahan belum disimpan" footer={<><Button onClick={() => setGuard(false)}>Tetap di halaman</Button><Button variant="danger" onClick={() => router.push(access.url("/attendance"))}>Keluar tanpa menyimpan</Button></>}>File, form, dan preview akan hilang.</Modal></>;
}
function StatusPreview({ preview }: { preview: AttendanceImportPreview }) { return <Alert tone={preview.readiness.readyToValidate ? "success" : "warning"} title={`Duplicate: ${preview.duplicates.decision}`}>{preview.readiness.nextAction}{preview.readiness.blockers.map(item => <span key={item}>{item}</span>)}</Alert>; }
