"use client";

import Link from "next/link";
import { usePathname,useRouter,useSearchParams } from "next/navigation";
import { useCallback,useEffect,useMemo,useState } from "react";
import { createColumnHelper,tableFeatures,useTable } from "@tanstack/react-table";
import { faArrowDown,faArrowUp,faFilter,faPlus,faRotate } from "@fortawesome/free-solid-svg-icons";
import { AppIcon,Badge,Button,Card,DataState,LoadingState,PageHeader,StatusBadge,TableShell } from "@/components/ui";
import type { ProjectListItem,ProjectStatus } from "@/features/foundation/domain/models";
import { normalizeProjectListQuery } from "@/features/foundation/domain/project-list";
import { useBillingCyclesQuery,useCustomersQuery,useProjectsQuery,useUsersQuery } from "@/features/foundation/queries/hooks";
import { formatDate } from "@/lib/formatters";
import { useDemoProjectAccess } from "../permissions/demo-access";

const features=tableFeatures({});
const helper=createColumnHelper<typeof features,ProjectListItem>();
const columns=helper.columns([
  helper.accessor("code",{header:"Kode project"}),helper.accessor("name",{header:"Nama project"}),
  helper.accessor("customerName",{header:"Customer"}),helper.accessor("picName",{header:"PIC"}),
  helper.accessor("billingCycleName",{header:"Siklus penagihan"}),
  helper.display({id:"period",header:"Periode kontrak",cell:({row})=>`${formatDate(row.original.contractStart)} - ${formatDate(row.original.contractEnd)}`}),
  helper.accessor("branchCount",{header:"Cabang"}),helper.accessor("serviceCount",{header:"Layanan"}),
  helper.accessor("status",{header:"Status",cell:({getValue})=><StatusBadge tone={getValue()==="Active"?"success":getValue()==="Draft"?"info":"warning"}>{getValue()}</StatusBadge>}),
  helper.display({id:"readiness",header:"Readiness",cell:({row})=><Badge tone={row.original.readiness.ready?"success":"warning"}>{row.original.readiness.ready?"Siap":"Belum lengkap"} · {row.original.readiness.completedCount}/{row.original.readiness.totalCount}</Badge>}),
  helper.accessor("updatedAt",{header:"Terakhir diperbarui",cell:({getValue})=>formatDate(getValue(),true)}),
  helper.display({id:"actions",header:"Tindakan",cell:()=>null}),
]);
const statuses:readonly ProjectStatus[]=["Draft","Active","On Hold","Closed","Cancelled"];

export function ProjectListPage(){
  const router=useRouter(),pathname=usePathname(),searchParams=useSearchParams(),access=useDemoProjectAccess();
  const parsed=useMemo(()=>normalizeProjectListQuery({search:searchParams.get("search")??undefined,statuses:searchParams.getAll("status") as ProjectStatus[],customerIds:searchParams.get("customer")?[searchParams.get("customer")!]:[],picUserIds:searchParams.get("pic")?[searchParams.get("pic")!]:[],billingCycleIds:searchParams.get("billing")?[searchParams.get("billing")!]:[],contractStartFrom:searchParams.get("start")??undefined,contractEndTo:searchParams.get("end")??undefined,sort:(searchParams.get("sort") as "code"|"name"|"status"|"contractStart"|"contractEnd"|"updatedAt")??undefined,direction:searchParams.get("direction")==="asc"?"asc":"desc",page:Number(searchParams.get("page")||1),pageSize:Number(searchParams.get("pageSize")||20)}),[searchParams]);
  const [search,setSearch]=useState(parsed.search);const [hidden,setHidden]=useState<Set<string>>(new Set());
  const query=useProjectsQuery(parsed,access.canView),customers=useCustomersQuery(access.canView),users=useUsersQuery(access.canView),cycles=useBillingCyclesQuery(access.canView);
  const table=useTable({features,columns,data:query.data?.items??[],getRowId:(row)=>row.id});
  const update=useCallback((changes:Record<string,string|string[]|undefined>,resetPage=true)=>{const next=new URLSearchParams(searchParams.toString());for(const [key,value] of Object.entries(changes)){next.delete(key);if(Array.isArray(value))value.filter(Boolean).forEach((item)=>next.append(key,item));else if(value)next.set(key,value);}next.set("access",access.access);if(resetPage)next.delete("page");router.replace(`${pathname}?${next}`,{scroll:false});},[access.access,pathname,router,searchParams]);
  const reset=useCallback(()=>{setSearch("");router.replace(access.url(pathname));},[access,pathname,router]);
  useEffect(()=>{const timer=setTimeout(()=>{if(search!==parsed.search)update({search:search||undefined});},350);return()=>clearTimeout(timer);},[parsed.search,search,update]);
  if(!access.canView)return <DataState kind="denied" title="Akses project dibatasi" description="Persona demo ini tidak memiliki project.view dan tidak memuat metadata project."/>;
  const activeFilters=[parsed.search,parsed.statuses.length,parsed.customerIds.length,parsed.picUserIds.length,parsed.billingCycleIds.length,parsed.contractStartFrom,parsed.contractEndTo].filter(Boolean).length;
  return <><PageHeader eyebrow="Project Operations" title="Project dan SPH" description="Temukan project, readiness, blocker, dan tindakan berikutnya." meta={<Badge tone="warning">Data demo - belum terhubung API</Badge>} actions={access.canManage?<Link className="button button-primary" href={access.url("/projects/new")}><AppIcon icon={faPlus}/>Buat project</Link>:undefined}/>
    <Card className="filter-card"><div className="project-filters"><label><span>Cari project</span><input value={search} onChange={(event)=>setSearch(event.target.value)} placeholder="Kode, nama, customer, PIC, atau SPH"/></label><label><span>Status</span><select value={parsed.statuses[0]??""} onChange={(event)=>update({status:event.target.value||undefined})}><option value="">Semua status</option>{statuses.map((status)=><option key={status}>{status}</option>)}</select></label><label><span>Customer</span><select value={parsed.customerIds[0]??""} onChange={(event)=>update({customer:event.target.value||undefined})}><option value="">Semua customer</option>{customers.data?.map((item)=><option value={item.id} key={item.id}>{item.name}</option>)}</select></label><label><span>PIC</span><select value={parsed.picUserIds[0]??""} onChange={(event)=>update({pic:event.target.value||undefined})}><option value="">Semua PIC</option>{users.data?.map((item)=><option value={item.id} key={item.id}>{item.name}</option>)}</select></label><label><span>Siklus penagihan</span><select value={parsed.billingCycleIds[0]??""} onChange={(event)=>update({billing:event.target.value||undefined})}><option value="">Semua siklus</option>{cycles.data?.map((item)=><option value={item.id} key={item.id}>{item.name}</option>)}</select></label><label><span>Kontrak dimulai dari</span><input type="date" value={parsed.contractStartFrom??""} onChange={(event)=>update({start:event.target.value||undefined})}/></label><label><span>Kontrak berakhir sampai</span><input type="date" value={parsed.contractEndTo??""} onChange={(event)=>update({end:event.target.value||undefined})}/></label></div><div className="filter-actions"><Badge tone={activeFilters?"info":"neutral"}><AppIcon icon={faFilter}/>{activeFilters} filter aktif</Badge><Button variant="secondary" leadingIcon={<AppIcon icon={faRotate}/>} onClick={reset}>Reset filter</Button><Button variant="quiet" disabled>Saved view · belum aktif</Button></div></Card>
    <Card><div className="table-toolbar"><span>{query.data?.total??0} project</span><label>Ukuran halaman <select value={parsed.pageSize} onChange={(event)=>update({pageSize:event.target.value})}><option>10</option><option>20</option><option>50</option></select></label><details><summary>Kolom</summary>{columns.map((column)=><label key={column.id}><input type="checkbox" checked={!hidden.has(column.id!)} onChange={()=>setHidden((current)=>{const next=new Set(current);if(next.has(column.id!))next.delete(column.id!);else next.add(column.id!);return next;})}/>{String(column.id)}</label>)}</details></div>
      {query.isPending?<div className="table-state"><LoadingState/></div>:query.isError?<DataState kind="server" correlationId={query.error.correlation_id} action={<Button variant="secondary" onClick={()=>query.refetch()}>Coba lagi</Button>}/>:query.data.total===0?<DataState kind={activeFilters?"zero":"empty"} action={activeFilters?<Button variant="secondary" onClick={reset}>Reset filter</Button>:undefined}/>:<><TableShell caption="Daftar project, status, dan readiness"><thead>{table.getHeaderGroups().map((group)=><tr key={group.id}>{group.headers.filter((header)=>!hidden.has(header.column.id)).map((header)=><th key={header.id} scope="col">{["code","name","status","updatedAt"].includes(header.column.id)?<button className="sort-button" onClick={()=>update({sort:header.column.id,direction:parsed.sort===header.column.id&&parsed.direction==="asc"?"desc":"asc"})}>{header.isPlaceholder?null:<table.FlexRender header={header}/>}<AppIcon icon={parsed.sort===header.column.id&&parsed.direction==="asc"?faArrowUp:faArrowDown}/></button>:header.column.id==="actions"?"Tindakan":header.isPlaceholder?null:<table.FlexRender header={header}/>}</th>)}</tr>)}</thead><tbody>{table.getRowModel().rows.map((row)=><tr key={row.id}>{row.getAllCells().filter((cell)=>!hidden.has(cell.column.id)).map((cell)=><td key={cell.id}>{cell.column.id==="actions"?<Link className="table-link" href={access.url(`/projects/${row.original.id}`)}>Buka detail</Link>:<table.FlexRender cell={cell}/>}</td>)}</tr>)}</tbody></TableShell><div className="project-mobile-list">{query.data.items.map((project)=><article key={project.id}><StatusBadge tone={project.status==="Active"?"success":"info"}>{project.status}</StatusBadge><strong>{project.name}</strong><small>{project.code} · {project.customerName} · {project.readiness.ready?"Siap":"Belum lengkap"}</small><Link href={access.url(`/projects/${project.id}`)}>Buka detail</Link></article>)}</div><div className="pagination"><Button variant="secondary" disabled={parsed.page<=1} onClick={()=>update({page:String(parsed.page-1)},false)}>Sebelumnya</Button><span>Halaman {parsed.page}</span><Button variant="secondary" disabled={!query.data.hasNextPage} onClick={()=>update({page:String(parsed.page+1)},false)}>Berikutnya</Button></div></>}
    </Card></>;
}
