"use client";

import Link from "next/link";
import { useRouter,useSearchParams } from "next/navigation";
import { useState } from "react";
import { faCheck,faCircleExclamation,faFileContract,faPen,faRocket } from "@fortawesome/free-solid-svg-icons";
import { AppIcon,Alert,Badge,Button,Card,CardHeader,DataState,LoadingState,Modal,PageHeader,StatusBadge } from "@/components/ui";
import { useActivateProjectMutation,useAuditQuery,useBillingCyclesQuery,useCustomersQuery,useProjectQuery,useProjectReadinessQuery,useServicesQuery,useUsersQuery,useVendorsQuery } from "@/features/foundation/queries/hooks";
import type { DocumentMetadata } from "@/features/foundation/domain/models";
import { formatDate } from "@/lib/formatters";
import { projectMutationError } from "../domain/mutation-error";
import { useDemoProjectAccess } from "../permissions/demo-access";

const tabs=["overview","contract","rates","workforce","invoices","expenses","profitability","documents","audit"] as const;
type Tab=typeof tabs[number];
const labels:Record<Tab,string>={overview:"Ringkasan",contract:"Kontrak/SPH",rates:"Rate",workforce:"Tenaga kerja",invoices:"Invoice",expenses:"Biaya",profitability:"Profitabilitas",documents:"Dokumen",audit:"Audit"};

function DocumentRow({document,accessUrl}:{document:DocumentMetadata;accessUrl:(path:string)=>string}){return <article className="document-row"><AppIcon icon={faFileContract}/><span><strong>{document.category}</strong><small>{document.objectType} · version history tersedia</small></span><Link className="button button-secondary" href={accessUrl(`/documents/${document.id}`)}>Buka dokumen</Link></article>;}
function Placeholder({stage,dependency}:{stage:string;dependency:string}){return <DataState kind="empty" title={`Dibangun pada ${stage}`} description={`Fondasi Project sudah tersedia. ${dependency}`}/>;}

export function ProjectDetailPage({projectId}:{projectId:string}){
  const router=useRouter(),params=useSearchParams(),access=useDemoProjectAccess(),allowed=access.canView;
  const detail=useProjectQuery(projectId,allowed),readiness=useProjectReadinessQuery(projectId,allowed),customers=useCustomersQuery(allowed),vendors=useVendorsQuery(allowed),users=useUsersQuery(allowed),cycles=useBillingCyclesQuery(allowed),services=useServicesQuery(allowed),audits=useAuditQuery("Project",projectId,allowed),activate=useActivateProjectMutation();
  const [activateOpen,setActivateOpen]=useState(false),[attested,setAttested]=useState(false),[activity,setActivity]=useState("");
  if(!allowed)return <DataState kind="denied" title="Akses project dibatasi" description="Persona demo ini tidak memiliki project.view dan tidak memuat metadata project, customer, atau dokumen." action={<Link className="button button-secondary" href={access.url("/projects")}>Kembali ke daftar</Link>}/>;
  if(detail.isPending)return <LoadingState/>;
  if(detail.isError)return <DataState kind={detail.error.status===404?"empty":"server"} title={detail.error.status===404?"Project tidak ditemukan":undefined} description={detail.error.status===404?"Periksa tautan atau kembali ke daftar project.":undefined} correlationId={detail.error.correlation_id} action={<Link className="button button-secondary" href={access.url("/projects")}>Kembali ke daftar</Link>}/>;
  const aggregate=detail.data,project=aggregate.project,sph=aggregate.sph;
  const customer=customers.data?.find((item)=>item.id===project.customerId),vendor=vendors.data?.find((item)=>item.id===project.vendorId),pic=users.data?.find((item)=>item.id===project.picUserId),cycle=cycles.data?.find((item)=>item.id===sph.billingCycleId);
  const selected=tabs.includes(params.get("tab") as Tab)?params.get("tab") as Tab:"overview";
  const changeTab=(tab:Tab)=>{const next=new URLSearchParams(params.toString());if(tab==="overview")next.delete("tab");else next.set("tab",tab);router.replace(access.url(`/projects/${projectId}`,next),{scroll:false});};
  const confirmActivation=async()=>{try{const result=await activate.mutateAsync({projectId,currentVersion:project.version,attested,actor:access.actor});setActivity(result.message);setActivateOpen(false);setAttested(false);}catch(error){const mapped=projectMutationError(error);setActivity(`${mapped.message} · ${mapped.correlationId}${mapped.retryable?" · Dapat dicoba kembali":""}`);setActivateOpen(false);}};
  return <><PageHeader eyebrow={project.code} title={project.name} description={`${customer?.name??"Customer"} · PIC ${pic?.name??"-"}`} meta={<div className="header-meta"><StatusBadge tone={project.status==="Active"?"success":project.status==="Draft"?"info":"warning"}>{project.status}</StatusBadge><Badge tone="warning">Data demo - belum terhubung API</Badge><span>{formatDate(sph.startDate)} - {formatDate(sph.endDate)}</span><span>Diperbarui {formatDate(project.updatedAt,true)}</span></div>} actions={access.canManage?<><Link className="button button-secondary" href={access.url(`/projects/${projectId}/edit`)}><AppIcon icon={faPen}/>Edit</Link>{project.status==="Draft"&&readiness.data?.ready&&<Button leadingIcon={<AppIcon icon={faRocket}/>} onClick={()=>setActivateOpen(true)}>Aktifkan</Button>}</>:undefined}/>
    {(params.has("created")||params.has("updated")||activity)&&<Alert tone={activity&&activate.isError?"danger":"success"} title={activity||`Project berhasil ${params.has("created")?"dibuat":"diperbarui"}.`}>Status authoritative tetap terlihat di halaman.</Alert>}
    {(project.status==="Closed"||project.status==="Cancelled")&&<Alert tone="warning" title={`Project ${project.status} bersifat read-only`}>Transaksi baru dan aktivasi langsung ditolak.</Alert>}
    <nav className="project-tabs" aria-label="Bagian detail project">{tabs.map((tab)=>tab==="rates"?<Link key={tab} className="project-tab-link" href={access.url(`/projects/${projectId}/rates`)}>{labels[tab]}</Link>:<button key={tab} aria-current={selected===tab?"page":undefined} onClick={()=>changeTab(tab)}>{labels[tab]}</button>)}</nav>
    {selected==="overview"&&<div className="detail-grid"><Card><CardHeader title="Ringkasan"/><dl className="detail-list"><dt>Kode project</dt><dd>{project.code}</dd><dt>Status</dt><dd>{project.status}</dd><dt>Customer</dt><dd>{customer?.name??"-"}</dd><dt>Vendor</dt><dd>{vendor?.name??"Tidak digunakan"}</dd><dt>PIC</dt><dd>{pic?.name??"-"}</dd><dt>Siklus penagihan</dt><dd>{cycle?.name??"-"}</dd><dt>Cost center</dt><dd>{sph.costCenter}</dd><dt>Cabang aktif</dt><dd>{aggregate.branches.filter((item)=>item.isActive).length}</dd><dt>Layanan</dt><dd>{project.serviceIds.map((id)=>services.data?.find((item)=>item.id===id)?.name??id).join(", ")}</dd></dl></Card><ReadinessCard projectId={projectId}/></div>}
    {selected==="contract"&&<div className="detail-grid"><Card><CardHeader title="SPH / Kontrak"/><dl className="detail-list"><dt>Nomor SPH</dt><dd>{sph.number}</dd><dt>Periode</dt><dd>{formatDate(sph.startDate)} - {formatDate(sph.endDate)}</dd><dt>Siklus penagihan</dt><dd>{cycle?.name??"-"}</dd><dt>Cost center</dt><dd>{sph.costCenter}</dd><dt>Cabang</dt><dd>{aggregate.branches.map((item)=>`${item.code} · ${item.name}`).join(", ")}</dd></dl></Card><Card><CardHeader title="Dokumen kontrak"/>{aggregate.documents.sph.length?aggregate.documents.sph.map((doc)=><DocumentRow key={doc.id} document={doc} accessUrl={access.url}/>):<DataState kind="empty" title="Dokumen kontrak belum tersedia"/>}</Card></div>}
    {selected==="documents"&&<Card><CardHeader title="Ringkasan dokumen" description={`${Object.values(aggregate.documents.byRateVersion).flat().length+aggregate.documents.project.length+aggregate.documents.sph.length} dokumen terhubung ke Project, SPH, dan Rate Version.`} action={<div className="table-actions"><Link href={access.url(`/projects/${projectId}/documents`)}>Lihat semua dokumen</Link>{access.canManage&&<Link href={access.url(`/projects/${projectId}/documents/new`)}>Tambah dokumen</Link>}</div>}/><section className="document-groups"><h3>Dokumen project</h3>{aggregate.documents.project.map((doc)=><DocumentRow key={doc.id} document={doc} accessUrl={access.url}/>) }<h3>Dokumen SPH/kontrak</h3>{aggregate.documents.sph.map((doc)=><DocumentRow key={doc.id} document={doc} accessUrl={access.url}/>) }<h3>Dokumen versi rate</h3>{Object.values(aggregate.documents.byRateVersion).flat().map((doc)=><DocumentRow key={doc.id} document={doc} accessUrl={access.url}/>)}</section></Card>}
    {selected==="audit"&&<Card><CardHeader title="Ringkasan audit" description="Event terbaru, read-only. Audit Explorer lengkap tersedia pada Tahap 1E."/><div className="audit-list">{audits.data?.map((event)=><article key={event.id}><strong>{event.action}</strong><span>{users.data?.find((item)=>item.id===event.actorUserId)?.name??event.actorUserId} · {formatDate(event.occurredAt,true)}</span><small>{event.reason??"Tanpa alasan"} · {event.correlationId}</small></article>)}</div></Card>}
    {selected==="workforce"&&<Placeholder stage="Tahap 2" dependency="Tenaga kerja bergantung pada attendance dan payroll billing."/>}{selected==="invoices"&&<Placeholder stage="Tahap 2" dependency="Invoice bergantung pada billing run dan konfirmasi customer."/>}{selected==="expenses"&&<Placeholder stage="Tahap 3" dependency="Biaya bergantung pada payment request dan payment execution."/>}{selected==="profitability"&&<Placeholder stage="Tahap 4" dependency="Profitabilitas production bergantung pada revenue dan cost authoritative."/>}
    <Modal open={activateOpen} onClose={()=>setActivateOpen(false)} title="Aktifkan project" description="Tinjau readiness sebelum project menjadi siap transaksi." footer={<><Button variant="secondary" onClick={()=>setActivateOpen(false)}>Batal</Button><Button disabled={!attested||activate.isPending} onClick={confirmActivation}>Konfirmasi aktivasi</Button></>}><ReadinessCard projectId={projectId}/><label className="attestation"><input type="checkbox" checked={attested} onChange={(event)=>setAttested(event.target.checked)}/>Saya telah meninjau kode project, customer, PIC, SPH, periode, cabang, layanan, rate, dan dokumen.</label></Modal>
  </>;
}

function ReadinessCard({projectId}:{projectId:string}){const query=useProjectReadinessQuery(projectId);if(query.isPending)return <Card><LoadingState/></Card>;if(query.isError)return <Card><DataState kind="server" correlationId={query.error.correlation_id}/></Card>;const result=query.data;return <Card><CardHeader title="Readiness checklist" description={`${result.completedCount}/${result.totalCount} persyaratan lengkap`} action={<StatusBadge tone={result.ready?"success":"warning"}>{result.ready?"Siap diaktifkan":"Belum siap"}</StatusBadge>}/><div className="readiness-list">{result.items.map((item)=><article key={item.code}><AppIcon icon={item.complete?faCheck:faCircleExclamation}/><span><strong>{item.label}</strong><small>{item.description}</small><em>{item.complete?"Lengkap":`Blocker · ${item.nextAction}`} · Penanggung jawab {item.owner}</em></span></article>)}</div>{!result.ready&&<div className="next-action"><strong>Tindakan berikutnya</strong><span>{result.nextActions.join("; ")}</span></div>}</Card>;}
