"use client";

import Link from "next/link";
import { zodResolver } from "@hookform/resolvers/zod";
import { useFieldArray,useForm } from "react-hook-form";
import { useDropzone } from "react-dropzone";
import { z } from "zod";
import { useEffect,useMemo,useState } from "react";
import { useRouter } from "next/navigation";
import { toast } from "sonner";
import { faArrowLeft,faFileArrowUp,faPlus,faTrash } from "@fortawesome/free-solid-svg-icons";
import { AppIcon,Alert,Badge,Button,Card,CardHeader,DataState,Input,LoadingState,Modal,PageHeader,Select } from "@/components/ui";
import { useBillingCyclesQuery,useCreateProjectMutation,useCustomersQuery,useProjectQuery,useServicesQuery,useUpdateProjectMutation,useUsersQuery,useVendorsQuery } from "@/features/foundation/queries/hooks";
import { projectMutationError } from "../domain/mutation-error";
import { useDemoProjectAccess } from "../permissions/demo-access";

const schema=z.object({code:z.string().min(1,"Kode project wajib.").regex(/^PRJ-[A-Z0-9]+-[0-9]{3,}$/,"Gunakan format PRJ-UNIT-001."),name:z.string().min(1,"Nama project wajib."),description:z.string(),customerId:z.string().min(1,"Customer wajib."),vendorId:z.string(),picUserId:z.string().min(1,"PIC wajib."),sphNumber:z.string().min(1,"Nomor SPH wajib."),contractStartDate:z.string().min(1,"Tanggal mulai wajib."),contractEndDate:z.string().min(1,"Tanggal akhir wajib."),billingCycleId:z.string().min(1,"Siklus penagihan wajib."),costCenter:z.string().min(1,"Cost center wajib."),branches:z.array(z.object({id:z.string().optional(),code:z.string().min(1,"Kode cabang wajib."),name:z.string().min(1,"Nama cabang wajib."),location:z.string().min(1,"Lokasi wajib."),isActive:z.boolean()})).min(1,"Minimal satu cabang."),serviceIds:z.array(z.string()).min(1,"Minimal satu layanan aktif."),reason:z.string().optional()}).refine((data)=>data.contractEndDate>=data.contractStartDate,{path:["contractEndDate"],message:"Tanggal akhir tidak boleh sebelum tanggal mulai."}).refine((data)=>data.branches.some((branch)=>branch.isActive),{path:["branches"],message:"Minimal satu cabang harus aktif."});
type FormValues=z.infer<typeof schema>;
const empty:FormValues={code:"",name:"",description:"",customerId:"",vendorId:"",picUserId:"",sphNumber:"",contractStartDate:"",contractEndDate:"",billingCycleId:"",costCenter:"",branches:[{code:"",name:"",location:"",isActive:true}],serviceIds:[],reason:""};

export function ProjectFormPage({mode,projectId}:{mode:"create"|"edit";projectId?:string}){
  const router=useRouter(),access=useDemoProjectAccess(),editing=mode==="edit",allowed=access.canManage;
  const detail=useProjectQuery(projectId??"",editing&&allowed),customers=useCustomersQuery(allowed),vendors=useVendorsQuery(allowed),users=useUsersQuery(allowed),cycles=useBillingCyclesQuery(allowed),services=useServicesQuery(allowed);
  const createMutation=useCreateProjectMutation(),updateMutation=useUpdateProjectMutation();
  const [review,setReview]=useState<FormValues|null>(null),[leaveOpen,setLeaveOpen]=useState(false),[file,setFile]=useState<File|null>(null),[feedback,setFeedback]=useState("");
  const defaults=useMemo<FormValues>(()=>{if(editing&&detail.data){const {project,sph,branches}=detail.data;return{code:project.code,name:project.name,description:project.description,customerId:project.customerId,vendorId:project.vendorId??"",picUserId:project.picUserId,sphNumber:sph.number,contractStartDate:sph.startDate,contractEndDate:sph.endDate,billingCycleId:sph.billingCycleId,costCenter:sph.costCenter,branches:branches.map((branch)=>({id:branch.id,code:branch.code,name:branch.name,location:branch.location,isActive:branch.isActive})),serviceIds:[...project.serviceIds],reason:""};}return empty;},[detail.data,editing]);
  const form=useForm<FormValues>({resolver:zodResolver(schema),defaultValues:defaults}),{reset}=form;
  const fields=useFieldArray({control:form.control,name:"branches"});
  useEffect(()=>reset(defaults),[defaults,reset]);
  useEffect(()=>{const onBeforeUnload=(event:BeforeUnloadEvent)=>{if(form.formState.isDirty){event.preventDefault();event.returnValue="";}};window.addEventListener("beforeunload",onBeforeUnload);return()=>window.removeEventListener("beforeunload",onBeforeUnload);},[form.formState.isDirty]);
  const dropzone=useDropzone({disabled:editing,maxFiles:1,maxSize:5*1024*1024,accept:{"application/pdf":[".pdf"],"image/jpeg":[".jpg",".jpeg"],"image/png":[".png"]},onDropAccepted:(accepted)=>setFile(accepted[0]??null)});
  if(!allowed)return <DataState kind="denied" title="Tidak dapat mengelola project" description="Persona demo ini tidak memiliki project.manage." action={<Button variant="secondary" onClick={()=>router.push(access.url(projectId?`/projects/${projectId}`:"/projects"))}>Kembali</Button>}/>;
  if(editing&&detail.isPending)return <LoadingState/>;
  if(editing&&detail.isError)return <DataState kind={detail.error.status===404?"empty":"server"} title={detail.error.status===404?"Project tidak ditemukan":undefined} correlationId={detail.error.correlation_id} action={<Button variant="secondary" onClick={()=>router.push(access.url("/projects"))}>Kembali ke daftar</Button>}/>;
  const locked=editing&&(detail.data?.project.status==="Closed"||detail.data?.project.status==="Cancelled");
  const backUrl=access.url(editing?`/projects/${projectId}`:"/projects");
  const submit=form.handleSubmit((values)=>setReview(values),()=>document.querySelector<HTMLElement>("[aria-invalid='true']")?.focus());
  const confirm=async()=>{if(!review)return;try{const common={...review,contractDocument:!editing&&file?{fileName:file.name,mimeType:file.type,sizeBytes:file.size}:undefined,actor:access.actor};const result=editing?await updateMutation.mutateAsync({...common,projectId:projectId!,currentVersion:detail.data!.project.version}):await createMutation.mutateAsync(common);form.reset(review);setReview(null);toast.success(result.message);router.push(access.url(`/projects/${result.projectId}`,{[editing?"updated":"created"]:"1"}));}catch(error){const mapped=projectMutationError(error);for(const [name,messages] of Object.entries(mapped.fieldErrors))form.setError(name as keyof FormValues,{message:messages[0]});setReview(null);setFeedback(`${mapped.conflict?"Konflik versi: ":""}${mapped.message} · ${mapped.correlationId}${mapped.retryable?" · Dapat dicoba kembali":""}`);}};
  const currentDocument=detail.data?.documents.sph[0];
  return <><PageHeader eyebrow={editing?"Edit project":"Project baru"} title={editing?detail.data!.project.name:"Buat Draft project"} description={editing?`Versi ${detail.data!.project.version} · terakhir diperbarui ${detail.data!.project.updatedAt}`:"Lengkapi identitas, SPH, cabang, layanan, dan dokumen kontrak."} meta={<Badge tone="warning">Data demo - belum terhubung API</Badge>}/>
    {feedback&&<Alert tone={feedback.startsWith("Konflik")?"danger":"warning"} title={feedback}/>} {locked&&<DataState kind="validation" title={`Project ${detail.data!.project.status} bersifat read-only`}/>}<form onSubmit={submit} noValidate aria-label="Form project"><div className="form-error-summary" tabIndex={-1}>{Object.keys(form.formState.errors).length>0&&<Alert tone="danger" title="Periksa kembali form">Ada {Object.keys(form.formState.errors).length} bagian yang perlu diperbaiki.</Alert>}</div><div className="project-form-grid">
      <Card><CardHeader title="Identitas"/><div className="form-section"><Input label="Kode project" {...form.register("code")} error={form.formState.errors.code?.message} disabled={editing}/><Input label="Nama project" {...form.register("name")} error={form.formState.errors.name?.message}/><label className="field"><span className="field-label">Deskripsi</span><textarea className="input textarea" {...form.register("description")}/></label><Select label="PIC" {...form.register("picUserId")} error={form.formState.errors.picUserId?.message}><option value="">Pilih PIC aktif</option>{users.data?.filter((item)=>item.status==="Active").map((item)=><option value={item.id} key={item.id}>{item.name}</option>)}</Select></div></Card>
      <Card><CardHeader title="Customer dan SPH"/><div className="form-section"><Select label="Customer" {...form.register("customerId")} error={form.formState.errors.customerId?.message}><option value="">Pilih customer aktif</option>{customers.data?.filter((item)=>item.isActive).map((item)=><option value={item.id} key={item.id}>{item.name}</option>)}</Select><Select label="Vendor (opsional)" {...form.register("vendorId")}><option value="">Tanpa vendor</option>{vendors.data?.filter((item)=>item.isActive).map((item)=><option value={item.id} key={item.id}>{item.name}</option>)}</Select><Input label="Nomor SPH" {...form.register("sphNumber")} error={form.formState.errors.sphNumber?.message}/><div className="form-row"><Input type="date" label="Tanggal mulai kontrak" {...form.register("contractStartDate")} error={form.formState.errors.contractStartDate?.message}/><Input type="date" label="Tanggal akhir kontrak" {...form.register("contractEndDate")} error={form.formState.errors.contractEndDate?.message}/></div><Select label="Siklus penagihan" {...form.register("billingCycleId")} error={form.formState.errors.billingCycleId?.message}><option value="">Pilih siklus aktif</option>{cycles.data?.filter((item)=>item.isActive).map((item)=><option value={item.id} key={item.id}>{item.name}</option>)}</Select><Input label="Cost center" {...form.register("costCenter")} error={form.formState.errors.costCenter?.message}/></div></Card>
      <Card><CardHeader title="Cabang" action={<Button size="sm" variant="secondary" leadingIcon={<AppIcon icon={faPlus}/>} onClick={()=>fields.append({code:"",name:"",location:"",isActive:true})}>Tambah</Button>}/><div className="form-section">{fields.fields.map((branch,index)=><fieldset className="branch-fieldset" key={branch.id}><legend>Cabang {index+1}</legend><Input label="Kode cabang" {...form.register(`branches.${index}.code`)}/><Input label="Nama cabang" {...form.register(`branches.${index}.name`)}/><Input label="Lokasi/alamat" {...form.register(`branches.${index}.location`)}/><label><input type="checkbox" {...form.register(`branches.${index}.isActive`)}/> Cabang aktif</label>{fields.fields.length>1&&<Button size="sm" variant="quiet" leadingIcon={<AppIcon icon={faTrash}/>} onClick={()=>fields.remove(index)}>Hapus cabang</Button>}</fieldset>)}</div></Card>
      <Card><CardHeader title="Layanan dan dokumen"/><div className="form-section"><fieldset><legend>Layanan aktif</legend>{services.data?.filter((item)=>item.isActive).map((service)=><label className="check-row" key={service.id}><input type="checkbox" value={service.id} {...form.register("serviceIds")}/>{service.code} · {service.name}</label>)}</fieldset>{editing?<Alert tone="info" title="Dokumen kontrak saat ini">{currentDocument?<>{currentDocument.category} · metadata read-only. <Link href={access.url(`/documents/${currentDocument.id}/versions/new`)}>Upload versi baru</Link></>:<>Belum ada dokumen kontrak. <Link href={access.url(`/projects/${projectId}/documents/new`,{objectType:"SPH",objectId:detail.data?.sph.id})}>Tambah dokumen kontrak</Link></>}</Alert>:<><div {...dropzone.getRootProps({className:"dropzone"})}><input {...dropzone.getInputProps()}/><AppIcon icon={faFileArrowUp}/><strong>{file?.name??"Pilih dokumen kontrak"}</strong><span>PDF/JPG/PNG maksimal 5 MB. Validasi dan scanning server tetap authoritative.</span></div>{dropzone.fileRejections.map(({file:rejected})=><span className="field-error" key={rejected.name}>{rejected.name} tidak memenuhi tipe atau ukuran.</span>)}</>}{editing&&<Input label="Alasan perubahan material" {...form.register("reason")}/>}</div></Card>
    </div><div className="form-actions"><Button variant="secondary" leadingIcon={<AppIcon icon={faArrowLeft}/>} onClick={()=>form.formState.isDirty?setLeaveOpen(true):router.push(backUrl)}>Kembali</Button><Button type="submit" disabled={locked||createMutation.isPending||updateMutation.isPending}>Tinjau dan simpan</Button></div></form>
    <Modal open={Boolean(review)} onClose={()=>setReview(null)} title="Tinjau Draft project" description="Pastikan data berikut benar sebelum disimpan." footer={<><Button variant="secondary" onClick={()=>setReview(null)}>Kembali edit</Button><Button onClick={confirm}>Simpan Draft</Button></>}>{review&&<dl className="review-list"><dt>Project</dt><dd>{review.code} · {review.name}</dd><dt>SPH</dt><dd>{review.sphNumber}</dd><dt>Periode</dt><dd>{review.contractStartDate} - {review.contractEndDate}</dd><dt>Cabang / layanan</dt><dd>{review.branches.length} / {review.serviceIds.length}</dd>{!editing&&<><dt>Dokumen baru</dt><dd>{file?.name??"Belum dipilih"}</dd></>}</dl>}</Modal>
    <Modal open={leaveOpen} onClose={()=>setLeaveOpen(false)} title="Perubahan belum disimpan" description="Input tetap tersedia bila Anda tetap di halaman." footer={<><Button variant="secondary" onClick={()=>setLeaveOpen(false)}>Tetap di halaman</Button><Button variant="danger" onClick={()=>router.push(backUrl)}>Keluar tanpa menyimpan</Button></>}>Perubahan yang belum disimpan akan hilang.</Modal></>;
}
