import Decimal from "decimal.js";
import { AppError } from "@/features/foundation/domain/errors";
import type { InvoiceLine, InvoiceReconciliation, InvoiceRounding, InvoiceSourceOption, InvoiceSourceSnapshot, InvoiceSummary, InvoiceTaxPreview, NormalizedInvoiceListQuery, InvoiceListQuery } from "./types";

const unique = <T extends string>(values: readonly T[] | undefined) => [...new Set(values ?? [])].sort();
export function normalizeInvoiceListQuery(query: InvoiceListQuery = {}): NormalizedInvoiceListQuery { const size = query.pageSize === 10 || query.pageSize === 50 ? query.pageSize : 20; return { search: query.search?.trim().toLocaleLowerCase("id-ID") ?? "", projectIds: unique(query.projectIds), customerIds: unique(query.customerIds), periods: unique(query.periods), statuses: unique(query.statuses), sort: query.sort ?? "updatedAt", direction: query.direction ?? "desc", page: Math.max(1, Math.trunc(query.page ?? 1)), pageSize: size }; }
export function validateInvoiceSourceOption(option: InvoiceSourceOption) { if (!option.eligible) throw new AppError(422,"INVOICE_SOURCE_INELIGIBLE",option.blocker??"Source tidak eligible."); const projectIds=unique(option.lines.map(line=>line.source.projectId)),customerIds=unique(option.lines.map(line=>line.source.customerId)),sphIds=unique(option.lines.map(line=>line.source.sphId)),currencies=unique(option.lines.map(line=>line.source.currency)); if(projectIds.length!==1||projectIds[0]!==option.source.projectId)throw new AppError(422,"INVOICE_PROJECT_MISMATCH","Source line harus berasal dari Project yang sama.");if(customerIds.length!==1||customerIds[0]!==option.source.customerId)throw new AppError(422,"INVOICE_CUSTOMER_MISMATCH","Source line harus berasal dari Customer yang sama.");if(sphIds.length!==1||sphIds[0]!==option.source.sphId)throw new AppError(422,"INVOICE_MIXED_SPH","Satu Invoice hanya dapat menggunakan satu SPH.");if(currencies.length!==1||currencies[0]!==option.source.currency)throw new AppError(422,"INVOICE_CURRENCY_MISMATCH","Currency source tidak konsisten."); }
export function calculateInvoice(lines: readonly InvoiceLine[], source: InvoiceSourceSnapshot, chargeTotal = "0"): { summary: InvoiceSummary; reconciliation: InvoiceReconciliation; tax: InvoiceTaxPreview; rounding: InvoiceRounding } {
  const sourceIds = lines.map(line => line.source.payrollBillingLineId); const duplicateSourceLineIds = unique(sourceIds.filter((id, index) => sourceIds.indexOf(id) !== index));
  const mappedSourceTotal = lines.reduce((sum, line) => sum.plus(line.baseAmount).plus(line.componentAmount), new Decimal(0));
  const charges = new Decimal(chargeTotal); const preRound = mappedSourceTotal.plus(charges); const roundingAmount = new Decimal(0);
  const taxAmount = new Decimal(0); const withholdingAmount = new Decimal(0); const grandTotal = preRound.plus(taxAmount).minus(withholdingAmount).plus(roundingAmount);
  const expected = new Decimal(source.sourceFinancialTotal).plus(charges); const variance = grandTotal.minus(expected);
  const summary = { sourceLineSubtotal: mappedSourceTotal.toFixed(2), componentTotal: lines.reduce((sum,line)=>sum.plus(line.componentAmount),new Decimal(0)).toFixed(2), chargeTotal: charges.toFixed(2), taxBase: mappedSourceTotal.toFixed(2), taxAmount: taxAmount.toFixed(2), withholdingAmount: withholdingAmount.toFixed(2), roundingAmount: roundingAmount.toFixed(2), grandTotal: grandTotal.toFixed(2) };
  const currencyConsistent=lines.every(line=>line.source.currency===source.currency),singleSph=lines.every(line=>line.source.sphId===source.sphId);
  const reconciliation = { sourceTotal: source.sourceFinancialTotal, mappedSourceTotal: mappedSourceTotal.toFixed(2), feeAndChargeTotal: charges.toFixed(2), expectedAuthoritativeTotal: expected.toFixed(2), invoiceGrandTotal: grandTotal.toFixed(2), variance: variance.toFixed(2), allSourceLinesMapped: mappedSourceTotal.eq(source.sourceFinancialTotal), duplicateSourceLineIds, currencyConsistent, singleSph, reconciled: variance.eq(0) && duplicateSourceLineIds.length === 0 && mappedSourceTotal.eq(source.sourceFinancialTotal)&&currencyConsistent&&singleSph };
  const tax: InvoiceTaxPreview = source.taxMetadata.applicability === "NotApplicable" ? { applicability: "NotApplicable", amount: "0.00", explanation: "Tidak berlaku berdasarkan metadata source." } : source.taxMetadata.applicability === "PendingConfiguration" ? { applicability: "PendingConfiguration", explanation: "Menunggu konfigurasi backend; tidak ada rate pajak yang dihitung di frontend." } : { ...source.taxMetadata, amount: undefined, explanation: "Metadata tersedia; nominal menunggu perhitungan authoritative backend." };
  const rounding = { preRoundTotal: preRound.toFixed(2), method: source.roundingMetadata.method, adjustment: "0.00", finalTotal: grandTotal.toFixed(2), configured: source.roundingMetadata.configured };
  return { summary, reconciliation, tax, rounding };
}
