import type { CurrencyCode, EntityId, IsoDate, IsoDateTime, VersionNumber } from "@/features/foundation/domain/models";

export type InvoiceStatus = "Draft" | "Pending Customer" | "Revision" | "Pending Approval" | "Approved" | "Released" | "Sent" | "Partially Paid" | "Paid" | "Void" | "Overdue";
export type InvoiceAccess = "manage" | "review" | "view" | "none";
export type InvoiceSort = "updatedAt" | "billingPeriod" | "grandTotal" | "draftReference";
export type SortDirection = "asc" | "desc";
export interface PaginatedResult<T> { items: readonly T[]; total: number; page: number; pageSize: number; hasNextPage: boolean; totalPages: number; }
export interface InvoiceListQuery { search?: string; projectIds?: readonly EntityId[]; customerIds?: readonly EntityId[]; periods?: readonly string[]; statuses?: readonly InvoiceStatus[]; sort?: InvoiceSort; direction?: SortDirection; page?: number; pageSize?: 10 | 20 | 50; }
export interface NormalizedInvoiceListQuery { search: string; projectIds: readonly EntityId[]; customerIds: readonly EntityId[]; periods: readonly string[]; statuses: readonly InvoiceStatus[]; sort: InvoiceSort; direction: SortDirection; page: number; pageSize: 10 | 20 | 50; }
export interface InvoiceLineSource { payrollBillingLineId: EntityId; payrollBillingRunId: EntityId; payrollBillingRevisionId: EntityId; payrollBillingRevisionVersion: VersionNumber; projectId: EntityId; customerId: EntityId; sphId: EntityId; currency: CurrencyCode; attendanceSourceReference: string; }
export interface InvoiceLine { id: EntityId; description: string; serviceLabel: string; branchLabel: string; quantity: string; unit: string; unitRate: string; baseAmount: string; componentAmount: string; chargeAmount: string; taxable: boolean | null; taxBasis?: string; withholdingMetadata?: string; roundingAllocation: string; finalAmount: string; source: InvoiceLineSource; }
export interface InvoiceCharge { id: EntityId; label: string; amount: string; reason: string; source: "SourceSnapshot" | "ManualDraft"; }
export interface InvoiceSourceSnapshot { projectId: EntityId; projectCode: string; projectName: string; customerId: EntityId; customerName: string; billingAddress: string; customerTaxIdentityMasked: string; sphId: EntityId; sphNumber: string; contractStart: IsoDate; contractEnd: IsoDate; payrollBillingRunId: EntityId; payrollBillingRevisionId: EntityId; payrollBillingRevisionNumber: number; payrollBillingRevisionVersion: VersionNumber; attendancePeriod: string; attendanceSourceReference: string; rateVersionId: EntityId; rateVersionLabel: string; currency: CurrencyCode; serviceLabels: readonly string[]; branchLabels: readonly string[]; feeMetadata: string; taxMetadata: { applicability: "Applicable" | "NotApplicable" | "PendingConfiguration"; ruleReference?: string; ratePercent?: string; basis?: string; inclusive?: boolean; withholding?: string; }; roundingMetadata: { method?: string; configured: boolean; }; sourceFinancialTotal: string; capturedAt: IsoDateTime; }
export interface InvoiceTaxPreview { applicability: InvoiceSourceSnapshot["taxMetadata"]["applicability"]; ruleReference?: string; ratePercent?: string; basis?: string; amount?: string; inclusive?: boolean; withholdingAmount?: string; explanation: string; }
export interface InvoiceRounding { preRoundTotal: string; method?: string; adjustment: string; finalTotal: string; configured: boolean; }
export interface InvoiceSummary { sourceLineSubtotal: string; componentTotal: string; chargeTotal: string; taxBase: string; taxAmount: string; withholdingAmount: string; roundingAmount: string; grandTotal: string; }
export interface InvoiceReconciliation { sourceTotal: string; mappedSourceTotal: string; feeAndChargeTotal: string; expectedAuthoritativeTotal: string; invoiceGrandTotal: string; variance: string; allSourceLinesMapped: boolean; duplicateSourceLineIds: readonly EntityId[]; currencyConsistent: boolean; singleSph: boolean; reconciled: boolean; }
export interface InvoiceReadiness { readyForNextStage: boolean; blockers: readonly string[]; nextAction: string; }
export interface InvoiceRevision { id: EntityId; revisionNumber: number; version: VersionNumber; snapshot: { source: InvoiceSourceSnapshot; lines: readonly InvoiceLine[]; charges: readonly InvoiceCharge[]; summary: InvoiceSummary; reconciliation: InvoiceReconciliation; note: string; invoiceDate: IsoDate; }; updatedAt: IsoDateTime; updatedByUserId: EntityId; }
export interface Invoice { id: EntityId; draftReference: string; invoiceNumber?: never; status: InvoiceStatus; projectId: EntityId; customerId: EntityId; sphId: EntityId; payrollBillingRunId: EntityId; currentRevisionId: EntityId; currentRevisionNumber: number; version: VersionNumber; currency: CurrencyCode; billingPeriod: string; createdAt: IsoDateTime; updatedAt: IsoDateTime; autosavedAt?: IsoDateTime; createdByUserId: EntityId; updatedByUserId: EntityId; autosavedByUserId?: EntityId; }
export interface InvoiceActivity { id: EntityId; actorUserId: EntityId; actorName?: string; action: "invoice.draft-created" | "invoice.draft-saved" | "invoice.draft-autosaved" | "invoice.confirmation-requested" | "invoice.revision-requested" | "invoice.revision-saved" | "invoice.revision-resubmitted" | "invoice.customer-confirmed" | "invoice.pending-approval-handoff"; occurredAt: IsoDateTime; reason: string; version: VersionNumber; revisionNumber: number; correlationId: string; summary: string; }
export interface InvoiceDetail { invoice: Invoice; revision: InvoiceRevision; lines: readonly InvoiceLine[]; charges: readonly InvoiceCharge[]; summary: InvoiceSummary; reconciliation: InvoiceReconciliation; readiness: InvoiceReadiness; taxPreview: InvoiceTaxPreview; rounding: InvoiceRounding; activity: readonly InvoiceActivity[]; }
export interface InvoiceListItem { id: EntityId; draftReference: string; status: InvoiceStatus; projectId: EntityId; projectName: string; customerId: EntityId; customerName: string; sphNumber: string; payrollBillingReference: string; billingPeriod: string; currency: CurrencyCode; grandTotal: string; reconciled: boolean; variance: string; ready: boolean; updatedAt: IsoDateTime; autosavedAt?: IsoDateTime; version: VersionNumber; nextAction: string; }
export interface InvoiceSourceOption { id: EntityId; eligible: boolean; blocker?: string; source: InvoiceSourceSnapshot; lines: readonly InvoiceLine[]; }
export interface InvoiceDraftData { sourceOptionId?: EntityId; invoiceDate: IsoDate; note: string; lines?: readonly Pick<InvoiceLine, "id" | "description">[]; charges?: readonly InvoiceCharge[]; }
export interface InvoiceActor { userId: EntityId; permissionKeys: readonly string[]; }
export interface InvoiceDraftCommand { invoiceId?: EntityId; data: InvoiceDraftData; actor: InvoiceActor; reason: string; currentVersion?: VersionNumber; currentRevisionId?: EntityId; currentRevisionVersion?: VersionNumber; }
export interface InvoiceDraftMutationResult { invoiceId: EntityId; version: VersionNumber; revisionId: EntityId; revisionVersion: VersionNumber; savedAt: IsoDateTime; message: string; correlationId: string; }
export interface InvoicePreviewModel { draftLabel: "DRAFT" | "REVISION - BELUM DIKIRIM" | "MENUNGGU KONFIRMASI CUSTOMER" | "CUSTOMER CONFIRMED - BELUM DISETUJUI"; finalInvoiceNumber: null; source: InvoiceSourceSnapshot; invoiceDate: IsoDate; lines: readonly InvoiceLine[]; charges: readonly InvoiceCharge[]; summary: InvoiceSummary; tax: InvoiceTaxPreview; rounding: InvoiceRounding; reconciliation: InvoiceReconciliation; note: string; }
export interface InvoiceConflictDiff { field: string; attempted: string; latest: string; }
export type ConfirmationChannel="Meeting"|"Phone"|"EmailMetadata"|"DocumentReference";
export interface InvoiceConfirmationEvidence{id:EntityId;channel:ConfirmationChannel;displayLabel:string;reference:string;referenceDate:IsoDate;customerContactName:string;recordedAt:IsoDateTime;recordedByUserId:EntityId;note:string;documentId?:EntityId;documentStatus?:"Clean"|"Pending"|"Rejected";version:VersionNumber;correlationId:string;}
export interface InvoiceRequestedChange{id:EntityId;section:"Header"|"LinePresentation"|"Charge"|"TaxMetadata"|"Document";currentValueSummary:string;customerRequestSummary:string;requiresFinancialRecalculation:boolean;requiresSourceCorrection:boolean;requiresDocumentUpdate:boolean;resolutionStatus:"Open"|"Resolved";resolutionNote?:string;}
export interface InvoiceConfirmationRequest{id:EntityId;cycle:number;revisionId:EntityId;requestedAt:IsoDateTime;requestDate:IsoDate;actorUserId:EntityId;actorName?:string;channel:ConfirmationChannel;customerContactName:string;reference:string;note:string;evidence:InvoiceConfirmationEvidence;}
export interface InvoiceCustomerResponse{id:EntityId;cycle:number;kind:"RevisionRequested"|"Confirmed";respondedAt:IsoDateTime;customerContactName:string;reference:string;note:string;evidence:InvoiceConfirmationEvidence;}
export interface InvoiceRevisionRequest{id:EntityId;cycle:number;submittedRevisionId:EntityId;workingRevisionId:EntityId;reason:string;requestedChanges:readonly InvoiceRequestedChange[];response:InvoiceCustomerResponse;createdAt:IsoDateTime;actorUserId:EntityId;}
export interface InvoiceConfirmationRecord{id:EntityId;cycle:number;revisionId:EntityId;confirmedAt:IsoDateTime;statement:string;note:string;evidence:InvoiceConfirmationEvidence;picUserId:EntityId;picName?:string;correlationId:string;}
export interface InvoiceConfirmationCycle{cycle:number;request:InvoiceConfirmationRequest;response?:InvoiceCustomerResponse;revisionRequest?:InvoiceRevisionRequest;confirmation?:InvoiceConfirmationRecord;status:"Waiting"|"RevisionRequested"|"Confirmed";}
export interface InvoiceConfirmationReadiness{ready:boolean;blockers:readonly string[];confirmationCycle:number;nextAction:string;}
export interface InvoiceRevisionDiff{sourceRevisionId:EntityId;targetRevisionId:EntityId;changes:readonly {field:string;kind:"Added"|"Removed"|"Changed";before?:string;after?:string;requestedChangeId?:EntityId}[];grandTotalBefore:string;grandTotalAfter:string;absoluteDelta:string;percentageDelta?:string;denominatorZero:boolean;reconciledBefore:boolean;reconciledAfter:boolean;}
export interface InvoiceConfirmationState{cycles:readonly InvoiceConfirmationCycle[];revisions:readonly InvoiceRevision[];submittedRevisionId?:EntityId;workingRevisionId?:EntityId;requestedChanges:readonly InvoiceRequestedChange[];readiness:InvoiceConfirmationReadiness;picUserId:EntityId;}
export interface InvoiceWorkflowCommand<T>{invoiceId:EntityId;data:T;actor:InvoiceActor;reason:string;currentVersion:VersionNumber;currentRevisionId:EntityId;currentRevisionVersion:VersionNumber;}
export type RequestConfirmationCommand=InvoiceWorkflowCommand<{requestDate:IsoDate;channel:ConfirmationChannel;customerContactName:string;reference:string;note:string;attestation:boolean;evidence:Omit<InvoiceConfirmationEvidence,"id"|"recordedAt"|"recordedByUserId"|"version"|"correlationId">}>;
export type RecordRevisionRequestCommand=InvoiceWorkflowCommand<{responseDate:IsoDate;channel:ConfirmationChannel;customerContactName:string;reference:string;reason:string;note:string;requestedChanges:readonly Omit<InvoiceRequestedChange,"id">[];evidence:Omit<InvoiceConfirmationEvidence,"id"|"recordedAt"|"recordedByUserId"|"version"|"correlationId">}>;
export type SaveRevisionCommand=InvoiceWorkflowCommand<{invoiceDate:IsoDate;note:string;lines:readonly Pick<InvoiceLine,"id"|"description">[];resolutions:readonly {requestedChangeId:EntityId;resolutionNote:string;resolved:boolean}[]}>;
export type ResubmitRevisionCommand=InvoiceWorkflowCommand<{attestation:boolean;note:string}>;
export type RecordCustomerConfirmedCommand=InvoiceWorkflowCommand<{confirmedAt:IsoDateTime;channel:ConfirmationChannel;customerContactName:string;reference:string;statement:string;note:string;attestation:boolean;evidence:Omit<InvoiceConfirmationEvidence,"id"|"recordedAt"|"recordedByUserId"|"version"|"correlationId">}>;
