"use client";
import { useMutation,useQuery,type QueryKey,type UseMutationOptions } from "@tanstack/react-query";
import { queryKeys } from "@/lib/query-keys";
import { normalizeOrRethrowAppError,type AppError } from "../domain/errors";
import type { DocumentObjectType } from "../domain/models";
import { normalizeProjectListQuery } from "../domain/project-list";
import type { ProjectListQuery } from "../repositories/contracts";
import { repositories } from "../repositories";
import { useQueryClient } from "@tanstack/react-query";
import type { ActivateProjectInput,CreateProjectInput,UpdateProjectInput } from "@/features/projects/domain/commands";
export function useRepositoryMutation<TData,TVariables>(mutationFn:(variables:TVariables)=>Promise<TData>,options?:Omit<UseMutationOptions<TData,AppError,TVariables>,"mutationFn">){return useMutation<TData,AppError,TVariables>({mutationFn:async(variables)=>{try{return await mutationFn(variables);}catch(error){throw normalizeOrRethrowAppError(error);}},...options});}
function useRepositoryQuery<T>(queryKey:QueryKey,queryFn:(signal:AbortSignal)=>Promise<T>,enabled=true){return useQuery<T,AppError>({queryKey,enabled,queryFn:async({signal})=>{try{return await queryFn(signal);}catch(error){throw normalizeOrRethrowAppError(error);}}});}
export function useDashboardQuery(){return useRepositoryQuery(queryKeys.dashboard.snapshot,(signal)=>repositories.dashboard.getSnapshot(signal));}
export function useProjectsQuery(params:ProjectListQuery={},enabled=true){const normalized=normalizeProjectListQuery(params);return useRepositoryQuery(queryKeys.projects.list(normalized),(signal)=>repositories.projects.list(normalized,signal),enabled);}
export function useProjectQuery(projectId:string,enabled=projectId!=="__new__"&&projectId!==""){return useRepositoryQuery(queryKeys.projects.detail(projectId),(signal)=>repositories.projects.getById(projectId,signal),enabled);}
export function useCustomersQuery(enabled=true){return useRepositoryQuery(queryKeys.masterData.customers,(signal)=>repositories.masterData.listCustomers(signal),enabled);}export function useVendorsQuery(enabled=true){return useRepositoryQuery(queryKeys.masterData.vendors,(signal)=>repositories.masterData.listVendors(signal),enabled);}export function useServicesQuery(enabled=true){return useRepositoryQuery(queryKeys.masterData.services,(signal)=>repositories.masterData.listServices(signal),enabled);}export function useBillingCyclesQuery(enabled=true){return useRepositoryQuery(queryKeys.masterData.billingCycles,(signal)=>repositories.masterData.listBillingCycles(signal),enabled);}export function useTaxRulesQuery(){return useRepositoryQuery(queryKeys.masterData.taxRules,(signal)=>repositories.masterData.listTaxRules(signal));}
export function useRatesQuery(projectId:string){return useRepositoryQuery(queryKeys.rates.list(projectId,{search:"",statuses:[],effectiveStates:[],sort:"versionNumber",direction:"desc",page:1,pageSize:20}),(signal)=>repositories.rates.list(projectId,{},signal));}export function useCurrentUserQuery(){return useRepositoryQuery(queryKeys.identity.currentUser,(signal)=>repositories.identity.getCurrentUser(signal));}export function useUsersQuery(enabled=true){return useRepositoryQuery(queryKeys.identity.users,(signal)=>repositories.identity.listUsers(signal),enabled);}export function useRolesQuery(){return useRepositoryQuery(queryKeys.identity.roles,(signal)=>repositories.identity.listRoles(signal));}export function usePermissionsQuery(){return useRepositoryQuery(queryKeys.identity.permissions,(signal)=>repositories.identity.listPermissions(signal));}
export function useDocumentsQuery(objectType:DocumentObjectType,objectId:string){return useRepositoryQuery(queryKeys.documents.byObject(objectType,objectId),(signal)=>repositories.documents.listByObject(objectType,objectId,signal));}export function useDocumentVersionsQuery(documentId:string,enabled=true){return useRepositoryQuery(queryKeys.documents.versions(documentId),(signal)=>repositories.documents.listVersions(documentId,signal),enabled);}export function useAuditQuery(objectType:string,objectId:string,enabled=true){return useRepositoryQuery(queryKeys.audit.byObject(objectType,objectId),(signal)=>repositories.audit.listByObject(objectType,objectId,signal),enabled);}
export function useProjectReadinessQuery(projectId:string,enabled=true){return useRepositoryQuery(queryKeys.projects.readiness(projectId),(signal)=>repositories.projects.getReadiness(projectId,signal),enabled);}
export function useCreateProjectMutation(){const client=useQueryClient();return useRepositoryMutation((input:CreateProjectInput)=>repositories.projects.create(input),{onSuccess:()=>client.invalidateQueries({queryKey:queryKeys.projects.all})});}
export function useUpdateProjectMutation(){const client=useQueryClient();return useRepositoryMutation((input:UpdateProjectInput)=>repositories.projects.update(input),{onSuccess:(result)=>Promise.all([client.invalidateQueries({queryKey:queryKeys.projects.all}),client.invalidateQueries({queryKey:queryKeys.projects.detail(result.projectId)}),client.invalidateQueries({queryKey:queryKeys.projects.readiness(result.projectId)})])});}
export function useActivateProjectMutation(){const client=useQueryClient();return useRepositoryMutation((input:ActivateProjectInput)=>repositories.projects.activate(input),{onSuccess:(result)=>Promise.all([client.invalidateQueries({queryKey:queryKeys.projects.all}),client.invalidateQueries({queryKey:queryKeys.projects.detail(result.projectId)}),client.invalidateQueries({queryKey:queryKeys.projects.readiness(result.projectId)})])});}
