import { render, screen, waitFor } from "@testing-library/react";
import userEvent from "@testing-library/user-event";
import { beforeEach, describe, expect, it, vi } from "vitest";
import { AppError } from "@/features/foundation/domain/errors";
import { AdminDetailPage } from "./admin-detail-page";
import { AdminFormPage } from "./admin-form-page";

const mocks = vi.hoisted(() => ({ pathname: "/admin/users/usr-dewi/edit", mutate: vi.fn() }));
const conflict = (type: "user" | "role", lifecycle = false) => new AppError(409, `${type.toUpperCase()}_VERSION_CONFLICT`, "Data telah berubah.", {}, false, `corr-${type}`, { userVersion: 1, latestVersion: 2, currentStatus: lifecycle ? "Active" : undefined, targetStatus: lifecycle ? "Inactive" : undefined, diffs: [{ field: lifecycle ? "status" : "name", label: lifecycle ? "Status" : "Nama", before: lifecycle ? "Tujuan: Inactive" : "Submitted", after: lifecycle ? "Status terbaru: Active" : "Latest" }] });
vi.mock("next/navigation", () => ({ useRouter: () => ({ push: vi.fn() }), usePathname: () => mocks.pathname, useSearchParams: () => new URLSearchParams("access=manage") }));
vi.mock("../permissions/demo-access", () => ({ useAccessPersona: () => ({ access: "manage", canView: true, canManage: true, actor: { userId: "usr-dewi", permissionKeys: ["access.manage"] }, url: (path: string) => `${path}?access=manage` }) }));
vi.mock("../queries/hooks", () => { const base = { isPending: false, isError: false, error: null, refetch: vi.fn() }, role = { id: "role-view", code: "VIEW", name: "Viewer", description: "View", status: "Active", permissionKeys: ["access.view"], isSystem: false, createdAt: "2026-08-10T00:00:00+07:00", updatedAt: "2026-08-10T00:00:00+07:00", version: 2 }, user = { id: "usr-dewi", employeeId: "EMP-001", name: "Dewi Sari", email: "dewi@example.test", status: "Active", roleIds: [role.id], projectScopeIds: ["prj-019"], createdAt: role.createdAt, updatedAt: role.updatedAt, version: 2 }; const mutation = () => ({ mutateAsync: mocks.mutate, isPending: false, cancel: vi.fn() }); return { useAccessUser: () => ({ ...base, data: { user, roles: [role], effectivePermissions: ["access.view"], sodFindings: [], audit: [] } }), useAccessRole: () => ({ ...base, data: { role, userCount: 1, sodFindings: [], audit: [] } }), useAccessRoles: () => ({ ...base, data: { items: [{ ...role, userCount: 1, sodFindings: [] }], total: 1, page: 1, pageSize: 50, hasNextPage: false } }), usePermissionCatalog: () => ({ ...base, data: [{ key: "access.view", module: "Access", label: "Lihat", description: "Lihat", risk: "Sensitive" }] }), useUserAudit: () => ({ ...base, data: [] }), useRoleAudit: () => ({ ...base, data: [] }), useSaveUser: mutation, useSaveRole: mutation, useUserLifecycle: mutation, useRoleLifecycle: mutation }; });

beforeEach(() => { mocks.mutate.mockReset(); });

async function submitEdit(kind: "users" | "roles") { const actor = userEvent.setup(); render(<AdminFormPage kind={kind} mode="edit" id={kind === "users" ? "usr-dewi" : "role-view"} />); await waitFor(() => expect(screen.getByLabelText(kind === "users" ? "Nama" : "Nama role")).toHaveValue(kind === "users" ? "Dewi Sari" : "Viewer")); await actor.type(screen.getByLabelText("Alasan perubahan"), "uji conflict"); await actor.click(screen.getByRole("button", { name: "Tinjau perubahan" })); await actor.click(screen.getByRole("button", { name: "Simpan" })); }
async function submitLifecycle(kind: "users" | "roles") { const actor = userEvent.setup(); render(<AdminDetailPage kind={kind} id={kind === "users" ? "usr-dewi" : "role-view"} />); await actor.click(screen.getByRole("button", { name: "Nonaktifkan" })); await actor.type(screen.getByLabelText(/^Alasan/), "uji conflict"); await actor.click(screen.getByRole("button", { name: "Konfirmasi" })); }

describe("persona-preserving production conflict recovery", () => {
  it("provides explicit User edit recovery without repeating mutation", async () => { mocks.pathname = "/admin/users/usr-dewi/edit"; mocks.mutate.mockRejectedValue(conflict("user")); await submitEdit("users"); expect(await screen.findByText("Data telah berubah")).toBeVisible(); expect(screen.getByText(/corr-user/)).toBeVisible(); expect(screen.getByRole("link", { name: "Muat versi terbaru" })).toHaveAttribute("href", "/admin/users/usr-dewi/edit?access=manage"); expect(screen.getByRole("link", { name: "Kembali tanpa menyimpan" })).toHaveAttribute("href", "/admin/users/usr-dewi?access=manage"); expect(mocks.mutate).toHaveBeenCalledOnce(); });
  it("provides explicit Role edit recovery", async () => { mocks.pathname = "/admin/roles/role-view/edit"; mocks.mutate.mockRejectedValue(conflict("role")); await submitEdit("roles"); expect(await screen.findByText("Data telah berubah")).toBeVisible(); expect(screen.getByRole("link", { name: "Muat versi terbaru" })).toHaveAttribute("href", "/admin/roles/role-view/edit?access=manage"); expect(screen.getByRole("link", { name: "Kembali tanpa menyimpan" })).toHaveAttribute("href", "/admin/roles/role-view?access=manage"); });
  it("provides deterministic User lifecycle recovery with status diff", async () => { mocks.pathname = "/admin/users/usr-dewi"; mocks.mutate.mockRejectedValue(conflict("user", true)); await submitLifecycle("users"); expect(await screen.findByText(/Status terbaru Active; target Inactive/)).toBeVisible(); expect(screen.getByRole("link", { name: "Muat versi terbaru" })).toHaveAttribute("href", "/admin/users/usr-dewi?access=manage"); expect(screen.getByRole("link", { name: "Kembali tanpa menyimpan" })).toHaveAttribute("href", "/admin/users?access=manage"); });
  it("provides deterministic Role lifecycle recovery", async () => { mocks.pathname = "/admin/roles/role-view"; mocks.mutate.mockRejectedValue(conflict("role", true)); await submitLifecycle("roles"); expect(await screen.findByText(/corr-role/)).toBeVisible(); expect(screen.getByRole("link", { name: "Muat versi terbaru" })).toHaveAttribute("href", "/admin/roles/role-view?access=manage"); expect(screen.getByRole("link", { name: "Kembali tanpa menyimpan" })).toHaveAttribute("href", "/admin/roles?access=manage"); expect(screen.queryByText(/force overwrite/i)).not.toBeInTheDocument(); });
});
