import { render, screen, waitFor, within } from "@testing-library/react";
import userEvent from "@testing-library/user-event";
import { beforeEach, describe, expect, it, vi } from "vitest";
import { AppError } from "@/features/foundation/domain/errors";
import { AdminDetailPage } from "./admin-detail-page";

type QueryState = "data" | "loading" | "404" | "403" | "503";
type AuditState = "events" | "loading" | "empty" | "403" | "503" | "cancel";
const state = vi.hoisted(() => ({ persona: "manage" as "manage" | "view" | "none", status: "Active" as "Active" | "Inactive", detail: "data" as QueryState, audit: "events" as AuditState, lifecycle: vi.fn(), detailRetry: vi.fn(), auditRetry: vi.fn(), userEnabled: vi.fn(), roleEnabled: vi.fn(), userAuditEnabled: vi.fn(), roleAuditEnabled: vi.fn() }));
const role = { id: "role-view", code: "VIEW", name: "Viewer", description: "Read", status: "Active" as const, permissionKeys: ["access.view"] as const, isSystem: false, createdAt: "2026-08-10T00:00:00+07:00", updatedAt: "2026-08-10T00:00:00+07:00", version: 3 };
const user = { id: "usr-1", employeeId: "EMP-001", name: "Dewi Sari", email: "dewi@example.test", status: "Active" as const, roleIds: [role.id], projectScopeIds: [], createdAt: role.createdAt, updatedAt: role.updatedAt, version: 2 };
const q = <T,>(data: T) => state.detail === "loading" ? { data: undefined, isPending: true, isError: false, error: null, refetch: state.detailRetry } : state.detail !== "data" ? { data: undefined, isPending: false, isError: true, error: new AppError(state.detail === "404" ? 404 : state.detail === "403" ? 403 : 503, `DETAIL_${state.detail}`, "Gagal.", {}, state.detail === "503", "corr-detail"), refetch: state.detailRetry } : { data, isPending: false, isError: false, error: null, refetch: state.detailRetry };
const aq = () => state.audit === "loading" || state.audit === "cancel" ? { data: undefined, isPending: true, isError: false, error: null, refetch: state.auditRetry } : state.audit === "403" || state.audit === "503" ? { data: undefined, isPending: false, isError: true, error: new AppError(state.audit === "403" ? 403 : 503, `AUDIT_${state.audit}`, "Audit gagal.", {}, state.audit === "503", "corr-audit-error"), refetch: state.auditRetry } : { data: state.audit === "empty" ? [] : [{ id: "a1", actorUserId: "usr-actor", actorName: "Admin Demo", action: "user.updated", objectType: "User", objectId: "usr-1", occurredAt: role.updatedAt, reason: "Ubah role", correlationId: "corr-event", before: { roleIds: ["old"] }, after: { roleIds: ["role-view"] } }, { id: "a2", actorUserId: "usr-missing", action: "role.updated", objectType: "Role", objectId: "role-view", occurredAt: role.updatedAt, reason: "Ubah izin", correlationId: "corr-fallback" }], isPending: false, isError: false, error: null, refetch: state.auditRetry };

vi.mock("next/navigation", () => ({ usePathname: () => "/admin/users/usr-1", useSearchParams: () => new URLSearchParams("access=manage") }));
vi.mock("../permissions/demo-access", () => ({ useAccessPersona: () => ({ access: state.persona, canView: state.persona !== "none", canManage: state.persona === "manage", actor: { userId: "usr-actor", permissionKeys: ["access.manage"] }, url: (path: string) => `${path}?access=${state.persona}` }) }));
vi.mock("../queries/hooks", () => ({
  useAccessUser: (_id: string, enabled: boolean) => { state.userEnabled(enabled); return q({ user: { ...user, status: state.status }, roles: [role], effectivePermissions: ["access.view"], sodFindings: [], audit: [] }); },
  useAccessRole: (_id: string, enabled: boolean) => { state.roleEnabled(enabled); return q({ role: { ...role, status: state.status }, userCount: 4, sodFindings: [], audit: [] }); },
  useUserAudit: (_id: string, enabled: boolean) => { state.userAuditEnabled(enabled); return aq(); }, useRoleAudit: (_id: string, enabled: boolean) => { state.roleAuditEnabled(enabled); return aq(); },
  useUserLifecycle: () => ({ mutateAsync: state.lifecycle, isPending: false, cancel: vi.fn() }), useRoleLifecycle: () => ({ mutateAsync: state.lifecycle, isPending: false, cancel: vi.fn() }),
}));

beforeEach(() => { state.persona = "manage"; state.status = "Active"; state.detail = "data"; state.audit = "events"; for (const mock of [state.lifecycle, state.detailRetry, state.auditRetry, state.userEnabled, state.roleEnabled, state.userAuditEnabled, state.roleAuditEnabled]) mock.mockReset(); });

describe("AdminDetailPage and audit acceptance", () => {
  it("renders User identity, assignments, permissions, status, version and manage actions", () => { render(<AdminDetailPage kind="users" id="usr-1" />); expect(screen.getByRole("heading", { name: "Dewi Sari" })).toBeVisible(); expect(screen.getByText("dewi@example.test")).toBeVisible(); expect(screen.getByText("EMP-001")).toBeVisible(); expect(screen.getByText("Viewer")).toBeVisible(); expect(screen.getByText("access.view")).toBeVisible(); expect(screen.getByText("2")).toBeVisible(); expect(screen.getByRole("link", { name: "Edit" })).toHaveAttribute("href", "/admin/users/usr-1/edit?access=manage"); expect(screen.getByRole("button", { name: "Nonaktifkan" })).toBeVisible(); });
  it("renders Role identity, permission usage and read-only view persona", () => { state.persona = "view"; render(<AdminDetailPage kind="roles" id="role-view" />); expect(screen.getByRole("heading", { name: "Viewer" })).toBeVisible(); expect(screen.getByText(/VIEW.*4 pengguna/)).toBeVisible(); expect(screen.getByText("access.view")).toBeVisible(); expect(screen.queryByRole("link", { name: "Edit" })).not.toBeInTheDocument(); expect(screen.queryByRole("button", { name: /Nonaktifkan/ })).not.toBeInTheDocument(); });
  it("suppresses detail and audit for persona none", () => { state.persona = "none"; render(<AdminDetailPage kind="users" id="usr-1" />); expect(screen.getByText("Akses administrasi ditolak")).toBeVisible(); expect(screen.queryByText(user.email)).not.toBeInTheDocument(); expect(state.userEnabled).toHaveBeenCalledWith(false); expect(state.userAuditEnabled).not.toHaveBeenCalled(); });
  it("handles detail loading, 404, 403, and retryable 503", async () => { state.detail = "loading"; const loading = render(<AdminDetailPage kind="users" id="usr-1" />); expect(screen.getByLabelText("Memuat data")).toBeVisible(); loading.unmount(); state.detail = "404"; const missing = render(<AdminDetailPage kind="users" id="usr-1" />); expect(screen.getByText("Belum ada data")).toBeVisible(); missing.unmount(); state.detail = "403"; const denied = render(<AdminDetailPage kind="users" id="usr-1" />); expect(screen.getByText("Akses terbatas")).toBeVisible(); denied.unmount(); state.detail = "503"; render(<AdminDetailPage kind="users" id="usr-1" />); await userEvent.click(screen.getByRole("button", { name: "Coba lagi" })); expect(state.detailRetry).toHaveBeenCalledOnce(); });
  it("keeps main detail visible through local audit loading, empty, error and retry", async () => { state.audit = "loading"; const loading = render(<AdminDetailPage kind="users" id="usr-1" />); expect(screen.getByRole("heading", { name: "Dewi Sari" })).toBeVisible(); expect(screen.getByLabelText("Memuat data")).toBeVisible(); loading.unmount(); state.audit = "empty"; const empty = render(<AdminDetailPage kind="users" id="usr-1" />); expect(screen.getByText("Belum ada audit perubahan")).toBeVisible(); empty.unmount(); state.audit = "403"; const denied = render(<AdminDetailPage kind="users" id="usr-1" />); expect(screen.getByRole("heading", { name: "Dewi Sari" })).toBeVisible(); expect(screen.queryByRole("button", { name: "Coba lagi audit" })).not.toBeInTheDocument(); denied.unmount(); state.audit = "503"; render(<AdminDetailPage kind="users" id="usr-1" />); await userEvent.click(screen.getByRole("button", { name: "Coba lagi audit" })); expect(state.auditRetry).toHaveBeenCalledOnce(); });
  it("renders authoritative audit actor name, ID fallback, safe summaries and correlation IDs", () => { render(<AdminDetailPage kind="users" id="usr-1" />); expect(screen.getByText(/Admin Demo/)).toBeVisible(); expect(screen.getByText(/usr-missing/)).toBeVisible(); expect(screen.getByText(/corr-event/)).toBeVisible(); expect(screen.getByText(/corr-fallback/)).toBeVisible(); expect(screen.getByText(/Sebelum:.*old/)).toBeVisible(); expect(screen.getByText(/Sesudah:.*role-view/)).toBeVisible(); expect(screen.getByText(/Ubah role.*corr-event/)).toBeVisible(); });
  it("validates lifecycle reason and sends versioned User command once", async () => { state.lifecycle.mockResolvedValue({ objectId: "usr-1", version: 3, message: "Dinonaktifkan", correlationId: "corr-success" }); const actor = userEvent.setup(); render(<AdminDetailPage kind="users" id="usr-1" />); await actor.click(screen.getByRole("button", { name: "Nonaktifkan" })); const dialog = screen.getByRole("dialog", { name: "Nonaktifkan pengguna" }); expect(within(dialog).getByText(/Status saat ini: Active.*Target: Inactive.*Versi: 2/)).toBeVisible(); expect(within(dialog).getByRole("button", { name: "Konfirmasi" })).toBeDisabled(); await actor.type(within(dialog).getByLabelText(/^Alasan/), "nonaktifkan user"); await actor.click(within(dialog).getByRole("button", { name: "Konfirmasi" })); await waitFor(() => expect(state.lifecycle).toHaveBeenCalledOnce()); expect(state.lifecycle.mock.calls[0][0]).toMatchObject({ objectId: "usr-1", currentVersion: 2, target: "Inactive", reason: "nonaktifkan user", actor: { userId: "usr-actor" } }); expect(screen.getByText(/Dinonaktifkan.*corr-success/)).toBeVisible(); expect(screen.queryByRole("dialog", { name: "Nonaktifkan pengguna" })).not.toBeInTheDocument(); });
  it("keeps lifecycle review on cancellation and does not show false error", async () => { state.lifecycle.mockRejectedValue(new DOMException("cancel", "AbortError")); const actor = userEvent.setup(); render(<AdminDetailPage kind="roles" id="role-view" />); await actor.click(screen.getByRole("button", { name: "Nonaktifkan" })); await actor.type(screen.getByLabelText(/^Alasan/), "cancel role"); await actor.click(screen.getByRole("button", { name: "Konfirmasi" })); await waitFor(() => expect(state.lifecycle).toHaveBeenCalledOnce()); expect(screen.getByRole("dialog", { name: "Nonaktifkan role" })).toBeVisible(); expect(screen.queryByText(/ID korelasi/)).not.toBeInTheDocument(); });
  it.each([["users", "USER_ASSIGNMENT_INVALID"], ["roles", "ROLE_IN_USE"], ["users", "USER_STATE_INVALID"], ["roles", "ROLE_STATE_INVALID"]] as const)("renders non-retryable 422 %s %s lifecycle failure without a second mutation", async (kind, code) => { state.lifecycle.mockRejectedValue(new AppError(422, code, "Perubahan status tidak valid.", { target: ["Periksa dependency."] }, false, `corr-${kind}`)); const actor = userEvent.setup(); render(<AdminDetailPage kind={kind} id={kind === "users" ? "usr-1" : "role-view"} />); await actor.click(screen.getByRole("button", { name: "Nonaktifkan" })); const dialog = screen.getByRole("dialog"); await actor.type(within(dialog).getByLabelText(/^Alasan/), `alasan ${kind}`); await actor.click(within(dialog).getByRole("button", { name: "Konfirmasi" })); await waitFor(() => expect(screen.getByText(new RegExp(code))).toBeVisible()); expect(screen.getByText(new RegExp(`corr-${kind}`))).toBeVisible(); expect(screen.queryByRole("button", { name: "Coba lagi" })).not.toBeInTheDocument(); expect(screen.queryByText(/berhasil/i)).not.toBeInTheDocument(); expect(state.lifecycle).toHaveBeenCalledOnce(); if (kind === "roles") expect(screen.getAllByText(/4 pengguna/).length).toBeGreaterThan(0); });
  it.each(["users", "roles"] as const)("renders typed SoD metadata for %s activation and prevents retry or force overwrite", async kind => { state.status = "Inactive"; state.lifecycle.mockRejectedValue(new AppError(422, "SOD_CONFLICT", "Kombinasi permission konflik.", {}, false, `corr-sod-${kind}`, { findings: [{ ruleId: "SOD-ADMIN-FINAL-APPROVAL", severity: "Critical", permissionKeys: ["access.manage", "pic.approve"], explanation: "Pengelola akses tidak boleh menjadi final approver.", guidance: "Pisahkan tanggung jawab.", blocking: true }] })); const actor = userEvent.setup(); render(<AdminDetailPage kind={kind} id={kind === "users" ? "usr-1" : "role-view"} />); await actor.click(screen.getByRole("button", { name: "Aktifkan" })); await actor.type(screen.getByLabelText(/^Alasan/), `aktivasi ${kind}`); await actor.click(screen.getByRole("button", { name: "Konfirmasi" })); await waitFor(() => expect(screen.getByText(/SOD-ADMIN-FINAL-APPROVAL/)).toBeVisible()); expect(screen.getByText(/access.manage \+ pic.approve/)).toBeVisible(); expect(screen.getByText(/Pengelola akses/)).toBeVisible(); expect(screen.getByText(/Pisahkan tanggung jawab/)).toBeVisible(); expect(screen.getByText(/Blocking: ya/)).toBeVisible(); expect(screen.queryByRole("button", { name: /Coba lagi|Timpa/ })).not.toBeInTheDocument(); expect(state.lifecycle).toHaveBeenCalledOnce(); });
  it.each(["users", "roles"] as const)("renders safe 403 for %s lifecycle without retry or success", async kind => { state.lifecycle.mockRejectedValue(new AppError(403, "ACCESS_FORBIDDEN", "Anda tidak berwenang.", {}, false, `corr-403-${kind}`)); const actor = userEvent.setup(); render(<AdminDetailPage kind={kind} id={kind === "users" ? "usr-1" : "role-view"} />); await actor.click(screen.getByRole("button", { name: "Nonaktifkan" })); await actor.type(screen.getByLabelText(/^Alasan/), "rahasia alasan"); await actor.click(screen.getByRole("button", { name: "Konfirmasi" })); await waitFor(() => expect(screen.getByText(/ACCESS_FORBIDDEN/)).toBeVisible()); const alert = screen.getByRole("alert"); expect(within(alert).getAllByText(/Anda tidak berwenang/).length).toBeGreaterThan(0); expect(alert).not.toHaveTextContent("rahasia alasan"); expect(screen.queryByRole("button", { name: "Coba lagi" })).not.toBeInTheDocument(); expect(state.lifecycle).toHaveBeenCalledOnce(); });
  it.each(["users", "roles"] as const)("retries %s lifecycle 503 once with an identical versioned command", async kind => { state.lifecycle.mockRejectedValueOnce(new AppError(503, "SERVICE_UNAVAILABLE", "Layanan sementara gagal.", {}, true, `corr-503-${kind}`)).mockResolvedValueOnce({ objectId: "target", version: 4, message: "Status berhasil diubah", correlationId: "corr-ok" }); const actor = userEvent.setup(); render(<AdminDetailPage kind={kind} id={kind === "users" ? "usr-1" : "role-view"} />); await actor.click(screen.getByRole("button", { name: "Nonaktifkan" })); await actor.type(screen.getByLabelText(/^Alasan/), `retry ${kind}`); await actor.click(screen.getByRole("button", { name: "Konfirmasi" })); await waitFor(() => expect(screen.getByRole("button", { name: "Coba lagi" })).toBeVisible()); expect(screen.getByText(new RegExp(`corr-503-${kind}`))).toBeVisible(); await actor.click(screen.getByRole("button", { name: "Coba lagi" })); await waitFor(() => expect(screen.getByText(/Status berhasil diubah/)).toBeVisible()); expect(state.lifecycle).toHaveBeenCalledTimes(2); expect(state.lifecycle.mock.calls[1]?.[0]).toEqual(state.lifecycle.mock.calls[0]?.[0]); });
  it("keeps User detail visible when audit query is cancelled without false recovery metadata", () => { state.audit = "cancel"; render(<AdminDetailPage kind="users" id="usr-1" />); expect(screen.getByRole("heading", { name: "Dewi Sari" })).toBeVisible(); expect(screen.getByLabelText("Memuat data")).toBeVisible(); expect(screen.queryByRole("button", { name: "Coba lagi audit" })).not.toBeInTheDocument(); expect(screen.queryByText(/ID korelasi/)).not.toBeInTheDocument(); });
});
