"use client";

import { faArrowDown, faArrowUp, faPlus, faRotate } from "@fortawesome/free-solid-svg-icons";
import { columnVisibilityFeature, createColumnHelper, tableFeatures, useTable } from "@tanstack/react-table";
import Link from "next/link";
import { usePathname, useRouter, useSearchParams } from "next/navigation";
import { useCallback, useEffect, useMemo, useState } from "react";
import { AppIcon, Badge, Button, Card, DataState, LoadingState, PageHeader, StatusBadge, TableShell } from "@/components/ui";
import { formatDate } from "@/lib/formatters";
import { normalizeAccessListQuery } from "../domain/logic";
import type { NormalizedAccessListQuery, RoleListItem, UserListItem } from "../domain/types";
import { useAccessPersona } from "../permissions/demo-access";
import { useAccessRoles, useAccessUsers } from "../queries/hooks";

const features = tableFeatures({ columnVisibilityFeature }), userHelper = createColumnHelper<typeof features, UserListItem>(), roleHelper = createColumnHelper<typeof features, RoleListItem>();
type Update = (changes: Readonly<Record<string, string | undefined>>) => void;

export function AdminListPage({ kind }: { kind: "users" | "roles" }) {
  const access = useAccessPersona(), params = useSearchParams(), router = useRouter(), pathname = usePathname();
  const query = useMemo(() => normalizeAccessListQuery({ search: params.get("search") ?? undefined, statuses: params.get("status") ? [params.get("status") as "Active" | "Inactive"] : [], roleIds: params.getAll("role"), sort: (params.get("sort") as "name" | "status" | "updatedAt") ?? undefined, direction: params.get("direction") === "asc" ? "asc" : "desc", page: Number(params.get("page") || 1), pageSize: Number(params.get("pageSize") || 20) }), [params]);
  const [search, setSearch] = useState(query.search), users = useAccessUsers(query, access.canView && kind === "users"), roles = useAccessRoles(query, access.canView && kind === "roles"), roleOptions = useAccessRoles({ sort: "name", direction: "asc", pageSize: 50 }, access.canView && kind === "users"), result = kind === "users" ? users : roles;
  const update = useCallback<Update>(changes => { const next = new URLSearchParams(params); for (const [key, value] of Object.entries(changes)) { next.delete(key); if (value) value.split(",").forEach(item => next.append(key, item)); } next.set("access", access.access); router.replace(`${pathname}?${next}`, { scroll: false }); }, [access.access, params, pathname, router]);
  useEffect(() => { const timer = setTimeout(() => { const normalizedSearch = search.trim(); if (normalizedSearch.toLocaleLowerCase("id-ID") !== query.search) update({ search: normalizedSearch || undefined, page: undefined }); }, 350); return () => clearTimeout(timer); }, [query.search, search, update]);
  if (!access.canView) return <DataState kind="denied" title="Akses administrasi ditolak" />;
  if (result.isPending || (kind === "users" && roleOptions.isPending)) return <LoadingState />;
  if (result.isError) return <DataState kind={result.error.status === 403 ? "denied" : "server"} correlationId={result.error.correlation_id} action={result.error.retryable ? <Button onClick={() => result.refetch()}>Coba lagi</Button> : undefined} />;
  const data = result.data, totalPages = data.total ? Math.ceil(data.total / data.pageSize) : 0, filtered = Boolean(query.search || query.statuses.length || query.roleIds.length), reset = () => { setSearch(""); router.replace(access.url(pathname)); };
  return <><PageHeader eyebrow="Access Management" title={kind === "users" ? "Pengguna" : "Role dan Permission"} description="Simulasi UI demo; authorization backend tetap authoritative." meta={<Badge tone="warning">Data demo</Badge>} actions={access.canManage ? <Link className="button button-primary" href={access.url(`${pathname}/new`)}><AppIcon icon={faPlus} />Tambah {kind === "users" ? "user" : "role"}</Link> : undefined} /><Card className="filter-card"><div className="project-filters"><label><span>Cari</span><input aria-label="Cari" value={search} onChange={event => setSearch(event.target.value)} /></label><label><span>Status</span><select aria-label="Status" value={query.statuses[0] ?? ""} onChange={event => update({ status: event.target.value || undefined, page: undefined })}><option value="">Semua</option><option>Active</option><option>Inactive</option></select></label>{kind === "users" && <label><span>Role</span><select aria-label="Role" value={query.roleIds[0] ?? ""} onChange={event => update({ role: event.target.value || undefined, page: undefined })}><option value="">Semua role</option>{roleOptions.data?.items.map(role => <option key={role.id} value={role.id}>{role.name}</option>)}</select></label>}<Button variant="secondary" leadingIcon={<AppIcon icon={faRotate} />} onClick={reset}>Reset filter</Button></div></Card><Card>{data.items.length === 0 ? <DataState kind={filtered ? "zero" : "empty"} action={filtered ? <Button onClick={reset}>Reset filter</Button> : undefined} /> : kind === "users" ? <UserTable data={users.data!.items} query={query} update={update} accessUrl={access.url} /> : <RoleTable data={roles.data!.items} query={query} update={update} accessUrl={access.url} />}<div className="pagination"><label>Ukuran halaman <select aria-label="Ukuran halaman" value={query.pageSize} onChange={event => update({ pageSize: event.target.value, page: undefined })}><option>10</option><option>20</option><option>50</option></select></label><Button variant="secondary" disabled={query.page <= 1} onClick={() => update({ page: String(query.page - 1) })}>Sebelumnya</Button><span>Halaman {data.total ? query.page : 0} dari {totalPages} · {data.total} hasil</span><Button variant="secondary" disabled={!data.hasNextPage} onClick={() => update({ page: String(query.page + 1) })}>Berikutnya</Button></div></Card></>;
}

function SortHeader({ id, label, query, update }: { id: "name" | "status" | "updatedAt"; label: string; query: NormalizedAccessListQuery; update: Update }) { const current = query.sort === id; return <th scope="col" aria-sort={current ? query.direction === "asc" ? "ascending" : "descending" : "none"}><button className="sort-button" onClick={() => update({ sort: id, direction: current && query.direction === "asc" ? "desc" : "asc", page: undefined })}>{label}<AppIcon icon={current && query.direction === "asc" ? faArrowUp : faArrowDown} /></button></th>; }

function UserTable({ data, query, update, accessUrl }: { data: readonly UserListItem[]; query: NormalizedAccessListQuery; update: Update; accessUrl: (path: string) => string }) {
  const columns = useMemo(() => userHelper.columns([userHelper.accessor("name", { header: "Pengguna", cell: ({ row }) => <><strong>{row.original.name}</strong><small className="table-subtext">{row.original.employeeId} · {row.original.email}</small></> }), userHelper.accessor("roleNames", { header: "Role", cell: ({ getValue }) => getValue().join(", ") }), userHelper.accessor("status", { header: "Status", cell: ({ getValue }) => <StatusBadge tone={getValue() === "Active" ? "success" : "neutral"}>{getValue()}</StatusBadge> }), userHelper.accessor("effectivePermissions", { header: "Effective", cell: ({ getValue }) => `${getValue().length} permission` }), userHelper.accessor("updatedAt", { header: "Diperbarui", cell: ({ getValue }) => formatDate(getValue(), true) }), userHelper.display({ id: "action", header: "Tindakan", cell: ({ row }) => <Link href={accessUrl(`/admin/users/${row.original.id}`)}>Buka</Link> })]), [accessUrl]);
  const table = useTable({ features, columns, data: [...data], getRowId: row => row.id });
  return <><div className="table-toolbar"><span>Atur tampilan</span><details><summary>Kolom</summary>{table.getAllLeafColumns().filter(column => !["name", "action"].includes(column.id)).map(column => <label key={column.id}><input type="checkbox" aria-label={`Tampilkan kolom ${column.id}`} checked={column.getIsVisible()} onChange={column.getToggleVisibilityHandler()} />{String(column.columnDef.header)}</label>)}</details></div><TableShell caption="Daftar pengguna"><thead><tr><SortHeader id="name" label="Pengguna" query={query} update={update} />{table.getAllLeafColumns().filter(column => column.getIsVisible() && !["name", "status", "updatedAt"].includes(column.id)).map(column => <th key={column.id} scope="col">{String(column.columnDef.header)}</th>)}{table.getColumn("status")?.getIsVisible() && <SortHeader id="status" label="Status" query={query} update={update} />}{table.getColumn("updatedAt")?.getIsVisible() && <SortHeader id="updatedAt" label="Diperbarui" query={query} update={update} />}</tr></thead><tbody>{table.getRowModel().rows.map(row => <tr key={row.id}>{row.getVisibleCells().map(cell => <td key={cell.id}><table.FlexRender cell={cell} /></td>)}</tr>)}</tbody></TableShell><MobileUsers data={data} accessUrl={accessUrl} /></>;
}

function RoleTable({ data, query, update, accessUrl }: { data: readonly RoleListItem[]; query: NormalizedAccessListQuery; update: Update; accessUrl: (path: string) => string }) {
  const columns = useMemo(() => roleHelper.columns([roleHelper.accessor("name", { header: "Role", cell: ({ row }) => <><strong>{row.original.name}</strong><small className="table-subtext">{row.original.code}</small></> }), roleHelper.accessor("status", { header: "Status", cell: ({ getValue }) => <StatusBadge tone={getValue() === "Active" ? "success" : "neutral"}>{getValue()}</StatusBadge> }), roleHelper.accessor("permissionKeys", { header: "Permission", cell: ({ getValue }) => getValue().length }), roleHelper.accessor("userCount", { header: "Pengguna" }), roleHelper.accessor("sodFindings", { header: "SoD", cell: ({ getValue }) => <StatusBadge tone={getValue().length ? "danger" : "success"}>{getValue().length ? "Konflik" : "Aman"}</StatusBadge> }), roleHelper.display({ id: "action", header: "Tindakan", cell: ({ row }) => <Link href={accessUrl(`/admin/roles/${row.original.id}`)}>Buka</Link> })]), [accessUrl]);
  const table = useTable({ features, columns, data: [...data], getRowId: row => row.id });
  return <><div className="table-toolbar"><span>Atur tampilan</span><details><summary>Kolom</summary>{table.getAllLeafColumns().filter(column => !["name", "action"].includes(column.id)).map(column => <label key={column.id}><input type="checkbox" aria-label={`Tampilkan kolom ${column.id}`} checked={column.getIsVisible()} onChange={column.getToggleVisibilityHandler()} />{String(column.columnDef.header)}</label>)}</details></div><TableShell caption="Daftar role"><thead><tr><SortHeader id="name" label="Role" query={query} update={update} />{table.getAllLeafColumns().filter(column => column.getIsVisible() && !["name", "status"].includes(column.id)).map(column => <th key={column.id} scope="col">{String(column.columnDef.header)}</th>)}{table.getColumn("status")?.getIsVisible() && <SortHeader id="status" label="Status" query={query} update={update} />}</tr></thead><tbody>{table.getRowModel().rows.map(row => <tr key={row.id}>{row.getVisibleCells().map(cell => <td key={cell.id}><table.FlexRender cell={cell} /></td>)}</tr>)}</tbody></TableShell><div className="project-mobile-list">{data.map(item => <article key={item.id}><StatusBadge tone={item.status === "Active" ? "success" : "neutral"}>{item.status}</StatusBadge><strong>{item.name}</strong><small>{item.code} · {item.permissionKeys.length} permission · {item.userCount} pengguna</small><Link href={accessUrl(`/admin/roles/${item.id}`)}>Buka detail</Link></article>)}</div></>;
}

function MobileUsers({ data, accessUrl }: { data: readonly UserListItem[]; accessUrl: (path: string) => string }) { return <div className="project-mobile-list">{data.map(item => <article key={item.id}><StatusBadge tone={item.status === "Active" ? "success" : "neutral"}>{item.status}</StatusBadge><strong>{item.name}</strong><small>{item.employeeId} · {item.roleNames.join(", ")}</small><Link href={accessUrl(`/admin/users/${item.id}`)}>Buka detail</Link></article>)}</div>; }
