import { act, fireEvent, render, screen } from "@testing-library/react";
import userEvent from "@testing-library/user-event";
import { afterEach, beforeEach, describe, expect, it, vi } from "vitest";
import { AppError } from "@/features/foundation/domain/errors";
import { AdminListPage } from "./admin-list-page";

type StateKind = "data" | "loading" | "empty" | "error" | "cancel";
const state = vi.hoisted(() => ({ persona: "manage" as "manage" | "view" | "none", kind: "data" as StateKind, search: "access=manage", pathname: "/admin/users", page: 1, pageSize: 20, total: 1, hasNextPage: false, replace: vi.fn(), refetch: vi.fn(), usersEnabled: vi.fn(), rolesEnabled: vi.fn(), usersQuery: vi.fn() }));
const role = { id: "role-view", code: "VIEW", name: "Viewer", description: "View", status: "Active" as const, permissionKeys: ["access.view"], isSystem: false, createdAt: "2026-08-10T00:00:00+07:00", updatedAt: "2026-08-10T00:00:00+07:00", version: 2, userCount: 2, sodFindings: [] };
const user = { id: "usr-1", employeeId: "EMP-001", name: "Dewi Sari", email: "dewi@example.test", status: "Active" as const, roleIds: [role.id], projectScopeIds: [], createdAt: role.createdAt, updatedAt: role.updatedAt, version: 2, roleNames: [role.name], effectivePermissions: ["access.view"] };
const result = <T,>(items: readonly T[]) => state.kind === "loading" || state.kind === "cancel" ? { data: undefined, isPending: true, isError: false, error: null, refetch: state.refetch } : state.kind === "error" ? { data: undefined, isPending: false, isError: true, error: new AppError(503, "SERVICE_UNAVAILABLE", "Tidak tersedia.", {}, true, "corr-list"), refetch: state.refetch } : { data: { items: state.kind === "empty" ? [] : items, total: state.kind === "empty" ? 0 : state.total, page: state.page, pageSize: state.pageSize, hasNextPage: state.hasNextPage }, isPending: false, isError: false, error: null, refetch: state.refetch };

vi.mock("next/navigation", () => ({ useRouter: () => ({ replace: state.replace }), usePathname: () => state.pathname, useSearchParams: () => new URLSearchParams(state.search) }));
vi.mock("../permissions/demo-access", () => ({ useAccessPersona: () => ({ access: state.persona, canView: state.persona !== "none", canManage: state.persona === "manage", url: (path: string) => `${path}?access=${state.persona}` }) }));
vi.mock("../queries/hooks", () => ({ useAccessUsers: (query: unknown, enabled: boolean) => { state.usersQuery(query); state.usersEnabled(enabled); return result([user]); }, useAccessRoles: (_query: unknown, enabled: boolean) => { state.rolesEnabled(enabled); return result([role]); } }));

beforeEach(() => { state.persona = "manage"; state.kind = "data"; state.search = "access=manage"; state.pathname = "/admin/users"; state.page = 1; state.pageSize = 20; state.total = 1; state.hasNextPage = false; state.replace.mockReset(); state.refetch.mockReset(); state.usersEnabled.mockReset(); state.rolesEnabled.mockReset(); state.usersQuery.mockReset(); });
afterEach(() => vi.useRealTimers());

describe("AdminListPage acceptance", () => {
  it("renders equivalent semantic User table and mobile representation with persona links", () => { render(<AdminListPage kind="users" />); expect(screen.getByRole("table", { name: "Daftar pengguna" })).toBeVisible(); expect(screen.getByRole("columnheader", { name: /Pengguna/ })).toHaveAttribute("aria-sort", "none"); expect(screen.getAllByText("Dewi Sari")).toHaveLength(2); expect(screen.getAllByText("Active").length).toBeGreaterThanOrEqual(2); expect(screen.getByRole("link", { name: "Buka" })).toHaveAttribute("href", "/admin/users/usr-1?access=manage"); expect(screen.getByRole("link", { name: "Buka detail" })).toHaveAttribute("href", "/admin/users/usr-1?access=manage"); });
  it("renders Role usage, permission, SoD and mobile representation", () => { state.pathname = "/admin/roles"; render(<AdminListPage kind="roles" />); expect(screen.getByRole("table", { name: "Daftar role" })).toBeVisible(); expect(screen.getAllByText("Viewer")).toHaveLength(2); expect(screen.getAllByText("Aman").length).toBeGreaterThan(0); expect(screen.getAllByText(/1 permission/).length).toBeGreaterThan(0); expect(screen.getByRole("link", { name: "Buka detail" })).toHaveAttribute("href", "/admin/roles/role-view?access=manage"); });
  it("distinguishes loading, cancellation, empty and filtered zero states", () => { state.kind = "loading"; const view = render(<AdminListPage kind="users" />); expect(screen.getByLabelText("Memuat data")).toBeVisible(); view.unmount(); state.kind = "cancel"; render(<AdminListPage kind="users" />); expect(screen.getByLabelText("Memuat data")).toBeVisible(); expect(screen.queryByText(/server/i)).not.toBeInTheDocument(); });
  it("renders authoritative empty and filtered zero states", () => { state.kind = "empty"; const view = render(<AdminListPage kind="users" />); expect(screen.getByText("Belum ada data")).toBeVisible(); expect(screen.getByText(/Halaman 0 dari 0/)).toBeVisible(); view.unmount(); state.search = "access=manage&search=missing"; render(<AdminListPage kind="users" />); expect(screen.getByText("Tidak ada hasil")).toBeVisible(); expect(screen.getAllByRole("button", { name: "Reset filter" })).toHaveLength(2); });
  it("retries retryable server errors", async () => { state.kind = "error"; render(<AdminListPage kind="roles" />); expect(screen.getByText(/corr-list/)).toBeVisible(); await userEvent.click(screen.getByRole("button", { name: "Coba lagi" })); expect(state.refetch).toHaveBeenCalledOnce(); });
  it("enforces manage, view, and none personas with query suppression", () => { state.persona = "view"; const view = render(<AdminListPage kind="users" />); expect(screen.queryByRole("link", { name: /Tambah user/ })).not.toBeInTheDocument(); expect(screen.getByRole("link", { name: "Buka" })).toHaveAttribute("href", "/admin/users/usr-1?access=view"); view.unmount(); state.persona = "none"; render(<AdminListPage kind="users" />); expect(screen.getByText("Akses administrasi ditolak")).toBeVisible(); expect(screen.queryByText(user.email)).not.toBeInTheDocument(); expect(state.usersEnabled).toHaveBeenLastCalledWith(false); });
  it("debounces normalized search and resets page while retaining persona", async () => { vi.useFakeTimers(); state.search = "access=manage&page=3"; render(<AdminListPage kind="users" />); fireEvent.change(screen.getByRole("textbox", { name: "Cari" }), { target: { value: "  DEWI  " } }); await act(async () => { vi.advanceTimersByTime(350); }); expect(state.replace).toHaveBeenLastCalledWith(expect.stringMatching(/search=DEWI.*access=manage|access=manage.*search=DEWI/), { scroll: false }); expect(state.replace.mock.calls.at(-1)?.[0]).not.toContain("page=3"); });
  it("updates filters, sorting, pagination, page size, reset, and column visibility accessibly", async () => { const actor = userEvent.setup(); state.search = "access=manage&page=2&status=Active"; render(<AdminListPage kind="users" />); await actor.selectOptions(screen.getByRole("combobox", { name: "Status" }), "Inactive"); expect(state.replace.mock.calls.at(-1)?.[0]).toContain("status=Inactive"); await actor.click(screen.getByRole("button", { name: /Pengguna/ })); expect(state.replace.mock.calls.at(-1)?.[0]).toContain("sort=name"); await actor.selectOptions(screen.getByRole("combobox", { name: "Ukuran halaman" }), "50"); expect(state.replace.mock.calls.at(-1)?.[0]).toContain("pageSize=50"); const visibility = screen.getByRole("checkbox", { name: "Tampilkan kolom roleNames" }); await actor.click(visibility); expect(visibility).not.toBeChecked(); expect(screen.getAllByText("Dewi Sari")).toHaveLength(2); await actor.click(screen.getByRole("button", { name: "Reset filter" })); expect(state.replace).toHaveBeenLastCalledWith("/admin/users?access=manage"); });
  it("applies and clears the User role filter while preserving normalized URL state", async () => { const actor = userEvent.setup(); state.search = "access=manage&page=3&search=dewi&status=Active&sort=updatedAt&direction=desc&pageSize=50"; const view = render(<AdminListPage kind="users" />); expect(screen.getByRole("option", { name: "Viewer" })).toHaveValue("role-view"); await actor.selectOptions(screen.getByRole("combobox", { name: "Role" }), "role-view"); const selected = String(state.replace.mock.calls.at(-1)?.[0]); expect(selected).toContain("role=role-view"); expect(selected).toContain("search=dewi"); expect(selected).toContain("status=Active"); expect(selected).toContain("sort=updatedAt"); expect(selected).toContain("direction=desc"); expect(selected).toContain("pageSize=50"); expect(selected).toContain("access=manage"); expect(selected).not.toContain("page=3"); view.unmount(); state.search = selected.split("?")[1] ?? ""; render(<AdminListPage kind="users" />); expect(state.usersQuery).toHaveBeenLastCalledWith(expect.objectContaining({ roleIds: ["role-view"] })); await actor.selectOptions(screen.getByRole("combobox", { name: "Role" }), ""); expect(String(state.replace.mock.calls.at(-1)?.[0])).not.toContain("role="); });
  it.each(["users", "roles"] as const)("navigates %s pages and preserves list parameters", async kind => { const actor = userEvent.setup(); state.pathname = `/admin/${kind}`; state.search = "access=view&page=2&search=ops&status=Active&sort=name&direction=asc&pageSize=10"; state.page = 2; state.pageSize = 10; state.total = 25; state.hasNextPage = true; render(<AdminListPage kind={kind} />); expect(screen.getByText(/Halaman 2 dari 3/)).toBeVisible(); await actor.click(screen.getByRole("button", { name: "Berikutnya" })); const next = String(state.replace.mock.calls.at(-1)?.[0]); expect(next).toContain("page=3"); for (const value of ["access=manage", "search=ops", "status=Active", "sort=name", "direction=asc", "pageSize=10"]) expect(next).toContain(value); await actor.click(screen.getByRole("button", { name: "Sebelumnya" })); expect(String(state.replace.mock.calls.at(-1)?.[0])).toContain("page=1"); });
  it("disables pagination boundaries and normalizes invalid page and page size", () => { state.search = "access=manage&page=0&pageSize=999"; render(<AdminListPage kind="users" />); expect(screen.getByRole("button", { name: "Sebelumnya" })).toBeDisabled(); expect(screen.getByRole("button", { name: "Berikutnya" })).toBeDisabled(); expect(screen.getByRole("combobox", { name: "Ukuran halaman" })).toHaveValue("20"); expect(state.usersQuery).toHaveBeenLastCalledWith(expect.objectContaining({ page: 1, pageSize: 20 })); expect(screen.getAllByRole("option").filter(option => ["10", "20", "50"].includes(option.textContent ?? "")).map(option => option.textContent)).toEqual(expect.arrayContaining(["10", "20", "50"])); });
});
