import type { DocumentObjectType } from "@/features/foundation/domain/models";
import type { DocumentCategory,DocumentProcessingStatus,ManagedDocument,ManagedDocumentVersion,UploadMetadata } from "./types";
export const DOCUMENT_MAX_SIZE_BYTES=5*1024*1024;
export const DOCUMENT_MIME_TYPES=["application/pdf","image/jpeg","image/png"] as const;
export function safeFileName(input:string){const basename=input.replace(/\\/g,"/").split("/").at(-1)?.trim()??"";if(!basename||basename.length>180||/[\u0000-\u001f\u007f]/.test(basename))return undefined;return basename;}
export function validateUploadMetadata(input:UploadMetadata){const errors:Record<string,string[]>={},filename=safeFileName(input.originalFileName);if(!filename)errors.originalFileName=["Nama file tidak valid atau terlalu panjang."];if(!DOCUMENT_MIME_TYPES.includes(input.mimeType as typeof DOCUMENT_MIME_TYPES[number]))errors.mimeType=["Tipe file harus PDF, JPEG, atau PNG."];const extension=filename?.split(".").at(-1)?.toLocaleLowerCase("id-ID"),expected:Readonly<Record<string,readonly string[]>>={"application/pdf":["pdf"],"image/jpeg":["jpg","jpeg"],"image/png":["png"]};if(filename&&expected[input.mimeType]&&(!extension||!expected[input.mimeType].includes(extension)))errors.originalFileName=["Ekstensi file tidak konsisten dengan MIME type."];if(!Number.isInteger(input.sizeBytes)||input.sizeBytes<=0)errors.sizeBytes=["Ukuran file harus lebih dari nol."];else if(input.sizeBytes>DOCUMENT_MAX_SIZE_BYTES)errors.sizeBytes=["Ukuran file maksimal 5 MB pada baseline mock."];return{valid:Object.keys(errors).length===0,errors,normalized:filename?{...input,originalFileName:filename,displayFileName:filename}:undefined};}
export function normalizeDocumentListQuery(input:import("./types").DocumentListQuery={}):import("./types").NormalizedDocumentListQuery{return{search:(input.search??"").trim().toLocaleLowerCase("id-ID"),categories:[...new Set(input.categories??[])].sort(),statuses:[...new Set(input.statuses??[])].sort(),processingStatuses:[...new Set(input.processingStatuses??[])].sort(),completeness:input.completeness??"all",sort:input.sort??"updatedAt",direction:input.direction??"desc",page:Math.max(1,Math.trunc(input.page??1)),pageSize:[10,20,50].includes(input.pageSize??20)?input.pageSize??20:20};}

const CATEGORY_POLICY:Readonly<Record<DocumentObjectType,readonly DocumentCategory[]>>={Project:["Project Brief","Other"],SPH:["Contract","Other"],RateVersion:["Rate Support","Other"]};
export const allowedDocumentCategories=(type:DocumentObjectType)=>CATEGORY_POLICY[type];
export const defaultDocumentCategory=(type:DocumentObjectType)=>CATEGORY_POLICY[type][0];
const TRANSITIONS:Readonly<Record<DocumentProcessingStatus,readonly DocumentProcessingStatus[]>>={Pending:["Scanning","Clean","Rejected","Failed"],Scanning:["Clean","Rejected","Failed"],Clean:[],Rejected:[],Failed:[]};
export const allowedDocumentVersionTransitions=(from:DocumentProcessingStatus)=>TRANSITIONS[from]??[];
export const canTransitionDocumentVersion=(from:DocumentProcessingStatus,to:DocumentProcessingStatus)=>allowedDocumentVersionTransitions(from).includes(to);
export function hasCurrentCleanVersion(document:ManagedDocument,versions:readonly ManagedDocumentVersion[]){const current=versions.find((item)=>item.id===document.currentVersionId);return Boolean(current&&current.documentId===document.id&&current.isCurrent&&current.processingStatus==="Clean"&&current.scanStatus==="Clean"&&current.validationStatus==="Valid");}
export function assertDocumentInvariant(document:ManagedDocument,versions:readonly ManagedDocumentVersion[]){const owned=versions.filter((item)=>item.documentId===document.id),current=owned.filter((item)=>item.isCurrent);if(current.length>1)throw new Error("DOCUMENT_INVARIANT_MULTIPLE_CURRENT");if(document.currentVersionId&&!hasCurrentCleanVersion(document,owned))throw new Error("DOCUMENT_INVARIANT_CURRENT_INVALID");if(!document.currentVersionId&&current.length)throw new Error("DOCUMENT_INVARIANT_POINTER_MISSING");}
