import { describe,expect,it } from "vitest";
import type { AuditEvent,Project,ProjectBranch,Service } from "@/features/foundation/domain/models";
import * as seed from "@/features/foundation/infrastructure/mock/seed";
import { createRateRepository } from "./mock-adapter";
const manager={userId:"usr-raka",permissionKeys:["rate.view","rate.manage","rate.activate"]};
const editor={userId:"usr-dewi",permissionKeys:["rate.view","rate.manage"]};
const data={effectiveFrom:"2026-09-01",effectiveTo:"2026-12-31",reason:"Rate masa depan",notes:"Demo",lines:[{serviceId:"svc-fm",branchId:"br-jkt",rateType:"Fixed Amount" as const,amount:"13000000.50",currency:"IDR" as const,unit:"Person-month",notes:""}]};
function repo(options:{projects?:readonly Project[];services?:readonly Service[];branches?:readonly ProjectBranch[];audits?:AuditEvent[];currentDate?:string}={}){const audits=options.audits??[];return{value:createRateRepository({projects:options.projects??seed.projects.map((item)=>({...item})),contracts:structuredClone(seed.contracts),branches:options.branches??structuredClone(seed.branches),services:options.services??structuredClone(seed.services),customers:seed.customers,users:seed.users,audits,currentDate:options.currentDate??"2026-08-10"}),audits};}
type ReferenceMutation="service-inactive"|"service-outside"|"service-missing"|"branch-inactive"|"branch-outside"|"branch-missing";
function mutableReferenceRepo(){let projects=seed.projects.map((item)=>structuredClone(item)),services=seed.services.map((item)=>structuredClone(item)),branches=seed.branches.map((item)=>structuredClone(item));const audits:AuditEvent[]=[],value=createRateRepository({projects,services,branches,contracts:structuredClone(seed.contracts),customers:seed.customers,users:seed.users,audits,currentDate:"2026-09-01",references:{getProjects:()=>projects,getServices:()=>services,getBranches:()=>branches}});return{value,audits,mutate(kind:ReferenceMutation){switch(kind){case"service-inactive":services=services.map((item)=>item.id==="svc-fm"?{...item,isActive:false}:item);break;case"service-outside":projects=projects.map((item)=>item.id==="prj-026"?{...item,serviceIds:[]}:item);break;case"service-missing":services=services.filter((item)=>item.id!=="svc-fm");break;case"branch-inactive":branches=branches.map((item)=>item.id==="br-jkt"?{...item,isActive:false}:item);break;case"branch-outside":branches=branches.map((item)=>item.id==="br-jkt"?{...item,projectId:"prj-019"}:item);break;case"branch-missing":branches=branches.filter((item)=>item.id!=="br-jkt");}}};}

describe("rate mock repository remediation",()=>{
 it("paginates and sorts while summary and timeline remain authoritative",async()=>{const {value}=repo();await value.createDraft({projectId:"prj-026",data,actor:editor});const filtered=await value.list("prj-026",{statuses:["Draft"],page:1,pageSize:1,sort:"versionNumber",direction:"desc"});expect(filtered.items).toHaveLength(1);expect(filtered.hasNextPage).toBe(false);expect(filtered.summary.current).toMatchObject({versionNumber:2});expect(filtered.timeline).toHaveLength(3);expect(filtered.summary).toMatchObject({futureCount:1,historicalCount:1,draftCount:1});const zero=await value.list("prj-026",{search:"tidak-ada",pageSize:1});expect(zero.items).toHaveLength(0);expect(zero.summary.current?.versionNumber).toBe(2);expect(zero.timeline).toHaveLength(3);});
 it("supports page one/page two and ascending/descending repository sorting",async()=>{const {value}=repo();await value.createDraft({projectId:"prj-026",data,actor:editor});const first=await value.list("prj-026",{page:1,pageSize:1,sort:"versionNumber",direction:"asc"}),second=await value.list("prj-026",{page:2,pageSize:1,sort:"versionNumber",direction:"asc"}),descending=await value.list("prj-026",{page:1,pageSize:1,sort:"versionNumber",direction:"desc"});expect(first.items[0]?.versionNumber).toBe(1);expect(first.hasNextPage).toBe(true);expect(second.items[0]?.versionNumber).toBe(2);expect(descending.items[0]?.versionNumber).toBe(3);});
 it("uses deterministic clock for effective boundaries",async()=>{expect((await repo({currentDate:"2026-08-10"}).value.getCurrentByProject("prj-026"))?.versionNumber).toBe(2);expect((await repo({currentDate:"2026-06-01"}).value.getCurrentByProject("prj-026"))?.versionNumber).toBe(2);expect((await repo({currentDate:"2026-08-31"}).value.getCurrentByProject("prj-026"))?.versionNumber).toBe(2);const list=await repo({currentDate:"2026-09-01"}).value.list("prj-026",{});expect(list.timeline.find((item)=>item.versionNumber===2)?.effectiveState).toBe("Historical");});
 it("rejects early activation without mutating current, Draft, or audit",async()=>{const audits:AuditEvent[]=[];const {value}=repo({audits}),created=await value.createDraft({projectId:"prj-026",sourceVersionId:"rate-prj-026-v2",data,actor:editor}),count=audits.length;await expect(value.activate({projectId:"prj-026",rateVersionId:created.id,currentVersion:1,reason:"Disetujui",attested:true,actor:manager})).rejects.toMatchObject({status:422,code:"RATE_ACTIVATION_TOO_EARLY"});expect((await value.getById("prj-026",created.id)).rate.status).toBe("Draft");expect((await value.getCurrentByProject("prj-026"))?.versionNumber).toBe(2);expect(audits).toHaveLength(count);});
 it("enforces activation reason, attestation, permission and stale version",async()=>{const {value}=repo({currentDate:"2026-09-01"}),created=await value.createDraft({projectId:"prj-026",data,actor:editor});await expect(value.activate({projectId:"prj-026",rateVersionId:created.id,currentVersion:1,reason:"",attested:true,actor:manager})).rejects.toMatchObject({code:"RATE_ACTIVATION_REASON_REQUIRED"});await expect(value.activate({projectId:"prj-026",rateVersionId:created.id,currentVersion:1,reason:"OK",attested:false,actor:manager})).rejects.toMatchObject({code:"RATE_ATTESTATION_REQUIRED"});await expect(value.activate({projectId:"prj-026",rateVersionId:created.id,currentVersion:1,reason:"OK",attested:true,actor:editor})).rejects.toMatchObject({status:403});await expect(value.activate({projectId:"prj-026",rateVersionId:created.id,currentVersion:0,reason:"OK",attested:true,actor:manager})).rejects.toMatchObject({status:409});});
 it("activates atomically on effective date and audits both versions",async()=>{const audits:AuditEvent[]=[];const {value}=repo({currentDate:"2026-09-01",audits}),created=await value.createDraft({projectId:"prj-026",sourceVersionId:"rate-prj-026-v2",data,actor:editor}),result=await value.activate({projectId:"prj-026",rateVersionId:created.id,currentVersion:1,reason:"Disetujui PIC",attested:true,actor:manager});expect(result.previousActiveId).toBe("rate-prj-026-v2");expect((await value.getCurrentByProject("prj-026"))?.id).toBe(created.id);expect((await value.getById("prj-026","rate-prj-026-v2")).rate.status).toBe("Superseded");expect(audits.map((item)=>item.action)).toEqual(expect.arrayContaining(["rate.activated","rate.superseded"]));});
 it("rejects overlap and terminal project without partial activation",async()=>{const audits:AuditEvent[]=[],activeData={...data,effectiveFrom:"2026-08-01",effectiveTo:"2026-10-01"},{value}=repo({audits}),created=await value.createDraft({projectId:"prj-026",data:activeData,actor:editor}),count=audits.length;await expect(value.activate({projectId:"prj-026",rateVersionId:created.id,currentVersion:1,reason:"OK",attested:true,actor:manager})).rejects.toMatchObject({code:"RATE_OVERLAP"});expect((await value.getById("prj-026",created.id)).rate.status).toBe("Draft");expect(audits).toHaveLength(count);const closed=seed.projects.map((item)=>item.id==="prj-026"?{...item,status:"Closed" as const}:item);await expect(repo({projects:closed}).value.createDraft({projectId:"prj-026",data,actor:editor})).rejects.toMatchObject({code:"INVALID_PROJECT_STATE"});});
 it.each([
  ["unknown service",{...data,lines:[{...data.lines[0],serviceId:"missing"}]},"RATE_SERVICE_INVALID"],
  ["unknown branch",{...data,lines:[{...data.lines[0],branchId:"missing"}]},"RATE_BRANCH_INVALID"],
  ["branch from another project",{...data,lines:[{...data.lines[0],branchId:"br-sby"}]},"RATE_BRANCH_OUTSIDE_PROJECT"],
  ["invalid amount",{...data,lines:[{...data.lines[0],amount:"-1"}]},"RATE_VALUE_INVALID"],
  ["malformed date",{...data,effectiveFrom:"2026-99-01"},"RATE_DATE_INVALID"],
  ["end before start",{...data,effectiveFrom:"2026-12-01",effectiveTo:"2026-09-01"},"RATE_DATE_RANGE_INVALID"],
  ["duplicate scope",{...data,lines:[data.lines[0],data.lines[0]]},"RATE_DUPLICATE_SCOPE"]
 ] as const)("rejects structurally unsafe %s",async(_label,payload,code)=>{await expect(repo().value.createDraft({projectId:"prj-026",data:payload,actor:editor})).rejects.toMatchObject({status:422,code});});
 it("rejects inactive/outside-project services and inactive branches",async()=>{const services=seed.services.map((item)=>item.id==="svc-fm"?{...item,isActive:false}:item);await expect(repo({services}).value.createDraft({projectId:"prj-026",data,actor:editor})).rejects.toMatchObject({code:"RATE_SERVICE_INACTIVE"});const outside=[...seed.services,{id:"svc-other",code:"OTHER",name:"Other",category:"Ops",unit:"Month",isActive:true}];await expect(repo({services:outside}).value.createDraft({projectId:"prj-026",data:{...data,lines:[{...data.lines[0],serviceId:"svc-other"}]},actor:editor})).rejects.toMatchObject({code:"RATE_SERVICE_OUTSIDE_PROJECT"});const branches=seed.branches.map((item)=>item.id==="br-jkt"?{...item,isActive:false}:item);await expect(repo({branches}).value.createDraft({projectId:"prj-026",data,actor:editor})).rejects.toMatchObject({code:"RATE_BRANCH_INACTIVE"});});
 it("keeps historical inactive references readable",async()=>{const services=seed.services.map((item)=>item.id==="svc-fm"?{...item,isActive:false}:item);const detail=await repo({services}).value.getById("prj-026","rate-prj-026-v1");expect(detail.rate.lines[0]?.serviceName).toBe("Facility Management");});
 it.each(["service-inactive","service-outside","service-missing","branch-inactive","branch-outside","branch-missing"] as const)("revalidates %s after Draft is stored without partial activation",async(kind)=>{const fixture=mutableReferenceRepo(),created=await fixture.value.createDraft({projectId:"prj-026",sourceVersionId:"rate-prj-026-v2",data,actor:editor}),beforeAudit=fixture.audits.length;fixture.mutate(kind);const detail=await fixture.value.getById("prj-026",created.id),readiness=await fixture.value.getReadiness("prj-026",created.id);expect(detail.rate.lines[0]).toMatchObject({serviceCode:"SVC-FM",serviceName:"Facility Management",branchName:"Jakarta Selatan"});expect(readiness.ready).toBe(false);expect(readiness.checks.find((item)=>item.code==="CURRENT_REFERENCES")).toMatchObject({complete:false});expect(readiness.referenceValidation.issues[0]).toMatchObject({lineIndex:0,lineId:expect.any(String),referenceId:expect.any(String),nextAction:expect.any(String)});await expect(fixture.value.activate({projectId:"prj-026",rateVersionId:created.id,currentVersion:1,reason:"Disetujui",attested:true,actor:manager})).rejects.toMatchObject({status:422,code:"RATE_REFERENCE_INVALID",metadata:{issues:expect.any(Array)}});expect((await fixture.value.getById("prj-026",created.id)).rate.status).toBe("Draft");expect((await fixture.value.getById("prj-026","rate-prj-026-v2")).rate.status).toBe("Active");expect(fixture.audits).toHaveLength(beforeAudit);});
 it("keeps immutable snapshot readable when current references disappear",async()=>{const fixture=mutableReferenceRepo();fixture.mutate("service-missing");fixture.mutate("branch-missing");const active=await fixture.value.getById("prj-026","rate-prj-026-v2"),historical=await fixture.value.getById("prj-026","rate-prj-026-v1");expect(active.rate.lines[0]).toMatchObject({serviceName:"Facility Management",branchName:"Jakarta Selatan"});expect(historical.rate.lines[0]).toMatchObject({serviceName:"Facility Management",branchName:"Jakarta Selatan"});expect(active.readiness.checks.find((item)=>item.code==="CURRENT_REFERENCES")?.description).toContain("Tidak berlaku");});
 it("preserves AbortError",async()=>{const {value}=repo(),controller=new AbortController(),request=value.list("prj-026",{},controller.signal);controller.abort();await expect(request).rejects.toMatchObject({name:"AbortError"});});
});
