import { fireEvent,render,screen,waitFor } from "@testing-library/react";
import userEvent from "@testing-library/user-event";
import { beforeEach,describe,expect,it,vi } from "vitest";
import { PartyMasterForm } from "./party-master-form";
import { ReferenceMasterForm } from "./reference-master-form";
import { ConflictState } from "./form-shared";
import { useUnsavedGuard } from "./use-unsaved-guard";
import { Button } from "@/components/ui";
import { AppError } from "@/features/foundation/domain/errors";

let search="access=manage";
const push=vi.fn();
vi.mock("next/navigation",()=>({useRouter:()=>({push,replace:vi.fn(),refresh:vi.fn()}),usePathname:()=>"/master-data/customers",useSearchParams:()=>new URLSearchParams(search)}));
const idleMutation={mutateAsync:vi.fn(),isPending:false};
vi.mock("../queries/hooks",()=>({useCreateParty:()=>idleMutation,useUpdateParty:()=>idleMutation,useCreateReference:()=>idleMutation,useUpdateReference:()=>idleMutation,useMasterTransition:()=>idleMutation}));

beforeEach(()=>{search="access=manage";push.mockReset();idleMutation.mutateAsync.mockReset();});

describe("production master forms",()=>{
 it("shows accessible Party errors, focuses summary, and does not open review",async()=>{const user=userEvent.setup();render(<PartyMasterForm kind="customers"/>);await user.clear(screen.getByLabelText("Termin pembayaran"));await user.click(screen.getByRole("button",{name:"Tinjau dan simpan"}));const summary=await screen.findByRole("alert");await waitFor(()=>expect(summary).toHaveFocus());expect(document.getElementById("code")).toHaveAttribute("aria-invalid","true");expect(screen.getByText("Kode wajib diisi.")).toBeVisible();expect(screen.queryByRole("dialog",{name:"Tinjau perubahan"})).not.toBeInTheDocument();});
 it("validates Service required fields",async()=>{const user=userEvent.setup();render(<ReferenceMasterForm kind="services"/>);await user.click(screen.getByRole("button",{name:"Tinjau dan simpan"}));expect(await screen.findByText("Nama layanan wajib diisi.")).toBeVisible();expect(screen.getByRole("textbox",{name:/^Unit/})).toHaveAttribute("aria-invalid","true");expect(screen.queryByRole("dialog",{name:"Tinjau perubahan"})).not.toBeInTheDocument();});
 it("updates Billing Cycle preview reactively and remains safe for invalid values",async()=>{const user=userEvent.setup();render(<ReferenceMasterForm kind="billingCycles"/>);expect(screen.getByText(/Siklus bulanan ditutup setiap tanggal 25/)).toBeVisible();const cutoff=screen.getByLabelText("Tanggal cutoff");await user.clear(cutoff);await user.type(cutoff,"20");expect(screen.getByText(/tanggal 20/)).toBeVisible();const offset=screen.getByLabelText("Jarak invoice");await user.clear(offset);await user.type(offset,"4");expect(screen.getByText(/disiapkan 4 hari/)).toBeVisible();const due=screen.getByLabelText("Jatuh tempo");await user.clear(due);await user.type(due,"45");expect(screen.getByText(/jatuh tempo 45 hari/)).toBeVisible();await user.clear(offset);await user.type(offset,"-1");expect(screen.getByText("Lengkapi aturan untuk melihat ringkasan.")).toBeVisible();expect(document.body).not.toHaveTextContent("NaN");expect(document.body).not.toHaveTextContent("undefined");});
 it("renders lifecycle 409 as persistent structured conflict",async()=>{search="access=manage&scenario=transition-conflict";idleMutation.mutateAsync.mockRejectedValue(new AppError(409,"MASTER_VERSION_CONFLICT","Record telah berubah.",{},false,"transition-corr",{userVersion:1,latestVersion:2,diffs:[{field:"status",label:"Status",before:"Tujuan: Inactive",after:"Status terbaru: Active"}]}));const detail={id:"svc-fm",code:"SVC-FM",name:"Facility Management",description:"Deskripsi",category:"Operations",unit:"Person-month",frequency:"Monthly" as const,cutoffDay:25,invoiceOffsetDays:2,dueDays:30,status:"Active" as const,createdAt:"2026-08-10T10:00:00+07:00",updatedAt:"2026-08-10T10:00:00+07:00",version:2,usage:{projectCount:0,projectIds:[],historicalReferenceCount:0,canDeactivate:true},humanRule:""};const user=userEvent.setup();render(<ReferenceMasterForm kind="services" detail={detail}/>);await user.click(screen.getByRole("button",{name:"Nonaktifkan"}));await user.type(screen.getByLabelText("Alasan wajib"),"Tidak digunakan");await user.click(screen.getByRole("button",{name:"Konfirmasi"}));expect(await screen.findByText("Record telah berubah")).toBeVisible();expect(screen.getByText(/Versi form Anda 1; versi terbaru 2/)).toBeVisible();expect(screen.getByText(/transition-corr/)).toBeVisible();expect(screen.getByRole("link",{name:"Muat versi terbaru"})).toHaveAttribute("href","/master-data/services/svc-fm/edit?access=manage");expect(screen.queryByText(/force overwrite/i)).not.toBeInTheDocument();});
});

describe("shared conflict and unsaved UI",()=>{
 it("renders structured conflict and persona-preserving recovery without force overwrite",()=>{render(<ConflictState metadata={{userVersion:3,latestVersion:5,diffs:[{field:"name",label:"Nama",before:"Nama kiriman",after:"Nama terbaru"}]}} correlationId="corr-409" reload="/master-data/customers/cus-aruna/edit?access=view" back="/master-data/customers/cus-aruna?access=view"/>);expect(screen.getByText("Record telah berubah")).toBeVisible();expect(screen.getByText(/Versi form Anda 3; versi terbaru 5/)).toBeVisible();expect(screen.getByText(/Nama kiriman → Nama terbaru/)).toBeVisible();expect(screen.getByText(/corr-409/)).toBeVisible();expect(screen.getByRole("link",{name:"Muat versi terbaru"})).toHaveAttribute("href","/master-data/customers/cus-aruna/edit?access=view");expect(screen.getByRole("link",{name:"Kembali tanpa menyimpan"})).toHaveAttribute("href","/master-data/customers/cus-aruna?access=view");expect(screen.queryByText(/overwrite/i)).not.toBeInTheDocument();});
 it("guards dirty navigation, preserves data on stay, navigates on leave, and cleans listener",async()=>{const remove=vi.spyOn(window,"removeEventListener");function Harness(){const guard=useUnsavedGuard(true,()=>push("/target"));return <><input aria-label="Draft" defaultValue="tetap"/><Button onClick={guard.requestLeave}>Kembali</Button>{guard.open&&<div role="dialog"><Button onClick={guard.stay}>Tetap di halaman</Button><Button onClick={guard.leave}>Keluar tanpa menyimpan</Button></div>}</>;}const user=userEvent.setup();const view=render(<Harness/>);await user.click(screen.getByRole("button",{name:"Kembali"}));expect(screen.getByRole("dialog")).toBeVisible();await user.click(screen.getByRole("button",{name:"Tetap di halaman"}));expect(screen.getByLabelText("Draft")).toHaveValue("tetap");await user.click(screen.getByRole("button",{name:"Kembali"}));await user.click(screen.getByRole("button",{name:"Keluar tanpa menyimpan"}));expect(push).toHaveBeenCalledWith("/target");view.unmount();expect(remove).toHaveBeenCalledWith("beforeunload",expect.any(Function));});
 it("does not guard a clean form",()=>{function Clean(){const guard=useUnsavedGuard(false,()=>push("/clean"));return <Button onClick={guard.requestLeave}>Kembali</Button>;}render(<Clean/>);fireEvent.click(screen.getByRole("button",{name:"Kembali"}));expect(push).toHaveBeenCalledWith("/clean");expect(screen.queryByRole("dialog")).not.toBeInTheDocument();});
});
