"use client";
import { faArrowRight,faClock,faFileCircleCheck,faMoneyBillTransfer,faTriangleExclamation } from "@fortawesome/free-solid-svg-icons";
import { FinancialChart } from "@/components/charts/financial-chart";
import { ProjectTable } from "@/components/data-table/project-table";
import { AppIcon,Badge,Button,Card,CardHeader,DataState,LoadingState,PageHeader,StatusBadge } from "@/components/ui";
import { DEMO_DATA_LABEL } from "@/features/foundation/domain/models";
import { useDashboardQuery } from "@/features/foundation/queries/hooks";
import { formatLongDate,formatRupiah } from "@/lib/formatters";

const workIcons={overdue:faClock,approval:faFileCircleCheck,confirmation:faTriangleExclamation};
export function Dashboard(){ const query=useDashboardQuery(); if(query.isPending)return <LoadingState/>; if(query.isError)return <DataState kind="server" correlationId={query.error.correlation_id} action={<Button variant="secondary" onClick={()=>query.refetch()}>Coba lagi</Button>}/>; const snapshot=query.data; const metrics=[{label:"Total revenue",value:formatRupiah(snapshot.revenue,true),helper:"Snapshot demo",tone:"success" as const},{label:"Biaya project",value:formatRupiah(snapshot.projectCost,true),helper:"Snapshot demo",tone:"info" as const},{label:"Laba kotor",value:formatRupiah(snapshot.grossProfit,true),helper:"Belum laporan production",tone:"success" as const},{label:"AR outstanding",value:formatRupiah(snapshot.arOutstanding,true),helper:`${formatRupiah(snapshot.overdueAr,true)} jatuh tempo`,tone:"receivable" as const}]; return <><PageHeader eyebrow={formatLongDate(snapshot.asOf)} title="Selamat pagi, Dewi." description="Ringkasan kesehatan finance dan pekerjaan yang memerlukan tindak lanjut." meta={<Badge tone="warning">{DEMO_DATA_LABEL}</Badge>} actions={<Button variant="secondary">Agustus 2026</Button>}/><section className="metrics-grid" aria-label="Ringkasan keuangan mock">{metrics.map((metric)=><Card className="metric-card" key={metric.label}><span>{metric.label}</span><strong>{metric.value}</strong><StatusBadge tone={metric.tone}>{metric.helper}</StatusBadge></Card>)}</section><section className="dashboard-grid"><Card><CardHeader title="Kinerja keuangan" description="Revenue, biaya, dan laba kotor - mock 6 bulan"/><FinancialChart data={snapshot.chartSeries}/></Card><Card><CardHeader title="Perlu perhatian" description="Prioritas operasional hari ini" action={<Badge tone="danger">{snapshot.workItems.length} tugas</Badge>}/><div className="work-list">{snapshot.workItems.map((item)=><a href="#" key={item.id}><AppIcon icon={workIcons[item.kind]}/><span><strong>{item.title}</strong><small>{item.detail}</small></span><AppIcon icon={faArrowRight}/></a>)}</div><div className="card-action"><Button variant="secondary" leadingIcon={<AppIcon icon={faMoneyBillTransfer}/>}>Buka work queue</Button></div></Card></section><Card><CardHeader title="Performa project" description="Project dari repository demo" action={<Badge tone="neutral">{DEMO_DATA_LABEL}</Badge>}/><ProjectTable/></Card></>; }
