import Decimal from "decimal.js";
import type { NormalizedRateListQuery,RateLine,RateListQuery,RateOverlap,RateType,RateVersion,RateVersionFields } from "./types";

export function normalizeRateListQuery(input:RateListQuery):NormalizedRateListQuery{return{search:(input.search??"").trim().toLocaleLowerCase("id-ID"),statuses:[...(input.statuses??[])].sort(),effectiveStates:[...(input.effectiveStates??[])].sort(),sort:input.sort??"versionNumber",direction:input.direction??"desc",page:Math.max(1,input.page??1),pageSize:[1,10,20,50].includes(input.pageSize??20)?input.pageSize??20:20};}
export function rateScopeKey(line:Pick<RateLine,"serviceId"|"branchId"|"rateType"|"unit">){return[line.serviceId,line.branchId??"all",line.rateType,line.unit].join("|");}
export function validateAmount(rateType:RateType,amount?:string,formula?:string){if(rateType==="Formula")return Boolean(formula?.trim());if(!amount?.trim())return false;try{return new Decimal(amount).greaterThanOrEqualTo(0);}catch{return false;}}
export function isIsoDate(value:string){if(!/^\d{4}-\d{2}-\d{2}$/.test(value))return false;const date=new Date(`${value}T00:00:00Z`);return !Number.isNaN(date.valueOf())&&date.toISOString().slice(0,10)===value;}
export function periodsOverlap(aFrom:string,aTo:string|undefined,bFrom:string,bTo:string|undefined){return aFrom<=(bTo??"9999-12-31")&&bFrom<=(aTo??"9999-12-31");}
export function findDuplicateScopes(lines:readonly Pick<RateLine,"serviceId"|"branchId"|"rateType"|"unit">[]){const seen=new Set<string>(),duplicates=new Set<string>();for(const line of lines){const key=rateScopeKey(line);if(seen.has(key))duplicates.add(key);seen.add(key);}return[...duplicates];}
export function findOverlaps(fields:RateVersionFields,existing:readonly RateVersion[],excludeId?:string):RateOverlap[]{const result:RateOverlap[]=[];fields.lines.forEach((line,lineIndex)=>{const scopeKey=rateScopeKey(line);for(const version of existing){if(version.id===excludeId||version.status==="Cancelled"||version.status==="Superseded")continue;if(!periodsOverlap(fields.effectiveFrom,fields.effectiveTo,version.effectiveFrom,version.effectiveTo))continue;if(version.lines.some((item)=>item.scopeKey===scopeKey))result.push({lineIndex,scopeKey,serviceName:line.serviceId,scopeLabel:line.branchId??"Semua cabang",draftPeriod:`${fields.effectiveFrom} - ${fields.effectiveTo??"seterusnya"}`,existingVersionId:version.id,existingVersionNumber:version.versionNumber,existingStatus:version.status,existingPeriod:`${version.effectiveFrom} - ${version.effectiveTo??"seterusnya"}`});}});return result;}
export function decimalChange(before:string,after:string){const previous=new Decimal(before),next=new Decimal(after),absolute=next.minus(previous);return{absolute:absolute.toString(),percentage:previous.isZero()?undefined:absolute.div(previous).mul(100).toDecimalPlaces(2).toString()};}
