import type { DocumentObjectType } from "@/features/foundation/domain/models";
import type { NormalizedProjectListQuery } from "@/features/foundation/domain/project-list";
import type { NormalizedMasterListQuery } from "@/features/master-data/domain/list-query";
import type { NormalizedRateListQuery } from "@/features/rates/domain/types";
import type { NormalizedDocumentListQuery } from "@/features/documents/domain/types";
import type { NormalizedAccessListQuery } from "@/features/access-management/domain/types";
import type { AttendanceIssueQuery, NormalizedAttendanceListQuery } from "@/features/attendance/domain/types";
import type { NormalizedPayrollBillingExceptionQuery, NormalizedPayrollBillingListQuery } from "@/features/payroll-billing/domain/types";
import type { NormalizedInvoiceListQuery } from "@/features/invoices/domain/types";
export const queryKeys={
  dashboard:{snapshot:["dashboard","snapshot"] as const},
  projects:{all:["projects"] as const,list:(params:NormalizedProjectListQuery)=>["projects","list",params] as const,detail:(id:string)=>["projects","detail",id] as const,readiness:(id:string)=>["projects","readiness",id] as const},
  masterData:{customers:["master-data","customers"] as const,vendors:["master-data","vendors"] as const,services:["master-data","services"] as const,billingCycles:["master-data","billing-cycles"] as const,taxRules:["master-data","tax-rules"] as const},
  masterManagement:{all:["master-management"] as const,list:(kind:string,params:NormalizedMasterListQuery)=>["master-management",kind,"list",params] as const,detail:(kind:string,id:string)=>["master-management",kind,"detail",id] as const,usage:(kind:string,id:string)=>["master-management",kind,"usage",id] as const},
  rates:{all:["rates"] as const,listRoot:(projectId:string)=>["rates",projectId,"list"] as const,list:(projectId:string,params:NormalizedRateListQuery)=>["rates",projectId,"list",params] as const,detail:(projectId:string,id:string)=>["rates",projectId,"detail",id] as const,current:(projectId:string)=>["rates",projectId,"current"] as const,comparisons:(projectId:string,id:string)=>["rates",projectId,"comparison",id] as const,comparison:(projectId:string,id:string,sourceId?:string)=>["rates",projectId,"comparison",id,sourceId??"source"] as const,impact:(projectId:string,id:string)=>["rates",projectId,"impact",id] as const,readiness:(projectId:string,id:string)=>["rates",projectId,"readiness",id] as const},identity:{currentUser:["identity","current-user"] as const,users:["identity","users"] as const,roles:["identity","roles"] as const,permissions:["identity","permissions"] as const},
  documents:{all:["documents"] as const,owner:(objectType:DocumentObjectType,objectId:string)=>["documents","owner",objectType,objectId] as const,list:(objectType:DocumentObjectType,objectId:string,params:NormalizedDocumentListQuery)=>["documents","owner",objectType,objectId,"list",params] as const,detail:(documentId:string)=>["documents","detail",documentId] as const,byObject:(objectType:DocumentObjectType,objectId:string)=>["documents",objectType,objectId] as const,versions:(documentId:string)=>["documents","detail",documentId,"versions"] as const,readiness:(objectType:DocumentObjectType,objectId:string)=>["documents","owner",objectType,objectId,"readiness"] as const},audit:{byObject:(objectType:string,objectId:string)=>["audit",objectType,objectId] as const},
  access:{all:["access-management"] as const,users:{all:["access-management","users"] as const,list:(params:NormalizedAccessListQuery)=>["access-management","users","list",params] as const,detail:(id:string)=>["access-management","users","detail",id] as const,effective:(id:string)=>["access-management","users",id,"effective"] as const,sod:(id:string)=>["access-management","users",id,"sod"] as const,audit:(id:string)=>["access-management","users",id,"audit"] as const},roles:{all:["access-management","roles"] as const,list:(params:NormalizedAccessListQuery)=>["access-management","roles","list",params] as const,detail:(id:string)=>["access-management","roles","detail",id] as const,matrix:(id:string)=>["access-management","roles",id,"matrix"] as const,usage:(id:string)=>["access-management","roles",id,"usage"] as const,sod:(id:string)=>["access-management","roles",id,"sod"] as const,audit:(id:string)=>["access-management","roles",id,"audit"] as const},permissions:["access-management","permissions"] as const},
  attendance:{all:["attendance"] as const,lists:["attendance","list"] as const,list:(params:NormalizedAttendanceListQuery)=>["attendance","list",params] as const,template:["attendance","template"] as const,detail:(id:string)=>["attendance","detail",id] as const,mapping:(id:string)=>["attendance","detail",id,"mapping"] as const,summary:(id:string)=>["attendance","detail",id,"summary"] as const,issues:(id:string,params:AttendanceIssueQuery)=>["attendance","detail",id,"issues",params] as const,duplicates:(id:string)=>["attendance","detail",id,"duplicates"] as const,revisions:(id:string)=>["attendance","detail",id,"revisions"] as const,readiness:(id:string)=>["attendance","detail",id,"readiness"] as const,activity:(id:string)=>["attendance","detail",id,"activity"] as const},
  payrollBilling:{all:["payroll-billing"] as const,lists:["payroll-billing","list"] as const,list:(params:NormalizedPayrollBillingListQuery)=>["payroll-billing","list",params] as const,detail:(id:string)=>["payroll-billing","detail",id] as const,currentRevision:(id:string)=>["payroll-billing","detail",id,"current-revision"] as const,revision:(id:string,revisionId:string)=>["payroll-billing","detail",id,"revision",revisionId] as const,revisions:(id:string)=>["payroll-billing","detail",id,"revisions"] as const,revisionDiff:(id:string,sourceId:string,targetId:string)=>["payroll-billing","detail",id,"revision-diff",sourceId,targetId] as const,lines:(id:string)=>["payroll-billing","detail",id,"lines"] as const,traces:(id:string)=>["payroll-billing","detail",id,"trace"] as const,trace:(id:string,lineId:string)=>["payroll-billing","detail",id,"trace",lineId] as const,summary:(id:string)=>["payroll-billing","detail",id,"summary"] as const,exceptionLists:(id:string)=>["payroll-billing","detail",id,"exceptions"] as const,exceptions:(id:string,params:NormalizedPayrollBillingExceptionQuery)=>["payroll-billing","detail",id,"exceptions",params] as const,readiness:(id:string)=>["payroll-billing","detail",id,"readiness"] as const,reconciliation:(id:string)=>["payroll-billing","detail",id,"reconciliation"] as const,activity:(id:string)=>["payroll-billing","detail",id,"activity"] as const,sourceOptions:["payroll-billing","source-options"] as const},
  invoices:{all:["invoices"] as const,lists:["invoices","list"] as const,list:(params:NormalizedInvoiceListQuery)=>["invoices","list",params] as const,detail:(id:string)=>["invoices","detail",id] as const,currentRevision:(id:string)=>["invoices","detail",id,"current-revision"] as const,history:(id:string)=>["invoices","detail",id,"history"] as const,revision:(id:string,revisionId:string)=>["invoices","detail",id,"revision",revisionId] as const,revisionDiffs:(id:string)=>["invoices","detail",id,"revision-diff"] as const,revisionDiff:(id:string,sourceId:string,targetId:string)=>["invoices","detail",id,"revision-diff",sourceId,targetId] as const,workingRevision:(id:string)=>["invoices","detail",id,"working-revision"] as const,lines:(id:string)=>["invoices","detail",id,"lines"] as const,summary:(id:string)=>["invoices","detail",id,"summary"] as const,reconciliation:(id:string)=>["invoices","detail",id,"reconciliation"] as const,readiness:(id:string)=>["invoices","detail",id,"readiness"] as const,confirmationReadiness:(id:string)=>["invoices","detail",id,"confirmation-readiness"] as const,confirmationCycles:(id:string)=>["invoices","detail",id,"confirmation-cycles"] as const,evidence:(id:string)=>["invoices","detail",id,"confirmation-evidence"] as const,customerResponses:(id:string)=>["invoices","detail",id,"customer-responses"] as const,revisionRequests:(id:string)=>["invoices","detail",id,"revision-requests"] as const,preview:(id:string)=>["invoices","detail",id,"preview"] as const,activity:(id:string)=>["invoices","detail",id,"activity"] as const,sourceOptions:["invoices","source-options"] as const},
} as const;
