import { describe, expect, it } from "vitest";
import { ATTENDANCE_TRANSITIONS, attendanceReadiness, mappingReady, maskAttendanceValue, normalizeAttendanceListQuery, validateFileMetadata, validatePeriod } from "./logic";
import type { AttendanceBatch, AttendanceFileMetadata } from "./types";
const file: AttendanceFileMetadata = { originalFilename: "attendance.xlsx", displayFilename: "attendance.xlsx", mimeType: "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet", sizeBytes: 100 };
const batch = (status: AttendanceBatch["status"], blockingIssueCount = 0): AttendanceBatch => ({ id: "att", projectId: "prj", projectLabel: "Project", period: "2026-08", status, revisionNumber: 1, file, mapping: [{ sourceColumn: "demo", targetField: "placeholder", required: true, status: "Ready", exampleValue: "aman" }], summary: { totalRows: 1, validRows: blockingIssueCount ? 0 : 1, invalidRows: blockingIssueCount, duplicateRows: 0, warningRows: 0, commitEligibleRows: blockingIssueCount ? 0 : 1, blockingIssueCount }, duplicates: { withinFile: 0, priorBatch: 0, fileDuplicate: false, decision: "Allowed", note: "demo", simulated: true }, createdAt: "2026-08-11T09:00:00+07:00", createdByUserId: "actor", correlationId: "corr", version: 1 });
describe("attendance domain", () => {
  it("normalizes stable list parameters", () => expect(normalizeAttendanceListQuery({ search: "  JULI ", statuses: ["Imported", "Imported"], projectIds: ["b", "a"], page: 0, pageSize: 999 })).toEqual({ search: "juli", statuses: ["Imported"], projectIds: ["a", "b"], sort: "createdAt", direction: "desc", page: 1, pageSize: 20 }));
  it("defines only the SRS attendance transitions in scope", () => { expect(ATTENDANCE_TRANSITIONS.Draft).toEqual(["Imported"]); expect(ATTENDANCE_TRANSITIONS.Imported).toEqual(["Validated", "Rejected"]); expect(ATTENDANCE_TRANSITIONS.Validated).toEqual(["Locked", "Rejected"]); expect(ATTENDANCE_TRANSITIONS.Calculated).toEqual([]); expect(ATTENDANCE_TRANSITIONS.Locked).toEqual([]); });
  it("validates period and demo file metadata without parsing binary", () => { expect(validatePeriod("2026-08")).toBeUndefined(); expect(validatePeriod("08/2026")).toMatch(/YYYY-MM/); expect(validateFileMetadata(file)).toEqual([]); expect(validateFileMetadata({ ...file, originalFilename: "bad.csv", mimeType: "text/csv", sizeBytes: 0 })).toEqual(expect.arrayContaining([expect.stringMatching(/kosong/), expect.stringMatching(/Ekstensi/), expect.stringMatching(/MIME/)])); });
  it("requires complete mapping and authoritative summary readiness", () => { expect(mappingReady(batch("Imported").mapping)).toBe(true); expect(attendanceReadiness(batch("Imported"))).toMatchObject({ readyToValidate: true }); expect(attendanceReadiness(batch("Imported", 2))).toMatchObject({ readyToValidate: false, blockers: [expect.stringMatching(/2 issue/)] }); expect(attendanceReadiness(batch("Validated"))).toMatchObject({ readyToLock: true }); });
  it("masks long numeric identifiers and bounds arbitrary values", () => { expect(maskAttendanceValue("123456789012")).toBe("••••••••9012"); expect(maskAttendanceValue("")).toBe("-"); expect(maskAttendanceValue("x".repeat(40))).toHaveLength(32); });
});
