import type { AttendanceBatch, AttendanceFileMetadata, AttendanceListQuery, AttendanceMapping, AttendanceReadiness, AttendanceStatus, NormalizedAttendanceListQuery } from "./types";

export const ATTENDANCE_TRANSITIONS: Readonly<Record<AttendanceStatus, readonly AttendanceStatus[]>> = { Draft: ["Imported"], Imported: ["Validated", "Rejected"], Validated: ["Locked", "Rejected"], Calculated: [], Locked: [], Rejected: [] };
export const DEMO_FILE_POLICY = { label: "Kebijakan file demo - menunggu kontrak backend", extensions: [".xlsx"] as const, mimeTypes: ["application/vnd.openxmlformats-officedocument.spreadsheetml.sheet"] as const, maxBytes: 5_000_000, maxFilenameLength: 120 };
export function normalizeAttendanceListQuery(input: AttendanceListQuery = {}): NormalizedAttendanceListQuery { const size = [10, 20, 50].includes(input.pageSize ?? 20) ? input.pageSize as 10 | 20 | 50 : 20; return { search: input.search?.trim().toLocaleLowerCase("id-ID") ?? "", statuses: [...new Set(input.statuses ?? [])].sort(), projectIds: [...new Set(input.projectIds ?? [])].sort(), sort: input.sort ?? "createdAt", direction: input.direction ?? "desc", page: Number.isInteger(input.page) && (input.page ?? 0) > 0 ? input.page! : 1, pageSize: size }; }
export function validatePeriod(period: string): string | undefined { return /^\d{4}-(0[1-9]|1[0-2])$/.test(period) ? undefined : "Periode harus berformat YYYY-MM."; }
export function validateFileMetadata(file?: AttendanceFileMetadata): readonly string[] { if (!file) return ["File wajib dipilih."]; const errors: string[] = [], lower = file.originalFilename.toLocaleLowerCase("id-ID"); if (file.sizeBytes === 0) errors.push("File kosong tidak dapat diproses."); if (file.originalFilename.length > DEMO_FILE_POLICY.maxFilenameLength) errors.push("Nama file terlalu panjang."); if (/[\\/:*?\"<>|\x00-\x1F\x7F]/.test(file.originalFilename)) errors.push("Nama file mengandung karakter yang tidak aman."); if (!lower.endsWith(".xlsx")) errors.push("Ekstensi file harus .xlsx pada kebijakan demo."); if (!DEMO_FILE_POLICY.mimeTypes.includes(file.mimeType as (typeof DEMO_FILE_POLICY.mimeTypes)[number])) errors.push("MIME file tidak didukung pada kebijakan demo."); if (file.sizeBytes > DEMO_FILE_POLICY.maxBytes) errors.push("Ukuran file melebihi batas demo 5 MB."); return errors; }
export function mappingReady(mapping: readonly AttendanceMapping[]): boolean { return mapping.length > 0 && mapping.every(item => item.status === "Ready" && (!item.required || Boolean(item.targetField))); }
export function attendanceReadiness(batch: AttendanceBatch): AttendanceReadiness { const blockers: string[] = []; if (!batch.file) blockers.push("File belum diimpor."); if (!mappingReady(batch.mapping)) blockers.push("Mapping belum siap."); if (batch.summary.blockingIssueCount) blockers.push(`${batch.summary.blockingIssueCount} issue blocking belum diperbaiki.`); if (batch.duplicates.decision === "Blocking") blockers.push("Duplikasi blocking harus diselesaikan."); return { readyToValidate: batch.status === "Imported" && blockers.length === 0, readyToLock: batch.status === "Validated" && blockers.length === 0, blockers, nextAction: batch.status === "Draft" ? "Pilih file dan tinjau mapping." : batch.status === "Imported" ? blockers[0] ?? "Tinjau ringkasan lalu validasi seluruh batch." : batch.status === "Validated" ? "Kunci batch saat review selesai." : batch.status === "Locked" ? "Batch immutable; buat correction revision bila diperlukan." : batch.status === "Rejected" ? "Buat correction revision dengan file yang diperbaiki." : "Menunggu Tahap 2B; kalkulasi tidak tersedia di Tahap 2A." }; }
export function maskAttendanceValue(value: string): string { const trimmed = value.trim(); if (!trimmed) return "-"; if (/^\d{10,}$/.test(trimmed)) return `${"•".repeat(Math.max(0, trimmed.length - 4))}${trimmed.slice(-4)}`; return trimmed.length > 32 ? `${trimmed.slice(0, 29)}...` : trimmed; }
