import {QueryClient,QueryClientProvider} from "@tanstack/react-query";
import {act,renderHook,waitFor} from "@testing-library/react";
import type {ReactNode} from "react";
import {describe,expect,it,vi} from "vitest";
import {payrollBillingRepository} from "../repositories";
import type {PayrollMutationResult} from "../domain/types";
import {payrollBillingInvalidationKeys,useAdjustPayrollBilling,useLockPayrollBilling,usePayrollBillingExceptions,usePayrollBillingList,useRecalculatePayrollBilling,useRejectPayrollBilling,useReviewPayrollBilling} from "./hooks";
const wrapperFor=(client:QueryClient)=>function QueryWrapper({children}:{children:ReactNode}){return <QueryClientProvider client={client}>{children}</QueryClientProvider>;};
const base={data:{runId:"pbr-hook",revisionId:"rev-1",revisionVersion:1},actor:{userId:"u",permissionKeys:[]},reason:"reason",currentVersion:1};
describe("Payroll Billing hooks",()=>{
it("normalizes keys, forwards signals, and disables sensitive persona none queries",async()=>{let listSignal:AbortSignal|undefined,exceptionSignal:AbortSignal|undefined;const list=vi.spyOn(payrollBillingRepository,"list").mockImplementation(async(_query,signal)=>{listSignal=signal;return{items:[],total:0,page:1,pageSize:20,hasNextPage:false,totalPages:1};}),exceptions=vi.spyOn(payrollBillingRepository,"exceptions").mockImplementation(async(_id,_query,signal)=>{exceptionSignal=signal;return{items:[],total:0,page:1,pageSize:20,hasNextPage:false,totalPages:1};}),client=new QueryClient({defaultOptions:{queries:{retry:false}}}),wrapper=wrapperFor(client),enabled=renderHook(()=>({list:usePayrollBillingList({search:" x ",statuses:["Locked","Locked"]}),exceptions:usePayrollBillingExceptions("pbr-hook",{severities:["Warning","Warning"]})}),{wrapper}),disabled=renderHook(()=>usePayrollBillingExceptions("pbr-hook",{},"none"),{wrapper});await waitFor(()=>expect(enabled.result.current.list.data).toBeDefined());await waitFor(()=>expect(enabled.result.current.exceptions.data).toBeDefined());expect(listSignal).toBeInstanceOf(AbortSignal);expect(exceptionSignal).toBeInstanceOf(AbortSignal);expect(disabled.result.current.fetchStatus).toBe("idle");enabled.unmount();disabled.unmount();list.mockRestore();exceptions.mockRestore();});
it.each([{name:"adjust",hook:useAdjustPayrollBilling,method:"adjust",kind:"revision",command:{...base,data:{...base.data,scope:"Run" as const,type:"Addition" as const,amount:"1",currency:"IDR" as const}}},{name:"recalculate",hook:useRecalculatePayrollBilling,method:"recalculate",kind:"revision",command:base},{name:"review",hook:useReviewPayrollBilling,method:"review",kind:"state",command:{...base,data:{...base.data,attestation:true}}},{name:"reject",hook:useRejectPayrollBilling,method:"reject",kind:"state",command:base},{name:"lock",hook:useLockPayrollBilling,method:"lock",kind:"state",command:{...base,data:{...base.data,attestation:true}}}] as const)("uses a fresh signal and scoped $name invalidation",async entry=>{const spy=vi.spyOn(payrollBillingRepository,entry.method).mockResolvedValue({runId:"pbr-hook",version:2,revisionNumber:1,message:"ok",correlationId:"corr"});const client=new QueryClient(),invalidate=vi.spyOn(client,"invalidateQueries"),hook=renderHook(()=>entry.hook(),{wrapper:wrapperFor(client)});await act(async()=>{await (hook.result.current.mutateAsync as (command:typeof entry.command)=>Promise<unknown>)(entry.command);});const signal=spy.mock.calls[0]?.[1];expect(signal).toBeInstanceOf(AbortSignal);expect(signal?.aborted).toBe(false);expect(invalidate.mock.calls.map(([options])=>options?.queryKey)).toEqual(payrollBillingInvalidationKeys("pbr-hook",entry.kind));expect(invalidate.mock.calls[0]?.[0]?.exact).toBe(false);expect(invalidate.mock.calls.slice(1).every(([options])=>typeof options?.exact==="boolean")).toBe(true);hook.unmount();spy.mockRestore();});
it("aborts an owned mutation on unmount and never invalidates cancellation",async()=>{let signal:AbortSignal|undefined;const spy=vi.spyOn(payrollBillingRepository,"reject").mockImplementation((_command,current)=>new Promise((_resolve,reject)=>{signal=current;current?.addEventListener("abort",()=>reject(new DOMException("stop","AbortError")),{once:true});}));const client=new QueryClient(),invalidate=vi.spyOn(client,"invalidateQueries"),hook=renderHook(()=>useRejectPayrollBilling(),{wrapper:wrapperFor(client)});let pending:Promise<unknown>;act(()=>{pending=hook.result.current.mutateAsync(base).catch(error=>error);});await waitFor(()=>expect(signal).toBeInstanceOf(AbortSignal));hook.unmount();await expect(pending!).resolves.toMatchObject({name:"AbortError"});expect(signal?.aborted).toBe(true);expect(invalidate).not.toHaveBeenCalled();spy.mockRestore();});
it.each([{name:"adjust",hook:useAdjustPayrollBilling,method:"adjust",kind:"revision",command:{...base,data:{...base.data,scope:"Run" as const,type:"Addition" as const,amount:"1",currency:"IDR" as const}}},{name:"recalculate",hook:useRecalculatePayrollBilling,method:"recalculate",kind:"revision",command:base},{name:"review",hook:useReviewPayrollBilling,method:"review",kind:"state",command:{...base,data:{...base.data,attestation:true}}},{name:"reject",hook:useRejectPayrollBilling,method:"reject",kind:"state",command:base},{name:"lock",hook:useLockPayrollBilling,method:"lock",kind:"state",command:{...base,data:{...base.data,attestation:true}}}] as const)("gives remounted $name a fresh controller and invalidates only the new success",async entry=>{const signals:AbortSignal[]=[];let calls=0;const spy=vi.spyOn(payrollBillingRepository,entry.method);spy.mockImplementation(function(...args:readonly unknown[]):Promise<PayrollMutationResult>{calls++;const signal=args[1] as AbortSignal;signals.push(signal);if(calls===1)return new Promise<PayrollMutationResult>((_resolve,reject)=>signal.addEventListener("abort",()=>reject(new DOMException("old","AbortError")),{once:true}));return Promise.resolve({runId:"pbr-hook",version:2,revisionNumber:1,message:"ok",correlationId:"corr"});});const client=new QueryClient(),invalidate=vi.spyOn(client,"invalidateQueries"),first=renderHook(()=>entry.hook(),{wrapper:wrapperFor(client)}),mutate=(hook:typeof first)=>(hook.result.current.mutateAsync as (command:typeof entry.command)=>Promise<unknown>)(entry.command);let old:Promise<unknown>;act(()=>{old=mutate(first).catch(error=>error);});await waitFor(()=>expect(signals).toHaveLength(1));first.unmount();await expect(old!).resolves.toMatchObject({name:"AbortError"});expect(signals[0]?.aborted).toBe(true);expect(invalidate).not.toHaveBeenCalled();const second=renderHook(()=>entry.hook(),{wrapper:wrapperFor(client)});await act(async()=>{await mutate(second);});expect(signals[1]).not.toBe(signals[0]);expect(signals[1]?.aborted).toBe(false);expect(invalidate.mock.calls.map(([options])=>options?.queryKey)).toEqual(payrollBillingInvalidationKeys("pbr-hook",entry.kind));second.unmount();spy.mockRestore();});
});
