"use client";
import {useEffect,useRef} from "react";
import {useMutation,useQuery,useQueryClient} from "@tanstack/react-query";
import {normalizeOrRethrowAppError} from "@/features/foundation/domain/errors";
import {queryKeys} from "@/lib/query-keys";
import {normalizePayrollBillingExceptionQuery,normalizePayrollBillingListQuery} from "../domain/hardening";
import type {AdjustPayrollBillingCommand,CreatePayrollBillingCommand,LockPayrollBillingCommand,PayrollBillingExceptionQuery,PayrollBillingListQuery,PayrollMutationResult,RecalculatePayrollBillingCommand,RejectPayrollBillingCommand,ReviewPayrollBillingCommand} from "../domain/types";
import {payrollBillingRepository as repository} from "../repositories";

const safe=async<T,>(operation:()=>Promise<T>)=>{try{return await operation();}catch(error){throw normalizeOrRethrowAppError(error);}};
const allowed=(enabled:boolean,id?:string,access?:string)=>enabled&&Boolean(id)&&access!=="none";
export const usePayrollBillingList=(input:PayrollBillingListQuery,access="view",enabled=true)=>{const query=normalizePayrollBillingListQuery(input);return useQuery({queryKey:queryKeys.payrollBilling.list(query),enabled:enabled&&access!=="none",queryFn:({signal})=>safe(()=>repository.list(query,signal))});};
export const usePayrollBillingDetail=(id:string,access="view",enabled=true)=>useQuery({queryKey:queryKeys.payrollBilling.detail(id),enabled:allowed(enabled,id,access),queryFn:({signal})=>safe(()=>repository.get(id,signal))});
export const usePayrollBillingCurrentRevision=(id:string,access="view",enabled=true)=>useQuery({queryKey:queryKeys.payrollBilling.currentRevision(id),enabled:allowed(enabled,id,access),queryFn:({signal})=>safe(()=>repository.currentRevision(id,signal))});
export const usePayrollBillingRevision=(id:string,revisionId:string,access="view",enabled=true)=>useQuery({queryKey:queryKeys.payrollBilling.revision(id,revisionId),enabled:allowed(enabled,id,access)&&Boolean(revisionId),queryFn:({signal})=>safe(()=>repository.revision(id,revisionId,signal))});
export const usePayrollBillingRevisions=(id:string,access="view",enabled=true)=>useQuery({queryKey:queryKeys.payrollBilling.revisions(id),enabled:allowed(enabled,id,access),queryFn:({signal})=>safe(()=>repository.revisions(id,signal))});
export const usePayrollBillingRevisionDiff=(id:string,sourceId:string,targetId:string,access="view",enabled=true)=>useQuery({queryKey:queryKeys.payrollBilling.revisionDiff(id,sourceId,targetId),enabled:allowed(enabled,id,access)&&Boolean(sourceId&&targetId),queryFn:({signal})=>safe(()=>repository.revisionDiff(id,sourceId,targetId,signal))});
export const usePayrollBillingLines=(id:string,access="view",enabled=true)=>useQuery({queryKey:queryKeys.payrollBilling.lines(id),enabled:allowed(enabled,id,access),queryFn:({signal})=>safe(()=>repository.lines(id,signal))});
export const usePayrollBillingTrace=(id:string,lineId:string,access="view",enabled=true)=>useQuery({queryKey:queryKeys.payrollBilling.trace(id,lineId),enabled:allowed(enabled,id,access)&&Boolean(lineId),queryFn:({signal})=>safe(()=>repository.trace(id,lineId,signal))});
export const usePayrollBillingSummary=(id:string,access="view",enabled=true)=>useQuery({queryKey:queryKeys.payrollBilling.summary(id),enabled:allowed(enabled,id,access),queryFn:({signal})=>safe(()=>repository.summary(id,signal))});
export const usePayrollBillingExceptions=(id:string,input:PayrollBillingExceptionQuery,access="view",enabled=true)=>{const query=normalizePayrollBillingExceptionQuery(input);return useQuery({queryKey:queryKeys.payrollBilling.exceptions(id,query),enabled:allowed(enabled,id,access),queryFn:({signal})=>safe(()=>repository.exceptions(id,query,signal))});};
export const usePayrollBillingReadiness=(id:string,access="view",enabled=true)=>useQuery({queryKey:queryKeys.payrollBilling.readiness(id),enabled:allowed(enabled,id,access),queryFn:({signal})=>safe(()=>repository.readiness(id,signal))});
export const usePayrollBillingReconciliation=(id:string,access="view",enabled=true)=>useQuery({queryKey:queryKeys.payrollBilling.reconciliation(id),enabled:allowed(enabled,id,access),queryFn:({signal})=>safe(()=>repository.reconciliation(id,signal))});
export const usePayrollBillingActivity=(id:string,access="view",enabled=true)=>useQuery({queryKey:queryKeys.payrollBilling.activity(id),enabled:allowed(enabled,id,access),queryFn:({signal})=>safe(()=>repository.activity(id,signal))});
export const usePayrollBillingSourceOptions=(access="manage",enabled=true)=>useQuery({queryKey:queryKeys.payrollBilling.sourceOptions,enabled:enabled&&access!=="none"&&access!=="view",queryFn:({signal})=>safe(()=>repository.sourceOptions(signal))});

type Kind="revision"|"state";
export const payrollBillingInvalidationKeys=(id:string,kind:Kind)=>kind==="revision"?[queryKeys.payrollBilling.lists,queryKeys.payrollBilling.detail(id),queryKeys.payrollBilling.currentRevision(id),queryKeys.payrollBilling.revisions(id),["payroll-billing","detail",id,"revision-diff"] as const,queryKeys.payrollBilling.lines(id),queryKeys.payrollBilling.traces(id),queryKeys.payrollBilling.summary(id),queryKeys.payrollBilling.exceptionLists(id),queryKeys.payrollBilling.readiness(id),queryKeys.payrollBilling.reconciliation(id),queryKeys.payrollBilling.activity(id)]:[queryKeys.payrollBilling.lists,queryKeys.payrollBilling.detail(id),queryKeys.payrollBilling.currentRevision(id),queryKeys.payrollBilling.readiness(id),queryKeys.payrollBilling.activity(id)];
const isFamilyKey=(key:readonly unknown[])=>key===queryKeys.payrollBilling.lists||key.at(-1)==="revision-diff"||key.at(-1)==="trace"||key.at(-1)==="exceptions";
function usePayrollMutation<T>(operation:(command:T,signal:AbortSignal)=>Promise<PayrollMutationResult>,getId:(command:T)=>string,kind:Kind){const client=useQueryClient(),controller=useRef<AbortController|null>(null),mounted=useRef(false);useEffect(()=>{mounted.current=true;return()=>{mounted.current=false;controller.current?.abort();};},[]);const mutation=useMutation<PayrollMutationResult,Error,T>({mutationFn:command=>{controller.current?.abort();const current=new AbortController();controller.current=current;return safe(()=>operation(command,current.signal)).finally(()=>{if(controller.current===current)controller.current=null;});},onSuccess:(_result,command)=>{if(!mounted.current)return;for(const key of payrollBillingInvalidationKeys(getId(command),kind))void client.invalidateQueries({queryKey:key,exact:!isFamilyKey(key)});}});return{...mutation,cancel:()=>controller.current?.abort()};}
export const useAdjustPayrollBilling=()=>usePayrollMutation<AdjustPayrollBillingCommand>((command,signal)=>repository.adjust(command,signal),command=>command.data.runId,"revision");
export function useCreatePayrollBilling(){const client=useQueryClient(),controller=useRef<AbortController|null>(null);useEffect(()=>()=>controller.current?.abort(),[]);const mutation=useMutation<PayrollMutationResult,Error,CreatePayrollBillingCommand>({mutationFn:command=>{controller.current?.abort();const current=new AbortController();controller.current=current;return safe(()=>repository.create(command,current.signal)).finally(()=>{if(controller.current===current)controller.current=null;});},onSuccess:result=>{for(const key of payrollBillingInvalidationKeys(result.runId,"revision"))void client.invalidateQueries({queryKey:key,exact:!isFamilyKey(key)});void client.invalidateQueries({queryKey:queryKeys.payrollBilling.sourceOptions,exact:true});}});return{...mutation,cancel:()=>controller.current?.abort()};}
export const useRecalculatePayrollBilling=()=>usePayrollMutation<RecalculatePayrollBillingCommand>((command,signal)=>repository.recalculate(command,signal),command=>command.data.runId,"revision");
export const useReviewPayrollBilling=()=>usePayrollMutation<ReviewPayrollBillingCommand>((command,signal)=>repository.review(command,signal),command=>command.data.runId,"state");
export const useRejectPayrollBilling=()=>usePayrollMutation<RejectPayrollBillingCommand>((command,signal)=>repository.reject(command,signal),command=>command.data.runId,"state");
export const useLockPayrollBilling=()=>usePayrollMutation<LockPayrollBillingCommand>((command,signal)=>repository.lock(command,signal),command=>command.data.runId,"state");
